"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { filterCurrentOnlyDefinitions, currentOnlyVisualization, type CurrentOnlyDefinition, type CurrentOnlyWorkshopViewModel } from "@/lib/calibration-workshop/currentOnlyViewModel";
import { buildWorkshopDeepLink } from "@/lib/calibration-workshop/workshopNavigation";

type Availability = "all" | CurrentOnlyDefinition["availability"];
const filters: readonly Readonly<{ id: Availability; label: string }>[] = Object.freeze([{ id: "all", label: "All Tables" }, { id: "current_available", label: "Current available" }, { id: "unavailable", label: "Unavailable" }, { id: "unavailable_quarantined", label: "Quarantined" }]);
const shown = (value: number) => Number.isInteger(value) ? value.toLocaleString() : Number(value.toPrecision(7)).toLocaleString();

export default function CurrentOnlyWorkshopClient({ workshop, vehicleId, subscriberSession }: { workshop: CurrentOnlyWorkshopViewModel; vehicleId: string; subscriberSession?: string }) {
  const [search, setSearch] = useState(""), [filter, setFilter] = useState<Availability>("all"), [view, setView] = useState<"grid" | "2d" | "3d">("grid"), [selectedCell, setSelectedCell] = useState(0);
  const definitions = useMemo(() => filterCurrentOnlyDefinitions(workshop.definitions, search, filter), [workshop.definitions, search, filter]);
  const detail = workshop.selectedDefinition, visual = useMemo(() => currentOnlyVisualization(detail), [detail]), cell = detail.cells[selectedCell] ?? detail.cells[0] ?? null;
  return <section className="grid gap-4 xl:grid-cols-[320px_minmax(0,1fr)_320px]">
    <aside className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-300">Table Explorer</p><input aria-label="Search Tables" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search Tables" className="mt-3 w-full rounded-lg border border-zinc-700 bg-black px-3 py-2 text-sm"/><div className="mt-3 flex flex-wrap gap-2">{filters.map(item => <button key={item.id} type="button" onClick={() => setFilter(item.id)} className={`rounded-lg border px-2 py-1 text-xs ${filter === item.id ? "border-blue-400 text-blue-200" : "border-zinc-700 text-zinc-400"}`}>{item.label}</button>)}</div><div className="mt-4 max-h-[700px] space-y-1 overflow-auto">{definitions.map(item => <Link key={item.key} href={buildWorkshopDeepLink({ vehicleId, subscriberSession, definition: item.key })} className={`block rounded-lg border p-3 text-sm ${item.key === detail.key ? "border-blue-400/50 bg-blue-400/10" : "border-zinc-800"}`}><span className="block font-medium">{item.title}</span><span className="mt-1 block text-xs text-zinc-500">{item.availability.replaceAll("_", " ")}</span></Link>)}</div></aside>
    <main className="bmw-border min-w-0 rounded-2xl bg-zinc-950 p-5"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-zinc-800 pb-4"><div><p className="text-xs uppercase tracking-[.16em] text-blue-300">Current Calibration</p><h2 className="mt-1 text-xl font-semibold">{detail.title}</h2><p className="mt-1 text-xs text-zinc-500">{detail.rows} × {detail.columns} · {detail.units ?? "units not supplied"}</p></div><div className="flex rounded-lg border border-zinc-700 p-1">{(["grid", "2d", "3d"] as const).map(mode => { const enabled = visual.capabilities[mode === "2d" ? "twoDimensional" : mode === "3d" ? "threeDimensional" : "grid"]; return <button key={mode} type="button" disabled={!enabled} onClick={() => setView(mode)} className={`rounded px-4 py-2 text-xs font-semibold ${view === mode ? "bg-blue-500/20 text-blue-200" : enabled ? "text-zinc-400" : "text-zinc-700"}`}>{mode === "grid" ? "Grid" : mode.toUpperCase()}</button>; })}</div></div>
      {detail.availability !== "current_available" ? <div className="mt-5 rounded-xl border border-amber-400/35 bg-amber-400/10 p-5" role="alert"><p className="font-semibold text-amber-200">{detail.availability === "unavailable_quarantined" ? "Unavailable / Quarantined" : "Unavailable"}</p>{detail.findings.map(item => <p key={item} className="mt-2 text-sm text-amber-50">{item}</p>)}<p className="mt-3 text-sm text-zinc-300">Editing, Suggested Calibration, reconstruction mutation and flashing eligibility are prohibited.</p></div> : view === "grid" ? <div className="mt-5 overflow-auto"><table className="w-full border-collapse text-right font-mono text-xs"><tbody>{Array.from({ length: detail.rows }, (_, row) => <tr key={row}>{detail.cells.filter(item => item.row === row).map(item => <td key={item.index} onClick={() => setSelectedCell(item.index)} className={`cursor-pointer border p-2 ${item.index === selectedCell ? "border-blue-400 bg-blue-400/15" : "border-zinc-800"}`}>{shown(item.currentValue)}</td>)}</tr>)}</tbody></table></div> : <CurrentPlot detail={detail} perspective={view === "3d"}/>} 
    </main>
    <aside className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-300">Cell Inspector</p>{cell ? <dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><dt className="text-zinc-500">Row / column</dt><dd>{cell.row} / {cell.column}</dd><dt className="text-zinc-500">Current</dt><dd>{shown(cell.currentValue)} {cell.units}</dd><dt className="text-zinc-500">Raw</dt><dd>{shown(cell.currentRawValue)}</dd><dt className="text-zinc-500">Offset</dt><dd className="font-mono">0x{cell.currentRawOffset.toString(16)}</dd><dt className="text-zinc-500">Reference</dt><dd>Not established</dd><dt className="text-zinc-500">Delta</dt><dd>Unavailable</dd></dl> : <p className="mt-4 text-sm text-zinc-500">No qualified cell is available.</p>}<h3 className="mt-6 font-semibold">Table Information</h3><p className="mt-2 break-all font-mono text-xs text-zinc-500">{detail.definitionRevision}</p>{detail.provenance.map(item => <p key={item} className="mt-2 text-xs text-zinc-400">{item}</p>)}</aside>
  </section>;
}

function CurrentPlot({ detail, perspective }: { detail: CurrentOnlyDefinition; perspective: boolean }) {
  const values = detail.cells.map(item => item.currentValue), minimum = Math.min(...values), maximum = Math.max(...values), span = maximum - minimum || 1;
  const points = detail.cells.map((item, index) => `${(index / Math.max(1, detail.cells.length - 1)) * 100},${95 - ((item.currentValue - minimum) / span) * 85}`).join(" ");
  return <div className={`mt-5 rounded-xl border border-zinc-800 bg-black p-4 ${perspective ? "[transform:perspective(900px)_rotateX(18deg)]" : ""}`}><svg role="img" aria-label={perspective ? "Current 3D Table visualization" : "Current 2D Table visualization"} viewBox="0 0 100 100" className="h-[420px] w-full" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="#60a5fa" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/></svg><p className="mt-2 text-xs text-zinc-500">Current engineering values only · Reference and comparison unavailable</p></div>;
}
