"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { filterCurrentOnlyDefinitions, currentOnlyVisualization, type CurrentOnlyDefinition, type CurrentOnlyWorkshopViewModel } from "@/lib/calibration-workshop/currentOnlyViewModel";
import { buildWorkshopDeepLink } from "@/lib/calibration-workshop/workshopNavigation";
import { applyWorkingEdit, createWorkingCalibration, redoWorkingEdit, undoWorkingEdit, workingCellDelta, workingCellValue, type WorkingCalibration, type WorkingEditOperation } from "@/lib/calibration-workshop/workingCalibration";
import { createBrowserWorkingCalibrationStore } from "@/lib/calibration-workshop/workingCalibrationPersistence";

type Availability = "all" | CurrentOnlyDefinition["availability"];
const filters: readonly Readonly<{ id: Availability; label: string }>[] = Object.freeze([{ id: "all", label: "All Tables" }, { id: "current_available", label: "Current available" }, { id: "unavailable", label: "Unavailable" }, { id: "unavailable_quarantined", label: "Quarantined" }]);
const shown = (value: number) => Number.isInteger(value) ? value.toLocaleString() : Number(value.toPrecision(7)).toLocaleString();

export default function CurrentOnlyWorkshopClient({ workshop, vehicleId, ownerScope, subscriberSession }: { workshop: CurrentOnlyWorkshopViewModel; vehicleId: string; ownerScope: string; subscriberSession?: string }) {
  const [search, setSearch] = useState(""), [filter, setFilter] = useState<Availability>("all"), [view, setView] = useState<"grid" | "2d" | "3d">("grid"), [selectedCells, setSelectedCells] = useState<readonly number[]>([0]), [working, setWorking] = useState<WorkingCalibration | null>(null), [operation, setOperation] = useState<WorkingEditOperation>("assign"), [operand, setOperand] = useState(""), [finding, setFinding] = useState<string | null>(null);
  const definitions = useMemo(() => filterCurrentOnlyDefinitions(workshop.definitions, search, filter), [workshop.definitions, search, filter]);
  const detail = workshop.selectedDefinition, visual = useMemo(() => currentOnlyVisualization(detail), [detail]), selectedCell = selectedCells[0] ?? 0, cell = detail.cells[selectedCell] ?? detail.cells[0] ?? null;
  const scope = useMemo(() => ({ ownerScope, vehicleId, currentDatasetId: workshop.source.currentDatasetId }), [ownerScope, vehicleId, workshop.source.currentDatasetId]);
  const newWorking = useCallback((createdAt = new Date().toISOString()) => createWorkingCalibration({ ownerScope, vehicleId, currentDatasetId: workshop.source.currentDatasetId, currentDatasetRevision: workshop.source.currentDatasetRevision, romLayoutId: workshop.source.romLayoutId, relationshipRevision: workshop.source.relationshipRevision, definitionSetRevision: workshop.source.definitionSetRevision, createdAt, definitions: workshop.definitions.map((definition) => ({ definitionRevision: definition.definitionRevision, occurrence: definition.occurrence, rows: definition.rows, columns: definition.columns, availability: definition.availability === "current_available" ? "available" : definition.availability === "unavailable_quarantined" ? "quarantined" : "unavailable", capability: definition.editCapability, cells: definition.cells.map((item) => ({ definitionRevision: definition.definitionRevision, occurrence: definition.occurrence, index: item.index, row: item.row, column: item.column, currentValue: item.currentValue, units: item.units })) })) }), [ownerScope, vehicleId, workshop]);
  useEffect(() => { const seed = newWorking("2000-01-01T00:00:00.000Z"); setWorking(createBrowserWorkingCalibrationStore(window.localStorage).load(scope, seed)); }, [scope, newWorking]);
  useEffect(() => { if (working) createBrowserWorkingCalibrationStore(window.localStorage).save(working); }, [working]);
  const createWorking = () => setWorking(newWorking());
  const selectCell = (index: number, region: boolean) => { if (!region || selectedCells.length === 0) { setSelectedCells([index]); return; } const anchor = detail.cells[selectedCells[0]!]!, target = detail.cells[index]!; const minRow = Math.min(anchor.row, target.row), maxRow = Math.max(anchor.row, target.row), minColumn = Math.min(anchor.column, target.column), maxColumn = Math.max(anchor.column, target.column); setSelectedCells(detail.cells.filter((item) => item.row >= minRow && item.row <= maxRow && item.column >= minColumn && item.column <= maxColumn).map((item) => item.index)); };
  const apply = () => { if (!working) return; const value = Number(operand), targets = selectedCells.map((index) => ({ definitionRevision: detail.definitionRevision, occurrence: detail.occurrence, index, row: detail.cells[index]!.row, column: detail.cells[index]!.column })), result = applyWorkingEdit(working, { operation, operand: value, targets, updatedAt: new Date().toISOString() }); if (result.status === "applied") { setWorking(result.calibration); setFinding(result.calibration.validation); } else setFinding(result.findings.join(" ")); };
  return <section className="grid gap-4 xl:grid-cols-[320px_minmax(0,1fr)_320px]">
    <aside className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-300">Table Explorer</p><input aria-label="Search Tables" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search Tables" className="mt-3 w-full rounded-lg border border-zinc-700 bg-black px-3 py-2 text-sm"/><div className="mt-3 flex flex-wrap gap-2">{filters.map(item => <button key={item.id} type="button" onClick={() => setFilter(item.id)} className={`rounded-lg border px-2 py-1 text-xs ${filter === item.id ? "border-blue-400 text-blue-200" : "border-zinc-700 text-zinc-400"}`}>{item.label}</button>)}</div><div className="mt-4 max-h-[700px] space-y-1 overflow-auto">{definitions.map(item => <Link key={item.key} href={buildWorkshopDeepLink({ vehicleId, subscriberSession, definition: item.key })} className={`block rounded-lg border p-3 text-sm ${item.key === detail.key ? "border-blue-400/50 bg-blue-400/10" : "border-zinc-800"}`}><span className="block font-medium">{item.title}</span><span className="mt-1 block text-xs text-zinc-500">{item.availability.replaceAll("_", " ")}</span></Link>)}</div></aside>
    <main className="bmw-border min-w-0 rounded-2xl bg-zinc-950 p-5"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-zinc-800 pb-4"><div><p className="text-xs uppercase tracking-[.16em] text-blue-300">{working ? "Working Calibration" : "Current Calibration"}</p><h2 className="mt-1 text-xl font-semibold">{detail.title}</h2><p className="mt-1 text-xs text-zinc-500">{detail.rows} × {detail.columns} · {detail.units ?? "units not supplied"}</p></div><div className="flex rounded-lg border border-zinc-700 p-1">{(["grid", "2d", "3d"] as const).map(mode => { const enabled = visual.capabilities[mode === "2d" ? "twoDimensional" : mode === "3d" ? "threeDimensional" : "grid"]; return <button key={mode} type="button" disabled={!enabled} onClick={() => setView(mode)} className={`rounded px-4 py-2 text-xs font-semibold ${view === mode ? "bg-blue-500/20 text-blue-200" : enabled ? "text-zinc-400" : "text-zinc-700"}`}>{mode === "grid" ? "Grid" : mode.toUpperCase()}</button>; })}</div></div>
      <div className="mt-4 rounded-xl border border-zinc-800 bg-zinc-900 p-4"><div className="flex flex-wrap items-center gap-2">{!working ? <button type="button" onClick={createWorking} className="rounded-lg border border-blue-400 px-3 py-2 text-xs text-blue-200">Create Working Calibration</button> : <><span className="text-xs text-zinc-400">{working.state} · {working.mutations.slice(0, working.cursor).length} changes</span><button type="button" disabled={working.cursor === 0} onClick={() => setWorking(undoWorkingEdit(working, new Date().toISOString()))} className="rounded border border-zinc-700 px-3 py-2 text-xs disabled:opacity-40">Undo</button><button type="button" disabled={working.cursor >= working.mutations.length} onClick={() => setWorking(redoWorkingEdit(working, new Date().toISOString()))} className="rounded border border-zinc-700 px-3 py-2 text-xs disabled:opacity-40">Redo</button><select aria-label="Edit operation" value={operation} onChange={(event) => setOperation(event.target.value as WorkingEditOperation)} className="rounded border border-zinc-700 bg-black px-2 py-2 text-xs"><option value="assign">Set value</option><option value="delta">Add delta</option><option value="percentage">Change %</option></select><input aria-label="Edit value" value={operand} onChange={(event) => setOperand(event.target.value)} inputMode="decimal" className="w-28 rounded border border-zinc-700 bg-black px-2 py-2 text-xs"/><button type="button" disabled={detail.editCapability.state !== "EDIT_QUALIFIED"} onClick={apply} className="rounded border border-blue-400 px-3 py-2 text-xs text-blue-200 disabled:border-zinc-700 disabled:text-zinc-600">Apply to {selectedCells.length} cell{selectedCells.length === 1 ? "" : "s"}</button></>}</div>{detail.editCapability.state !== "EDIT_QUALIFIED" && <p className="mt-3 text-xs text-amber-200">VIEW only — technical readiness does not grant EDIT authority. {detail.editCapability.blockers.join(" ")}</p>}{finding && <p className="mt-2 text-xs text-zinc-400">Validation: {finding}</p>}</div>
      {detail.availability !== "current_available" ? <div className="mt-5 rounded-xl border border-amber-400/35 bg-amber-400/10 p-5" role="alert"><p className="font-semibold text-amber-200">{detail.availability === "unavailable_quarantined" ? "Unavailable / Quarantined" : "Unavailable"}</p>{detail.findings.map(item => <p key={item} className="mt-2 text-sm text-amber-50">{item}</p>)}<p className="mt-3 text-sm text-zinc-300">Editing, Suggested Calibration, reconstruction mutation and flashing eligibility are prohibited.</p></div> : view === "grid" ? <div className="mt-5 overflow-auto"><table className="w-full border-collapse text-right font-mono text-xs"><tbody>{Array.from({ length: detail.rows }, (_, row) => <tr key={row}>{detail.cells.filter(item => item.row === row).map(item => { const address = { definitionRevision: detail.definitionRevision, occurrence: detail.occurrence, index: item.index, row: item.row, column: item.column }, delta = working ? workingCellDelta(working, address) : null, value = working ? workingCellValue(working, address) ?? item.currentValue : item.currentValue; return <td key={item.index} onClick={(event) => selectCell(item.index, event.shiftKey)} className={`cursor-pointer border p-2 ${selectedCells.includes(item.index) ? "border-blue-400 bg-blue-400/15" : delta?.delta ? "border-emerald-500/40 bg-emerald-500/10" : "border-zinc-800"}`}><span className="block">{shown(value)}</span>{delta?.delta ? <span className="block text-[9px] text-emerald-300">CUR {shown(item.currentValue)}</span> : null}</td>; })}</tr>)}</tbody></table><p className="mt-2 text-xs text-zinc-500">Shift-click selects a rectangular region.</p></div> : <CurrentPlot detail={detail} perspective={view === "3d"} working={working}/>}</main>
    <aside className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-300">Cell Inspector</p>{cell ? <dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><dt className="text-zinc-500">Row / column</dt><dd>{cell.row} / {cell.column}</dd><dt className="text-zinc-500">Current</dt><dd>{shown(cell.currentValue)} {cell.units}</dd><dt className="text-zinc-500">Working</dt><dd>{working ? shown(workingCellValue(working, { definitionRevision: detail.definitionRevision, occurrence: detail.occurrence, index: cell.index, row: cell.row, column: cell.column }) ?? cell.currentValue) : "Not created"}</dd><dt className="text-zinc-500">Delta</dt><dd>{working ? shown(workingCellDelta(working, { definitionRevision: detail.definitionRevision, occurrence: detail.occurrence, index: cell.index, row: cell.row, column: cell.column })?.delta ?? 0) : "Unavailable"}</dd><dt className="text-zinc-500">Raw</dt><dd>{shown(cell.currentRawValue)}</dd><dt className="text-zinc-500">Offset</dt><dd className="font-mono">0x{cell.currentRawOffset.toString(16)}</dd><dt className="text-zinc-500">Reference</dt><dd>Not established</dd></dl> : <p className="mt-4 text-sm text-zinc-500">No qualified cell is available.</p>}<h3 className="mt-6 font-semibold">Table Information</h3><p className="mt-2 break-all font-mono text-xs text-zinc-500">{detail.definitionRevision}</p>{detail.provenance.map(item => <p key={item} className="mt-2 text-xs text-zinc-400">{item}</p>)}</aside>
  </section>;
}

function CurrentPlot({ detail, perspective, working }: { detail: CurrentOnlyDefinition; perspective: boolean; working: WorkingCalibration | null }) {
  const values = detail.cells.map(item => working ? workingCellValue(working, { definitionRevision: detail.definitionRevision, occurrence: detail.occurrence, index: item.index, row: item.row, column: item.column }) ?? item.currentValue : item.currentValue), minimum = Math.min(...values), maximum = Math.max(...values), span = maximum - minimum || 1;
  const points = values.map((value, index) => `${(index / Math.max(1, values.length - 1)) * 100},${95 - ((value - minimum) / span) * 85}`).join(" ");
  return <div className={`mt-5 rounded-xl border border-zinc-800 bg-black p-4 ${perspective ? "[transform:perspective(900px)_rotateX(18deg)]" : ""}`}><svg role="img" aria-label={perspective ? `${working ? "Working" : "Current"} 3D Table visualization` : `${working ? "Working" : "Current"} 2D Table visualization`} viewBox="0 0 100 100" className="h-[420px] w-full" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="#60a5fa" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/></svg><p className="mt-2 text-xs text-zinc-500">{working ? "Working values with immutable Current baseline" : "Current engineering values only"} · Reference and comparison unavailable</p></div>;
}
