"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { filterCurrentOnlyDefinitions, currentOnlyVisualization, type CurrentOnlyDefinition, type CurrentOnlyWorkshopViewModel } from "@/lib/calibration-workshop/currentOnlyViewModel";
import { buildWorkshopDeepLink } from "@/lib/calibration-workshop/workshopNavigation";
import { applyWorkingEdit, createWorkingCalibration, previewWorkingEdit, redoWorkingEdit, undoWorkingEdit, workingCellDelta, workingCellValue, workingChangedDefinitionKeys, type WorkingCalibration, type WorkingEditOperation } from "@/lib/calibration-workshop/workingCalibration";
import { createBrowserWorkingCalibrationStore } from "@/lib/calibration-workshop/workingCalibrationPersistence";
import WorkingCalibrationPanel, { type CalibrationDisplayMode } from "./working-calibration-panel";

type Availability = "all" | CurrentOnlyDefinition["availability"];
const filters: readonly Readonly<{ id: Availability; label: string }>[] = Object.freeze([{ id: "all", label: "All Tables" }, { id: "current_available", label: "Current available" }, { id: "unavailable", label: "Unavailable" }, { id: "unavailable_quarantined", label: "Quarantined" }]);
const shown = (value: number) => Number.isInteger(value) ? value.toLocaleString() : Number(value.toPrecision(7)).toLocaleString();

export default function CurrentOnlyWorkshopClient({ workshop, vehicleId, ownerScope, subscriberSession }: { workshop: CurrentOnlyWorkshopViewModel; vehicleId: string; ownerScope: string; subscriberSession?: string }) {
  const [search, setSearch] = useState(""), [filter, setFilter] = useState<Availability>("all"), [view, setView] = useState<"grid" | "2d" | "3d">("grid"), [selectedCells, setSelectedCells] = useState<readonly number[]>([0]), [working, setWorking] = useState<WorkingCalibration | null>(null), [displayMode, setDisplayMode] = useState<CalibrationDisplayMode>("current"), [operation, setOperation] = useState<WorkingEditOperation>("assign"), [operand, setOperand] = useState(""), [saveStatus, setSaveStatus] = useState<"loading" | "saved" | "not-created">("loading");
  const definitions = useMemo(() => filterCurrentOnlyDefinitions(workshop.definitions, search, filter), [workshop.definitions, search, filter]);
  const detail = workshop.selectedDefinition, visual = useMemo(() => currentOnlyVisualization(detail), [detail]), selectedCell = selectedCells[0] ?? 0, cell = detail.cells[selectedCell] ?? detail.cells[0] ?? null;
  const scope = useMemo(() => ({ ownerScope, vehicleId, currentDatasetId: workshop.source.currentDatasetId }), [ownerScope, vehicleId, workshop.source.currentDatasetId]);
  const resolveWorkingDefinition = useCallback((definitionRevision: string, occurrence: number) => { const definition = workshop.definitions.find((item) => item.definitionRevision === definitionRevision && item.occurrence === occurrence); return definition ? { definitionRevision, occurrence, rows: definition.rows, columns: definition.columns, availability: definition.availability === "current_available" ? "available" as const : definition.availability === "unavailable_quarantined" ? "quarantined" as const : "unavailable" as const, capability: definition.editCapability, cells: definition.cells.map((item) => ({ definitionRevision, occurrence, index: item.index, row: item.row, column: item.column, currentValue: item.currentValue, units: item.units })) } : undefined; }, [workshop.definitions]);
  const activeWorkingDefinition = useMemo(() => resolveWorkingDefinition(detail.definitionRevision, detail.occurrence), [detail.definitionRevision, detail.occurrence, resolveWorkingDefinition]);
  const newWorking = useCallback((createdAt = new Date().toISOString()) => createWorkingCalibration({ ownerScope, vehicleId, currentDatasetId: workshop.source.currentDatasetId, currentDatasetRevision: workshop.source.currentDatasetRevision, romLayoutId: workshop.source.romLayoutId, relationshipRevision: workshop.source.relationshipRevision, definitionSetRevision: workshop.source.definitionSetRevision, createdAt }), [ownerScope, vehicleId, workshop.source]);
  useEffect(() => { const seed = newWorking("2000-01-01T00:00:00.000Z"), restored = createBrowserWorkingCalibrationStore(window.localStorage).load(scope, seed, resolveWorkingDefinition); setWorking(restored); setDisplayMode(restored ? "working" : "current"); setSaveStatus(restored ? "saved" : "not-created"); }, [scope, newWorking, resolveWorkingDefinition]);
  useEffect(() => { if (working) { createBrowserWorkingCalibrationStore(window.localStorage).save(working); setSaveStatus("saved"); } }, [working]);
  const createWorking = () => { setWorking(newWorking()); setDisplayMode("working"); };
  const selectCell = (index: number, region: boolean) => { if (!region || selectedCells.length === 0) { setSelectedCells([index]); return; } const anchor = detail.cells[selectedCells[0]!]!, target = detail.cells[index]!; const minRow = Math.min(anchor.row, target.row), maxRow = Math.max(anchor.row, target.row), minColumn = Math.min(anchor.column, target.column), maxColumn = Math.max(anchor.column, target.column); setSelectedCells(detail.cells.filter((item) => item.row >= minRow && item.row <= maxRow && item.column >= minColumn && item.column <= maxColumn).map((item) => item.index)); };
  const targets = useMemo(() => selectedCells.flatMap(index => { const selected = detail.cells[index]; return selected ? [{ definitionRevision: detail.definitionRevision, occurrence: detail.occurrence, index, row: selected.row, column: selected.column }] : []; }), [detail, selectedCells]);
  const preview = useMemo(() => working && operand.trim() && activeWorkingDefinition ? previewWorkingEdit(working, { operation, operand: Number(operand), targets, definitions: [activeWorkingDefinition] }) : null, [working, operation, operand, targets, activeWorkingDefinition]);
  const changedDefinitionKeys = useMemo(() => new Set(working ? workingChangedDefinitionKeys(working) : []), [working]);
  const apply = () => { if (!working || !preview || preview.validation === "BLOCKED" || !activeWorkingDefinition) return; const result = applyWorkingEdit(working, { operation, operand: Number(operand), targets, definitions: [activeWorkingDefinition], updatedAt: new Date().toISOString() }); if (result.status === "applied") { setWorking(result.calibration); setSaveStatus("saved"); } };
  return <section className="grid gap-4 xl:grid-cols-[320px_minmax(0,1fr)_320px]">
    <aside className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-300">Table Explorer</p><input aria-label="Search Tables" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search Tables" className="mt-3 w-full rounded-lg border border-zinc-700 bg-black px-3 py-2 text-sm"/><div className="mt-3 flex flex-wrap gap-2">{filters.map(item => <button key={item.id} type="button" onClick={() => setFilter(item.id)} className={`rounded-lg border px-2 py-1 text-xs ${filter === item.id ? "border-blue-400 text-blue-200" : "border-zinc-700 text-zinc-400"}`}>{item.label}</button>)}</div><div className="mt-4 max-h-[700px] space-y-1 overflow-auto">{definitions.map(item => { const changed = changedDefinitionKeys.has(`${item.definitionRevision}:${item.occurrence}`); return <Link key={item.key} href={buildWorkshopDeepLink({ vehicleId, subscriberSession, definition: item.key })} className={`block rounded-lg border p-3 text-sm ${item.key === detail.key ? "border-blue-400/50 bg-blue-400/10" : changed ? "border-emerald-400/30 bg-emerald-400/5" : "border-zinc-800"}`}><span className="block font-medium">{item.title}</span><span className="mt-1 flex gap-2 text-xs text-zinc-500"><span>{item.availability.replaceAll("_", " ")}</span>{changed && <span className="text-emerald-300">Working changes</span>}{item.editCapability.state !== "EDIT_QUALIFIED" && <span className="text-amber-300">Non-editable</span>}</span></Link>; })}</div></aside>
    <main className="bmw-border min-w-0 rounded-2xl bg-zinc-950 p-5"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-zinc-800 pb-4"><div><p className="text-xs uppercase tracking-[.16em] text-blue-300">{displayMode === "working" ? "Working Calibration" : "Current Calibration · Immutable"}</p><h2 className="mt-1 text-xl font-semibold">{detail.title}</h2><p className="mt-1 text-xs text-zinc-500">{detail.rows} × {detail.columns} · {detail.units ?? "units not supplied"}</p></div><div className="flex rounded-lg border border-zinc-700 p-1">{(["grid", "2d", "3d"] as const).map(mode => { const enabled = visual.capabilities[mode === "2d" ? "twoDimensional" : mode === "3d" ? "threeDimensional" : "grid"]; return <button key={mode} type="button" disabled={!enabled} onClick={() => setView(mode)} className={`rounded px-4 py-2 text-xs font-semibold ${view === mode ? "bg-blue-500/20 text-blue-200" : enabled ? "text-zinc-400" : "text-zinc-700"}`}>{mode === "grid" ? "Grid" : mode.toUpperCase()}</button>; })}</div></div>
      <WorkingCalibrationPanel mode={displayMode} onMode={setDisplayMode} working={working} onCreate={createWorking} onUndo={() => working && setWorking(undoWorkingEdit(working, new Date().toISOString()))} onRedo={() => working && setWorking(redoWorkingEdit(working, new Date().toISOString()))} operation={operation} onOperation={setOperation} operand={operand} onOperand={setOperand} preview={preview} onApply={apply} selectedCount={selectedCells.length} definitionTitles={Object.fromEntries(workshop.definitions.map(item => [`${item.definitionRevision}:${item.occurrence}`, item.title]))} editQualified={detail.editCapability.state === "EDIT_QUALIFIED"} blockers={detail.editCapability.blockers} warnings={detail.editCapability.warnings} saveStatus={saveStatus}/>
      {detail.availability !== "current_available" ? <div className="mt-5 rounded-xl border border-amber-400/35 bg-amber-400/10 p-5" role="alert"><p className="font-semibold text-amber-200">{detail.availability === "unavailable_quarantined" ? "Unavailable / Quarantined" : "Unavailable"}</p>{detail.findings.map(item => <p key={item} className="mt-2 text-sm text-amber-50">{item}</p>)}<p className="mt-3 text-sm text-zinc-300">Editing, Suggested Calibration, reconstruction mutation and flashing eligibility are prohibited.</p></div> : view === "grid" ? <div className="mt-5 overflow-auto"><table className="w-full border-collapse text-right font-mono text-xs"><tbody>{Array.from({ length: detail.rows }, (_, row) => <tr key={row}>{detail.cells.filter(item => item.row === row).map(item => { const address = { definitionRevision: detail.definitionRevision, occurrence: detail.occurrence, index: item.index, row: item.row, column: item.column }, delta = working ? workingCellDelta(working, address) : null, value = displayMode === "working" && working ? workingCellValue(working, address) ?? item.currentValue : item.currentValue; return <td key={item.index} className="p-0.5"><button type="button" aria-label={`Cell row ${item.row} column ${item.column}`} onPointerDown={(event) => selectCell(item.index, event.shiftKey)} onPointerEnter={(event) => { if (event.buttons === 1) selectCell(item.index, true); }} onKeyDown={(event) => { const step = event.key === "ArrowLeft" ? -1 : event.key === "ArrowRight" ? 1 : event.key === "ArrowUp" ? -detail.columns : event.key === "ArrowDown" ? detail.columns : 0; if (step) { event.preventDefault(); const next = Math.max(0, Math.min(detail.cells.length - 1, item.index + step)); selectCell(next, event.shiftKey); document.querySelector<HTMLButtonElement>(`[data-working-cell="${next}"]`)?.focus(); } }} data-working-cell={item.index} className={`w-full min-w-24 rounded border p-2 text-right ${selectedCells.includes(item.index) ? "border-blue-400 bg-blue-400/15" : delta?.delta ? "border-emerald-500/40 bg-emerald-500/10" : "border-zinc-800"}`}><span className="block">{shown(value)}</span>{delta?.delta ? <span className="block text-[9px] text-emerald-300">CURRENT {shown(item.currentValue)}</span> : null}</button></td>; })}</tr>)}</tbody></table><p className="mt-2 text-xs text-zinc-500">Drag or Shift-click selects a rectangular region. Arrow keys move by governed cell coordinates; hold Shift to extend.</p></div> : <CurrentPlot detail={detail} perspective={view === "3d"} working={displayMode === "working" ? working : null}/>}</main>
    <aside className="rounded-2xl border border-zinc-800 bg-zinc-950 p-4"><p className="text-xs font-semibold uppercase tracking-[.16em] text-blue-300">Cell Inspector</p>{cell ? (() => { const delta = working ? workingCellDelta(working, { definitionRevision: detail.definitionRevision, occurrence: detail.occurrence, index: cell.index, row: cell.row, column: cell.column }) : null; return <dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><dt className="text-zinc-500">Row / column</dt><dd>{cell.row} / {cell.column}</dd><dt className="text-zinc-500">Current</dt><dd>{shown(cell.currentValue)} {cell.units}</dd><dt className="text-zinc-500">Working</dt><dd>{working ? shown(delta?.working ?? cell.currentValue) : "Not created"}</dd><dt className="text-zinc-500">Delta</dt><dd>{delta ? shown(delta.delta) : "Unavailable"}</dd><dt className="text-zinc-500">Percentage delta</dt><dd>{delta?.percentageDelta === null ? "Undefined from zero" : delta ? `${shown(delta.percentageDelta)}%` : "Unavailable"}</dd><dt className="text-zinc-500">Raw representation</dt><dd>{shown(cell.currentRawValue)}</dd><dt className="text-zinc-500">EDIT capability</dt><dd>{detail.editCapability.state}</dd><dt className="text-zinc-500">Reference</dt><dd>Not established</dd></dl>; })() : <p className="mt-4 text-sm text-zinc-500">No qualified cell is available.</p>}<h3 className="mt-6 font-semibold">Table Information</h3><p className="mt-2 break-all font-mono text-xs text-zinc-500">{detail.definitionRevision}</p>{[...detail.editCapability.warnings, ...detail.editCapability.blockers].map(item => <p key={item} className="mt-2 text-xs text-amber-200">{item}</p>)}{detail.provenance.map(item => <p key={item} className="mt-2 text-xs text-zinc-400">{item}</p>)}</aside>
  </section>;
}

function CurrentPlot({ detail, perspective, working }: { detail: CurrentOnlyDefinition; perspective: boolean; working: WorkingCalibration | null }) {
  const values = detail.cells.map(item => working ? workingCellValue(working, { definitionRevision: detail.definitionRevision, occurrence: detail.occurrence, index: item.index, row: item.row, column: item.column }) ?? item.currentValue : item.currentValue), minimum = Math.min(...values), maximum = Math.max(...values), span = maximum - minimum || 1;
  const points = values.map((value, index) => `${(index / Math.max(1, values.length - 1)) * 100},${95 - ((value - minimum) / span) * 85}`).join(" ");
  return <div className={`mt-5 rounded-xl border border-zinc-800 bg-black p-4 ${perspective ? "[transform:perspective(900px)_rotateX(18deg)]" : ""}`}><svg role="img" aria-label={perspective ? `${working ? "Working" : "Current"} 3D Table visualization` : `${working ? "Working" : "Current"} 2D Table visualization`} viewBox="0 0 100 100" className="h-[420px] w-full" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="#60a5fa" strokeWidth="1.5" vectorEffect="non-scaling-stroke"/></svg><p className="mt-2 text-xs text-zinc-500">{working ? "Working values with immutable Current baseline" : "Current engineering values only"} · Reference and comparison unavailable</p></div>;
}
