import { defineCalibrationKnowledgeObject, type CalibrationApplicability, type CalibrationKnowledgeObject, type GovernedVocabularyReference, type KnowledgeEvidenceReference, type KnowledgeProvenanceReference, type QualifiedAssertion } from "./calibrationKnowledge.ts";
import { defineCalibrationKnowledgeLookupResult, defineCalibrationKnowledgeQuery, type CalibrationKnowledgeApplicabilityConflictEvidence, type CalibrationKnowledgeCandidate, type CalibrationKnowledgeLookupResult, type CalibrationKnowledgeQuery, type CalibrationKnowledgeQuerySelector, type CalibrationKnowledgeReader } from "./calibrationKnowledgeLookup.ts";
import { isAuthoritativeStockVariantStatus, type KnowledgeConfidenceState } from "./stockVariants.ts";

export type ImmutableCalibrationKnowledgeRegistry = CalibrationKnowledgeReader;
type MatchKind = "canonical_identity" | "qualified_alias" | "source_reference";
type ExactMatch = Readonly<{ knowledge: CalibrationKnowledgeObject; assertion: QualifiedAssertion<unknown>; selector: CalibrationKnowledgeQuerySelector; kind: MatchKind }>;
type ExactCandidate = Readonly<{ candidateId: string; matches: readonly ExactMatch[] }>;
type ExactMatchCollection = Readonly<{ query: CalibrationKnowledgeQuery; candidates: readonly ExactCandidate[] }>;
type MaterialComponent = Readonly<{ role: "canonical_identity" | "canonical_applicability" | "matched_assertion" | "query_selector" | "query_context"; kind: MatchKind | "query_context"; assertion: QualifiedAssertion<unknown>; contributors: readonly QualifiedAssertion<unknown>[] }>;
type MaterialCandidate = Readonly<{ candidateId: string; knowledge: CalibrationKnowledgeObject; matches: readonly ExactMatch[]; components: readonly MaterialComponent[] }>;
type MaterialComponentCollection = Readonly<{ query: CalibrationKnowledgeQuery; candidates: readonly MaterialCandidate[] }>;
type Qualification = Readonly<{ currentAuthoritative: boolean; matchKinds: readonly MatchKind[]; selectorIds: readonly string[]; provenance: readonly KnowledgeProvenanceReference[]; supportingEvidence: readonly KnowledgeEvidenceReference[]; contradictoryEvidence: readonly KnowledgeEvidenceReference[]; conflictState: "none" | "unresolved" | "resolved"; limitations: readonly string[] }>;
type QualifiedCandidate = MaterialCandidate & Readonly<{ qualification: Qualification }>;
type QualificationAssessment = Readonly<{ query: CalibrationKnowledgeQuery; candidates: readonly QualifiedCandidate[] }>;
type Applicability = Readonly<{ aggregate: CalibrationApplicability; assessment: QualifiedAssertion<CalibrationApplicability>; authoritative: boolean; contextContradictions: readonly string[]; internalConflicts: readonly CalibrationKnowledgeApplicabilityConflictEvidence[] }>;
type ApplicableCandidate = QualifiedCandidate & Readonly<{ applicability: Applicability }>;
type ApplicabilityAssessment = Readonly<{ query: CalibrationKnowledgeQuery; candidates: readonly ApplicableCandidate[] }>;
type ConfidentCandidate = ApplicableCandidate & Readonly<{ aggregateConfidence: KnowledgeConfidenceState }>;
type ConfidenceAssessment = Readonly<{ query: CalibrationKnowledgeQuery; candidates: readonly ConfidentCandidate[] }>;
type EvaluatedCandidate = ConfidentCandidate & Readonly<{ contradictoryAssertionIds: readonly string[] }>;
type ConflictEvaluation = Readonly<{ query: CalibrationKnowledgeQuery; candidates: readonly EvaluatedCandidate[]; selectorConflictAssertionIds: readonly string[] }>;

const contextFields: Readonly<Record<string, keyof Omit<CalibrationApplicability, "scope" | "unresolvedReason">>> = Object.freeze({ platform: "platforms", engine_family: "engineFamilies", ecu_family: "ecuFamilies", dme_variant: "dmeVariants", control_strategy: "controlStrategies", rom_family: "romFamilies", software_version: "softwareVersions", calibration_id: "calibrationIds", stock_variant: "stockVariantIds", operating_mode: "operatingModes", transmission: "transmissions", region: "regions", emissions_specification: "emissionsSpecifications", hardware_configuration: "hardwareConfigurations", source_reference: "sourceReferenceIds" });
const confidenceOrder: Readonly<Record<KnowledgeConfidenceState, number>> = Object.freeze({ unknown: 0, low: 1, medium: 2, high: 3 });
const verificationOrder = Object.freeze({ unknown: 0, rejected: 1, disputed: 2, deprecated: 3, superseded: 4, observed: 5, candidate: 6, provisional: 7, verified: 8, founder_verified: 9, authoritatively_verified: 10 } as const);
const lifecycleOrder = Object.freeze({ rejected: 0, superseded: 1, deprecated: 2, active: 3 } as const);
function stableIdentity(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableIdentity).join(",")}]`; if (value !== null && typeof value === "object") return `{${Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => `${JSON.stringify(key)}:${stableIdentity(item)}`).join(",")}}`; return JSON.stringify(value); }
function deepFreeze<T>(value: T): T { if (value !== null && typeof value === "object" && !Object.isFrozen(value)) { Object.values(value).forEach((item) => deepFreeze(item)); Object.freeze(value); } return value; }
function uniqueBy<T>(values: readonly T[], key: (value: T) => string): readonly T[] { const seen = new Set<string>(); return values.filter((value) => { const id = key(value); if (seen.has(id)) return false; seen.add(id); return true; }); }
const provenanceIdentity = (value: KnowledgeProvenanceReference) => stableIdentity(value);
const evidenceIdentity = (value: KnowledgeEvidenceReference) => stableIdentity(value);
function vocabulary(kind: MatchKind): GovernedVocabularyReference { return { vocabularyId: "calibration-knowledge-match-basis", vocabularyVersion: "1", termId: kind, label: kind.replaceAll("_", " "), recognition: "known" }; }
function sameVocabulary(a: GovernedVocabularyReference, b: GovernedVocabularyReference): boolean { return a.vocabularyId === b.vocabularyId && a.vocabularyVersion === b.vocabularyVersion && a.termId === b.termId; }
function canonicalApplicability(value: CalibrationApplicability): CalibrationApplicability { const strings = (items: readonly string[]) => [...new Set(items)].sort(); return { ...value, platforms: strings(value.platforms), engineFamilies: strings(value.engineFamilies), ecuFamilies: strings(value.ecuFamilies), dmeVariants: strings(value.dmeVariants), controlStrategies: strings(value.controlStrategies), romFamilies: strings(value.romFamilies), softwareVersions: strings(value.softwareVersions), calibrationIds: strings(value.calibrationIds), stockVariantIds: strings(value.stockVariantIds), operatingModes: strings(value.operatingModes), transmissions: strings(value.transmissions), regions: strings(value.regions), emissionsSpecifications: strings(value.emissionsSpecifications), hardwareConfigurations: strings(value.hardwareConfigurations), sourceReferenceIds: strings(value.sourceReferenceIds) }; }
function canonicalAssertion<T>(assertion: QualifiedAssertion<T>): QualifiedAssertion<T> { return { ...assertion, provenance: [...assertion.provenance].sort((a, b) => provenanceIdentity(a).localeCompare(provenanceIdentity(b))), supportingEvidence: [...assertion.supportingEvidence].sort((a, b) => evidenceIdentity(a).localeCompare(evidenceIdentity(b))), contradictoryEvidence: [...assertion.contradictoryEvidence].sort((a, b) => evidenceIdentity(a).localeCompare(evidenceIdentity(b))), applicability: canonicalApplicability(assertion.applicability), lifecycle: { ...assertion.lifecycle, supersedesIds: assertion.lifecycle.supersedesIds ? [...assertion.lifecycle.supersedesIds].sort() : undefined } }; }
function canonicalKnowledge(value: CalibrationKnowledgeObject): CalibrationKnowledgeObject { const assertions = <T>(items: readonly QualifiedAssertion<T>[]) => items.map(canonicalAssertion).sort((a, b) => stableIdentity([a.assertionId, a]).localeCompare(stableIdentity([b.assertionId, b]))); return defineCalibrationKnowledgeObject({ ...value, identity: canonicalAssertion(value.identity), canonicalName: canonicalAssertion(value.canonicalName), aliases: assertions(value.aliases), purposes: assertions(value.purposes), engineeringIntents: assertions(value.engineeringIntents), calibrationKind: canonicalAssertion(value.calibrationKind), primarySubsystem: canonicalAssertion(value.primarySubsystem), relatedSubsystems: assertions(value.relatedSubsystems), applicability: canonicalAssertion(value.applicability), sourceRepresentations: assertions(value.sourceRepresentations), directionalBehaviours: assertions(value.directionalBehaviours), relationships: assertions(value.relationships), provenance: [...value.provenance].sort((a, b) => provenanceIdentity(a).localeCompare(provenanceIdentity(b))) }); }
function unknownApplicability(reason: string): CalibrationApplicability { return { scope: { vocabularyId: "calibration-applicability-scope", vocabularyVersion: "1", termId: "unknown", label: "unknown", recognition: "unknown" }, platforms: [], engineFamilies: [], ecuFamilies: [], dmeVariants: [], controlStrategies: [], romFamilies: [], softwareVersions: [], calibrationIds: [], stockVariantIds: [], operatingModes: [], transmissions: [], regions: [], emissionsSpecifications: [], hardwareConfigurations: [], sourceReferenceIds: [], unresolvedReason: reason }; }

// Stage 1: exact matching only.
function exactMatches(record: CalibrationKnowledgeObject, selector: CalibrationKnowledgeQuerySelector): readonly ExactMatch[] { const value = selector.value; if (!value) return []; if (value.kind === "canonical_identity") return record.identity.value?.stableId === value.stableId ? [deepFreeze({ knowledge: record, assertion: record.identity, selector, kind: value.kind })] : []; if (value.kind === "qualified_alias") return record.aliases.filter((item) => item.value?.name === value.alias).map((assertion) => deepFreeze({ knowledge: record, assertion, selector, kind: value.kind })); return record.sourceRepresentations.filter((item) => item.value?.sourceReferenceId === value.sourceReferenceId && item.value !== null && sameVocabulary(item.value.sourceType, value.sourceType)).map((assertion) => deepFreeze({ knowledge: record, assertion, selector, kind: value.kind })); }
function collectExactMatches(records: readonly CalibrationKnowledgeObject[], query: CalibrationKnowledgeQuery): ExactMatchCollection { const grouped = new Map<string, ExactMatch[]>(); for (const record of records) for (const selector of query.selectors) for (const match of exactMatches(record, selector)) { const id = record.identity.value?.stableId; if (!id) throw new Error("Registered Calibration Knowledge lost canonical identity."); grouped.set(id, [...(grouped.get(id) ?? []), match]); } const candidates = [...grouped.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([candidateId, matches]) => ({ candidateId, matches: [...matches].sort((a, b) => stableIdentity([a.kind, a.assertion.assertionId, a.selector.assertionId]).localeCompare(stableIdentity([b.kind, b.assertion.assertionId, b.selector.assertionId]))) })); return deepFreeze({ query, candidates }); }

// Stage 2: canonical material components, collected once.
function representationIdentity(match: ExactMatch): string { if (match.kind === "qualified_alias") return stableIdentity([match.kind, match.assertion.value]); if (match.kind === "source_reference") { const value = match.assertion.value as Readonly<{ sourceReferenceId?: string; sourceType?: GovernedVocabularyReference }> | null; return stableIdentity([match.kind, value?.sourceReferenceId, value?.sourceType?.vocabularyId, value?.sourceType?.vocabularyVersion, value?.sourceType?.termId]); } return stableIdentity([match.kind, match.assertion.assertionId]); }
function mergeRepresentationAssertions(assertions: readonly QualifiedAssertion<unknown>[]): QualifiedAssertion<unknown> { const ordered = [...assertions].sort((a, b) => stableIdentity(a).localeCompare(stableIdentity(b))); const first = ordered[0]; if (!first) throw new Error("Semantic representation requires a qualified assertion."); const confidence = ordered.reduce<KnowledgeConfidenceState>((lowest, item) => confidenceOrder[item.confidence] < confidenceOrder[lowest] ? item.confidence : lowest, "high"); const verificationStatus = ordered.reduce((weakest, item) => verificationOrder[item.verificationStatus] < verificationOrder[weakest] ? item.verificationStatus : weakest, first.verificationStatus); const lifecycleStatus = ordered.reduce((weakest, item) => lifecycleOrder[item.lifecycle.status] < lifecycleOrder[weakest] ? item.lifecycle.status : weakest, first.lifecycle.status); const applicabilityValues = uniqueBy(ordered.map((item) => item.applicability), stableIdentity); const applicability = applicabilityValues.length === 1 ? applicabilityValues[0] : unknownApplicability("Semantic duplicate representations carry different applicability qualification."); const unresolvedReasons = [...new Set(ordered.map((item) => item.unresolvedReason).filter((value): value is string => value !== null))].sort(); const conflictState = ordered.some((item) => item.conflictState === "unresolved") ? "unresolved" : ordered.some((item) => item.conflictState === "resolved") ? "resolved" : "none"; const allAuthoritative = ordered.every((item) => isAuthoritativeStockVariantStatus(item.verificationStatus) && item.authority !== null); const authorities = [...uniqueBy(ordered.map((item) => item.authority).filter((value) => value !== null), stableIdentity)].sort((a, b) => stableIdentity(a).localeCompare(stableIdentity(b))); return deepFreeze({ ...first, verificationStatus, confidence, authority: allAuthoritative ? authorities[0] ?? null : null, provenance: [...uniqueBy(ordered.flatMap((item) => item.provenance), provenanceIdentity)].sort((a, b) => provenanceIdentity(a).localeCompare(provenanceIdentity(b))), supportingEvidence: [...uniqueBy(ordered.flatMap((item) => item.supportingEvidence), evidenceIdentity)].sort((a, b) => evidenceIdentity(a).localeCompare(evidenceIdentity(b))), contradictoryEvidence: [...uniqueBy(ordered.flatMap((item) => item.contradictoryEvidence), evidenceIdentity)].sort((a, b) => evidenceIdentity(a).localeCompare(evidenceIdentity(b))), applicability, conflictState, unresolvedReason: unresolvedReasons.length ? unresolvedReasons.join(" | ") : applicabilityValues.length === 1 ? null : applicability.unresolvedReason, lifecycle: { ...first.lifecycle, status: lifecycleStatus, supersedesIds: [...new Set(ordered.flatMap((item) => item.lifecycle.supersedesIds ?? []))].sort() } }); }
function collectMaterialComponents(input: ExactMatchCollection): MaterialComponentCollection { const candidates = input.candidates.map((candidate): MaterialCandidate => { const knowledge = candidate.matches[0]?.knowledge; if (!knowledge) throw new Error("Calibration candidate requires an exact match."); const groups = new Map<string, ExactMatch[]>(); candidate.matches.filter((match) => match.kind !== "canonical_identity").forEach((match) => { const key = representationIdentity(match); groups.set(key, [...(groups.get(key) ?? []), match]); }); const matched = [...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([, matches]): MaterialComponent => { const assertions = [...uniqueBy(matches.map((match) => match.assertion), (assertion) => assertion.assertionId)].sort((a, b) => stableIdentity(a).localeCompare(stableIdentity(b))); return { role: "matched_assertion", kind: matches[0]?.kind ?? "qualified_alias", assertion: mergeRepresentationAssertions(assertions), contributors: assertions }; }); const selectors = uniqueBy(candidate.matches.map((match) => ({ role: "query_selector" as const, kind: match.kind, assertion: match.selector, contributors: [match.selector] })), (item) => item.assertion.assertionId); const raw: readonly MaterialComponent[] = [{ role: "canonical_identity", kind: "canonical_identity", assertion: knowledge.identity, contributors: [knowledge.identity] }, { role: "canonical_applicability", kind: "canonical_identity", assertion: knowledge.applicability, contributors: [knowledge.applicability] }, ...matched, ...selectors, ...input.query.context.assertions.map((assertion) => ({ role: "query_context" as const, kind: "query_context" as const, assertion, contributors: [assertion] }))]; const components = [...raw].sort((a, b) => stableIdentity([a.role, a.kind, a.assertion.assertionId, a.assertion]).localeCompare(stableIdentity([b.role, b.kind, b.assertion.assertionId, b.assertion]))); return { ...candidate, knowledge, components }; }); return deepFreeze({ query: input.query, candidates }); }

// Stage 3: qualification and lifecycle assessment only.
function assessQualification(input: MaterialComponentCollection): QualificationAssessment { const candidates = input.candidates.map((candidate): QualifiedCandidate => { const currentAuthoritative = candidate.components.every(({ assertion }) => isAuthoritativeStockVariantStatus(assertion.verificationStatus) && assertion.authority !== null && assertion.lifecycle.status === "active" && assertion.conflictState === "none" && assertion.unresolvedReason === null); const provenance = [...uniqueBy(candidate.components.flatMap(({ assertion }) => assertion.provenance), provenanceIdentity)].sort((a, b) => provenanceIdentity(a).localeCompare(provenanceIdentity(b))); const supportingEvidence = [...uniqueBy(candidate.components.flatMap(({ assertion }) => assertion.supportingEvidence), evidenceIdentity)].sort((a, b) => evidenceIdentity(a).localeCompare(evidenceIdentity(b))); const contradictoryEvidence = [...uniqueBy(candidate.components.flatMap(({ assertion }) => assertion.contradictoryEvidence), evidenceIdentity)].sort((a, b) => evidenceIdentity(a).localeCompare(evidenceIdentity(b))); const conflictState: Qualification["conflictState"] = candidate.components.some(({ assertion }) => assertion.conflictState === "unresolved") ? "unresolved" : candidate.components.some(({ assertion }) => assertion.conflictState === "resolved") ? "resolved" : "none"; const limitations = candidate.components.flatMap((item) => item.contributors.map((contributor) => `Match component ${item.kind}/${item.role}/${contributor.assertionId}; verification=${contributor.verificationStatus}; confidence=${contributor.confidence}; authority=${contributor.authority?.authorityType ?? "none"}:${contributor.authority?.authorityIdentifier ?? "none"}; lifecycle=${contributor.lifecycle.status}:${contributor.lifecycle.version}; conflict=${contributor.conflictState}; unresolved=${contributor.unresolvedReason ?? "none"}; applicability=${JSON.stringify(contributor.applicability)}.`)).sort(); const qualification = { currentAuthoritative, matchKinds: [...new Set(candidate.matches.map(({ kind }) => kind))].sort(), selectorIds: [...new Set(candidate.matches.map(({ selector }) => selector.assertionId))].sort(), provenance, supportingEvidence, contradictoryEvidence, conflictState, limitations }; return { ...candidate, qualification }; }); return deepFreeze({ query: input.query, candidates }); }

function applicabilityCanConflict(assertion: QualifiedAssertion<unknown>): boolean { return assertion.applicability.scope.recognition === "known" && assertion.applicability.unresolvedReason === null && assertion.unresolvedReason === null && assertion.verificationStatus !== "unknown" && assertion.verificationStatus !== "provisional"; }
function typedApplicabilityConflicts(components: readonly MaterialComponent[]): readonly CalibrationKnowledgeApplicabilityConflictEvidence[] { const eligible = components.filter(({ assertion }) => applicabilityCanConflict(assertion)); const conflicts: CalibrationKnowledgeApplicabilityConflictEvidence[] = []; for (let leftIndex = 0; leftIndex < eligible.length; leftIndex += 1) for (let rightIndex = leftIndex + 1; rightIndex < eligible.length; rightIndex += 1) { const left = eligible[leftIndex]; const right = eligible[rightIndex]; if (!left || !right) continue; for (const field of Object.values(contextFields)) { const leftValues = [...new Set(left.assertion.applicability[field])].sort(); const rightValues = [...new Set(right.assertion.applicability[field])].sort(); if (leftValues.length > 0 && rightValues.length > 0 && !leftValues.some((value) => rightValues.includes(value))) conflicts.push({ kind: "applicability_conflict", leftAssertionId: left.assertion.assertionId, rightAssertionId: right.assertion.assertionId, dimension: field, leftValues, rightValues, rationale: `Preserved ${field} applicability values are disjoint.` }); } } return Object.freeze([...uniqueBy(conflicts, stableIdentity)].sort((a, b) => stableIdentity(a).localeCompare(stableIdentity(b)))); }
function contextContradictions(candidate: MaterialCandidate): readonly string[] { const applicable = candidate.components.filter(({ role, assertion }) => role !== "query_context" && applicabilityCanConflict(assertion)).map(({ assertion }) => assertion.applicability); return Object.freeze(candidate.components.filter(({ role }) => role === "query_context").flatMap(({ assertion }) => { if (assertion.conflictState !== "none") return [assertion.assertionId]; if (!assertion.value || !applicabilityCanConflict(assertion)) return []; const value = assertion.value as Readonly<{ dimension?: GovernedVocabularyReference; values?: readonly string[] }>; if (!value.dimension || !value.values) return []; const field = contextFields[value.dimension.termId]; return field && applicable.some((scope) => scope[field].length > 0 && !value.values?.some((item) => scope[field].includes(item))) ? [assertion.assertionId] : []; }).sort()); }

// Stage 4: applicability assessment only.
function assessApplicability(input: QualificationAssessment): ApplicabilityAssessment { const candidates = input.candidates.map((candidate): ApplicableCandidate => { const values = [...uniqueBy([candidate.knowledge.applicability.value, ...candidate.components.map(({ assertion }) => assertion.applicability)].filter((value): value is CalibrationApplicability => value !== null), stableIdentity)].sort((a, b) => stableIdentity(a).localeCompare(stableIdentity(b))); const authoritative = candidate.qualification.currentAuthoritative && values.length === 1 && values[0]?.scope.recognition === "known" && values[0].unresolvedReason === null; const reason = candidate.knowledge.applicability.unresolvedReason ?? "Material match components do not establish one authoritative applicability scope."; const aggregate = authoritative && values[0] ? values[0] : unknownApplicability(reason); const assessment = { ...candidate.knowledge.applicability, assertionId: `applicability-assessment:${candidate.candidateId}`, value: aggregate, verificationStatus: authoritative ? candidate.knowledge.applicability.verificationStatus : "unknown" as const, confidence: authoritative ? candidate.knowledge.applicability.confidence : "unknown" as const, authority: authoritative ? candidate.knowledge.applicability.authority : null, unresolvedReason: authoritative ? null : aggregate.unresolvedReason }; const applicability = { aggregate, assessment, authoritative, contextContradictions: contextContradictions(candidate), internalConflicts: typedApplicabilityConflicts(candidate.components) }; return { ...candidate, applicability }; }); return deepFreeze({ query: input.query, candidates }); }

// Stage 5: conservative confidence assessment only.
function assessConfidence(input: ApplicabilityAssessment): ConfidenceAssessment { const candidates = input.candidates.map((candidate): ConfidentCandidate => { const aggregateConfidence = candidate.components.reduce<KnowledgeConfidenceState>((lowest, { assertion }) => confidenceOrder[assertion.confidence] < confidenceOrder[lowest] ? assertion.confidence : lowest, "high"); return { ...candidate, aggregateConfidence }; }); return deepFreeze({ query: input.query, candidates }); }

// Stage 6: conflict evaluation from completed assessments only.
function evaluateConflicts(input: ConfidenceAssessment): ConflictEvaluation { const candidates = input.candidates.map((candidate): EvaluatedCandidate => ({ ...candidate, contradictoryAssertionIds: [...new Set([...candidate.applicability.contextContradictions, ...candidate.applicability.internalConflicts.flatMap((item) => [item.leftAssertionId, item.rightAssertionId])])].sort() })); const targets = new Map<string, Set<string>>(); for (const candidate of candidates) for (const selectorId of candidate.qualification.selectorIds) targets.set(selectorId, new Set([...(targets.get(selectorId) ?? []), candidate.candidateId])); const uniqueTargets = [...targets.entries()].filter(([, ids]) => ids.size === 1).sort(([a], [b]) => a.localeCompare(b)); const selectorConflictAssertionIds = new Set(uniqueTargets.flatMap(([, ids]) => [...ids])).size > 1 ? uniqueTargets.map(([id]) => id) : []; return deepFreeze({ query: input.query, candidates, selectorConflictAssertionIds }); }

function buildCandidate(item: EvaluatedCandidate): CalibrationKnowledgeCandidate { const identity = item.knowledge.identity.value?.stableId; if (!identity) throw new Error("Registered Calibration Knowledge lost canonical identity."); const firstKind = item.qualification.matchKinds[0] ?? "canonical_identity"; const authoritative = item.qualification.currentAuthoritative && item.applicability.authoritative; return { candidateId: identity, knowledge: item.knowledge, matchBasis: { ...item.knowledge.identity, assertionId: `match-basis:${identity}`, value: { kind: item.qualification.matchKinds.length === 1 ? vocabulary(firstKind) : { ...vocabulary("canonical_identity"), termId: "combined_exact", label: "combined exact" }, matchScope: "exact", selectorIds: item.qualification.selectorIds, description: `Exact match through: ${item.qualification.matchKinds.join(", ")}.` }, verificationStatus: authoritative ? item.knowledge.identity.verificationStatus : "unknown", confidence: authoritative ? item.aggregateConfidence : "unknown", authority: authoritative ? item.knowledge.identity.authority : null, provenance: item.qualification.provenance, supportingEvidence: item.qualification.supportingEvidence, contradictoryEvidence: item.qualification.contradictoryEvidence, applicability: item.applicability.aggregate, conflictState: item.qualification.conflictState, unresolvedReason: authoritative ? null : "One or more exact match components remain below authoritative verification or do not establish one applicability scope." }, applicabilityAssessment: item.applicability.assessment, provenance: [...uniqueBy([...item.knowledge.provenance, ...item.qualification.provenance], provenanceIdentity)].sort((a, b) => provenanceIdentity(a).localeCompare(provenanceIdentity(b))), limitations: item.qualification.limitations }; }

// Stage 7: outcome construction from completed assessments only.
function constructOutcome(input: ConflictEvaluation): CalibrationKnowledgeLookupResult { const candidates = input.candidates.map(buildCandidate); const provenance = [...uniqueBy(candidates.flatMap((item) => item.provenance), provenanceIdentity)].sort((a, b) => provenanceIdentity(a).localeCompare(provenanceIdentity(b))); const common = { query: input.query, candidates, provenance, missingContext: [], limitations: [], contractVersion: input.query.contractVersion } as const; if (candidates.length === 0) return defineCalibrationKnowledgeLookupResult({ ...common, outcome: "unknown", candidates: [], unresolvedReason: "No canonical Calibration Knowledge answers the exact query selectors." }); const contradictions = input.candidates.flatMap((item) => item.contradictoryAssertionIds); if (contradictions.length > 0 || input.selectorConflictAssertionIds.length > 0) { const contradictoryAssertionIds = [...new Set([...contradictions, ...input.selectorConflictAssertionIds])].sort(); const applicabilityConflictEvidence = input.candidates.flatMap((item) => item.applicability.internalConflicts); return defineCalibrationKnowledgeLookupResult({ ...common, outcome: "conflict", conflicts: [{ conflictId: `conflict:${input.query.queryId}`, summary: "Exact Calibration Knowledge and qualified query evidence materially disagree.", candidateIds: candidates.map((item) => item.candidateId), contradictoryAssertionIds, provenance, unresolvedReason: "The contradiction requires authorised Knowledge resolution.", ...(applicabilityConflictEvidence.length ? { applicabilityConflictEvidence } : {}) }], unresolvedReason: "Material Calibration Knowledge conflict remains unresolved." }); } if (candidates.length > 1) return defineCalibrationKnowledgeLookupResult({ ...common, outcome: "multiple_candidates", unresolvedReason: "Multiple exact qualified candidates remain viable without material contradiction." }); const match = candidates[0]; const authoritative = [match.knowledge.identity.verificationStatus, match.matchBasis.verificationStatus, match.applicabilityAssessment.verificationStatus].every(isAuthoritativeStockVariantStatus); return defineCalibrationKnowledgeLookupResult(authoritative ? { ...common, outcome: "exact_verified", match, unresolvedReason: null } : { ...common, outcome: "exact_candidate", match, unresolvedReason: "Exact Calibration Knowledge exists but required authority remains incomplete." }); }

function performLookup(records: readonly CalibrationKnowledgeObject[], input: CalibrationKnowledgeQuery): CalibrationKnowledgeLookupResult { let query: CalibrationKnowledgeQuery; try { const validated = defineCalibrationKnowledgeQuery(input); query = defineCalibrationKnowledgeQuery({ ...validated, selectors: [...validated.selectors].sort((a, b) => stableIdentity(a).localeCompare(stableIdentity(b))), context: { assertions: [...validated.context.assertions].sort((a, b) => stableIdentity(a).localeCompare(stableIdentity(b))) } }); } catch (error) { const message = error instanceof Error ? error.message : "Calibration Knowledge query is invalid."; return defineCalibrationKnowledgeLookupResult({ outcome: "invalid", queryInput: input, candidates: [], validationIssues: [message], unresolvedReason: "Calibration Knowledge lookup was not executed because the query is invalid.", provenance: [], missingContext: [], limitations: [], contractVersion: "1" }); } const stage1 = collectExactMatches(records, query); const stage2 = collectMaterialComponents(stage1); const stage3 = assessQualification(stage2); const stage4 = assessApplicability(stage3); const stage5 = assessConfidence(stage4); const stage6 = evaluateConflicts(stage5); return constructOutcome(stage6); }

export function createImmutableCalibrationKnowledgeRegistry(records: readonly CalibrationKnowledgeObject[] = []): ImmutableCalibrationKnowledgeRegistry { const identities = new Set<string>(); const snapshots = Object.freeze(records.map((record) => { const snapshot = canonicalKnowledge(record); const id = snapshot.identity.value?.stableId; if (!id) throw new Error("Calibration Knowledge requires canonical identity."); if (identities.has(id)) throw new Error(`Calibration Knowledge identity ${id} is duplicated.`); identities.add(id); return snapshot; })); return Object.freeze({ async lookup(query: CalibrationKnowledgeQuery) { return performLookup(snapshots, query); } }); }
