import assert from "node:assert/strict";
import test from "node:test";
import {
  defineCalibrationKnowledgeObject,
  type CalibrationApplicability,
  type CalibrationKnowledgeObject,
  type GovernedVocabularyReference,
  type QualifiedAssertion,
} from "./calibrationKnowledge.ts";
import {
  defineAdmissionAssertionAssessment,
  defineAdmissionAuthorityClaim,
  defineAdmissionConflictAssessment,
  defineAdmissionEvidencePackage,
  defineAdmissionIdentityAssessment,
  defineAdmissionValidationFinding,
  defineCalibrationKnowledgeAdmissionAssessment,
  defineCalibrationKnowledgeAdmissionDecision,
  defineCalibrationKnowledgeAdmissionProposal,
  defineCalibrationKnowledgePublicationInstruction,
  defineCalibrationKnowledgePublicationReceipt,
  defineProposedCalibrationKnowledgeRevision,
  type AdmissionAssertionAssessment,
  type AdmissionAuthorityClaim,
  type AdmissionConflictAssessment,
  type AdmissionEvidencePackage,
  type AdmissionIdentityAssessment,
  type AdmissionPolicyReference,
  type AdmissionStableIdentity,
  type AdmissionValidationFinding,
  type CalibrationKnowledgeAdmissionAssessment,
  type CalibrationKnowledgeAdmissionDecision,
  type CalibrationKnowledgeAdmissionProposal,
  type CalibrationKnowledgePublicationInstruction,
  type CalibrationKnowledgePublicationReceipt,
  type ProposedCalibrationKnowledgeRevision,
} from "./calibrationKnowledgeAdmission.ts";

const digest = (seed: string) => {
  const encoded = [...seed]
    .map((character) => character.charCodeAt(0).toString(16))
    .join("");
  return `sha256:${encoded.padEnd(64, "0").slice(0, 64)}`;
};
const identity = (id: string, revision = "1"): AdmissionStableIdentity => ({ id, revision, contentDigest: digest(id.replace(/[^a-f0-9]/gi, "a")) });
const vocabulary = (termId: string): GovernedVocabularyReference => ({ vocabularyId: "admission", vocabularyVersion: "1", termId, label: termId, recognition: "known" });
const applicability = (): CalibrationApplicability => ({ scope: vocabulary("universal"), platforms: [], engineFamilies: [], ecuFamilies: [], dmeVariants: [], controlStrategies: [], romFamilies: [], softwareVersions: [], calibrationIds: [], stockVariantIds: [], operatingModes: [], transmissions: [], regions: [], emissionsSpecifications: [], hardwareConfigurations: [], sourceReferenceIds: [], unresolvedReason: null });
function assertion<T>(assertionId: string, value: T): QualifiedAssertion<T> { return { assertionId, value, verificationStatus: "candidate", confidence: "medium", authority: null, provenance: [{ sourceType: "test", sourceIdentifier: assertionId }], supportingEvidence: [{ evidenceId: `e:${assertionId}`, sourceType: "test", sourceIdentifier: assertionId }], contradictoryEvidence: [], applicability: applicability(), conflictState: "none", unresolvedReason: null, version: "1", lifecycle: { status: "active", version: "1" } }; }
function knowledge(): CalibrationKnowledgeObject { return defineCalibrationKnowledgeObject({ identity: assertion("identity:1", { stableId: "cal:1" }), canonicalName: assertion("name:1", "Calibration One"), aliases: [], purposes: [], engineeringIntents: [], calibrationKind: assertion("kind:1", vocabulary("target")), primarySubsystem: assertion("subsystem:1", vocabulary("boost")), relatedSubsystems: [], applicability: assertion("applicability:1", applicability()), sourceRepresentations: [], directionalBehaviours: [], relationships: [], provenance: [{ sourceType: "test", sourceIdentifier: "record:1" }], lifecycle: { status: "active", version: "1" }, version: "1" }); }
const lifecycle = (status: "submitted" | "assessed" | "decision_ready" | "decided" | "publication_ready" | "published" | "blocked" = "submitted") => ({ status, version: "1", effectiveAt: "2026-08-01T00:00:00Z" } as const);
const manifest = () => ({ addedAssertionIds: ["identity:1"], amendedAssertionIds: [], retainedAssertionIds: [], supersededAssertionIds: [], removedFromCurrentAssertionIds: [] });
const policy = (): AdmissionPolicyReference => ({ policyId: "policy:1", policyVersion: "1", effectiveDate: "2026-08-01", applicableProposalKinds: ["register_new"], validationRuleVersions: ["1"], authorityRuleVersion: "1", publicationRuleVersion: "1" });
function proposed(): ProposedCalibrationKnowledgeRevision { return { revisionIdentity: identity("revision:1"), knowledge: knowledge(), proposedStableKnowledgeId: "cal:1", proposedKnowledgeVersion: "1", expectedPredecessorKnowledgeVersion: null, changeManifest: manifest(), publicationRationale: "Publish a structurally qualified candidate." }; }
function evidencePackage(): AdmissionEvidencePackage { return { packageIdentity: identity("evidence:package"), evidence: [{ evidenceId: "e:identity", sourceType: "test", sourceIdentifier: "source:1" }], provenance: [{ sourceType: "test", sourceIdentifier: "source:1" }], sourceRevisionDigests: [identity("source:1")], assertionMappings: [{ assertionId: "identity:1", supportingEvidenceIds: ["e:identity"], contradictoryEvidenceIds: [] }], collectionMethod: "Controlled test collection.", transformationHistory: [], chainOfCustody: ["Collected by test authority."], knownLimitations: ["Fixture only."], createdDate: "2026-08-01", supersededPackageRevision: null }; }
function authorityClaim(): AdmissionAuthorityClaim { return { claimIdentity: identity("authority:claim"), authority: { authorityType: "founder", authorityIdentifier: "founder:1" }, assertionCategories: [vocabulary("identity")], applicability: [vocabulary("universal")], permittedVerificationCeiling: "founder_verified", effectiveFrom: "2026-08-01", effectiveUntil: null, supportingAuthorityEvidenceIds: ["e:authority"], limitations: ["Identity only."], lifecycle: lifecycle("submitted") }; }
function proposal(): CalibrationKnowledgeAdmissionProposal { return { proposalIdentity: identity("proposal:1"), proposalKind: "register_new", proposedRevision: proposed(), evidencePackageIdentity: identity("evidence:package"), authorityClaimIds: ["authority:claim"], proposer: { authorityType: "engineer", authorityIdentifier: "engineer:1" }, proposerSourceRole: vocabulary("controlled_proposer"), intendedPublicationClass: vocabulary("provisional"), submittedAt: "2026-08-01T00:00:00Z", contractVersion: "1", previousProposalRevision: null, rationale: "Submit candidate Knowledge.", unresolvedQuestions: ["Engineering Intent remains unknown."], lifecycle: lifecycle("submitted") }; }
function finding(): AdmissionValidationFinding { return { findingId: "finding:1", findingCode: "EVIDENCE_REQUIRED", severity: "error", category: "evidence", affectedProposalPaths: ["proposedRevision.knowledge.identity"], affectedAssertionIds: ["identity:1"], affectedEvidenceIds: [], affectedAuthorityClaimIds: [], message: "Additional evidence is required.", blocking: true, resolutionRequirement: "Supply traceable identity evidence.", lifecycle: lifecycle("assessed") }; }
function assertionAssessment(): AdmissionAssertionAssessment { return { assertionId: "identity:1", assertionCategory: vocabulary("identity"), status: "requires_evidence", evidenceCoverage: vocabulary("incomplete"), supportingEvidenceIds: [], contradictoryEvidenceIds: [], provenanceComplete: false, authorityClaimIds: [], verificationCeiling: "candidate", preservedConfidence: "medium", applicabilityStatus: vocabulary("known"), vocabularyStatus: vocabulary("known"), conflictStatus: "none", lifecycleStatus: vocabulary("active"), publicationEligible: false, unresolvedReasons: ["Evidence is incomplete."] }; }
function identityAssessment(): AdmissionIdentityAssessment { return { assessmentId: "identity-assessment:1", relationship: "new_identity", proposedStableKnowledgeId: "cal:1", existingKnowledgeIds: [], candidateKnowledgeIds: [], supportingEvidenceIds: ["e:identity"], contradictoryEvidenceIds: [], proposedLineageOperation: "register", unresolvedReason: null }; }
function conflictAssessment(): AdmissionConflictAssessment { return { assessmentId: "conflict-assessment:1", status: "none", conflicts: [], unresolvedReason: null }; }
function assessment(): CalibrationKnowledgeAdmissionAssessment { return { assessmentIdentity: identity("assessment:1"), proposalIdentity: identity("proposal:1"), evidencePackageIdentity: identity("evidence:package"), canonicalBaselineIdentity: identity("baseline:1"), policy: policy(), evaluatedKnowledgeDigest: digest("knowledge"), findings: [finding()], assertionAssessments: [assertionAssessment()], identityAssessment: identityAssessment(), conflictAssessment: conflictAssessment(), publicationEligibility: { eligibleOutcomes: ["requires_evidence", "deferred", "rejected"], blockingFindingIds: ["finding:1"], unresolvedConditions: ["Identity evidence remains incomplete."], publicationEligible: false }, unresolvedConditions: ["Evidence remains incomplete."], assessedAt: "2026-08-01T01:00:00Z", lifecycle: lifecycle("assessed") }; }
function decision(): CalibrationKnowledgeAdmissionDecision { return { decisionIdentity: identity("decision:1"), proposalIdentity: identity("proposal:1"), assessmentIdentity: identity("assessment:1"), outcome: "deferred", decisionAuthority: { authorityType: "founder", authorityIdentifier: "founder:1" }, decidedAt: "2026-08-01T02:00:00Z", rationale: "Await further evidence.", acceptedFindingIds: ["finding:1"], rejectedFindingIds: [], unresolvedConditions: ["Evidence remains incomplete."], contractVersion: "1", supersededDecisionId: null, lifecycle: lifecycle("decided"), publicationInstructionId: null }; }
function instruction(): CalibrationKnowledgePublicationInstruction { return { instructionIdentity: identity("instruction:1", "publication-r1"), acceptedDecisionIdentity: identity("decision:accepted"), operation: "register", targetStableKnowledgeId: "cal:1", expectedPredecessorKnowledgeVersion: null, acceptedKnowledgeDigest: digest("accepted"), resultingKnowledgeVersion: "1", changeManifest: manifest(), policy: policy(), expectedResultingCanonicalDigest: digest("result"), lifecycle: lifecycle("publication_ready") }; }
function receipt(): CalibrationKnowledgePublicationReceipt { return { receiptIdentity: identity("receipt:1"), instructionIdentity: identity("instruction:1"), outcome: "published", resultingStableKnowledgeId: "cal:1", resultingKnowledgeVersion: "1", resultingContentDigest: digest("published"), predecessorKnowledgeVersion: null, publishedAt: "2026-08-01T03:00:00Z", publicationSourceRevision: "source:1", registrySnapshotReference: "registry:1", failureReason: null, lifecycle: lifecycle("published") }; }

test("constructs every Slice 4.1 public contract without performing admission", () => { assert.ok(defineProposedCalibrationKnowledgeRevision(proposed())); assert.ok(defineAdmissionEvidencePackage(evidencePackage())); assert.ok(defineAdmissionAuthorityClaim(authorityClaim())); assert.ok(defineCalibrationKnowledgeAdmissionProposal(proposal())); assert.ok(defineAdmissionValidationFinding(finding())); assert.ok(defineAdmissionAssertionAssessment(assertionAssessment())); assert.ok(defineAdmissionIdentityAssessment(identityAssessment())); assert.ok(defineAdmissionConflictAssessment(conflictAssessment())); assert.ok(defineCalibrationKnowledgeAdmissionAssessment(assessment())); assert.ok(defineCalibrationKnowledgeAdmissionDecision(decision())); assert.ok(defineCalibrationKnowledgePublicationInstruction(instruction())); assert.ok(defineCalibrationKnowledgePublicationReceipt(receipt())); });

test("constructors defensively clone and recursively freeze nested inputs", () => { const input = proposal(); const questions = [...input.unresolvedQuestions]; const result = defineCalibrationKnowledgeAdmissionProposal({ ...input, unresolvedQuestions: questions }); questions[0] = "Changed"; assert.equal(result.unresolvedQuestions[0], "Engineering Intent remains unknown."); assert.ok(Object.isFrozen(result)); assert.ok(Object.isFrozen(result.proposedRevision)); assert.ok(Object.isFrozen(result.proposedRevision.knowledge.identity)); assert.ok(Object.isFrozen(result.unresolvedQuestions)); assert.equal(Reflect.set(result.proposedRevision.knowledge, "version", "2"), false); });

test("proposal, Evidence, Knowledge, assessment, decision, and publication versions remain separate", () => { const input = proposal(); const result = defineCalibrationKnowledgeAdmissionProposal({ ...input, proposalIdentity: identity("proposal:1", "proposal-r2"), proposedRevision: { ...input.proposedRevision, revisionIdentity: identity("revision:1", "evidence-r7"), proposedKnowledgeVersion: "knowledge-v3", knowledge: { ...input.proposedRevision.knowledge, version: "knowledge-v3" } }, contractVersion: "contract-v4" }); assert.equal(result.proposalIdentity.revision, "proposal-r2"); assert.equal(result.proposedRevision.revisionIdentity.revision, "evidence-r7"); assert.equal(result.proposedRevision.proposedKnowledgeVersion, "knowledge-v3"); assert.equal(result.contractVersion, "contract-v4"); });

test("stable identities require independent revision and algorithm-qualified digest", () => { assert.throws(() => Reflect.apply(defineAdmissionEvidencePackage, undefined, [{ ...evidencePackage(), packageIdentity: { id: "package", revision: " ", contentDigest: digest("x") } }]), /revision is required/); assert.throws(() => Reflect.apply(defineAdmissionEvidencePackage, undefined, [{ ...evidencePackage(), packageIdentity: { id: "package", revision: "1", contentDigest: "not-a-digest" } }]), /algorithm-qualified digest/); });

test("proposed Knowledge identity and version must match its canonical object", () => { assert.throws(() => defineProposedCalibrationKnowledgeRevision({ ...proposed(), proposedStableKnowledgeId: "cal:other" }), /must match the canonical object identity/); assert.throws(() => defineProposedCalibrationKnowledgeRevision({ ...proposed(), proposedKnowledgeVersion: "2" }), /must match the canonical object version/); });

test("change manifests reject duplicate assertion identities across operations", () => { assert.throws(() => defineProposedCalibrationKnowledgeRevision({ ...proposed(), changeManifest: { ...manifest(), amendedAssertionIds: ["identity:1"] } }), /duplicate identity identity:1/); });

test("Evidence packages reject duplicate and unresolved Evidence references", () => { const base = evidencePackage(); assert.throws(() => defineAdmissionEvidencePackage({ ...base, evidence: [...base.evidence, base.evidence[0]] }), /duplicate identity e:identity/); assert.throws(() => defineAdmissionEvidencePackage({ ...base, assertionMappings: [{ assertionId: "identity:1", supportingEvidenceIds: ["e:missing"], contradictoryEvidenceIds: [] }] }), /unknown Evidence e:missing/); });

test("Evidence package calendar dates are validated", () => { assert.throws(() => defineAdmissionEvidencePackage({ ...evidencePackage(), createdDate: "2026-02-30" }), /valid calendar date/); });

test("authority claims validate scope, dates, and lifecycle without assessing authority", () => { assert.throws(() => defineAdmissionAuthorityClaim({ ...authorityClaim(), assertionCategories: [] }), /requires an assertion category/); assert.throws(() => defineAdmissionAuthorityClaim({ ...authorityClaim(), effectiveFrom: "2026-08-02", effectiveUntil: "2026-08-01" }), /cannot precede/); const result = defineAdmissionAuthorityClaim({ ...authorityClaim(), permittedVerificationCeiling: "authoritatively_verified", limitations: ["Claimed ceiling only; not assessed."] }); assert.equal(result.permittedVerificationCeiling, "authoritatively_verified"); });

test("proposal kinds reject impossible predecessor combinations", () => { assert.throws(() => defineCalibrationKnowledgeAdmissionProposal({ ...proposal(), proposedRevision: { ...proposed(), expectedPredecessorKnowledgeVersion: "1" } }), /New registration cannot/); const amendment = { ...proposal(), proposalKind: "correct_existing" as const }; assert.throws(() => defineCalibrationKnowledgeAdmissionProposal(amendment), /requires a predecessor/); });

test("runtime-invalid proposal vocabulary is rejected", () => { assert.throws(() => Reflect.apply(defineCalibrationKnowledgeAdmissionProposal, undefined, [{ ...proposal(), proposalKind: "invented" }]), /proposal kind is invalid/); });

test("submitted proposals cannot retain draft lifecycle", () => { assert.throws(() => Reflect.apply(defineCalibrationKnowledgeAdmissionProposal, undefined, [{ ...proposal(), lifecycle: { status: "draft", version: "1" } }]), /cannot retain draft/); });

test("blocking findings require explicit resolution requirements", () => { assert.throws(() => defineAdmissionValidationFinding({ ...finding(), resolutionRequirement: null }), /requires a resolution requirement/); });

test("finding severity and category vocabularies reject unknown values", () => { assert.throws(() => Reflect.apply(defineAdmissionValidationFinding, undefined, [{ ...finding(), severity: "severe" }]), /severity is invalid/); assert.throws(() => Reflect.apply(defineAdmissionValidationFinding, undefined, [{ ...finding(), category: "diagnosis" }]), /category is invalid/); });

test("assertion assessments preserve confidence separately from verification and authority", () => { const result = defineAdmissionAssertionAssessment({ ...assertionAssessment(), status: "eligible", publicationEligible: true, verificationCeiling: "candidate", preservedConfidence: "high", authorityClaimIds: ["authority:claim"] }); assert.equal(result.verificationCeiling, "candidate"); assert.equal(result.preservedConfidence, "high"); assert.deepEqual(result.authorityClaimIds, ["authority:claim"]); });

test("unresolved assertion outcomes require reasons and cannot be publication eligible", () => { assert.throws(() => defineAdmissionAssertionAssessment({ ...assertionAssessment(), unresolvedReasons: [] }), /requires a reason/); assert.throws(() => defineAdmissionAssertionAssessment({ ...assertionAssessment(), publicationEligible: true }), /Only an eligible/); });

test("identity assessment preserves unknown and conflict without selecting an identity", () => { const unresolved = defineAdmissionIdentityAssessment({ ...identityAssessment(), relationship: "unresolved", proposedLineageOperation: null, unresolvedReason: "Identity evidence is insufficient." }); assert.equal(unresolved.relationship, "unresolved"); assert.equal(unresolved.proposedLineageOperation, null); assert.throws(() => defineAdmissionIdentityAssessment({ ...identityAssessment(), relationship: "conflict", unresolvedReason: null }), /requires a reason/); });

test("new identity assessment cannot reference existing Knowledge", () => { assert.throws(() => defineAdmissionIdentityAssessment({ ...identityAssessment(), existingKnowledgeIds: ["cal:existing"] }), /cannot reference existing/); });

test("conflict assessment preserves conflict details and rejects impossible combinations", () => { const conflict = { conflictId: "conflict:1", category: "identity" as const, summary: "Identity evidence conflicts.", assertionIds: ["identity:1"], evidenceIds: ["e:identity"], authorityClaimIds: [], canonicalKnowledgeIds: ["cal:existing"], unresolvedReason: "Requires authorised resolution." }; const result = defineAdmissionConflictAssessment({ assessmentId: "conflicts:1", status: "unresolved", conflicts: [conflict], unresolvedReason: "Material conflict remains." }); assert.equal(result.conflicts[0].assertionIds[0], "identity:1"); assert.throws(() => defineAdmissionConflictAssessment({ assessmentId: "conflicts:1", status: "none", conflicts: [conflict], unresolvedReason: null }), /cannot contain conflicts/); assert.throws(() => defineAdmissionConflictAssessment({ assessmentId: "conflicts:1", status: "unresolved", conflicts: [], unresolvedReason: "Missing details." }), /requires conflict details/); });

test("admission assessment validates policy and finding references without making a decision", () => { const result = defineCalibrationKnowledgeAdmissionAssessment(assessment()); assert.deepEqual(result.publicationEligibility.eligibleOutcomes, ["requires_evidence", "deferred", "rejected"]); assert.throws(() => defineCalibrationKnowledgeAdmissionAssessment({ ...assessment(), publicationEligibility: { ...assessment().publicationEligibility, blockingFindingIds: ["finding:missing"] } }), /unknown finding/); assert.throws(() => defineCalibrationKnowledgeAdmissionAssessment({ ...assessment(), policy: { ...policy(), effectiveDate: "2026-13-01" } }), /valid calendar date/); });

test("publication eligibility cannot be true while blocking findings remain", () => { assert.throws(() => defineCalibrationKnowledgeAdmissionAssessment({ ...assessment(), publicationEligibility: { ...assessment().publicationEligibility, publicationEligible: true } }), /cannot retain blocking findings/); });

test("only accepted decisions may reference publication instructions", () => { assert.throws(() => Reflect.apply(defineCalibrationKnowledgeAdmissionDecision, undefined, [{ ...decision(), publicationInstructionId: "instruction:1" }]), /Only an accepted/); const accepted = defineCalibrationKnowledgeAdmissionDecision({ ...decision(), outcome: "accepted_provisional", publicationInstructionId: "instruction:1", unresolvedConditions: [] }); assert.equal(accepted.outcome, "accepted_provisional"); assert.throws(() => Reflect.apply(defineCalibrationKnowledgeAdmissionDecision, undefined, [{ ...accepted, publicationInstructionId: null }]), /Only an accepted/); });

test("decision finding classifications cannot overlap", () => { assert.throws(() => defineCalibrationKnowledgeAdmissionDecision({ ...decision(), rejectedFindingIds: ["finding:1"] }), /duplicate identity finding:1/); });

test("publication instructions preserve admission and publication separation", () => { const result = defineCalibrationKnowledgePublicationInstruction(instruction()); assert.equal(result.acceptedDecisionIdentity.id, "decision:accepted"); assert.equal(result.resultingKnowledgeVersion, "1"); assert.notEqual(result.instructionIdentity.revision, result.resultingKnowledgeVersion); });

test("publication instructions enforce operation lineage and readiness", () => { assert.throws(() => defineCalibrationKnowledgePublicationInstruction({ ...instruction(), expectedPredecessorKnowledgeVersion: "1" }), /Register publication cannot/); assert.throws(() => defineCalibrationKnowledgePublicationInstruction({ ...instruction(), operation: "correct", expectedPredecessorKnowledgeVersion: null }), /requires a predecessor/); assert.throws(() => defineCalibrationKnowledgePublicationInstruction({ ...instruction(), lifecycle: lifecycle("decided") }), /must be publication ready/); });

test("published receipts require published fields and lifecycle", () => { const result = defineCalibrationKnowledgePublicationReceipt(receipt()); assert.equal(result.outcome, "published"); assert.throws(() => defineCalibrationKnowledgePublicationReceipt({ ...receipt(), lifecycle: lifecycle("blocked") }), /requires published lifecycle/); assert.throws(() => Reflect.apply(defineCalibrationKnowledgePublicationReceipt, undefined, [{ ...receipt(), registrySnapshotReference: " " }]), /Registry snapshot reference is required/); });

test("blocked receipts preserve failure without fabricating published Knowledge", () => { const blocked = defineCalibrationKnowledgePublicationReceipt({ receiptIdentity: identity("receipt:blocked"), instructionIdentity: identity("instruction:1"), outcome: "publication_blocked", resultingStableKnowledgeId: null, resultingKnowledgeVersion: null, resultingContentDigest: null, predecessorKnowledgeVersion: "1", publishedAt: null, publicationSourceRevision: "source:2", registrySnapshotReference: null, failureReason: "Canonical baseline changed.", lifecycle: lifecycle("blocked") }); assert.equal(blocked.resultingStableKnowledgeId, null); assert.equal(blocked.failureReason, "Canonical baseline changed."); assert.throws(() => Reflect.apply(defineCalibrationKnowledgePublicationReceipt, undefined, [{ ...blocked, failureReason: " " }]), /failure reason is required/); });

test("superseded lifecycle requires preserved supersession identity", () => { assert.throws(() => Reflect.apply(defineAdmissionAuthorityClaim, undefined, [{ ...authorityClaim(), lifecycle: { status: "superseded", version: "2" } }]), /requires a superseded identity/); });

test("duplicate identities are rejected across all reference collections", () => { assert.throws(() => defineCalibrationKnowledgeAdmissionProposal({ ...proposal(), authorityClaimIds: ["claim:1", "claim:1"] }), /duplicate identity claim:1/); assert.throws(() => defineAdmissionAssertionAssessment({ ...assertionAssessment(), supportingEvidenceIds: ["e:1", "e:1"] }), /duplicate identity e:1/); });
