import assert from "node:assert/strict";
import test from "node:test";
import {
  defineCalibrationKnowledgeObject,
  type CalibrationApplicability,
  type CalibrationKnowledgeObject,
  type GovernedVocabularyReference,
  type KnowledgeVerificationStatus,
  type QualifiedAssertion,
} from "./calibrationKnowledge.ts";
import {
  defineAdmissionAuthorityClaim,
  defineAdmissionEvidencePackage,
  defineCalibrationKnowledgeAdmissionProposal,
  defineProposedCalibrationKnowledgeRevision,
  type AdmissionAuthorityClaim,
  type AdmissionEvidencePackage,
  type AdmissionStableIdentity,
  type CalibrationKnowledgeAdmissionProposal,
} from "./calibrationKnowledgeAdmission.ts";
import {
  assessCalibrationKnowledgeEvidenceAndAuthority,
  type AdmissionAssertionAssessmentRequirement,
  type AdmissionEvidenceAuthorityAssessmentInput,
  type AdmissionEvidenceAuthorityAssessmentPolicy,
  type AdmissionEvidenceClassification,
} from "./calibrationKnowledgeEvidenceAuthorityAssessment.ts";

const digest = (seed: string) => `sha256:${[...seed].map((item) => item.charCodeAt(0).toString(16)).join("").padEnd(64, "0").slice(0, 64)}`;
const identity = (id: string, revision = "1"): AdmissionStableIdentity => ({ id, revision, contentDigest: digest(`${id}:${revision}`) });
const vocab = (termId: string, vocabularyId = "calibration-admission"): GovernedVocabularyReference => ({ vocabularyId, vocabularyVersion: "1", termId, label: termId, recognition: "known" });
const app = (): CalibrationApplicability => ({ scope: vocab("universal", "applicability"), platforms: [], engineFamilies: [], ecuFamilies: [], dmeVariants: [], controlStrategies: [], romFamilies: [], softwareVersions: [], calibrationIds: [], stockVariantIds: [], operatingModes: [], transmissions: [], regions: [], emissionsSpecifications: [], hardwareConfigurations: [], sourceReferenceIds: [], unresolvedReason: null });
function assertion<T>(id: string, value: T, verificationStatus: KnowledgeVerificationStatus = "candidate", confidence: "unknown" | "low" | "medium" | "high" = "medium"): QualifiedAssertion<T> { return { assertionId: id, value, verificationStatus, confidence, authority: null, provenance: [{ sourceType: "controlled", sourceIdentifier: id }], supportingEvidence: [{ evidenceId: `e:${id}`, sourceType: "controlled", sourceIdentifier: id }], contradictoryEvidence: [], applicability: app(), conflictState: "none", unresolvedReason: null, version: "1", lifecycle: { status: "active", version: "1" } }; }
function knowledge(options: { purpose?: boolean; intent?: boolean; verification?: KnowledgeVerificationStatus; confidence?: "unknown" | "low" | "medium" | "high" } = {}): CalibrationKnowledgeObject { const status = options.verification ?? "candidate"; const confidence = options.confidence ?? "medium"; return defineCalibrationKnowledgeObject({ identity: assertion("identity", { stableId: "cal:1" }, status, confidence), canonicalName: assertion("canonical-name", "Calibration One", status, confidence), aliases: [], purposes: options.purpose ? [assertion("purpose", { summary: "Controls a documented request." }, status, confidence)] : [], engineeringIntents: options.intent ? [assertion("intent", { summary: "Serves a documented strategy.", engineeringObjectives: [], participatingSubsystems: [], protectedInterests: [], governingConstraints: [], documentedTradeoffs: [] }, status, confidence)] : [], calibrationKind: assertion("kind", vocab("target", "calibration-kind"), status, confidence), primarySubsystem: assertion("subsystem", vocab("boost", "subsystem"), status, confidence), relatedSubsystems: [], applicability: assertion("applicability", app(), status, confidence), sourceRepresentations: [], directionalBehaviours: [], relationships: [], provenance: [{ sourceType: "controlled", sourceIdentifier: "knowledge" }], lifecycle: { status: "active", version: "1" }, version: "1" }); }
function allAssertions(record: CalibrationKnowledgeObject): readonly QualifiedAssertion<unknown>[] { return [record.identity, record.canonicalName, ...record.purposes, ...record.engineeringIntents, record.calibrationKind, record.primarySubsystem, record.applicability]; }
const categoryFor = (id: string): GovernedVocabularyReference => vocab(id === "canonical-name" ? "canonical_name" : id === "intent" ? "engineering_intent" : id, "calibration-assertion-category");
const universalScope = vocab("universal", "authority-scope");
const controlledSource = vocab("controlled_source", "authority-source-scope");

function packageFor(record: CalibrationKnowledgeObject, limitations: readonly string[] = []): AdmissionEvidencePackage {
  const assertions = allAssertions(record);
  return defineAdmissionEvidencePackage({
    packageIdentity: identity("evidence-package"),
    evidence: [
      ...assertions.map((item) => ({ evidenceId: `e:${item.assertionId}`, sourceType: "controlled", sourceIdentifier: item.assertionId })),
      { evidenceId: "e:authority", sourceType: "authority_record", sourceIdentifier: "authority:1" },
    ],
    provenance: [{ sourceType: "controlled", sourceIdentifier: "package" }],
    sourceRevisionDigests: [identity("source")],
    assertionMappings: assertions.map((item) => ({ assertionId: item.assertionId, supportingEvidenceIds: [`e:${item.assertionId}`], contradictoryEvidenceIds: [] })),
    collectionMethod: "Controlled assessment fixture.",
    transformationHistory: ["No transformation."],
    chainOfCustody: ["Controlled fixture custody."],
    knownLimitations: limitations,
    createdDate: "2026-08-01",
    supersededPackageRevision: null,
  });
}

function proposalFor(record: CalibrationKnowledgeObject, evidencePackage: AdmissionEvidencePackage): CalibrationKnowledgeAdmissionProposal {
  const proposedRevision = defineProposedCalibrationKnowledgeRevision({ revisionIdentity: identity("knowledge-revision"), knowledge: record, proposedStableKnowledgeId: "cal:1", proposedKnowledgeVersion: "1", expectedPredecessorStableKnowledgeId: null, expectedPredecessorKnowledgeVersion: null, changeManifest: { addedAssertionIds: allAssertions(record).map((item) => item.assertionId), amendedAssertionIds: [], retainedAssertionIds: [], supersededAssertionIds: [], removedFromCurrentAssertionIds: [] }, lifecycleChangeManifest: { changes: [] }, publicationRationale: "Assess fixture Knowledge." });
  return defineCalibrationKnowledgeAdmissionProposal({ proposalIdentity: identity("proposal"), proposalKind: "register_new", proposedRevision, evidencePackageIdentity: evidencePackage.packageIdentity, authorityClaimIds: ["authority:1"], proposer: { authorityType: "engineer", authorityIdentifier: "engineer:1" }, proposerSourceRole: vocab("controlled_proposer"), intendedPublicationClass: vocab("provisional"), submittedAt: "2026-08-01T00:00:00Z", contractVersion: "1", previousProposalRevision: null, rationale: "Submit for assessment.", unresolvedQuestions: [], lifecycle: { status: "submitted", version: "1" } });
}

function authorityFor(record: CalibrationKnowledgeObject, options: { id?: string; authorityType?: string; categories?: readonly GovernedVocabularyReference[]; scopes?: readonly GovernedVocabularyReference[]; ceiling?: KnowledgeVerificationStatus; from?: string; until?: string | null; evidenceIds?: readonly string[]; superseded?: boolean; limitations?: readonly string[] } = {}): AdmissionAuthorityClaim {
  return defineAdmissionAuthorityClaim({ claimIdentity: identity(options.id ?? "authority:1"), authority: { authorityType: options.authorityType ?? "oem_documentation", authorityIdentifier: "authority-source:1" }, assertionCategories: options.categories ?? allAssertions(record).map((item) => categoryFor(item.assertionId)), applicability: options.scopes ?? [universalScope, controlledSource], permittedVerificationCeiling: options.ceiling ?? "authoritatively_verified", effectiveFrom: options.from ?? "2026-01-01", effectiveUntil: options.until ?? null, supportingAuthorityEvidenceIds: options.evidenceIds ?? ["e:authority"], limitations: options.limitations ?? [], lifecycle: options.superseded ? { status: "superseded", version: "2", supersedesIds: ["authority:0"] } : { status: "submitted", version: "1" } });
}

function requirementsFor(record: CalibrationKnowledgeObject): readonly AdmissionAssertionAssessmentRequirement[] {
  return allAssertions(record).map((item) => ({ assertionId: item.assertionId, assertionCategory: categoryFor(item.assertionId), evidenceRequirement: "required", propositionIds: [`proposition:${item.assertionId}`], propositionCoverage: [{ propositionId: `proposition:${item.assertionId}`, supportingEvidenceIds: [`e:${item.assertionId}`] }], applicabilityEvidenceIds: [`e:${item.assertionId}`], provenanceRequired: true, requestedVerificationStatus: item.verificationStatus, authorityClaimIds: ["authority:1"], unresolvedAuthorityClaimIds: [], conflictingAuthorityClaimIds: [], requiredAuthorityScopes: [universalScope], requiredSourceScopes: [controlledSource], applicableAuthorityLimitationIndexes: {} }));
}

const policy = (): AdmissionEvidenceAuthorityAssessmentPolicy => ({ policyId: "evidence-authority-policy", policyVersion: "1", requireSourceRevision: true, requireTransformationHistory: true, requireChainOfCustody: true, founderAuthorityTypes: ["founder"], founderPermittedAssertionCategories: [categoryFor("canonical-name"), vocab("source_representation", "calibration-assertion-category"), vocab("calibration_kind", "calibration-assertion-category")], founderProhibitedAssertionCategories: [categoryFor("intent"), vocab("directional_behaviour", "calibration-assertion-category"), vocab("protective_response", "calibration-assertion-category") ] });

function inputFor(options: { record?: CalibrationKnowledgeObject; evidencePackage?: AdmissionEvidencePackage; claims?: readonly AdmissionAuthorityClaim[]; requirements?: readonly AdmissionAssertionAssessmentRequirement[]; classifications?: Readonly<Record<string, AdmissionEvidenceClassification>>; date?: string } = {}): AdmissionEvidenceAuthorityAssessmentInput {
  const record = options.record ?? knowledge();
  const evidencePackage = options.evidencePackage ?? packageFor(record);
  const claims = options.claims ?? [authorityFor(record)];
  return { assessmentIdentity: identity("assessment"), proposal: proposalFor(record, evidencePackage), evidencePackage, authorityClaims: claims, evidenceClassifications: evidencePackage.evidence.map((item) => ({ evidenceId: item.evidenceId, classification: options.classifications?.[item.evidenceId] ?? "authoritative_documentation" })), assertionRequirements: options.requirements ?? requirementsFor(record), policy: policy(), assessmentDate: options.date ?? "2026-08-01" };
}

test("valid package and scoped authority produce complete immutable assessments", () => { const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor()); assert.equal(result.evidenceAssessment.state, "complete"); assert.ok(result.assertionEvidenceAssessments.every((item) => item.state === "complete")); assert.ok(result.authorityAssessments.every((item) => item.state === "qualified")); assert.ok(result.verificationCeilings.every((item) => item.maximumPermittedVerificationStatus === "authoritatively_verified")); assert.ok(Object.isFrozen(result)); assert.ok(Object.isFrozen(result.evidenceAssessment.references)); assert.ok(Object.isFrozen(result.verificationCeilings[0])); });

test("caller mutation cannot alter assessment inputs or outputs", () => { const input = inputFor(); const requirements = [...input.assertionRequirements]; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, assertionRequirements: requirements }); requirements[0] = { ...requirements[0], assertionId: "changed" }; assert.equal(result.assertionEvidenceAssessments[0].assertionId, "applicability"); assert.equal(Reflect.set(result.evidenceAssessment, "state", "invalid"), false); });

test("equivalent caller order produces structurally identical assessment", () => { const input = inputFor(); const reversed = { ...input, evidencePackage: { ...input.evidencePackage, evidence: [...input.evidencePackage.evidence].reverse(), assertionMappings: [...input.evidencePackage.assertionMappings].reverse() }, evidenceClassifications: [...input.evidenceClassifications].reverse(), assertionRequirements: [...input.assertionRequirements].reverse() }; assert.deepEqual(assessCalibrationKnowledgeEvidenceAndAuthority(reversed), assessCalibrationKnowledgeEvidenceAndAuthority(input)); });

test("mismatched Evidence package revision or digest remains invalid", () => { const input = inputFor(); const proposal = { ...input.proposal, evidencePackageIdentity: identity("evidence-package", "older") }; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, proposal }); assert.equal(result.evidenceAssessment.state, "invalid"); assert.equal(result.evidenceAssessment.staleOrMismatchedIdentity, true); });

test("duplicate Evidence references do not increase coverage", () => { const input = inputFor(); const evidence = [...input.evidencePackage.evidence, input.evidencePackage.evidence[0]]; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage: { ...input.evidencePackage, evidence } }); assert.equal(result.evidenceAssessment.state, "invalid"); assert.deepEqual(result.evidenceAssessment.duplicateEvidenceIds, [input.evidencePackage.evidence[0].evidenceId]); const identityResult = result.assertionEvidenceAssessments.find((item) => item.assertionId === "identity"); assert.equal(identityResult?.supportingEvidenceIds.length, 1); });

test("missing mapped Evidence remains explicit", () => { const input = inputFor(); const first = input.evidencePackage.evidence[0]; const evidencePackage = { ...input.evidencePackage, evidence: input.evidencePackage.evidence.filter((item) => item.evidenceId !== first.evidenceId) }; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage, evidenceClassifications: input.evidenceClassifications.filter((item) => item.evidenceId !== first.evidenceId) }); assert.equal(result.evidenceAssessment.state, "partial"); assert.deepEqual(result.evidenceAssessment.missingEvidenceIds, [first.evidenceId]); });

test("supporting and contradictory Evidence remain separate", () => { const input = inputFor(); const mappings = input.evidencePackage.assertionMappings.map((item) => item.assertionId === "identity" ? { ...item, contradictoryEvidenceIds: ["e:identity"] } : item); const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage: { ...input.evidencePackage, assertionMappings: mappings } }); const assessed = result.assertionEvidenceAssessments.find((item) => item.assertionId === "identity"); assert.equal(assessed?.state, "contradictory"); assert.deepEqual(assessed?.supportingEvidenceIds, ["e:identity"]); assert.deepEqual(assessed?.contradictoryEvidenceIds, ["e:identity"]); });

test("missing source revision, transformation history, and custody produce partial integrity", () => { const input = inputFor(); const evidencePackage = { ...input.evidencePackage, sourceRevisionDigests: [], transformationHistory: [], chainOfCustody: [] }; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage }); assert.equal(result.evidenceAssessment.state, "partial"); assert.equal(result.evidenceAssessment.sourceIdentityComplete, false); assert.equal(result.evidenceAssessment.transformationHistoryComplete, false); assert.equal(result.evidenceAssessment.chainOfCustodyComplete, false); });

test("malformed Evidence source identity remains partial rather than acquiring coverage authority", () => { const input = inputFor(); const evidencePackage = { ...input.evidencePackage, evidence: input.evidencePackage.evidence.map((item, index) => index === 0 ? { ...item, sourceIdentifier: " " } : item) }; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage }); assert.equal(result.evidenceAssessment.state, "partial"); assert.equal(result.evidenceAssessment.sourceIdentityComplete, false); });

test("known Evidence limitations remain unresolved", () => { const record = knowledge(); const evidencePackage = packageFor(record, ["Source authority requires review."]); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, evidencePackage })); assert.equal(result.evidenceAssessment.state, "unresolved"); assert.deepEqual(result.evidenceAssessment.limitations, ["Source authority requires review."]); });

test("complete, partial, missing, contradictory, and not-required assertion states remain distinct", () => { const input = inputFor(); const requirements = input.assertionRequirements.map((item) => item.assertionId === "identity" ? { ...item, propositionIds: [...item.propositionIds, "identity:embedded"] } : item.assertionId === "canonical-name" ? { ...item, evidenceRequirement: "not_required" as const } : item); const mappings = input.evidencePackage.assertionMappings.filter((item) => item.assertionId !== "kind").map((item) => item.assertionId === "subsystem" ? { ...item, contradictoryEvidenceIds: item.supportingEvidenceIds } : item); const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, assertionRequirements: requirements, evidencePackage: { ...input.evidencePackage, assertionMappings: mappings } }); const states = new Map(result.assertionEvidenceAssessments.map((item) => [item.assertionId, item.state])); assert.equal(states.get("applicability"), "complete"); assert.equal(states.get("identity"), "partial"); assert.equal(states.get("kind"), "missing"); assert.equal(states.get("subsystem"), "contradictory"); assert.equal(states.get("canonical-name"), "not_required"); });

test("embedded proposition and applicability coverage are explicit", () => { const input = inputFor(); const requirements = input.assertionRequirements.map((item) => item.assertionId === "identity" ? { ...item, propositionIds: ["identity:main", "identity:embedded"], propositionCoverage: [{ propositionId: "identity:main", supportingEvidenceIds: ["e:identity"] }], applicabilityEvidenceIds: ["e:missing-applicability"] } : item); const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, assertionRequirements: requirements }); const assessed = result.assertionEvidenceAssessments.find((item) => item.assertionId === "identity"); assert.equal(assessed?.state, "partial"); assert.deepEqual(assessed?.uncoveredPropositionIds, ["identity:embedded"]); assert.equal(assessed?.applicabilityCovered, false); });

test("incomplete assertion provenance remains partial", () => { const base = knowledge(); const record = defineCalibrationKnowledgeObject({ ...base, identity: { ...base.identity, provenance: [] } }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record })); const assessed = result.assertionEvidenceAssessments.find((item) => item.assertionId === "identity"); assert.equal(assessed?.state, "partial"); assert.equal(assessed?.provenanceComplete, false); });

test("Purpose Evidence never propagates to Engineering Intent", () => { const record = knowledge({ purpose: true, intent: true }); const input = inputFor({ record }); const evidencePackage = { ...input.evidencePackage, assertionMappings: input.evidencePackage.assertionMappings.filter((item) => item.assertionId !== "intent") }; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage }); assert.equal(result.assertionEvidenceAssessments.find((item) => item.assertionId === "purpose")?.state, "complete"); assert.equal(result.assertionEvidenceAssessments.find((item) => item.assertionId === "intent")?.state, "missing"); });

test("Engineering Intent Evidence never resolves Purpose independently", () => { const record = knowledge({ purpose: true, intent: true }); const input = inputFor({ record }); const evidencePackage = { ...input.evidencePackage, assertionMappings: input.evidencePackage.assertionMappings.filter((item) => item.assertionId !== "purpose") }; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage }); assert.equal(result.assertionEvidenceAssessments.find((item) => item.assertionId === "intent")?.state, "complete"); assert.equal(result.assertionEvidenceAssessments.find((item) => item.assertionId === "purpose")?.state, "missing"); });

test("unknown and provisional proposed qualification remain unchanged", () => { const provisional = knowledge({ verification: "provisional" }); const provisionalResult = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record: provisional })); assert.ok(provisionalResult.verificationCeilings.every((item) => item.proposedVerificationStatus === "provisional")); const unknownBase = knowledge(); const unknown = defineCalibrationKnowledgeObject({ ...unknownBase, canonicalName: { ...unknownBase.canonicalName, verificationStatus: "unknown", confidence: "unknown", unresolvedReason: "Qualification unknown." } }); const unknownResult = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record: unknown })); const assessed = unknownResult.verificationCeilings.find((item) => item.assertionId === "canonical-name"); assert.equal(assessed?.proposedVerificationStatus, "unknown"); assert.equal(assessed?.preservedConfidence, "unknown"); });

test("XDF label cannot establish Purpose or Engineering Intent", () => { const record = knowledge({ purpose: true, intent: true }); const input = inputFor({ record, classifications: { "e:purpose": "xdf_label", "e:intent": "xdf_label" } }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(input); assert.equal(result.assertionEvidenceAssessments.find((item) => item.assertionId === "purpose")?.state, "partial"); assert.equal(result.assertionEvidenceAssessments.find((item) => item.assertionId === "intent")?.state, "partial"); });

test("table address, filename, and folder cannot establish stable identity", () => { for (const classification of ["table_address", "filename", "folder"] as const) { const input = inputFor({ classifications: { "e:identity": classification } }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(input); assert.equal(result.assertionEvidenceAssessments.find((item) => item.assertionId === "identity")?.state, "partial"); } });

test("community convention cannot establish OEM Engineering Intent", () => { const record = knowledge({ intent: true }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, classifications: { "e:intent": "community_convention" } })); assert.equal(result.assertionEvidenceAssessments.find((item) => item.assertionId === "intent")?.state, "partial"); });

test("valid scoped authority qualifies only its exact category", () => { const record = knowledge({ purpose: true }); const claim = authorityFor(record, { categories: [categoryFor("identity")] }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [claim] })); assert.equal(result.authorityAssessments.find((item) => item.assertionId === "identity")?.state, "qualified"); assert.equal(result.authorityAssessments.find((item) => item.assertionId === "purpose")?.state, "outside_scope"); });

test("expired, inactive, and not-yet-effective authority remain distinct", () => { const record = knowledge(); const expired = authorityFor(record, { until: "2026-07-31" }); const inactive = authorityFor(record, { superseded: true }); const future = authorityFor(record, { from: "2026-08-02" }); assert.equal(assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [expired] })).authorityAssessments[0].state, "expired"); assert.equal(assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [inactive] })).authorityAssessments[0].state, "inactive"); assert.equal(assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [future] })).authorityAssessments[0].state, "inactive"); });

test("applicability and source scope are independently required", () => { const record = knowledge(); const applicabilityMissing = authorityFor(record, { scopes: [controlledSource] }); const sourceMissing = authorityFor(record, { scopes: [universalScope] }); const first = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [applicabilityMissing] })).authorityAssessments[0].claimAssessments[0]; const second = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [sourceMissing] })).authorityAssessments[0].claimAssessments[0]; assert.equal(first.applicabilityAuthorised, false); assert.equal(first.sourceScopeAuthorised, true); assert.equal(second.applicabilityAuthorised, true); assert.equal(second.sourceScopeAuthorised, false); });

test("missing supporting authority record remains unsupported", () => { const record = knowledge(); const claim = authorityFor(record, { evidenceIds: ["e:missing-authority"] }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [claim] })); assert.equal(result.authorityAssessments[0].state, "unsupported"); });

test("applicable authority limitations produce partial qualification", () => { const input = inputFor(); const requirements = input.assertionRequirements.map((item) => item.assertionId === "identity" ? { ...item, applicableAuthorityLimitationIndexes: { "authority:1": [0] } } : item); const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, assertionRequirements: requirements }); assert.equal(result.authorityAssessments.find((item) => item.assertionId === "identity")?.state, "partially_qualified"); });

test("unresolved and conflicting authority claims remain visible", () => { const input = inputFor(); const unresolvedRequirements = input.assertionRequirements.map((item) => item.assertionId === "identity" ? { ...item, unresolvedAuthorityClaimIds: ["authority:1"] } : item); const unresolved = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, assertionRequirements: unresolvedRequirements }); assert.equal(unresolved.authorityAssessments.find((item) => item.assertionId === "identity")?.state, "unresolved"); const conflictingRequirements = input.assertionRequirements.map((item) => item.assertionId === "identity" ? { ...item, conflictingAuthorityClaimIds: ["authority:1"] } : item); const conflicting = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, assertionRequirements: conflictingRequirements }); assert.equal(conflicting.authorityAssessments.find((item) => item.assertionId === "identity")?.state, "unresolved"); });

test("malformed authority identity remains invalid", () => { const input = inputFor(); const malformed = { ...input.authorityClaims[0], authority: { ...input.authorityClaims[0].authority, authorityIdentifier: " " } }; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, authorityClaims: [malformed] }); assert.equal(result.authorityAssessments[0].state, "invalid"); });

test("Founder authority supports canonical naming within scope", () => { const record = knowledge(); const claim = authorityFor(record, { authorityType: "founder", categories: [categoryFor("canonical-name")] }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [claim] })); assert.equal(result.authorityAssessments.find((item) => item.assertionId === "canonical-name")?.state, "qualified"); });

test("Founder authority cannot establish unsupported OEM Intent", () => { const record = knowledge({ intent: true }); const claim = authorityFor(record, { authorityType: "founder", categories: [categoryFor("intent")] }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [claim] })); assert.equal(result.authorityAssessments.find((item) => item.assertionId === "intent")?.state, "outside_scope"); });

test("identity and Purpose authority never propagate to other assertions", () => { const record = knowledge({ purpose: true, intent: true }); const claim = authorityFor(record, { categories: [categoryFor("identity"), categoryFor("purpose")] }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [claim] })); assert.equal(result.authorityAssessments.find((item) => item.assertionId === "identity")?.state, "qualified"); assert.equal(result.authorityAssessments.find((item) => item.assertionId === "purpose")?.state, "qualified"); assert.equal(result.authorityAssessments.find((item) => item.assertionId === "intent")?.state, "outside_scope"); assert.equal(result.authorityAssessments.find((item) => item.assertionId === "canonical-name")?.state, "outside_scope"); });

test("Evidence without authority cannot exceed candidate", () => { const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ claims: [] })); assert.ok(result.verificationCeilings.every((item) => item.maximumPermittedVerificationStatus === "candidate")); });

test("authority without Evidence cannot exceed unknown", () => { const input = inputFor(); const evidencePackage = { ...input.evidencePackage, assertionMappings: [] }; const result = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage }); assert.ok(result.verificationCeilings.every((item) => item.maximumPermittedVerificationStatus === "unknown")); });

test("complete Evidence and qualified authority expose the claim ceiling without upgrading proposal", () => { const record = knowledge({ verification: "candidate" }); const claim = authorityFor(record, { ceiling: "verified" }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [claim] })); assert.ok(result.verificationCeilings.every((item) => item.maximumPermittedVerificationStatus === "verified")); assert.ok(result.verificationCeilings.every((item) => item.proposedVerificationStatus === "candidate")); });

test("contradictory and unresolved Evidence bound verification", () => { const input = inputFor(); const mappings = input.evidencePackage.assertionMappings.map((item) => item.assertionId === "identity" ? { ...item, contradictoryEvidenceIds: item.supportingEvidenceIds } : item); const contradictory = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage: { ...input.evidencePackage, assertionMappings: mappings } }); assert.equal(contradictory.verificationCeilings.find((item) => item.assertionId === "identity")?.maximumPermittedVerificationStatus, "candidate"); const unresolved = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ classifications: { "e:identity": "other" } })); assert.equal(unresolved.verificationCeilings.find((item) => item.assertionId === "identity")?.maximumPermittedVerificationStatus, "candidate"); });

test("repeated Evidence cannot increase verification ceiling", () => { const input = inputFor(); const base = assessCalibrationKnowledgeEvidenceAndAuthority(input); const repeated = assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, evidencePackage: { ...input.evidencePackage, evidence: [...input.evidencePackage.evidence, input.evidencePackage.evidence[0]] } }); assert.equal(repeated.verificationCeilings.find((item) => item.assertionId === "identity")?.maximumPermittedVerificationStatus, base.verificationCeilings.find((item) => item.assertionId === "identity")?.maximumPermittedVerificationStatus); });

test("high confidence creates no authority and authority changes no confidence", () => { const record = knowledge({ confidence: "high" }); const noAuthority = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [] })); assert.equal(noAuthority.verificationCeilings[0].maximumPermittedVerificationStatus, "candidate"); assert.equal(noAuthority.verificationCeilings[0].preservedConfidence, "high"); const lowConfidence = knowledge({ confidence: "low" }); const withAuthority = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record: lowConfidence })); assert.ok(withAuthority.verificationCeilings.every((item) => item.preservedConfidence === "low")); });

test("requested verification above the derived ceiling is reported, not rewritten", () => { const record = knowledge({ verification: "provisional" }); const claim = authorityFor(record, { ceiling: "candidate" }); const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor({ record, claims: [claim] })); assert.ok(result.verificationCeilings.every((item) => item.proposedExceedsCeiling)); assert.ok(result.verificationCeilings.every((item) => item.proposedVerificationStatus === "provisional")); assert.ok(result.findings.some((item) => item.findingCode === "VERIFICATION_EXCEEDS_CEILING")); });

test("all material assertions require explicit assessment requirements", () => { const input = inputFor(); assert.throws(() => assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, assertionRequirements: input.assertionRequirements.slice(1) }), /requires an assessment requirement/); });

test("assessment requirements cannot substitute a different requested verification", () => { const input = inputFor(); const requirements = input.assertionRequirements.map((item) => item.assertionId === "identity" ? { ...item, requestedVerificationStatus: "verified" as const } : item); assert.throws(() => assessCalibrationKnowledgeEvidenceAndAuthority({ ...input, assertionRequirements: requirements }), /does not match the proposed assertion/); });

test("assessment has no decision, publication, eligibility, receipt, or registry surface", () => { const result = assessCalibrationKnowledgeEvidenceAndAuthority(inputFor()); assert.equal(Reflect.get(result, "decision"), undefined); assert.equal(Reflect.get(result, "publicationEligibility"), undefined); assert.equal(Reflect.get(result, "publicationInstruction"), undefined); assert.equal(Reflect.get(result, "publicationReceipt"), undefined); assert.equal(Reflect.get(result, "registry"), undefined); });
