import assert from "node:assert/strict";
import test from "node:test";
import type { GovernedVocabularyReference } from "./calibrationKnowledge.ts";
import {
  definePublicationReceiptReference,
  definePublicationSourceIdentity,
  defineRegistryRecordManifest,
  defineRegistryRecordReference,
  defineRegistrySnapshotIdentity,
  derivePublicationSourceEnvelope,
  deriveRegistryRecordSet,
  deriveRegistrySnapshotEnvelope,
  type PublicationSourceIdentity,
  type PublicationSourceIdentityInput,
  type RegistryRecordReference,
  type RegistrySnapshotIdentityInput,
} from "./calibrationKnowledgePublicationSourceRegistrySnapshot.ts";
import { canonicalizeDigestDomainPayload, deriveDomainSeparatedDigest } from "./calibrationKnowledgeCanonicalSerialization.ts";

const digest = (character: string): string => `sha256:${character.repeat(64)}`;
const sourceType = (overrides: Partial<GovernedVocabularyReference> = {}): GovernedVocabularyReference => ({ vocabularyId: "tunesight.publication-source-type", vocabularyVersion: "1", termId: "source-controlled-registry", label: "Source-controlled registry", recognition: "known", ...overrides });

function sourceMaterial(): Omit<PublicationSourceIdentity, "sourceEnvelopeDigest"> {
  return {
    sourceId: "publication-source:canonical",
    sourceRevision: "1",
    sourceContentDigest: digest("1"),
    sourceType: sourceType(),
    sourceContractId: "tunesight.calibration-knowledge.publication-source",
    sourceContractVersion: "1",
    authority: { authorityType: "founder-governance", authorityIdentifier: "authority:source-publication" },
    provenance: [{ provenanceId: "provenance:source", sourceType: "repository", sourceIdentifier: "lib/knowledge/source.ts", sourceRevisionOrigin: "commit:fixture", implementationOrigin: "repository:tunesight", sourceContractId: "tunesight.calibration-knowledge.publication-source", sourceContractVersion: "1", validationAuthority: "founder-review", transformationHistory: ["validated", "authored"] }],
    lifecycle: { state: "active", lifecycleVersion: "1", supersededBySourceId: null, supersededBySourceRevision: null },
    capabilities: [
      { capabilityId: "capability:register", operation: "register", supportState: "supported", contractRequirements: ["instruction-v1", "decision-v1"], limitations: ["no runtime availability claim"], compatiblePolicies: [{ policyId: "publication-policy", policyVersion: "1" }] },
      { capabilityId: "capability:correct", operation: "correct", supportState: "supported", contractRequirements: ["predecessor-v1"], limitations: [], compatiblePolicies: [] },
    ],
    knownLimitations: ["storage neutral", "execution neutral"],
  };
}

function sourceInput(material: Omit<PublicationSourceIdentity, "sourceEnvelopeDigest"> = sourceMaterial()): PublicationSourceIdentityInput {
  return { ...material, sourceEnvelopeDigest: derivePublicationSourceEnvelope(material).digest.qualifiedDigest };
}

const record = (overrides: Partial<RegistryRecordReference> = {}): RegistryRecordReference => ({ stableKnowledgeId: "calibration:boost-target-main", knowledgeVersion: "1", canonicalContentDigest: digest("2"), lifecycleState: "active", ...overrides });

function snapshotInput(overrides: Partial<RegistrySnapshotIdentityInput> = {}): RegistrySnapshotIdentityInput {
  const records = overrides.recordManifest?.records ?? [record()];
  const recordSet = deriveRegistryRecordSet(records);
  const base = {
    snapshotKind: "initial" as const,
    snapshotId: "registry-snapshot:initial",
    snapshotRevision: "1",
    registryContractId: "tunesight.calibration-knowledge.registry",
    registryContractVersion: "1",
    recordSetDigest: recordSet.digest.qualifiedDigest,
    recordManifest: recordSet.manifest,
    recordCount: recordSet.manifest.records.length,
    predecessorSnapshot: null,
    sourceReceiptReferences: [{ receiptId: "receipt:b", receiptRevision: "1", receiptDigest: digest("4") }, { receiptId: "receipt:a", receiptRevision: "1", receiptDigest: digest("3") }],
    constructedAt: "2026-08-01T00:00:00.000Z",
    lifecycle: { state: "active" as const, lifecycleVersion: "1" },
  };
  const merged = { ...base, ...overrides };
  const envelope = deriveRegistrySnapshotEnvelope({ snapshotId: merged.snapshotId, snapshotRevision: merged.snapshotRevision, registryContractId: merged.registryContractId, registryContractVersion: merged.registryContractVersion, recordSetDigest: merged.recordSetDigest, recordCount: merged.recordCount, predecessorSnapshot: merged.predecessorSnapshot, sourceReceiptReferences: merged.sourceReceiptReferences, constructedAt: merged.constructedAt, lifecycle: merged.lifecycle });
  return { ...merged, snapshotEnvelopeDigest: overrides.snapshotEnvelopeDigest ?? envelope.digest.qualifiedDigest };
}

test("defines an exact active immutable publication source revision", () => { const result = definePublicationSourceIdentity(sourceInput()); assert.equal(result.lifecycle.state, "active"); assert.equal(result.sourceEnvelopeDigest, derivePublicationSourceEnvelope(sourceMaterial()).digest.qualifiedDigest); assert.ok(Object.isFrozen(result)); assert.ok(Object.isFrozen(result.capabilities)); assert.ok(Object.isFrozen(result.provenance[0].transformationHistory)); });
test("rejects malformed source identity revision content and envelope digests", () => { const valid = sourceInput(); assert.throws(() => definePublicationSourceIdentity({ ...valid, sourceId: " " }), /identity/); assert.throws(() => definePublicationSourceIdentity({ ...valid, sourceRevision: "bad revision" }), /revision/); assert.throws(() => definePublicationSourceIdentity({ ...valid, sourceContentDigest: "bad" }), /content digest/); assert.throws(() => definePublicationSourceIdentity({ ...valid, sourceEnvelopeDigest: "bad" }), /envelope digest/); });
test("rejects invalid source contract source vocabulary and missing authority", () => { const valid = sourceInput(); assert.throws(() => definePublicationSourceIdentity({ ...valid, sourceContractId: " " }), /contract identity/); assert.throws(() => definePublicationSourceIdentity({ ...valid, sourceContractVersion: "bad version" }), /contract version/); assert.throws(() => definePublicationSourceIdentity(sourceInput({ ...sourceMaterial(), sourceType: sourceType({ recognition: "unknown" }) })), /known governed term/); assert.throws(() => definePublicationSourceIdentity({ ...valid, authority: { ...valid.authority, authorityIdentifier: " " } }), /authority identity/); });
test("requires complete uniquely identified provenance", () => { const material = sourceMaterial(); assert.throws(() => definePublicationSourceIdentity(sourceInput({ ...material, provenance: [] })), /requires provenance/); assert.throws(() => definePublicationSourceIdentity(sourceInput({ ...material, provenance: [{ ...material.provenance[0], validationAuthority: " " }] })), /validation authority/); assert.throws(() => definePublicationSourceIdentity(sourceInput({ ...material, provenance: [material.provenance[0], material.provenance[0]] })), /duplicate identity/); });
test("rejects duplicate capability identity contradictory operations and unsupported values", () => { const material = sourceMaterial(); assert.throws(() => definePublicationSourceIdentity(sourceInput({ ...material, capabilities: [material.capabilities[0], material.capabilities[0]] })), /duplicate identity/); assert.throws(() => definePublicationSourceIdentity(sourceInput({ ...material, capabilities: [material.capabilities[0], { ...material.capabilities[0], capabilityId: "capability:other", supportState: "unsupported" }] })), /contradictory/); assert.throws(() => definePublicationSourceIdentity(sourceInput({ ...material, capabilities: [{ ...material.capabilities[0], operation: "unknown" as "register" }] })), /unsupported/); });
test("source capability and provenance caller order are deterministic", () => { const material = sourceMaterial(); const reversed = { ...material, capabilities: [...material.capabilities].reverse(), provenance: [...material.provenance].reverse(), knownLimitations: [...material.knownLimitations].reverse() }; assert.deepEqual(definePublicationSourceIdentity(sourceInput(material)), definePublicationSourceIdentity(sourceInput(reversed))); });
test("source output is caller-isolated and recursively frozen", () => { const material = sourceMaterial(); const capabilities = [...material.capabilities]; const provenance = [...material.provenance]; const result = definePublicationSourceIdentity(sourceInput({ ...material, capabilities, provenance })); capabilities.reverse(); provenance.length = 0; assert.equal(result.capabilities[0].capabilityId, "capability:correct"); assert.equal(result.provenance.length, 1); assert.ok(Object.isFrozen(result.capabilities[0].compatiblePolicies)); });
test("source envelope digest is deterministic material-sensitive and domain separated", () => { const material = sourceMaterial(); const first = derivePublicationSourceEnvelope(material); const changed = derivePublicationSourceEnvelope({ ...material, sourceRevision: "2" }); assert.equal(first.digest.domain, "publication_source_identity"); assert.equal(first.digest.qualifiedDigest, derivePublicationSourceEnvelope(material).digest.qualifiedDigest); assert.notEqual(first.digest.qualifiedDigest, changed.digest.qualifiedDigest); assert.notEqual(first.digest.qualifiedDigest, deriveDomainSeparatedDigest(first.payload.canonicalBytes, "publication_instruction").qualifiedDigest); });
test("source envelope has no execution timestamp or runtime availability material", () => { const result = derivePublicationSourceEnvelope(sourceMaterial()); assert.doesNotMatch(result.payload.canonicalJson, /timestamp|runtimeAvailability|executedAt/); });
test("source lifecycle validates every representable state and supersession rules", () => { for (const state of ["active", "inactive", "deprecated", "unavailable"] as const) assert.equal(definePublicationSourceIdentity(sourceInput({ ...sourceMaterial(), lifecycle: { state, lifecycleVersion: "1", supersededBySourceId: null, supersededBySourceRevision: null } })).lifecycle.state, state); const superseded = sourceMaterial(); assert.equal(definePublicationSourceIdentity(sourceInput({ ...superseded, lifecycle: { state: "superseded", lifecycleVersion: "1", supersededBySourceId: "source:next", supersededBySourceRevision: "2" } })).lifecycle.state, "superseded"); assert.throws(() => definePublicationSourceIdentity(sourceInput({ ...superseded, lifecycle: { state: "superseded", lifecycleVersion: "1", supersededBySourceId: null, supersededBySourceRevision: null } })), /successor/); });
test("capability preserves support only and grants no engineering authority", () => { const result = definePublicationSourceIdentity(sourceInput()); assert.equal(Reflect.get(result.capabilities[0], "engineeringAuthority"), undefined); assert.equal(Reflect.get(result.capabilities[0], "verification"), undefined); assert.equal(Reflect.get(result.capabilities[0], "confidence"), undefined); });

test("defines a valid exact immutable registry record reference", () => { const result = defineRegistryRecordReference(record()); assert.deepEqual(result, record()); assert.ok(Object.isFrozen(result)); });
test("rejects malformed registry record identity version digest and lifecycle", () => { assert.throws(() => defineRegistryRecordReference(record({ stableKnowledgeId: " " })), /identity/); assert.throws(() => defineRegistryRecordReference(record({ knowledgeVersion: "bad version" })), /version/); assert.throws(() => defineRegistryRecordReference(record({ canonicalContentDigest: "bad" })), /digest/); assert.throws(() => defineRegistryRecordReference(record({ lifecycleState: "unknown" as "active" })), /lifecycle/); });
test("record manifest is canonical caller-order independent frozen and isolated", () => { const records = [record({ stableKnowledgeId: "calibration:b" }), record({ stableKnowledgeId: "calibration:a", canonicalContentDigest: digest("3") })]; const first = defineRegistryRecordManifest(records); const second = defineRegistryRecordManifest([...records].reverse()); records.reverse(); assert.deepEqual(first, second); assert.equal(first.records[0].stableKnowledgeId, "calibration:a"); assert.ok(Object.isFrozen(first)); assert.ok(Object.isFrozen(first.records)); });
test("record manifest rejects duplicate exact and conflicting identity-version references", () => { const value = record(); assert.throws(() => defineRegistryRecordManifest([value, value]), /duplicate identity/); assert.throws(() => defineRegistryRecordManifest([value, { ...value, canonicalContentDigest: digest("9") }]), /conflicting/); });
test("record-set digest is deterministic order-independent and material-sensitive", () => { const records = [record(), record({ stableKnowledgeId: "calibration:other", canonicalContentDigest: digest("3") })]; const first = deriveRegistryRecordSet(records); assert.equal(first.digest.domain, "registry_record_set_manifest"); assert.equal(first.digest.qualifiedDigest, deriveRegistryRecordSet([...records].reverse()).digest.qualifiedDigest); assert.notEqual(first.digest.qualifiedDigest, deriveRegistryRecordSet([record()]).digest.qualifiedDigest); });
test("record-set digest excludes all snapshot event metadata", () => { const records = [record()]; const first = deriveRegistryRecordSet(records); const left = defineRegistrySnapshotIdentity(snapshotInput({ snapshotId: "snapshot:left", recordManifest: first.manifest })); const right = defineRegistrySnapshotIdentity(snapshotInput({ snapshotId: "snapshot:right", snapshotRevision: "2", constructedAt: "2026-08-02T00:00:00.000Z", recordManifest: first.manifest })); assert.equal(left.recordSetDigest, right.recordSetDigest); assert.notEqual(left.snapshotEnvelopeDigest, right.snapshotEnvelopeDigest); });

test("defines valid initial and successor snapshot identities", () => { const initial = defineRegistrySnapshotIdentity(snapshotInput()); assert.equal(initial.predecessorSnapshot, null); const successor = defineRegistrySnapshotIdentity(snapshotInput({ snapshotKind: "successor", snapshotId: "registry-snapshot:successor", snapshotRevision: "2", predecessorSnapshot: { snapshotId: initial.snapshotId, snapshotRevision: initial.snapshotRevision, snapshotEnvelopeDigest: initial.snapshotEnvelopeDigest } })); assert.equal(successor.predecessorSnapshot?.snapshotId, initial.snapshotId); });
test("snapshot predecessor rules reject missing present and same identities", () => { const initialWithPredecessor = snapshotInput({ predecessorSnapshot: { snapshotId: "other", snapshotRevision: "1", snapshotEnvelopeDigest: digest("8") } }); assert.throws(() => defineRegistrySnapshotIdentity(initialWithPredecessor), /Initial/); const successorMissing = snapshotInput({ snapshotKind: "successor", snapshotId: "successor" }); assert.throws(() => defineRegistrySnapshotIdentity(successorMissing), /requires a predecessor/); const same = snapshotInput({ snapshotKind: "successor", predecessorSnapshot: { snapshotId: "registry-snapshot:initial", snapshotRevision: "0", snapshotEnvelopeDigest: digest("8") } }); assert.throws(() => defineRegistrySnapshotIdentity(same), /must differ/); });
test("snapshot validates record count and record-set digest", () => { const valid = snapshotInput(); assert.throws(() => defineRegistrySnapshotIdentity({ ...valid, recordCount: 2 }), /record count/); assert.throws(() => defineRegistrySnapshotIdentity({ ...valid, recordSetDigest: digest("9") }), /record-set digest/); });
test("typed receipt references validate identity revision digest order and uniqueness", () => { assert.ok(Object.isFrozen(definePublicationReceiptReference({ receiptId: "receipt:1", receiptRevision: "1", receiptDigest: digest("1") }))); assert.throws(() => definePublicationReceiptReference({ receiptId: " ", receiptRevision: "1", receiptDigest: digest("1") }), /identity/); assert.throws(() => definePublicationReceiptReference({ receiptId: "receipt:1", receiptRevision: "bad revision", receiptDigest: digest("1") }), /revision/); assert.throws(() => definePublicationReceiptReference({ receiptId: "receipt:1", receiptRevision: "1", receiptDigest: "bad" }), /digest/); const duplicate = snapshotInput(); const reference = duplicate.sourceReceiptReferences[0]; assert.throws(() => defineRegistrySnapshotIdentity({ ...duplicate, sourceReceiptReferences: [reference, reference] }), /duplicate identity/); assert.throws(() => defineRegistrySnapshotIdentity({ ...duplicate, sourceReceiptReferences: [reference, { ...reference, receiptDigest: digest("9") }] }), /conflicting/); });
test("snapshot receipt ordering is deterministic", () => { const first = defineRegistrySnapshotIdentity(snapshotInput()); const reversed = snapshotInput({ sourceReceiptReferences: [...snapshotInput().sourceReceiptReferences].reverse() }); assert.deepEqual(first, defineRegistrySnapshotIdentity(reversed)); assert.equal(first.sourceReceiptReferences[0].receiptId, "receipt:a"); });
test("snapshot requires explicit canonical UTC construction time", () => { const valid = snapshotInput(); assert.throws(() => defineRegistrySnapshotIdentity({ ...valid, constructedAt: "2026-08-01T10:00:00+10:00" }), /canonical UTC/); assert.throws(() => defineRegistrySnapshotIdentity({ ...valid, constructedAt: "invalid" }), /canonical UTC|Invalid time/); });
test("construction timestamp changes snapshot envelope only", () => { const first = defineRegistrySnapshotIdentity(snapshotInput()); const second = defineRegistrySnapshotIdentity(snapshotInput({ constructedAt: "2026-08-02T00:00:00.000Z" })); assert.equal(first.recordSetDigest, second.recordSetDigest); assert.notEqual(first.snapshotEnvelopeDigest, second.snapshotEnvelopeDigest); });
test("snapshot envelope is deterministic and uses its governed domain", () => { const input = snapshotInput(); const first = defineRegistrySnapshotIdentity(input); const second = defineRegistrySnapshotIdentity(snapshotInput()); assert.deepEqual(first, second); const derivation = deriveRegistrySnapshotEnvelope({ snapshotId: first.snapshotId, snapshotRevision: first.snapshotRevision, registryContractId: first.registryContractId, registryContractVersion: first.registryContractVersion, recordSetDigest: first.recordSetDigest, recordCount: first.recordCount, predecessorSnapshot: first.predecessorSnapshot, sourceReceiptReferences: first.sourceReceiptReferences, constructedAt: first.constructedAt, lifecycle: first.lifecycle }); assert.equal(derivation.digest.domain, "registry_snapshot_envelope"); assert.equal(derivation.digest.qualifiedDigest, first.snapshotEnvelopeDigest); });
test("snapshot output is recursively frozen and caller-isolated", () => { const input = snapshotInput(); const receipts = [...input.sourceReceiptReferences]; const records = [...input.recordManifest.records]; const result = defineRegistrySnapshotIdentity({ ...input, sourceReceiptReferences: receipts, recordManifest: { records } }); receipts.reverse(); records.length = 0; assert.equal(result.recordCount, 1); assert.equal(result.sourceReceiptReferences[0].receiptId, "receipt:a"); assert.ok(Object.isFrozen(result)); assert.ok(Object.isFrozen(result.recordManifest.records)); assert.ok(Object.isFrozen(result.sourceReceiptReferences)); });
test("source record-set and snapshot domains separate identical bytes", () => { const payload = canonicalizeDigestDomainPayload({ identity: "same" }); const source = deriveDomainSeparatedDigest(payload.canonicalBytes, "publication_source_identity"); const records = deriveDomainSeparatedDigest(payload.canonicalBytes, "registry_record_set_manifest"); const snapshot = deriveDomainSeparatedDigest(payload.canonicalBytes, "registry_snapshot_envelope"); assert.notEqual(source.qualifiedDigest, records.qualifiedDigest); assert.notEqual(source.qualifiedDigest, snapshot.qualifiedDigest); assert.notEqual(records.qualifiedDigest, snapshot.qualifiedDigest); });
test("slice exposes no execution availability negotiation receipt registry mutation persistence schema or runtime surface", () => { const result = definePublicationSourceIdentity(sourceInput()); for (const key of ["execute", "availability", "negotiateCapabilities", "publicationExecutionResult", "publicationReceipt", "registry", "mutate", "persistence", "schema", "database", "api", "runtime"]) assert.equal(Reflect.get(result, key), undefined); });
