import assert from "node:assert/strict";
import test from "node:test";
import { defineCalibrationKnowledgeObject, type CalibrationApplicability, type CalibrationKnowledgeObject, type CalibrationSourceReference, type GovernedVocabularyReference, type KnowledgeVerificationStatus, type QualifiedAssertion } from "./calibrationKnowledge.ts";
import { defineCalibrationKnowledgeQuery, type CalibrationKnowledgeQuery } from "./calibrationKnowledgeLookup.ts";
import { createImmutableCalibrationKnowledgeRegistry } from "./calibrationKnowledgeRegistry.ts";

const vocab=(termId:string):GovernedVocabularyReference=>({vocabularyId:"test",vocabularyVersion:"1",termId,label:termId,recognition:"known"});
const applicability=(platforms:readonly string[]=[]):CalibrationApplicability=>({scope:vocab(platforms.length?"platform_scoped":"universal"),platforms,engineFamilies:[],ecuFamilies:[],dmeVariants:[],controlStrategies:[],romFamilies:[],softwareVersions:[],calibrationIds:[],stockVariantIds:[],operatingModes:[],transmissions:[],regions:[],emissionsSpecifications:[],hardwareConfigurations:[],sourceReferenceIds:[],unresolvedReason:null});
function assertion<T>(id:string,value:T,status:KnowledgeVerificationStatus="candidate",app=applicability()):QualifiedAssertion<T>{const authoritative=["verified","founder_verified","authoritatively_verified"].includes(status);return{assertionId:id,value,verificationStatus:status,confidence:authoritative?"high":"medium",authority:authoritative?{authorityType:"test",authorityIdentifier:"founder"}:null,provenance:[{sourceType:"test",sourceIdentifier:id,validationMethod:authoritative?"review":undefined,validationAuthority:authoritative?"founder":undefined,validationDate:authoritative?"2026-08-01":undefined}],supportingEvidence:[{evidenceId:`e:${id}`,sourceType:"test",sourceIdentifier:id}],contradictoryEvidence:[],applicability:app,conflictState:"none",unresolvedReason:null,version:"1",lifecycle:{status:"active",version:"1"}};}
function record(id:string,status:KnowledgeVerificationStatus="candidate",alias="Alias",source="source:1",platforms:readonly string[]=[]):CalibrationKnowledgeObject{const app=applicability(platforms);return defineCalibrationKnowledgeObject({identity:assertion(`identity:${id}`,{stableId:id},status,app),canonicalName:assertion(`name:${id}`,`Name ${id}`),aliases:[assertion(`alias:${id}`,{name:alias},status,app)],purposes:[],engineeringIntents:[],calibrationKind:assertion(`kind:${id}`,vocab("target")),primarySubsystem:assertion(`subsystem:${id}`,vocab("boost")),relatedSubsystems:[],applicability:assertion(`app:${id}`,app,status,app),sourceRepresentations:[assertion(`source:${id}`,{sourceReferenceId:source,sourceType:vocab("xdf"),sourceIdentifier:source,axes:[],conversionMetadata:{}},status,app)],directionalBehaviours:[],relationships:[],provenance:[{sourceType:"test",sourceIdentifier:`record:${id}`}],lifecycle:{status:"active",version:"1"},version:"1"});}
function query(value:{kind:"canonical_identity";stableId:string}|{kind:"qualified_alias";alias:string}|{kind:"source_reference";sourceReferenceId:string;sourceType:GovernedVocabularyReference},status:KnowledgeVerificationStatus="candidate",platform?:string):CalibrationKnowledgeQuery{return defineCalibrationKnowledgeQuery({queryId:"q:1",selectors:[assertion("selector:1",value,status)],context:{assertions:platform?[assertion("context:platform",{dimension:vocab("platform"),values:[platform]})]:[]},contractVersion:"1"});}

test("empty registry is frozen, answers unknown, and is not unavailable",async()=>{const registry=createImmutableCalibrationKnowledgeRegistry();assert.ok(Object.isFrozen(registry));assert.deepEqual(Object.keys(registry),["lookup"]);const result=await registry.lookup(query({kind:"canonical_identity",stableId:"missing"}));assert.equal(result.outcome,"unknown");assert.notEqual(result.outcome,"runtime_unavailable");});
test("constructs one object and rejects duplicate canonical identities",()=>{assert.doesNotThrow(()=>createImmutableCalibrationKnowledgeRegistry([record("cal:1")]));assert.throws(()=>createImmutableCalibrationKnowledgeRegistry([record("cal:1"),record("cal:1")]),/duplicated/);});
test("rejects structurally invalid supplied objects",()=>{const valid=record("cal:1");assert.throws(()=>createImmutableCalibrationKnowledgeRegistry([{...valid,version:" "}]),/version is required/);});
test("caller mutation cannot alter the private registry snapshot",async()=>{const aliases=[assertion("alias",{name:"Original"})];const input={...record("cal:1"),aliases};const registry=createImmutableCalibrationKnowledgeRegistry([input]);aliases[0]={...aliases[0],value:{name:"Changed"}};const result=await registry.lookup(query({kind:"qualified_alias",alias:"Original"}));assert.equal(result.outcome,"exact_candidate");assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result.candidates));assert.ok(Object.isFrozen(result.candidates[0].knowledge));});
test("matches canonical identity exactly",async()=>{const result=await createImmutableCalibrationKnowledgeRegistry([record("cal:1")]).lookup(query({kind:"canonical_identity",stableId:"cal:1"}));assert.equal(result.outcome,"exact_candidate");assert.equal(result.candidates[0].matchBasis.value?.kind.termId,"canonical_identity");});
test("matches qualified alias exactly and rejects partial alias",async()=>{const registry=createImmutableCalibrationKnowledgeRegistry([record("cal:1","candidate","Boost Main")]);assert.equal((await registry.lookup(query({kind:"qualified_alias",alias:"Boost Main"}))).outcome,"exact_candidate");assert.equal((await registry.lookup(query({kind:"qualified_alias",alias:"Boost"}))).outcome,"unknown");});
test("matches qualified source identity and source type exactly",async()=>{const registry=createImmutableCalibrationKnowledgeRegistry([record("cal:1","candidate","Alias","xdf:1")]);assert.equal((await registry.lookup(query({kind:"source_reference",sourceReferenceId:"xdf:1",sourceType:vocab("xdf")}))).outcome,"exact_candidate");assert.equal((await registry.lookup(query({kind:"source_reference",sourceReferenceId:"xdf:1",sourceType:vocab("other")}))).outcome,"unknown");});
test("fully authoritative identity, selector, match basis, and applicability return exact_verified",async()=>{const result=await createImmutableCalibrationKnowledgeRegistry([record("cal:1","verified")]).lookup(query({kind:"canonical_identity",stableId:"cal:1"},"verified"));assert.equal(result.outcome,"exact_verified");});
test("incomplete selector authority keeps an authoritative record exact_candidate",async()=>{const result=await createImmutableCalibrationKnowledgeRegistry([record("cal:1","verified")]).lookup(query({kind:"canonical_identity",stableId:"cal:1"}));assert.equal(result.outcome,"exact_candidate");assert.equal(result.candidates[0].matchBasis.verificationStatus,"unknown");});
test("multiple exact alias candidates remain preserved without ranking",async()=>{const result=await createImmutableCalibrationKnowledgeRegistry([record("cal:1","candidate","Shared"),record("cal:2","verified","Shared")]).lookup(query({kind:"qualified_alias",alias:"Shared"}));assert.equal(result.outcome,"multiple_candidates");assert.deepEqual(result.candidates.map((item)=>item.candidateId),["cal:1","cal:2"]);});
test("qualified context contradiction remains conflict",async()=>{const result=await createImmutableCalibrationKnowledgeRegistry([record("cal:1","candidate","Alias","source:1",["N54"])]).lookup(query({kind:"canonical_identity",stableId:"cal:1"},"candidate","B58"));assert.equal(result.outcome,"conflict");if(result.outcome!=="conflict")return;assert.deepEqual(result.conflicts[0].candidateIds,["cal:1"]);assert.deepEqual(result.conflicts[0].contradictoryAssertionIds,["context:platform"]);});
test("selectors that deterministically identify different records remain conflict",async()=>{const registry=createImmutableCalibrationKnowledgeRegistry([record("cal:1","candidate","One"),record("cal:2","candidate","Two")]);const q=defineCalibrationKnowledgeQuery({queryId:"q:conflict",selectors:[assertion("selector:one",{kind:"canonical_identity" as const,stableId:"cal:1"}),assertion("selector:two",{kind:"canonical_identity" as const,stableId:"cal:2"})],context:{assertions:[]},contractVersion:"1"});const result=await registry.lookup(q);assert.equal(result.outcome,"conflict");if(result.outcome!=="conflict")return;assert.equal(result.candidates.length,2);});
test("repeated identical queries return deterministic deeply immutable results",async()=>{const registry=createImmutableCalibrationKnowledgeRegistry([record("cal:1")]);const q=query({kind:"canonical_identity",stableId:"cal:1"});const first=await registry.lookup(q);const second=await registry.lookup(q);assert.deepEqual(first,second);assert.ok(Object.isFrozen(first.candidates[0].matchBasis.value?.selectorIds));assert.equal(Reflect.set(first.candidates,"0",null),false);});
test("malformed runtime input returns invalid rather than unknown",async()=>{const registry=createImmutableCalibrationKnowledgeRegistry();const result=await Reflect.apply(registry.lookup,registry,[{queryId:"q",selectors:[],context:{assertions:[]},contractVersion:"1"}]);assert.equal(result.outcome,"invalid");});
test("registry exposes no mutation operation or internal collection",()=>{const registry=createImmutableCalibrationKnowledgeRegistry([record("cal:1")]);assert.deepEqual(Object.keys(registry),["lookup"]);assert.equal(Reflect.get(registry,"records"),undefined);assert.equal(Reflect.get(registry,"add"),undefined);});
test("convergent canonical and alias selectors are order-independent and conservatively qualified",async()=>{const base=record("cal:1","verified","Alias");const mixed=defineCalibrationKnowledgeObject({...base,aliases:[assertion("alias:provisional",{name:"Alias"},"provisional")]});const canonical=assertion("selector:canonical",{kind:"canonical_identity" as const,stableId:"cal:1"},"verified");const alias=assertion("selector:alias",{kind:"qualified_alias" as const,alias:"Alias"},"provisional");const make=(selectors:readonly (typeof canonical|typeof alias)[])=>defineCalibrationKnowledgeQuery({queryId:"q:convergent",selectors,context:{assertions:[]},contractVersion:"1"});const registry=createImmutableCalibrationKnowledgeRegistry([mixed]);const forward=await registry.lookup(make([canonical,alias]));const reverse=await registry.lookup(make([alias,canonical]));assert.equal(forward.outcome,"exact_candidate");assert.equal(reverse.outcome,"exact_candidate");assert.equal(forward.candidates.length,1);assert.deepEqual(forward.candidates[0].matchBasis,reverse.candidates[0].matchBasis);assert.deepEqual(forward.candidates[0].limitations,reverse.candidates[0].limitations);});

test("fully authoritative convergent selectors remain exact_verified",async()=>{const canonical=assertion("selector:canonical",{kind:"canonical_identity" as const,stableId:"cal:1"},"verified");const alias=assertion("selector:alias",{kind:"qualified_alias" as const,alias:"Alias"},"verified");const q=defineCalibrationKnowledgeQuery({queryId:"q:verified",selectors:[canonical,alias],context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([record("cal:1","verified","Alias")]).lookup(q);assert.equal(result.outcome,"exact_verified");assert.equal(result.candidates.length,1);});

test("duplicate aliases and source representations do not distort candidates or authority",async()=>{const base=record("cal:1","candidate","Alias","xdf:1");const duplicate=defineCalibrationKnowledgeObject({...base,aliases:[...base.aliases,assertion("alias:duplicate",{name:"Alias"})],sourceRepresentations:[...base.sourceRepresentations,assertion("source:duplicate",{sourceReferenceId:"xdf:1",sourceType:vocab("xdf"),sourceIdentifier:"xdf:1",axes:[],conversionMetadata:{}})]});const registry=createImmutableCalibrationKnowledgeRegistry([duplicate]);const aliasResult=await registry.lookup(query({kind:"qualified_alias",alias:"Alias"}));const sourceResult=await registry.lookup(query({kind:"source_reference",sourceReferenceId:"xdf:1",sourceType:vocab("xdf")}));assert.equal(aliasResult.candidates.length,1);assert.equal(sourceResult.candidates.length,1);assert.equal(aliasResult.outcome,"exact_candidate");assert.equal(sourceResult.outcome,"exact_candidate");});

test("source selector convergence remains order-independent",async()=>{const base=record("cal:1","candidate","Alias","xdf:1");const sources=[assertion("source:a",{sourceReferenceId:"xdf:1",sourceType:vocab("xdf"),sourceIdentifier:"xdf:1",axes:[],conversionMetadata:{}}),assertion("source:b",{sourceReferenceId:"xdf:2",sourceType:vocab("xdf"),sourceIdentifier:"xdf:2",axes:[],conversionMetadata:{}})];const item=defineCalibrationKnowledgeObject({...base,sourceRepresentations:sources});const one=assertion("selector:one",{kind:"source_reference" as const,sourceReferenceId:"xdf:1",sourceType:vocab("xdf")});const two=assertion("selector:two",{kind:"source_reference" as const,sourceReferenceId:"xdf:2",sourceType:vocab("xdf")});const make=(selectors:readonly (typeof one)[])=>defineCalibrationKnowledgeQuery({queryId:"q:sources",selectors,context:{assertions:[]},contractVersion:"1"});const registry=createImmutableCalibrationKnowledgeRegistry([item]);const forward=await registry.lookup(make([one,two]));const reverse=await registry.lookup(make([two,one]));assert.deepEqual(forward.candidates[0].matchBasis,reverse.candidates[0].matchBasis);assert.deepEqual(forward.candidates[0].limitations,reverse.candidates[0].limitations);});

test("canonical identity, alias, source identity, and source type are case-sensitive",async()=>{const registry=createImmutableCalibrationKnowledgeRegistry([record("Cal:One","candidate","Exact Alias","XDF:One")]);assert.equal((await registry.lookup(query({kind:"canonical_identity",stableId:"cal:one"}))).outcome,"unknown");assert.equal((await registry.lookup(query({kind:"qualified_alias",alias:"exact alias"}))).outcome,"unknown");assert.equal((await registry.lookup(query({kind:"source_reference",sourceReferenceId:"xdf:one",sourceType:vocab("xdf")}))).outcome,"unknown");assert.equal((await registry.lookup(query({kind:"source_reference",sourceReferenceId:"XDF:One",sourceType:vocab("XDF")}))).outcome,"unknown");});

test("missing applicability remains explicit and compatible applicability is deterministic",async()=>{const base=record("cal:1","candidate","Alias","source:1",["N54"]);const missing=defineCalibrationKnowledgeObject({...base,identity:{...base.identity,value:{stableId:"cal:missing"}},applicability:{...base.applicability,assertionId:"app:missing",value:null,verificationStatus:"unknown",confidence:"unknown",authority:null,unresolvedReason:"Applicability is unknown."}});const missingResult=await createImmutableCalibrationKnowledgeRegistry([missing]).lookup(query({kind:"canonical_identity",stableId:"cal:missing"}));assert.equal(missingResult.outcome,"exact_candidate");assert.equal(missingResult.candidates[0].applicabilityAssessment.verificationStatus,"unknown");assert.equal(missingResult.candidates[0].applicabilityAssessment.value?.scope.recognition,"unknown");assert.deepEqual(missingResult.candidates[0].applicabilityAssessment.value?.platforms,[]);const registry=createImmutableCalibrationKnowledgeRegistry([base]);const first=await registry.lookup(query({kind:"canonical_identity",stableId:"cal:1"},"candidate","N54"));const second=await registry.lookup(query({kind:"canonical_identity",stableId:"cal:1"},"candidate","N54"));assert.equal(first.outcome,"exact_candidate");assert.deepEqual(first,second);});
test("duplicate matches preserve selector provenance and Evidence exactly once",async()=>{const base=record("cal:dedupe","candidate","Alias");const duplicate=defineCalibrationKnowledgeObject({...base,aliases:[...base.aliases,assertion("alias:second",{name:"Alias"})]});const selector={...assertion("selector:dedupe",{kind:"qualified_alias" as const,alias:"Alias"}),contradictoryEvidence:[{evidenceId:"e:contradiction",sourceType:"test",sourceIdentifier:"contradiction"}]};const q=defineCalibrationKnowledgeQuery({queryId:"q:dedupe",selectors:[selector],context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([duplicate]).lookup(q);const basis=result.candidates[0].matchBasis;assert.equal(basis.provenance.filter((item)=>item.sourceIdentifier==="selector:dedupe").length,1);assert.equal(basis.supportingEvidence.filter((item)=>item.evidenceId==="e:selector:dedupe").length,1);assert.equal(basis.contradictoryEvidence.filter((item)=>item.evidenceId==="e:contradiction").length,1);assert.equal(result.outcome,"exact_candidate");});

test("distinct provenance and Evidence remain preserved",async()=>{const base=record("cal:distinct","candidate","Alias");const aliases=[assertion("alias:one",{name:"Alias"}),assertion("alias:two",{name:"Alias"})];const item=defineCalibrationKnowledgeObject({...base,aliases});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(query({kind:"qualified_alias",alias:"Alias"}));const basis=result.candidates[0].matchBasis;assert.ok(basis.provenance.some((entry)=>entry.sourceIdentifier==="alias:one"));assert.ok(basis.provenance.some((entry)=>entry.sourceIdentifier==="alias:two"));assert.ok(basis.supportingEvidence.some((entry)=>entry.evidenceId==="e:alias:one"));assert.ok(basis.supportingEvidence.some((entry)=>entry.evidenceId==="e:alias:two"));});

test("component applicability, authority, lifecycle, and unresolved qualification remain conservatively visible",async()=>{const base=record("cal:scope","verified","Alias");const narrow={...assertion("alias:narrow",{name:"Alias"},"verified",applicability(["N54"])),authority:{authorityType:"test",authorityIdentifier:"reviewer"}};const item=defineCalibrationKnowledgeObject({...base,aliases:[narrow]});const canonical=assertion("selector:canonical",{kind:"canonical_identity" as const,stableId:"cal:scope"},"verified");const alias=assertion("selector:alias",{kind:"qualified_alias" as const,alias:"Alias"},"verified",applicability(["N54"]));const q=defineCalibrationKnowledgeQuery({queryId:"q:scope",selectors:[canonical,alias],context:{assertions:[assertion("context:platform",{dimension:vocab("platform"),values:["B58"]})]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(q);assert.equal(result.outcome,"conflict");assert.equal(result.candidates[0].matchBasis.verificationStatus,"unknown");assert.equal(result.candidates[0].applicabilityAssessment.value?.scope.recognition,"unknown");assert.ok(result.candidates[0].limitations.some((value)=>value.includes("alias:narrow")&&value.includes("authority=test:reviewer")&&value.includes("lifecycle=active:1")&&value.includes('"N54"')));assert.ok(result.candidates[0].limitations.some((value)=>value.includes("authority=test:founder")));});

test("duplicate source matches preserve selector provenance and Evidence once without changing authority",async()=>{const base=record("cal:source-dedupe","candidate","Alias","xdf:1");const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const item=defineCalibrationKnowledgeObject({...base,sourceRepresentations:[base.sourceRepresentations[0],assertion("source:duplicate",sourceValue)]});const selector={...assertion("selector:source",{kind:"source_reference" as const,sourceReferenceId:"xdf:1",sourceType:vocab("xdf")}),contradictoryEvidence:[{evidenceId:"e:source-conflict",sourceType:"test",sourceIdentifier:"source-conflict"}]};const q=defineCalibrationKnowledgeQuery({queryId:"q:source-dedupe",selectors:[selector],context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(q);const basis=result.candidates[0].matchBasis;assert.equal(basis.provenance.filter((entry)=>entry.sourceIdentifier==="selector:source").length,1);assert.equal(basis.supportingEvidence.filter((entry)=>entry.evidenceId==="e:selector:source").length,1);assert.equal(basis.contradictoryEvidence.filter((entry)=>entry.evidenceId==="e:source-conflict").length,1);assert.equal(result.outcome,"exact_candidate");});

test("duplicate representation count cannot strengthen verification or alter outcome",async()=>{const base=record("cal:count","verified","Alias");const duplicate=defineCalibrationKnowledgeObject({...base,aliases:[...base.aliases,assertion("alias:duplicate",{name:"Alias"},"verified")]});const q=query({kind:"qualified_alias",alias:"Alias"},"candidate");const single=await createImmutableCalibrationKnowledgeRegistry([base]).lookup(q);const repeated=await createImmutableCalibrationKnowledgeRegistry([duplicate]).lookup(q);assert.equal(single.outcome,"exact_candidate");assert.equal(repeated.outcome,single.outcome);assert.equal(repeated.candidates[0].matchBasis.verificationStatus,single.candidates[0].matchBasis.verificationStatus);assert.equal(repeated.candidates[0].matchBasis.confidence,single.candidates[0].matchBasis.confidence);});

test("provisional alias and narrower selector applicability prevent exact_verified without widening",async()=>{const base=record("cal:bounded","verified","Alias");const item=defineCalibrationKnowledgeObject({...base,aliases:[assertion("alias:provisional",{name:"Alias"},"provisional",applicability(["N54"]))]});const selector=assertion("selector:narrow",{kind:"qualified_alias" as const,alias:"Alias"},"verified",applicability(["N54"]));const q=defineCalibrationKnowledgeQuery({queryId:"q:bounded",selectors:[selector],context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(q);assert.equal(result.outcome,"exact_candidate");assert.equal(result.candidates[0].matchBasis.verificationStatus,"unknown");assert.equal(result.candidates[0].applicabilityAssessment.value?.scope.recognition,"unknown");assert.ok(result.candidates[0].limitations.some((value)=>value.includes("alias:provisional")&&value.includes('"N54"')));assert.ok(result.candidates[0].limitations.some((value)=>value.includes("selector:narrow")&&value.includes('"N54"')));});

test("unknown source applicability and unresolved lifecycle qualification remain explicit",async()=>{const base=record("cal:unknown-source","verified","Alias","xdf:unknown");const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const unknownApp={...applicability(),scope:{...vocab("unknown"),recognition:"unknown" as const},unresolvedReason:"Source applicability is unknown."};const source={...assertion("source:unknown",sourceValue,"unknown",unknownApp),unresolvedReason:"Source qualification is unresolved.",lifecycle:{status:"deprecated" as const,version:"2"}};const item=defineCalibrationKnowledgeObject({...base,sourceRepresentations:[source]});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(query({kind:"source_reference",sourceReferenceId:"xdf:unknown",sourceType:vocab("xdf")},"verified"));assert.equal(result.outcome,"exact_candidate");assert.equal(result.candidates[0].applicabilityAssessment.value?.scope.recognition,"unknown");assert.ok(result.candidates[0].limitations.some((value)=>value.includes("source:unknown")&&value.includes("lifecycle=deprecated:2")&&value.includes("Source qualification is unresolved.")&&value.includes("Source applicability is unknown.")));});

test("distinct contradictory Evidence and component ordering remain preserved deterministically",async()=>{const base=record("cal:ordering","candidate","Alias");const aliases=[{...assertion("alias:a",{name:"Alias"}),contradictoryEvidence:[{evidenceId:"e:contra:a",sourceType:"test",sourceIdentifier:"a"}]},{...assertion("alias:b",{name:"Alias"}),contradictoryEvidence:[{evidenceId:"e:contra:b",sourceType:"test",sourceIdentifier:"b"}]}];const forward=defineCalibrationKnowledgeObject({...base,aliases});const reverse=defineCalibrationKnowledgeObject({...base,aliases:[...aliases].reverse()});const q=query({kind:"qualified_alias",alias:"Alias"});const first=await createImmutableCalibrationKnowledgeRegistry([forward]).lookup(q);const second=await createImmutableCalibrationKnowledgeRegistry([reverse]).lookup(q);assert.deepEqual(first,second);assert.deepEqual(first.candidates[0].matchBasis.contradictoryEvidence.map((entry)=>entry.evidenceId).sort(),["e:contra:a","e:contra:b"]);});

test("reversed registry order produces canonically ordered equivalent candidates and conflicts",async()=>{const records=[record("cal:b","candidate","Shared"),record("cal:a","candidate","Shared")];const q=query({kind:"qualified_alias",alias:"Shared"});const forward=await createImmutableCalibrationKnowledgeRegistry(records).lookup(q);const reverse=await createImmutableCalibrationKnowledgeRegistry([...records].reverse()).lookup(q);assert.deepEqual(forward,reverse);assert.deepEqual(forward.candidates.map((item)=>item.candidateId),["cal:a","cal:b"]);});

test("aggregate confidence is the most conservative material confidence",async()=>{const base=record("cal:confidence","verified","Alias");const low={...base.aliases[0],confidence:"low" as const};const item=defineCalibrationKnowledgeObject({...base,aliases:[low]});const highSelector=assertion("selector:confidence",{kind:"qualified_alias" as const,alias:"Alias"},"verified");const q=defineCalibrationKnowledgeQuery({queryId:"q:confidence",selectors:[highSelector],context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(q);assert.equal(result.outcome,"exact_verified");assert.equal(result.candidates[0].matchBasis.confidence,"low");});

test("compatible provisional and unknown context conservatively prevent exact_verified",async()=>{const registry=createImmutableCalibrationKnowledgeRegistry([record("cal:context","verified","Alias","source",["N54"])]);const selector=assertion("selector:context",{kind:"canonical_identity" as const,stableId:"cal:context"},"verified",applicability(["N54"]));const contextValue={dimension:vocab("platform"),values:["N54"]};const provisional=assertion("context:provisional",contextValue,"provisional",applicability(["N54"]));const unknown={...assertion("context:unknown",contextValue,"candidate",applicability(["N54"])),verificationStatus:"unknown" as const,confidence:"unknown" as const,authority:null,unresolvedReason:"Context authority is unknown."};for(const contextAssertion of [provisional,unknown]){const q=defineCalibrationKnowledgeQuery({queryId:`q:${contextAssertion.assertionId}`,selectors:[selector],context:{assertions:[contextAssertion]},contractVersion:"1"});const result=await registry.lookup(q);assert.equal(result.outcome,"exact_candidate");assert.equal(result.candidates[0].matchBasis.confidence,"unknown");assert.ok(result.candidates[0].limitations.some((value)=>value.includes(contextAssertion.assertionId)));}});

test("conflicting context qualification produces a preserved Slice 2 conflict",async()=>{const context={...assertion("context:conflict",{dimension:vocab("platform"),values:["N54"]},"candidate",applicability(["N54"])),conflictState:"unresolved" as const,unresolvedReason:"Context evidence conflicts."};const q=defineCalibrationKnowledgeQuery({queryId:"q:context-conflict",selectors:[assertion("selector:context-conflict",{kind:"canonical_identity" as const,stableId:"cal:context-conflict"})],context:{assertions:[context]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([record("cal:context-conflict","candidate","Alias","source",["N54"])]).lookup(q);assert.equal(result.outcome,"conflict");if(result.outcome==="conflict")assert.deepEqual(result.conflicts[0].contradictoryAssertionIds,["context:conflict"]);});

test("provenance identity preserves delimiter-like values and transformation boundaries",async()=>{const base=record("cal:provenance","candidate","Alias");const first={sourceType:"test",sourceIdentifier:"a\u001fb",transformationHistory:["c"]};const second={sourceType:"test",sourceIdentifier:"a",transformationHistory:["b","c"]};const alias={...base.aliases[0],provenance:[first,second,first]};const item=defineCalibrationKnowledgeObject({...base,aliases:[alias]});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(query({kind:"qualified_alias",alias:"Alias"}));assert.equal(result.candidates[0].matchBasis.provenance.filter((entry)=>entry.sourceType==="test"&&(entry.sourceIdentifier==="a"||entry.sourceIdentifier==="a\u001fb")).length,2);});

test("disjoint material component applicability produces conflict",async()=>{const base=record("cal:app-conflict","verified","Alias","xdf:conflict");const alias=assertion("alias:app-conflict",{name:"Alias"},"verified",applicability(["N54"]));const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const source=assertion("source:app-conflict",sourceValue,"verified",applicability(["B58"]));const item=defineCalibrationKnowledgeObject({...base,aliases:[alias],sourceRepresentations:[source]});const aliasSelector=assertion("selector:alias-conflict",{kind:"qualified_alias" as const,alias:"Alias"},"verified",applicability(["N54"]));const sourceSelector=assertion("selector:source-conflict",{kind:"source_reference" as const,sourceReferenceId:"xdf:conflict",sourceType:vocab("xdf")},"verified",applicability(["B58"]));const q=defineCalibrationKnowledgeQuery({queryId:"q:app-conflict",selectors:[aliasSelector,sourceSelector],context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(q);assert.equal(result.outcome,"conflict");if(result.outcome==="conflict")assert.deepEqual(result.conflicts[0].contradictoryAssertionIds,["alias:app-conflict","selector:alias-conflict","selector:source-conflict","source:app-conflict"]);});

test("conflicting assertion identity reuse is rejected during canonical construction",()=>{const base=record("cal:identity-reuse","candidate","Alias");const candidate=assertion("alias:reuse",{name:"Alias"},"candidate");const provisional={...assertion("alias:reuse",{name:"Alias"},"provisional"),confidence:"low" as const};assert.throws(()=>defineCalibrationKnowledgeObject({...base,aliases:[candidate,provisional]}),/assertion identity alias:reuse is duplicated/);});

test("unknown disjoint-looking applicability remains bounded and does not throw or conflict",async()=>{const base=record("cal:unknown-app","verified","Alias","xdf:unknown-app");const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const unknownScope={...applicability(["N54"]),scope:{...vocab("unknown"),recognition:"unknown" as const},unresolvedReason:"Applicability is unknown."};const alias=assertion("alias:unknown-app",{name:"Alias"},"candidate",unknownScope);const source=assertion("source:unknown-app",sourceValue,"verified",applicability(["B58"]));const item=defineCalibrationKnowledgeObject({...base,aliases:[alias],sourceRepresentations:[source]});const q=defineCalibrationKnowledgeQuery({queryId:"q:unknown-app",selectors:[assertion("selector:unknown-alias",{kind:"qualified_alias" as const,alias:"Alias"},"verified"),assertion("selector:unknown-source",{kind:"source_reference" as const,sourceReferenceId:"xdf:unknown-app",sourceType:vocab("xdf")},"verified")],context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(q);assert.equal(result.outcome,"exact_candidate");});

test("unresolved disjoint-looking applicability remains bounded and does not throw or conflict",async()=>{const base=record("cal:unresolved-app","verified","Alias","xdf:unresolved-app");const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const unresolvedScope={...applicability(["N54"]),unresolvedReason:"Applicability remains unresolved."};const alias={...assertion("alias:unresolved-app",{name:"Alias"},"candidate",unresolvedScope),unresolvedReason:"Alias applicability remains unresolved."};const source=assertion("source:unresolved-app",sourceValue,"verified",applicability(["B58"]));const item=defineCalibrationKnowledgeObject({...base,aliases:[alias],sourceRepresentations:[source]});const q=defineCalibrationKnowledgeQuery({queryId:"q:unresolved-app",selectors:[assertion("selector:unresolved-alias",{kind:"qualified_alias" as const,alias:"Alias"},"verified"),assertion("selector:unresolved-source",{kind:"source_reference" as const,sourceReferenceId:"xdf:unresolved-app",sourceType:vocab("xdf")},"verified")],context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(q);assert.equal(result.outcome,"exact_candidate");});

test("known resolved disjoint applicability preserves exact typed conflict evidence",async()=>{const base=record("cal:typed-app","verified","Alias","xdf:typed-app");const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const alias=assertion("alias:typed-app",{name:"Alias"},"verified",applicability(["N54"]));const source=assertion("source:typed-app",sourceValue,"verified",applicability(["B58"]));const item=defineCalibrationKnowledgeObject({...base,aliases:[alias],sourceRepresentations:[source]});const q=defineCalibrationKnowledgeQuery({queryId:"q:typed-app",selectors:[assertion("selector:typed-alias",{kind:"qualified_alias" as const,alias:"Alias"},"verified",applicability(["N54"])),assertion("selector:typed-source",{kind:"source_reference" as const,sourceReferenceId:"xdf:typed-app",sourceType:vocab("xdf")},"verified",applicability(["B58"]))],context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(q);assert.equal(result.outcome,"conflict");if(result.outcome!=="conflict")return;const evidence=result.conflicts[0].applicabilityConflictEvidence?.find((entry)=>entry.leftAssertionId==="alias:typed-app"&&entry.rightAssertionId==="source:typed-app");assert.ok(evidence);assert.equal(evidence.dimension,"platforms");assert.deepEqual(evidence.leftValues,["N54"]);assert.deepEqual(evidence.rightValues,["B58"]);});

test("non-current lifecycle states bound authority and remain visible",async()=>{for(const status of ["rejected","superseded","deprecated"] as const){const base=record(`cal:lifecycle:${status}`,"verified","Alias");const alias={...base.aliases[0],lifecycle:{status,version:"2"}};const item=defineCalibrationKnowledgeObject({...base,aliases:[alias]});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(query({kind:"qualified_alias",alias:"Alias"},"verified"));assert.equal(result.outcome,"exact_candidate");assert.ok(result.candidates[0].limitations.some((value)=>value.includes(`lifecycle=${status}:2`)));}});

test("canonical applicability versus alias applicability returns uniquely resolved typed conflict",async()=>{const base=record("cal:canonical-alias","verified","Alias","source",["N54"]);const alias=assertion("alias:canonical-alias",{name:"Alias"},"verified",applicability(["B58"]));const item=defineCalibrationKnowledgeObject({...base,aliases:[alias]});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(query({kind:"qualified_alias",alias:"Alias"},"verified"));assert.equal(result.outcome,"conflict");if(result.outcome!=="conflict")return;const evidence=result.conflicts[0].applicabilityConflictEvidence?.find((entry)=>new Set([entry.leftAssertionId,entry.rightAssertionId]).has(base.applicability.assertionId)&&new Set([entry.leftAssertionId,entry.rightAssertionId]).has(alias.assertionId));assert.ok(evidence);assert.equal(evidence.dimension,"platforms");const values=new Map([[evidence.leftAssertionId,evidence.leftValues],[evidence.rightAssertionId,evidence.rightValues]]);assert.deepEqual(values.get(base.applicability.assertionId),["N54"]);assert.deepEqual(values.get(alias.assertionId),["B58"]);assert.notEqual(result.candidates[0].applicabilityAssessment.assertionId,base.applicability.assertionId);});

test("canonical applicability versus source applicability returns uniquely resolved typed conflict",async()=>{const base=record("cal:canonical-source","verified","Alias","xdf:canonical-source",["N54"]);const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const source=assertion("source:canonical-source",sourceValue,"verified",applicability(["B58"]));const item=defineCalibrationKnowledgeObject({...base,sourceRepresentations:[source]});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(query({kind:"source_reference",sourceReferenceId:"xdf:canonical-source",sourceType:vocab("xdf")},"verified"));assert.equal(result.outcome,"conflict");if(result.outcome!=="conflict")return;const evidence=result.conflicts[0].applicabilityConflictEvidence?.find((entry)=>new Set([entry.leftAssertionId,entry.rightAssertionId]).has(base.applicability.assertionId)&&new Set([entry.leftAssertionId,entry.rightAssertionId]).has(source.assertionId));assert.ok(evidence);assert.equal(evidence.dimension,"platforms");});

test("semantic duplicate alias qualification is conservatively merged independent of order",async()=>{const base=record("cal:duplicate-alias","verified","Alias");const verified=base.aliases[0];const provisional={...assertion("alias:duplicate-provisional",{name:"Alias"},"provisional"),confidence:"low" as const};const forward=defineCalibrationKnowledgeObject({...base,aliases:[verified,provisional]});const reverse=defineCalibrationKnowledgeObject({...base,aliases:[provisional,verified]});const q=query({kind:"qualified_alias",alias:"Alias"},"verified");const first=await createImmutableCalibrationKnowledgeRegistry([forward]).lookup(q);const second=await createImmutableCalibrationKnowledgeRegistry([reverse]).lookup(q);assert.deepEqual(first,second);assert.equal(first.outcome,"exact_candidate");assert.equal(first.candidates.length,1);assert.ok(first.candidates[0].matchBasis.provenance.some((entry)=>entry.sourceIdentifier===verified.assertionId));assert.ok(first.candidates[0].matchBasis.provenance.some((entry)=>entry.sourceIdentifier===provisional.assertionId));});

test("semantic duplicate source count cannot change a verified outcome",async()=>{const base=record("cal:duplicate-source","verified","Alias","xdf:duplicate-source");const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const duplicate=assertion("source:duplicate-source",sourceValue,"verified");const single=await createImmutableCalibrationKnowledgeRegistry([base]).lookup(query({kind:"source_reference",sourceReferenceId:"xdf:duplicate-source",sourceType:vocab("xdf")},"verified"));const repeated=await createImmutableCalibrationKnowledgeRegistry([defineCalibrationKnowledgeObject({...base,sourceRepresentations:[base.sourceRepresentations[0],duplicate]})]).lookup(query({kind:"source_reference",sourceReferenceId:"xdf:duplicate-source",sourceType:vocab("xdf")},"verified"));assert.equal(single.outcome,"exact_verified");assert.equal(repeated.outcome,"exact_verified");assert.equal(repeated.candidates.length,1);assert.equal(repeated.candidates[0].matchBasis.confidence,single.candidates[0].matchBasis.confidence);});

test("source display and recognition metadata share governed semantic identity and merge conservatively",async()=>{const base=record("cal:source-metadata","verified","Alias","xdf:metadata");const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const verified=assertion("source:metadata-verified",{...sourceValue,sourceType:{...sourceValue.sourceType,label:"XDF display A",recognition:"known" as const}},"verified");const provisional={...assertion("source:metadata-provisional",{...sourceValue,sourceType:{...sourceValue.sourceType,label:"XDF display B",recognition:"unknown" as const}},"provisional"),confidence:"low" as const};const make=(sources:readonly QualifiedAssertion<CalibrationSourceReference>[])=>defineCalibrationKnowledgeObject({...base,sourceRepresentations:sources});const q=query({kind:"source_reference",sourceReferenceId:"xdf:metadata",sourceType:vocab("xdf")},"verified");const forward=await createImmutableCalibrationKnowledgeRegistry([make([verified,provisional])]).lookup(q);const reverse=await createImmutableCalibrationKnowledgeRegistry([make([provisional,verified])]).lookup(q);assert.deepEqual(forward,reverse);assert.equal(forward.outcome,"exact_candidate");assert.equal(forward.candidates.length,1);assert.equal(forward.candidates[0].matchBasis.confidence,"unknown");assert.ok(forward.candidates[0].matchBasis.provenance.some((entry)=>entry.sourceIdentifier===verified.assertionId));assert.ok(forward.candidates[0].matchBasis.provenance.some((entry)=>entry.sourceIdentifier===provisional.assertionId));});

test("source display metadata duplicates cannot change a verified outcome",async()=>{const base=record("cal:source-display","verified","Alias","xdf:display");const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const first=assertion("source:display-a",{...sourceValue,sourceType:{...sourceValue.sourceType,label:"Display A"}},"verified");const second=assertion("source:display-b",{...sourceValue,sourceType:{...sourceValue.sourceType,label:"Display B"}},"verified");const q=query({kind:"source_reference",sourceReferenceId:"xdf:display",sourceType:vocab("xdf")},"verified");const single=await createImmutableCalibrationKnowledgeRegistry([defineCalibrationKnowledgeObject({...base,sourceRepresentations:[first]})]).lookup(q);const duplicate=await createImmutableCalibrationKnowledgeRegistry([defineCalibrationKnowledgeObject({...base,sourceRepresentations:[first,second]})]).lookup(q);assert.equal(single.outcome,"exact_verified");assert.equal(duplicate.outcome,"exact_verified");assert.equal(duplicate.candidates[0].matchBasis.confidence,single.candidates[0].matchBasis.confidence);assert.equal(duplicate.candidates.length,1);});

test("distinct source term version and reference identities remain distinct",async()=>{const base=record("cal:source-distinct","verified","Alias","source:one");const sourceValue=base.sourceRepresentations[0].value;assert.ok(sourceValue);const term=assertion("source:distinct-term",{...sourceValue,sourceType:{...sourceValue.sourceType,termId:"other",label:"other"}},"verified");const version=assertion("source:distinct-version",{...sourceValue,sourceType:{...sourceValue.sourceType,vocabularyVersion:"2"}},"verified");const reference=assertion("source:distinct-reference",{...sourceValue,sourceReferenceId:"source:two",sourceIdentifier:"source:two"},"verified");const item=defineCalibrationKnowledgeObject({...base,sourceRepresentations:[base.sourceRepresentations[0],term,version,reference]});const selectors=[assertion("selector:source-base",{kind:"source_reference" as const,sourceReferenceId:"source:one",sourceType:vocab("xdf")},"verified"),assertion("selector:source-term",{kind:"source_reference" as const,sourceReferenceId:"source:one",sourceType:{...vocab("other"),termId:"other"}},"verified"),assertion("selector:source-version",{kind:"source_reference" as const,sourceReferenceId:"source:one",sourceType:{...vocab("xdf"),vocabularyVersion:"2"}},"verified"),assertion("selector:source-reference",{kind:"source_reference" as const,sourceReferenceId:"source:two",sourceType:vocab("xdf")},"verified")];const q=defineCalibrationKnowledgeQuery({queryId:"q:source-distinct",selectors,context:{assertions:[]},contractVersion:"1"});const result=await createImmutableCalibrationKnowledgeRegistry([item]).lookup(q);assert.equal(result.outcome,"exact_verified");assert.deepEqual(result.candidates[0].matchBasis.value?.selectorIds,selectors.map((selector)=>selector.assertionId).sort());for(const source of item.sourceRepresentations)assert.ok(result.candidates[0].matchBasis.provenance.some((entry)=>entry.sourceIdentifier===source.assertionId));});
