import assert from "node:assert/strict";
import test from "node:test";
import { defineCalibrationKnowledgeAdmissionProposal, defineProposedCalibrationKnowledgeRevision, type AdmissionDecisionOutcome, type AdmissionPolicyReference, type AdmissionStableIdentity, type CalibrationKnowledgeAdmissionProposal, type PublicationOperation } from "./calibrationKnowledgeAdmission.ts";
import { defineCalibrationKnowledgeObject, type CalibrationApplicability, type GovernedVocabularyReference, type QualifiedAssertion } from "./calibrationKnowledge.ts";
import type { CalibrationKnowledgeEvidenceAuthorityAssessment } from "./calibrationKnowledgeEvidenceAuthorityAssessment.ts";
import type { CalibrationIdentityLineageConflictAssessment } from "./calibrationKnowledgeIdentityLineageConflictAssessment.ts";
import type { CalibrationPublicationEligibilityAssessment } from "./calibrationKnowledgePublicationEligibilityAssessment.ts";
import { constructAuthorisedCalibrationKnowledgeAdmissionDecision, type AuthorisedCalibrationKnowledgeAdmissionDecisionInput, type CalibrationAdmissionDecisionAuthorityScope } from "./calibrationKnowledgeAuthorisedAdmissionDecision.ts";
import { CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1, CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1, deriveCalibrationKnowledgeContentDigests } from "./calibrationKnowledgeCanonicalSerialization.ts";
import { constructDeterministicCalibrationKnowledgePublicationInstruction, type DeterministicCalibrationKnowledgePublicationInstruction } from "./calibrationKnowledgeDeterministicPublicationInstruction.ts";
import { definePublicationSourceIdentity, defineRegistrySnapshotIdentity, derivePublicationSourceEnvelope, deriveRegistryRecordSet, deriveRegistrySnapshotEnvelope, type PublicationSourceIdentity, type RegistrySnapshotIdentity } from "./calibrationKnowledgePublicationSourceRegistrySnapshot.ts";
import { constructPublicationExecutionRequest, constructPublicationExecutionResult, deriveExecutionAttemptId, derivePublicationExecutionIdempotencyId, derivePublicationExecutionResult, type PublicationExecutionRequest, type PublicationExecutionResult } from "./calibrationKnowledgePublicationExecutionResult.ts";

const digest=(seed:string):string=>`sha256:${[...seed].map(item=>item.charCodeAt(0).toString(16)).join("").padEnd(64,"0").slice(0,64)}`;
const identity=(id:string,revision="1"):AdmissionStableIdentity=>({id,revision,contentDigest:digest(`${id}:${revision}`)});
const vocabulary=(termId:string):GovernedVocabularyReference=>({vocabularyId:"test",vocabularyVersion:"1",termId,label:termId,recognition:"known"});
const applicability=():CalibrationApplicability=>({scope:vocabulary("universal"),platforms:[],engineFamilies:[],ecuFamilies:[],dmeVariants:[],controlStrategies:[],romFamilies:[],softwareVersions:[],calibrationIds:[],stockVariantIds:[],operatingModes:[],transmissions:[],regions:[],emissionsSpecifications:[],hardwareConfigurations:[],sourceReferenceIds:[],unresolvedReason:null});
function assertion<T>(assertionId:string,value:T):QualifiedAssertion<T>{return{assertionId,value,verificationStatus:"candidate",confidence:"medium",authority:null,provenance:[{sourceType:"fixture",sourceIdentifier:assertionId}],supportingEvidence:[{evidenceId:`evidence:${assertionId}`,sourceType:"fixture",sourceIdentifier:assertionId}],contradictoryEvidence:[],applicability:applicability(),conflictState:"none",unresolvedReason:null,version:"1",lifecycle:{status:"active",version:"1"}};}
const proposalIdentity=identity("proposal:execution");
const evidencePackageIdentity=identity("evidence:execution");
function proposal():CalibrationKnowledgeAdmissionProposal{const stableId="calibration:execution";const knowledge=defineCalibrationKnowledgeObject({identity:assertion("identity",{stableId}),canonicalName:assertion("name","Boost Target Main"),aliases:[],purposes:[],engineeringIntents:[],calibrationKind:assertion("kind",vocabulary("target")),primarySubsystem:assertion("subsystem",vocabulary("boost")),relatedSubsystems:[],applicability:assertion("applicability",applicability()),sourceRepresentations:[],directionalBehaviours:[],relationships:[],provenance:[{sourceType:"fixture",sourceIdentifier:"record"}],lifecycle:{status:"active",version:"1"},version:"1"});const revision=defineProposedCalibrationKnowledgeRevision({revisionIdentity:identity("revision:execution","1"),knowledge,proposedStableKnowledgeId:stableId,proposedKnowledgeVersion:"1",expectedPredecessorStableKnowledgeId:null,expectedPredecessorKnowledgeVersion:null,changeManifest:{addedAssertionIds:["identity"],amendedAssertionIds:[],retainedAssertionIds:[],supersededAssertionIds:[],removedFromCurrentAssertionIds:[]},lifecycleChangeManifest:{changes:[]},publicationRationale:"Publish."});return defineCalibrationKnowledgeAdmissionProposal({proposalIdentity,proposalKind:"register_new",proposedRevision:revision,evidencePackageIdentity,authorityClaimIds:[],proposer:{authorityType:"engineer",authorityIdentifier:"engineer:1"},proposerSourceRole:vocabulary("proposer"),intendedPublicationClass:vocabulary("candidate"),submittedAt:"2026-08-01T00:00:00Z",contractVersion:"1",previousProposalRevision:null,rationale:"Submit.",unresolvedQuestions:[],lifecycle:{status:"submitted",version:"1"}});}
function revisionBinding(value:CalibrationKnowledgeAdmissionProposal){const revision=value.proposedRevision;return{revisionIdentity:revision.revisionIdentity,revisionNumber:revision.revisionIdentity.revision,proposedObjectDigest:revision.revisionIdentity.contentDigest,proposedStableKnowledgeId:revision.proposedStableKnowledgeId,proposedKnowledgeVersion:revision.proposedKnowledgeVersion,expectedPredecessorStableKnowledgeId:revision.expectedPredecessorStableKnowledgeId,expectedPredecessorKnowledgeVersion:revision.expectedPredecessorKnowledgeVersion,assertionChangeManifest:revision.changeManifest,lifecycleChangeManifest:revision.lifecycleChangeManifest};}
const admissionPolicy=():AdmissionPolicyReference=>({policyId:"eligibility-policy",policyVersion:"1",effectiveDate:"2026-08-01",applicableProposalKinds:["register_new"],validationRuleVersions:["1"],authorityRuleVersion:"1",publicationRuleVersion:"1"});
const evidenceAssessment=():CalibrationKnowledgeEvidenceAuthorityAssessment=>({assessmentIdentity:identity("assessment:evidence"),proposalIdentity,evidencePackageIdentity,policyId:"evidence-policy",policyVersion:"1",assessmentDate:"2026-08-01",evidenceAssessment:{packageIdentity:evidencePackageIdentity,expectedPackageIdentity:evidencePackageIdentity,state:"complete",references:[],missingEvidenceIds:[],duplicateEvidenceIds:[],staleOrMismatchedIdentity:false,sourceIdentityComplete:true,transformationHistoryComplete:true,chainOfCustodyComplete:true,limitations:[]},assertionEvidenceAssessments:[],authorityAssessments:[],verificationCeilings:[],findings:[]});
const identityAssessment=():CalibrationIdentityLineageConflictAssessment=>({assessmentIdentity:identity("assessment:identity"),proposalIdentity,identity:{state:"new_calibration",proposedStableKnowledgeId:"calibration:execution",matchedCanonicalKnowledgeIds:[],consideredClaimIds:[],prohibitedClaimIds:[],confidence:"unknown",unresolvedReason:null},lineage:{state:"new_root",operation:"register",targetStableKnowledgeId:"calibration:execution",predecessorVersion:null,currentCanonicalVersion:null,historyPreserved:true,unresolvedReason:null},conflict:{status:"none",conflicts:[],ambiguityProposalIds:[]},canonicalHistorySnapshot:[]});
const eligibility=():CalibrationPublicationEligibilityAssessment=>({assessmentIdentity:identity("assessment:eligibility"),proposalIdentity,state:"eligible",policyId:"eligibility-policy",policyVersion:"1",policyCompliant:true,lifecycleCompatible:true,predecessorCompatible:true,versionCompatible:true,operationPermitted:true,blockingConditions:[],unresolvedConditions:[],publicationConstraints:[],requiredFollowUp:[],outstandingEngineeringObligations:[],eligibleForAdmissionDecision:true});
const outcomes:readonly AdmissionDecisionOutcome[]=["invalid","requires_evidence","requires_authority","identity_unresolved","conflict","deferred","rejected","accepted_provisional","accepted_authoritative","accepted_lifecycle_change","superseded_proposal"];
const operations:readonly PublicationOperation[]=["register","enrich","correct","refine_applicability","add_evidence","record_dispute","resolve_conflict","supersede","deprecate","reject","restore"];
const authorityScope=():CalibrationAdmissionDecisionAuthorityScope=>({scopeId:"scope",scopeVersion:"1",authorityId:"founder:beau",permittedOutcomes:outcomes,permittedOperations:operations,permittedPolicyIds:["eligibility-policy"],limitations:[]});
function instruction():DeterministicCalibrationKnowledgePublicationInstruction{const sourceProposal=proposal();const decisionInput:AuthorisedCalibrationKnowledgeAdmissionDecisionInput={decisionIdentity:identity("decision:execution"),proposal:sourceProposal,proposalIdentity,evidencePackageIdentity,proposedRevisionBinding:revisionBinding(sourceProposal),evidenceAuthorityAssessment:evidenceAssessment(),identityLineageConflictAssessment:identityAssessment(),eligibilityAssessment:eligibility(),policy:admissionPolicy(),decisionAuthority:{authorityType:"founder",authorityIdentifier:"founder:beau"},decisionAuthorityScope:authorityScope(),outcome:"accepted_provisional",decisionDate:"2026-08-01",decidedAt:"2026-08-01T05:00:00Z",rationale:"Authorise.",acceptedFindingIds:[],rejectedFindingIds:[],unresolvedConditions:[],publicationInstructionId:"instruction:execution",supersededDecisionIdentity:null,contractVersion:"1"};const decision=constructAuthorisedCalibrationKnowledgeAdmissionDecision(decisionInput);const content=deriveCalibrationKnowledgeContentDigests(sourceProposal.proposedRevision.knowledge);return constructDeterministicCalibrationKnowledgePublicationInstruction({instructionId:"instruction:execution",instructionRevision:"1",instructionContractVersion:"1",createdAt:"2026-08-01T06:00:00.000Z",supersededInstructionIdentity:null,authorisedDecision:decision,proposal:sourceProposal,canonicalPayload:content.payload,acceptedKnowledgeDigest:content.acceptedKnowledgeDigest,expectedResultingCanonicalDigest:content.expectedResultingCanonicalDigest,admissionPolicy:admissionPolicy(),publicationPolicy:{policyId:"publication-policy",policyVersion:"1",compatibleAdmissionPolicyId:"eligibility-policy",compatibleAdmissionPolicyVersion:"1"},serializationPolicy:CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1,digestPolicy:CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1,operation:"register",assertionChangeManifest:sourceProposal.proposedRevision.changeManifest,lifecycleChangeManifest:sourceProposal.proposedRevision.lifecycleChangeManifest,publicationSourceRequirement:{requirementId:"qualified-source",requirementVersion:"1",qualifiedIdentityRequired:true,immutableRevisionRequired:true}});}

function source():PublicationSourceIdentity{const material:Omit<PublicationSourceIdentity,"sourceEnvelopeDigest">={sourceId:"source:execution",sourceRevision:"1",sourceContentDigest:digest("source-content"),sourceType:{vocabularyId:"source-types",vocabularyVersion:"1",termId:"canonical",label:"Canonical",recognition:"known"},sourceContractId:"publication-source",sourceContractVersion:"1",authority:{authorityType:"founder",authorityIdentifier:"founder:beau"},provenance:[{provenanceId:"source-provenance",sourceType:"repository",sourceIdentifier:"source.ts",sourceRevisionOrigin:"commit:1",implementationOrigin:"repository",sourceContractId:"publication-source",sourceContractVersion:"1",validationAuthority:"founder",transformationHistory:[]}],lifecycle:{state:"active",lifecycleVersion:"1",supersededBySourceId:null,supersededBySourceRevision:null},capabilities:[{capabilityId:"register",operation:"register",supportState:"supported",contractRequirements:["instruction-v1"],limitations:[],compatiblePolicies:[]}],knownLimitations:[]};return definePublicationSourceIdentity({...material,sourceEnvelopeDigest:derivePublicationSourceEnvelope(material).digest.qualifiedDigest});}
function snapshot():RegistrySnapshotIdentity{const recordSet=deriveRegistryRecordSet([]);const material={snapshotId:"snapshot:before",snapshotRevision:"1",registryContractId:"registry",registryContractVersion:"1",recordSetDigest:recordSet.digest.qualifiedDigest,recordCount:0,predecessorSnapshot:null,sourceReceiptReferences:[],constructedAt:"2026-08-01T05:30:00.000Z",lifecycle:{state:"active" as const,lifecycleVersion:"1"}};const envelope=deriveRegistrySnapshotEnvelope(material);return defineRegistrySnapshotIdentity({...material,snapshotKind:"initial",snapshotEnvelopeDigest:envelope.digest.qualifiedDigest,recordManifest:recordSet.manifest});}
function request(overrides:Partial<Parameters<typeof constructPublicationExecutionRequest>[0]>={}):PublicationExecutionRequest{const publicationInstruction=overrides.instruction??instruction();const publicationSource=overrides.publicationSource??source();const predecessorSnapshot=overrides.predecessorSnapshot??snapshot();const reference={idempotencyId:derivePublicationExecutionIdempotencyId(publicationInstruction,publicationSource,predecessorSnapshot),instructionId:publicationInstruction.instructionIdentity.id,instructionRevision:publicationInstruction.instructionIdentity.revision,instructionDigest:publicationInstruction.instructionIdentity.contentDigest,sourceId:publicationSource.sourceId,sourceRevision:publicationSource.sourceRevision,sourceEnvelopeDigest:publicationSource.sourceEnvelopeDigest,predecessorSnapshotId:predecessorSnapshot.snapshotId,predecessorSnapshotRevision:predecessorSnapshot.snapshotRevision,predecessorSnapshotDigest:predecessorSnapshot.snapshotEnvelopeDigest};const retrySequence=overrides.retrySequence??0;return constructPublicationExecutionRequest({requestId:"request:1",requestRevision:"1",instruction:publicationInstruction,publicationSource,predecessorSnapshot,attemptId:deriveExecutionAttemptId(reference,retrySequence),attemptRevision:"1",retrySequence,previousAttemptId:retrySequence>0?deriveExecutionAttemptId(reference,retrySequence-1):null,previousAttemptRevision:retrySequence>0?"1":null,requestedAt:"2026-08-01T06:01:00.000Z",...overrides});}
function resultMaterial(executionRequest:PublicationExecutionRequest=request(),overrides:Partial<Omit<PublicationExecutionResult,"resultDigest">>={}):Omit<PublicationExecutionResult,"resultDigest">{return{resultId:"result:1",resultRevision:"1",instructionIdentity:executionRequest.instruction.instructionIdentity,idempotencyReference:executionRequest.idempotencyReference,executionAttemptIdentity:executionRequest.attemptIdentity,state:"published",reasonCode:"publication_completed",retryClassification:"not_required",resultingKnowledgeId:executionRequest.instruction.targetStableKnowledgeId,resultingKnowledgeVersion:executionRequest.instruction.targetKnowledgeVersion,observedPredecessorKnowledgeId:executionRequest.instruction.expectedPredecessorStableKnowledgeId,observedPredecessorKnowledgeVersion:executionRequest.instruction.expectedPredecessorKnowledgeVersion,publicationSourceIdentity:{sourceId:executionRequest.publicationSource.sourceId,sourceRevision:executionRequest.publicationSource.sourceRevision,sourceEnvelopeDigest:executionRequest.publicationSource.sourceEnvelopeDigest},predecessorSnapshotIdentity:{snapshotId:executionRequest.predecessorSnapshot.snapshotId,snapshotRevision:executionRequest.predecessorSnapshot.snapshotRevision,snapshotEnvelopeDigest:executionRequest.predecessorSnapshot.snapshotEnvelopeDigest},resultingSnapshotIdentity:{snapshotId:"snapshot:after",snapshotRevision:"1",snapshotEnvelopeDigest:digest("after")},validationFindings:[],executedAt:"2026-08-01T06:02:00.000Z",replayStatus:"original",previousExecutionResult:null,atomicCommitCertainty:"complete",...overrides};}
function result(executionRequest:PublicationExecutionRequest=request(),overrides:Partial<Omit<PublicationExecutionResult,"resultDigest">>={}):PublicationExecutionResult{const material=resultMaterial(executionRequest,overrides);return constructPublicationExecutionResult({...material,request:executionRequest,resultDigest:derivePublicationExecutionResult(material).digest.qualifiedDigest});}

test("constructs a published execution result",()=>{const value=result();assert.equal(value.state,"published");assert.equal(value.atomicCommitCertainty,"complete");assert.match(value.resultDigest,/^sha256:[a-f0-9]{64}$/);});
test("constructs blocked failed and indeterminate results without fabricating publication",()=>{assert.equal(result(request(),{state:"blocked",reasonCode:"validation_failed",retryClassification:"retry_corrected_instruction",resultingKnowledgeId:null,resultingKnowledgeVersion:null,resultingSnapshotIdentity:null,atomicCommitCertainty:"incomplete"}).state,"blocked");assert.equal(result(request(),{state:"failed",reasonCode:"execution_failed",retryClassification:"retry_same_instruction",resultingKnowledgeId:null,resultingKnowledgeVersion:null,resultingSnapshotIdentity:null,atomicCommitCertainty:"incomplete"}).state,"failed");assert.equal(result(request(),{state:"indeterminate",reasonCode:"atomicity_indeterminate",retryClassification:"manual_review_required",resultingKnowledgeId:null,resultingKnowledgeVersion:null,resultingSnapshotIdentity:null,atomicCommitCertainty:"indeterminate"}).state,"indeterminate");});
test("constructs an idempotent replay with previous-result linkage",()=>{const previous=result();const replayRequest=request({retrySequence:1});const replay=result(replayRequest,{resultId:"result:2",state:"idempotent_replay",reasonCode:"prior_result_replayed",replayStatus:"replayed",previousExecutionResult:{resultId:previous.resultId,resultRevision:previous.resultRevision,resultDigest:previous.resultDigest}});assert.equal(replay.state,"idempotent_replay");assert.equal(replay.previousExecutionResult?.resultId,"result:1");});
test("instruction source and predecessor snapshot deterministically bind idempotency",()=>{const first=request();const second=request({retrySequence:1});assert.deepEqual(first.idempotencyReference,second.idempotencyReference);assert.notEqual(first.attemptIdentity.attemptId,second.attemptIdentity.attemptId);assert.equal(first.idempotencyReference.instructionDigest,first.instruction.instructionContentDigest);assert.equal(first.idempotencyReference.sourceEnvelopeDigest,first.publicationSource.sourceEnvelopeDigest);assert.equal(first.idempotencyReference.predecessorSnapshotDigest,first.predecessorSnapshot.snapshotEnvelopeDigest);});
test("retry identity and previous-attempt linkage are explicit and deterministic",()=>{assert.throws(()=>request({retrySequence:1,previousAttemptId:null,previousAttemptRevision:null}),/previous-attempt/);assert.throws(()=>request({previousAttemptId:"attempt:0",previousAttemptRevision:"1"}),/Initial/);assert.throws(()=>request({attemptId:"caller-selected"}),/deterministic identity/);const retried=request({retrySequence:1});assert.equal(retried.attemptIdentity.retrySequence,1);assert.equal(retried.attemptIdentity.previousAttemptId,deriveExecutionAttemptId(retried.idempotencyReference,0));});
test("rejects inconsistent instruction source and snapshot bindings",()=>{const valid=instruction();assert.throws(()=>request({instruction:{...valid,instructionContentDigest:digest("wrong")}}),/content digest/);const inactive=source();assert.throws(()=>request({publicationSource:{...inactive,lifecycle:{state:"inactive",lifecycleVersion:"1",supersededBySourceId:null,supersededBySourceRevision:null}}}),/envelope digest|active/);const before=snapshot();assert.throws(()=>request({predecessorSnapshot:{...before,snapshotEnvelopeDigest:digest("wrong")}}),/envelope identity/);});
test("rejects unsupported source operation without negotiating capability",()=>{const valid=source();const material={...valid,sourceEnvelopeDigest:undefined};Reflect.deleteProperty(material,"sourceEnvelopeDigest");const unsupportedMaterial={...material,capabilities:[{...valid.capabilities[0],operation:"enrich" as const}]};const unsupported=definePublicationSourceIdentity({...unsupportedMaterial,sourceEnvelopeDigest:derivePublicationSourceEnvelope(unsupportedMaterial).digest.qualifiedDigest});assert.throws(()=>request({publicationSource:unsupported}),/does not support/);});
test("execution state reason retry replay and atomicity remain separate validated concepts",()=>{const base=resultMaterial();assert.throws(()=>constructPublicationExecutionResult({...base,request:request(),state:"published",reasonCode:"execution_failed",resultDigest:derivePublicationExecutionResult({...base,reasonCode:"execution_failed"}).digest.qualifiedDigest}),/published-state/);assert.throws(()=>result(request(),{state:"indeterminate",reasonCode:"atomicity_indeterminate",atomicCommitCertainty:"complete"}),/Indeterminate/);});
test("result must preserve exact instruction target and predecessor",()=>{assert.throws(()=>result(request(),{resultingKnowledgeId:"other"}),/target Knowledge/);assert.throws(()=>result(request(),{observedPredecessorKnowledgeId:"other",observedPredecessorKnowledgeVersion:"1"}),/predecessor/);});
test("validation findings are deterministic unique immutable and caller isolated",()=>{const findings=[{findingId:"finding:b",code:"B",severity:"warning" as const,message:"B",blocking:false,instructionPaths:["z","a"],sourcePaths:[],snapshotPaths:[]},{findingId:"finding:a",code:"A",severity:"information" as const,message:"A",blocking:false,instructionPaths:[],sourcePaths:[],snapshotPaths:[]}];const value=result(request(),{validationFindings:findings});findings.reverse();assert.equal(value.validationFindings[0].findingId,"finding:a");assert.deepEqual(value.validationFindings[1].instructionPaths,["a","z"]);assert.ok(Object.isFrozen(value.validationFindings));assert.throws(()=>result(request(),{validationFindings:[value.validationFindings[0],value.validationFindings[0]]}),/duplicate identity/);});
test("execution-result digest is deterministic domain-separated and material-sensitive",()=>{const material=resultMaterial();const first=derivePublicationExecutionResult(material);assert.equal(first.digest.domain,"publication_execution_result");assert.equal(first.digest.qualifiedDigest,derivePublicationExecutionResult(material).digest.qualifiedDigest);assert.notEqual(first.digest.qualifiedDigest,derivePublicationExecutionResult({...material,executedAt:"2026-08-01T06:03:00.000Z"}).digest.qualifiedDigest);});
test("rejects malformed result identity digest and noncanonical explicit timestamp",()=>{const valid=resultMaterial();assert.throws(()=>constructPublicationExecutionResult({...valid,request:request(),resultId:" ",resultDigest:digest("x")}),/identity/);assert.throws(()=>constructPublicationExecutionResult({...valid,request:request(),resultDigest:"bad"}),/digest/);assert.throws(()=>constructPublicationExecutionResult({...valid,request:request(),executedAt:"2026-08-01T16:02:00+10:00",resultDigest:digest("x")}),/canonical UTC/);});
test("outputs recursively freeze and isolate request and result inputs",()=>{const executionRequest=request();const value=result(executionRequest);assert.ok(Object.isFrozen(executionRequest));assert.ok(Object.isFrozen(executionRequest.publicationSource));assert.ok(Object.isFrozen(value));assert.ok(Object.isFrozen(value.idempotencyReference));assert.ok(Object.isFrozen(value.predecessorSnapshotIdentity));});
test("slice exposes no receipt execution engine registry mutation persistence or runtime surface",()=>{const value=result();for(const key of ["publicationReceipt","execute","executionEngine","registry","mutate","persistence","schema","database","api","runtime"])assert.equal(Reflect.get(value,key),undefined);});
