import assert from "node:assert/strict";
import test from "node:test";
import { defineCalibrationKnowledgeObject, type CalibrationApplicability, type GovernedVocabularyReference, type QualifiedAssertion } from "./calibrationKnowledge.ts";
import { defineCalibrationKnowledgeAdmissionProposal, defineProposedCalibrationKnowledgeRevision, type AdmissionStableIdentity, type CalibrationKnowledgeAdmissionProposal, type PublicationOperation } from "./calibrationKnowledgeAdmission.ts";
import { assessCalibrationIdentityLineageAndConflict, type CalibrationCanonicalHistoryEntry, type CalibrationIdentityBasis, type CalibrationIdentityCorrespondenceClaim, type CalibrationIdentityLineageConflictAssessmentInput, type CalibrationReportedConflict } from "./calibrationKnowledgeIdentityLineageConflictAssessment.ts";

const digest=(s:string)=>`sha256:${[...s].map(c=>c.charCodeAt(0).toString(16)).join("").padEnd(64,"0").slice(0,64)}`;
const identity=(id:string):AdmissionStableIdentity=>({id,revision:"1",contentDigest:digest(id)});
const vocab=(termId:string):GovernedVocabularyReference=>({vocabularyId:"test",vocabularyVersion:"1",termId,label:termId,recognition:"known"});
const app=():CalibrationApplicability=>({scope:vocab("universal"),platforms:[],engineFamilies:[],ecuFamilies:[],dmeVariants:[],controlStrategies:[],romFamilies:[],softwareVersions:[],calibrationIds:[],stockVariantIds:[],operatingModes:[],transmissions:[],regions:[],emissionsSpecifications:[],hardwareConfigurations:[],sourceReferenceIds:[],unresolvedReason:null});
function assertion<T>(id:string,value:T):QualifiedAssertion<T>{return{assertionId:id,value,verificationStatus:"candidate",confidence:"medium",authority:null,provenance:[{sourceType:"test",sourceIdentifier:id}],supportingEvidence:[{evidenceId:`e:${id}`,sourceType:"test",sourceIdentifier:id}],contradictoryEvidence:[],applicability:app(),conflictState:"none",unresolvedReason:null,version:"1",lifecycle:{status:"active",version:"1"}};}
function proposal(kind:CalibrationKnowledgeAdmissionProposal["proposalKind"]="register_new",stableId="cal:new",predecessor:string|null=null):CalibrationKnowledgeAdmissionProposal{const knowledge=defineCalibrationKnowledgeObject({identity:assertion("identity",{stableId}),canonicalName:assertion("name","Shared Name"),aliases:[],purposes:[],engineeringIntents:[],calibrationKind:assertion("kind",vocab("target")),primarySubsystem:assertion("subsystem",vocab("boost")),relatedSubsystems:[],applicability:assertion("app",app()),sourceRepresentations:[],directionalBehaviours:[],relationships:[],provenance:[{sourceType:"test",sourceIdentifier:"record"}],lifecycle:{status:"active",version:"1"},version:"2"});const lifecycleOperation=kind==="supersede"||kind==="deprecate"||kind==="restore"||kind==="reject"||kind==="record_dispute"||kind==="resolve_conflict"?kind:null;const prior=lifecycleOperation==="restore"?"deprecated":"active";const proposedStatus=lifecycleOperation==="supersede"?"superseded":lifecycleOperation==="deprecate"?"deprecated":lifecycleOperation==="reject"?"rejected":"active";const revision=defineProposedCalibrationKnowledgeRevision({revisionIdentity:identity("revision"),knowledge,proposedStableKnowledgeId:stableId,proposedKnowledgeVersion:"2",expectedPredecessorStableKnowledgeId:predecessor===null?null:stableId,expectedPredecessorKnowledgeVersion:predecessor,changeManifest:{addedAssertionIds:["identity"],amendedAssertionIds:[],retainedAssertionIds:[],supersededAssertionIds:[],removedFromCurrentAssertionIds:[]},lifecycleChangeManifest:{changes:lifecycleOperation===null?[]:[{changeId:`lifecycle:${kind}`,sequence:1,operation:lifecycleOperation,targetStableKnowledgeId:stableId,targetKnowledgeVersion:"2",priorStatus:prior,proposedStatus,reason:vocab(kind),relatedStableKnowledgeIds:[]}]},publicationRationale:"Assess identity."});return defineCalibrationKnowledgeAdmissionProposal({proposalIdentity:identity("proposal"),proposalKind:kind,proposedRevision:revision,evidencePackageIdentity:identity("evidence"),authorityClaimIds:[],proposer:{authorityType:"engineer",authorityIdentifier:"one"},proposerSourceRole:vocab("proposer"),intendedPublicationClass:vocab("candidate"),submittedAt:"2026-08-01T00:00:00Z",contractVersion:"1",previousProposalRevision:null,rationale:"Assess.",unresolvedQuestions:[],lifecycle:{status:"submitted",version:"1"}});}
const history=(id="cal:existing",current="1",lifecycleStatus:"active"|"superseded"|"deprecated"|"rejected"="active"):CalibrationCanonicalHistoryEntry=>({stableKnowledgeId:id,versions:[current],currentVersion:current,lifecycleStatus,predecessorKnowledgeId:null,successorKnowledgeIds:[]});
const claim=(basis:CalibrationIdentityBasis="canonical_identity",state:"supports"|"contradicts"|"unresolved"="supports",canonicalKnowledgeId:string|null="cal:existing",confidence:"unknown"|"low"|"medium"|"high"="high"):CalibrationIdentityCorrespondenceClaim=>({claimId:`claim:${basis}:${state}`,state,basis,canonicalKnowledgeId,assertionIds:["identity"],evidenceIds:["e:identity"],authorityClaimIds:["authority:1"],confidence,unresolvedReason:state==="supports"?null:"Unresolved claim."});
function input(p=proposal(),claims:readonly CalibrationIdentityCorrespondenceClaim[]=[],canonicalHistory:readonly CalibrationCanonicalHistoryEntry[]=[],reportedConflicts:readonly CalibrationReportedConflict[]=[],concurrentProposals:readonly {proposalId:string;targetStableKnowledgeId:string;expectedPredecessorVersion:string|null;operation:PublicationOperation}[]=[]):CalibrationIdentityLineageConflictAssessmentInput{return{assessmentIdentity:identity("assessment"),proposal:p,canonicalHistory,identityClaims:claims,reportedConflicts,concurrentProposals};}

test("new calibration creates a new immutable lineage root",()=>{const result=assessCalibrationIdentityLineageAndConflict(input());assert.equal(result.identity.state,"new_calibration");assert.equal(result.lineage.state,"new_root");assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result.canonicalHistorySnapshot));});
test("existing calibration resolves through canonical identity evidence",()=>{const result=assessCalibrationIdentityLineageAndConflict(input(proposal("enrich_existing","cal:existing","1"),[claim()],[history()]));assert.equal(result.identity.state,"enrichment");assert.equal(result.lineage.state,"enrichment");assert.deepEqual(result.identity.matchedCanonicalKnowledgeIds,["cal:existing"]);});
for(const [kind,identityState,lineageState] of [["correct_existing","correction","correction"],["refine_applicability","applicability_refinement","refinement"],["supersede","supersession","supersession"],["restore","restoration","restoration"],["deprecate","lifecycle_amendment","deprecation"]] as const){test(`${kind} preserves its explicit identity and lineage meaning`,()=>{const result=assessCalibrationIdentityLineageAndConflict(input(proposal(kind,"cal:existing","1"),[claim()],[history()]));assert.equal(result.identity.state,identityState);assert.equal(result.lineage.state,lineageState);});}
test("unresolved identity remains unresolved",()=>{const result=assessCalibrationIdentityLineageAndConflict(input(proposal("enrich_existing","cal:existing","1"),[claim("qualified_identity_evidence","unresolved")],[history()]));assert.equal(result.identity.state,"unresolved");assert.equal(result.identity.confidence,"unknown");assert.equal(result.lineage.state,"unresolved");});
test("material identity disagreement remains conflict",()=>{const claims=[claim(),{...claim(),claimId:"claim:other",canonicalKnowledgeId:"cal:other"}];const result=assessCalibrationIdentityLineageAndConflict(input(proposal("enrich_existing","cal:existing","1"),claims,[history(),history("cal:other")]));assert.equal(result.identity.state,"conflict");assert.equal(result.conflict.status,"unresolved");assert.deepEqual(result.conflict.conflicts[0].canonicalKnowledgeIds,["cal:existing","cal:other"]);});
test("stale predecessor creates lineage conflict without mutating history",()=>{const source=[history("cal:existing","2")];const result=assessCalibrationIdentityLineageAndConflict(input(proposal("correct_existing","cal:existing","1"),[claim()],source));assert.equal(result.lineage.state,"conflict");assert.equal(result.canonicalHistorySnapshot[0].currentVersion,"2");assert.equal(source[0].currentVersion,"2");});
test("reported source applicability authority and lifecycle conflicts preserve exact references",()=>{for(const category of ["source","applicability","authority","lifecycle"] as const){const conflict:CalibrationReportedConflict={conflictId:`conflict:${category}`,category,material:true,ambiguityOnly:false,summary:"Material conflict.",assertionIds:["a:1"],evidenceIds:["e:1"],authorityClaimIds:["auth:1"],canonicalKnowledgeIds:["cal:existing"],proposalIds:["proposal"],unresolvedReason:"Unresolved."};const result=assessCalibrationIdentityLineageAndConflict(input(proposal("enrich_existing","cal:existing","1"),[claim()],[history()], [conflict]));assert.equal(result.conflict.conflicts[0].category,category);assert.deepEqual(result.conflict.conflicts[0].assertionIds,["a:1"]);}});
test("ambiguity is not promoted to conflict",()=>{const ambiguity:CalibrationReportedConflict={conflictId:"ambiguity",category:"identity",material:false,ambiguityOnly:true,summary:"Multiple candidates.",assertionIds:[],evidenceIds:[],authorityClaimIds:[],canonicalKnowledgeIds:[],proposalIds:["p:2"],unresolvedReason:"Ambiguous."};const result=assessCalibrationIdentityLineageAndConflict(input(proposal(),[],[],[ambiguity]));assert.equal(result.conflict.status,"none");assert.deepEqual(result.conflict.ambiguityProposalIds,["p:2"]);});
test("incompatible concurrent proposals remain conflict",()=>{const concurrent=[{proposalId:"p:2",targetStableKnowledgeId:"cal:existing",expectedPredecessorVersion:"1",operation:"correct" as const}];const result=assessCalibrationIdentityLineageAndConflict(input(proposal("enrich_existing","cal:existing","1"),[claim()],[history()],[],concurrent));assert.equal(result.conflict.conflicts[0].category,"concurrent_proposal");});
test("identical names do not merge distinct canonical identities",()=>{const result=assessCalibrationIdentityLineageAndConflict(input(proposal("register_new","cal:new"),[],[history("cal:other")]));assert.equal(result.identity.state,"new_calibration");assert.deepEqual(result.identity.matchedCanonicalKnowledgeIds,[]);});
test("different display names do not split one canonical identity",()=>{const p=proposal("enrich_existing","cal:existing","1");const changed={...p,proposedRevision:{...p.proposedRevision,knowledge:{...p.proposedRevision.knowledge,canonicalName:{...p.proposedRevision.knowledge.canonicalName,value:"Different Name"}}}};const result=assessCalibrationIdentityLineageAndConflict(input(changed,[claim()],[history()]));assert.equal(result.identity.state,"enrichment");});
test("XDF labels filenames folders table addresses and display names never establish identity",()=>{const bases=["xdf_label","filename","folder","table_address","display_name"] as const;const claims=bases.map(basis=>claim(basis));const result=assessCalibrationIdentityLineageAndConflict(input(proposal(),claims));assert.equal(result.identity.state,"new_calibration");assert.deepEqual(result.identity.prohibitedClaimIds,claims.map(item=>item.claimId).sort());});
test("identity confidence is conservative and does not alter Knowledge verification",()=>{const p=proposal("enrich_existing","cal:existing","1");const result=assessCalibrationIdentityLineageAndConflict(input(p,[claim("canonical_identity","supports","cal:existing","high"),{...claim("verified_source_mapping","supports","cal:existing","low"),claimId:"claim:low"}],[history()]));assert.equal(result.identity.confidence,"low");assert.equal(result.proposalIdentity.id,"proposal");assert.equal(p.proposedRevision.knowledge.identity.verificationStatus,"candidate");});
test("caller order is irrelevant and caller mutation cannot alter output",()=>{const claims=[claim(),{...claim("verified_source_mapping"),claimId:"claim:source"}];const forward=assessCalibrationIdentityLineageAndConflict(input(proposal("enrich_existing","cal:existing","1"),claims,[history()]));const reverse=assessCalibrationIdentityLineageAndConflict(input(proposal("enrich_existing","cal:existing","1"),[...claims].reverse(),[history()]));assert.deepEqual(forward,reverse);claims[0]={...claims[0],canonicalKnowledgeId:"changed"};assert.deepEqual(forward.identity.matchedCanonicalKnowledgeIds,["cal:existing"]);});
test("assessment exposes no decision publication registry or runtime surface",()=>{const result=assessCalibrationIdentityLineageAndConflict(input());for(const key of ["decision","publicationEligibility","publicationInstruction","publicationReceipt","registry","runtime"])assert.equal(Reflect.get(result,key),undefined);});
