import assert from "node:assert/strict";
import test from "node:test";
import {
  CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1,
  CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1,
  canonicalizeCalibrationKnowledge,
  canonicalizeDigestDomainPayload,
  defineCalibrationKnowledgeDigestPolicy,
  defineCanonicalSerializationPolicy,
  deriveCalibrationKnowledgeContentDigests,
  deriveDomainSeparatedDigest,
} from "./calibrationKnowledgeCanonicalSerialization.ts";
import type {
  CalibrationApplicability,
  CalibrationKnowledgeObject,
  GovernedVocabularyReference,
  QualifiedAssertion,
} from "./calibrationKnowledge.ts";

const vocabulary = (termId: string, label = termId): GovernedVocabularyReference => ({ vocabularyId: "tunesight.test", vocabularyVersion: "1", termId, label, recognition: "known" });
const applicability = (platforms: readonly string[] = ["B58", "N54"]): CalibrationApplicability => ({ scope: vocabulary("universal"), platforms, engineFamilies: [], ecuFamilies: [], dmeVariants: [], controlStrategies: [], romFamilies: [], softwareVersions: [], calibrationIds: [], stockVariantIds: [], operatingModes: [], transmissions: [], regions: [], emissionsSpecifications: [], hardwareConfigurations: [], sourceReferenceIds: [], unresolvedReason: null });
function assertion<T>(assertionId: string, value: T): QualifiedAssertion<T> { return { assertionId, value, verificationStatus: "candidate", confidence: "medium", authority: null, provenance: [{ sourceType: "fixture", sourceIdentifier: assertionId }], supportingEvidence: [{ evidenceId: `evidence:${assertionId}`, sourceType: "fixture", sourceIdentifier: assertionId }], contradictoryEvidence: [], applicability: applicability(), conflictState: "none", unresolvedReason: null, version: "1", lifecycle: { status: "active", version: "1" } }; }
function knowledge(aliasOrder: readonly string[] = ["alias:b", "alias:a"]): CalibrationKnowledgeObject {
  return {
    identity: assertion("identity", { stableId: "calibration:test" }),
    canonicalName: assertion("canonical-name", "Boost Target Main"),
    aliases: aliasOrder.map((id) => assertion(id, { name: id })),
    purposes: [assertion("purpose", { summary: "Defines requested manifold pressure." })],
    engineeringIntents: [assertion("intent", { summary: "Balance requested torque and system protection.", engineeringObjectives: [{ objectiveId: "objective:b", canonicalName: "Protection", vocabulary: vocabulary("protection") }, { objectiveId: "objective:a", canonicalName: "Torque", vocabulary: vocabulary("torque") }], participatingSubsystems: [vocabulary("turbo"), vocabulary("torque")], protectedInterests: ["durability", "combustion"], governingConstraints: [], documentedTradeoffs: [] })],
    calibrationKind: assertion("kind", vocabulary("target")),
    primarySubsystem: assertion("primary-subsystem", vocabulary("boost")),
    relatedSubsystems: [],
    applicability: assertion("applicability", applicability()),
    sourceRepresentations: [assertion("source", { sourceReferenceId: "source:1", sourceType: vocabulary("xdf"), sourceIdentifier: "Boost Target", axes: ["rpm", "load"], conversionMetadata: { factor: "1", offset: "0" } })],
    directionalBehaviours: [assertion("behaviour", { manipulatedQuantity: "requested pressure", response: vocabulary("nonlinear"), expectedEffect: "Changes requested boost.", affectedSubsystems: [vocabulary("torque"), vocabulary("turbo")], preconditions: ["load present", "engine running"], boundaryConditions: [], nonlinearCharacteristics: [], potentialProtectiveResponses: [], dependencyCalibrationIds: ["cal:b", "cal:a"], exceptions: [] })],
    relationships: [],
    provenance: [{ sourceType: "fixture", sourceIdentifier: "record" }],
    lifecycle: { status: "active", version: "1" },
    version: "1",
  };
}

test("constructs governed serialization and digest policies", () => { assert.deepEqual(defineCanonicalSerializationPolicy(CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1), CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1); assert.deepEqual(defineCalibrationKnowledgeDigestPolicy(CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1), CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1); });
test("rejects invalid serialization policies", () => { assert.throws(() => Reflect.apply(defineCanonicalSerializationPolicy, undefined, [{ ...CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1, policyId: "other" }]), /identity/); assert.throws(() => Reflect.apply(defineCanonicalSerializationPolicy, undefined, [{ ...CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1, policyVersion: " " }]), /version/); assert.throws(() => Reflect.apply(defineCanonicalSerializationPolicy, undefined, [{ ...CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1, format: "json" }]), /format/); assert.throws(() => Reflect.apply(defineCanonicalSerializationPolicy, undefined, [{ ...CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1, encoding: "utf-16" }]), /encoding/); });
test("rejects invalid digest policies", () => { assert.throws(() => Reflect.apply(defineCalibrationKnowledgeDigestPolicy, undefined, [{ ...CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1, policyId: "other" }]), /identity/); assert.throws(() => Reflect.apply(defineCalibrationKnowledgeDigestPolicy, undefined, [{ ...CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1, algorithm: "sha-1" }]), /algorithm/); assert.throws(() => Reflect.apply(defineCalibrationKnowledgeDigestPolicy, undefined, [{ ...CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1, encoding: "base64" }]), /encoding/); });
test("canonical property and insertion order are deterministic", () => { const first = canonicalizeCalibrationKnowledge(knowledge()); const source = knowledge(); const reordered = { version: source.version, lifecycle: source.lifecycle, provenance: source.provenance, relationships: source.relationships, directionalBehaviours: source.directionalBehaviours, sourceRepresentations: source.sourceRepresentations, applicability: source.applicability, relatedSubsystems: source.relatedSubsystems, primarySubsystem: source.primarySubsystem, calibrationKind: source.calibrationKind, engineeringIntents: source.engineeringIntents, purposes: source.purposes, aliases: source.aliases, canonicalName: source.canonicalName, identity: source.identity }; assert.equal(first.canonicalJson, canonicalizeCalibrationKnowledge(reordered).canonicalJson); });
test("set-like caller order does not change bytes or digest", () => { const first = deriveCalibrationKnowledgeContentDigests(knowledge(["alias:b", "alias:a"])); const second = deriveCalibrationKnowledgeContentDigests(knowledge(["alias:a", "alias:b"])); assert.deepEqual(first.payload.canonicalBytes.bytes, second.payload.canonicalBytes.bytes); assert.equal(first.acceptedKnowledgeDigest, second.acceptedKnowledgeDigest); });
test("ordered axes retain engineering order", () => { const source = knowledge(); const reversed = knowledge(); const changed = { ...reversed, sourceRepresentations: [{ ...reversed.sourceRepresentations[0], value: { ...reversed.sourceRepresentations[0].value!, axes: ["load", "rpm"] } }] }; assert.notEqual(canonicalizeCalibrationKnowledge(source).canonicalJson, canonicalizeCalibrationKnowledge(changed).canonicalJson); });
test("normalizes Unicode to NFC without changing engineering wording", () => { const composed = knowledge(); const decomposed = knowledge(); const left = { ...composed, canonicalName: { ...composed.canonicalName, value: "Caf\u00e9" } }; const right = { ...decomposed, canonicalName: { ...decomposed.canonicalName, value: "Cafe\u0301" } }; assert.equal(canonicalizeCalibrationKnowledge(left).canonicalJson, canonicalizeCalibrationKnowledge(right).canonicalJson); });
test("rejects object keys that collide after Unicode normalization", () => { assert.throws(() => canonicalizeDigestDomainPayload({ "\u00e9": 1, "e\u0301": 2 }), /duplicate normalized key/); });
test("rejects invalid surrogate strings", () => { const source = knowledge(); assert.throws(() => canonicalizeCalibrationKnowledge({ ...source, canonicalName: { ...source.canonicalName, value: "bad\ud800" } }), /surrogate/); });
test("rejects undefined and nonfinite numbers", () => { assert.throws(() => canonicalizeDigestDomainPayload({ value: undefined }), /undefined/); assert.throws(() => canonicalizeDigestDomainPayload({ value: Number.NaN }), /finite/); assert.throws(() => canonicalizeDigestDomainPayload({ value: Number.POSITIVE_INFINITY }), /finite/); });
test("normalizes negative zero and rejects unsafe integers", () => { assert.equal(canonicalizeDigestDomainPayload({ numeric: -0 }).canonicalJson, "{\"numeric\":0}"); assert.throws(() => canonicalizeDigestDomainPayload({ numeric: Number.MAX_SAFE_INTEGER + 1 }), /safe/); });
test("validates canonical calendar dates", () => { assert.equal(canonicalizeDigestDomainPayload({ validationDate: "2024-02-29" }).canonicalJson, "{\"validationDate\":\"2024-02-29\"}"); assert.throws(() => canonicalizeDigestDomainPayload({ validationDate: "2026-02-29" }), /date is invalid/); });
test("normalizes lifecycle timestamps to canonical UTC", () => { assert.equal(canonicalizeDigestDomainPayload({ effectiveAt: "2026-08-01T10:00:00+10:00" }).canonicalJson, "{\"effectiveAt\":\"2026-08-01T00:00:00.000Z\"}"); });
test("preserves permitted null and absent optional fields distinctly", () => { const result = canonicalizeCalibrationKnowledge(knowledge()).canonicalJson; assert.match(result, /\"unresolvedReason\":null/); assert.doesNotMatch(result, /\"effectiveAt\"/); });
test("preserves governed vocabulary identity rather than deriving it from labels", () => { const first = knowledge(); const second = knowledge(); const changed = { ...second, calibrationKind: { ...second.calibrationKind, value: { ...second.calibrationKind.value!, label: "Display label only" } } }; const firstPayload = canonicalizeCalibrationKnowledge(first); const secondPayload = canonicalizeCalibrationKnowledge(changed); assert.match(secondPayload.canonicalJson, /\"termId\":\"target\"/); assert.notEqual(firstPayload.canonicalJson, secondPayload.canonicalJson); });
test("rejects duplicate semantic identities without qualification merging", () => { const source = knowledge(["alias:a", "alias:a"]); assert.throws(() => canonicalizeCalibrationKnowledge(source), /duplicated|duplicate semantic identity/); });
test("canonical outputs are recursively frozen and caller-isolated", () => { const aliases = [assertion("alias:b", { name: "B" }), assertion("alias:a", { name: "A" })]; const source = { ...knowledge(), aliases }; const result = canonicalizeCalibrationKnowledge(source); aliases.reverse(); assert.equal(result.knowledge.aliases[0].assertionId, "alias:a"); assert.ok(Object.isFrozen(result)); assert.ok(Object.isFrozen(result.knowledge)); assert.ok(Object.isFrozen(result.canonicalBytes)); assert.ok(Object.isFrozen(result.canonicalBytes.bytes)); });
test("UTF-8 canonical bytes contain no byte-order mark", () => { const bytes = canonicalizeCalibrationKnowledge(knowledge()).canonicalBytes.bytes; assert.notDeepEqual(bytes.slice(0, 3), [0xef, 0xbb, 0xbf]); });
test("duplicate provenance identity is rejected rather than merged", () => { const source = knowledge(); const duplicate = { sourceType: "fixture", sourceIdentifier: "record", engineeringNotes: "Different metadata." }; assert.throws(() => canonicalizeCalibrationKnowledge({ ...source, provenance: [...source.provenance, duplicate] }), /duplicate semantic identity/); });
test("digest is qualified deterministic lowercase SHA-256", () => { const result = deriveCalibrationKnowledgeContentDigests(knowledge()); assert.match(result.acceptedKnowledgeDigest, /^sha256:[a-f0-9]{64}$/); assert.equal(result.acceptedKnowledgeDigest, deriveCalibrationKnowledgeContentDigests(knowledge()).acceptedKnowledgeDigest); });
test("material assertion change changes the content digest", () => { const source = knowledge(); const changed = { ...source, canonicalName: { ...source.canonicalName, value: "Different canonical name" } }; assert.notEqual(deriveCalibrationKnowledgeContentDigests(source).acceptedKnowledgeDigest, deriveCalibrationKnowledgeContentDigests(changed).acceptedKnowledgeDigest); });
test("domain separation prevents cross-domain digest validation", () => { const payload = canonicalizeCalibrationKnowledge(knowledge()); const content = deriveDomainSeparatedDigest(payload.canonicalBytes, "calibration_knowledge_content"); const instruction = deriveDomainSeparatedDigest(payload.canonicalBytes, "publication_instruction"); assert.notEqual(content.qualifiedDigest, instruction.qualifiedDigest); });
test("publication source identity is a governed digest domain with its exact label", () => { const payload = canonicalizeDigestDomainPayload({ sourceId: "source:fixture", sourceRevision: "1" }); const digest = deriveDomainSeparatedDigest(payload.canonicalBytes, "publication_source_identity"); assert.equal(digest.domain, "publication_source_identity"); assert.equal(digest.domainLabel, "tunesight.calibration-knowledge.publication-source"); assert.match(digest.qualifiedDigest, /^sha256:[a-f0-9]{64}$/); });
test("publication source identity digest derivation is deterministic and payload-sensitive", () => { const first = canonicalizeDigestDomainPayload({ sourceId: "source:fixture", capabilities: ["read", "verify"] }); const reordered = canonicalizeDigestDomainPayload({ capabilities: ["read", "verify"], sourceId: "source:fixture" }); const changed = canonicalizeDigestDomainPayload({ sourceId: "source:changed", capabilities: ["read", "verify"] }); const firstDigest = deriveDomainSeparatedDigest(first.canonicalBytes, "publication_source_identity"); assert.equal(firstDigest.qualifiedDigest, deriveDomainSeparatedDigest(first.canonicalBytes, "publication_source_identity").qualifiedDigest); assert.equal(firstDigest.qualifiedDigest, deriveDomainSeparatedDigest(reordered.canonicalBytes, "publication_source_identity").qualifiedDigest); assert.notEqual(firstDigest.qualifiedDigest, deriveDomainSeparatedDigest(changed.canonicalBytes, "publication_source_identity").qualifiedDigest); });
test("generic publication source payload derivation is caller-isolated and set-order independent", () => { const sourceReferenceIds = ["source:b", "source:a"]; const first = canonicalizeDigestDomainPayload({ sourceId: "source:fixture", sourceReferenceIds }); const reordered = canonicalizeDigestDomainPayload({ sourceReferenceIds: ["source:a", "source:b"], sourceId: "source:fixture" }); sourceReferenceIds.reverse(); const firstDigest = deriveDomainSeparatedDigest(first.canonicalBytes, "publication_source_identity"); assert.equal(firstDigest.qualifiedDigest, deriveDomainSeparatedDigest(reordered.canonicalBytes, "publication_source_identity").qualifiedDigest); assert.ok(Object.isFrozen(first)); assert.ok(Object.isFrozen(first.canonicalBytes)); assert.ok(Object.isFrozen(first.canonicalBytes.bytes)); });
test("publication source identity remains separated from every existing digest domain", () => { const payload = canonicalizeDigestDomainPayload({ sourceId: "source:fixture" }); const sourceDigest = deriveDomainSeparatedDigest(payload.canonicalBytes, "publication_source_identity"); const otherDomains = ["calibration_knowledge_content", "proposed_revision_envelope", "publication_instruction", "publication_execution_result", "publication_receipt", "registry_record_set_manifest", "registry_snapshot_envelope"] as const; for (const domain of otherDomains) assert.notEqual(sourceDigest.qualifiedDigest, deriveDomainSeparatedDigest(payload.canonicalBytes, domain).qualifiedDigest); });
test("known deterministic publication source identity vector remains stable", () => { const payload = canonicalizeDigestDomainPayload({ sourceId: "source:fixture", sourceRevision: "1" }); assert.equal(deriveDomainSeparatedDigest(payload.canonicalBytes, "publication_source_identity").qualifiedDigest, "sha256:92511c0f712eb45348d422f36a77bd1cfcd606a62b651d96ca886f13effc82a9"); });
test("policy versions participate in digest framing", () => { const payload = canonicalizeCalibrationKnowledge(knowledge()); const serializationV2 = defineCanonicalSerializationPolicy({ ...CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1, policyVersion: "2" }); const digestV2 = defineCalibrationKnowledgeDigestPolicy({ ...CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1, policyVersion: "2" }); assert.notEqual(deriveDomainSeparatedDigest(payload.canonicalBytes, "calibration_knowledge_content").qualifiedDigest, deriveDomainSeparatedDigest(payload.canonicalBytes, "calibration_knowledge_content", serializationV2).qualifiedDigest); assert.notEqual(deriveDomainSeparatedDigest(payload.canonicalBytes, "calibration_knowledge_content").qualifiedDigest, deriveDomainSeparatedDigest(payload.canonicalBytes, "calibration_knowledge_content", undefined, digestV2).qualifiedDigest); });
test("accepted and expected resulting digests share exactly one content derivation", () => { const result = deriveCalibrationKnowledgeContentDigests(knowledge()); assert.equal(result.acceptedKnowledgeDigest, result.expectedResultingCanonicalDigest); assert.equal(result.acceptedKnowledgeDigest, result.digest.qualifiedDigest); });
test("top-level audit metadata is excluded from Knowledge content identity", () => { const source = knowledge(); const withAudit = { ...source, admissionDecisionId: "decision:unrelated", publishedAt: "2026-08-01T00:00:00Z" } as CalibrationKnowledgeObject; assert.equal(deriveCalibrationKnowledgeContentDigests(source).acceptedKnowledgeDigest, deriveCalibrationKnowledgeContentDigests(withAudit).acceptedKnowledgeDigest); });
test("different canonical bytes change the digest", () => { const first = canonicalizeCalibrationKnowledge(knowledge()); const changedBytes = { ...first.canonicalBytes, bytes: [...first.canonicalBytes.bytes.slice(0, -1), 0] }; assert.notEqual(deriveDomainSeparatedDigest(first.canonicalBytes, "calibration_knowledge_content").qualifiedDigest, deriveDomainSeparatedDigest(changedBytes, "calibration_knowledge_content").qualifiedDigest); });
test("generic digest validation rejects malformed bytes and domains", () => { const payload = canonicalizeCalibrationKnowledge(knowledge()); assert.throws(() => deriveDomainSeparatedDigest({ ...payload.canonicalBytes, byteLength: payload.canonicalBytes.byteLength + 1 }, "calibration_knowledge_content"), /byte sequence/); assert.throws(() => Reflect.apply(deriveDomainSeparatedDigest, undefined, [payload.canonicalBytes, "other"]), /domain/); });
test("known deterministic content vector remains stable", () => { assert.equal(deriveCalibrationKnowledgeContentDigests(knowledge()).acceptedKnowledgeDigest, "sha256:57abc482d583201c7d2dfd889d0ab9cc6db080145d5d0cab3331b21a808e70f1"); });
test("slice exposes no publication source capability execution receipt snapshot registry or persistence surface", () => { const moduleResult = deriveCalibrationKnowledgeContentDigests(knowledge()); for (const key of ["publicationSourceIdentity", "sourceCapabilities", "publicationInstruction", "publicationExecution", "publicationReceipt", "registrySnapshot", "registry", "persistence", "schema", "runtime"]) assert.equal(Reflect.get(moduleResult, key), undefined); });
