import assert from "node:assert/strict";
import test from "node:test";
import {
  defineCalibrationKnowledgeAdmissionProposal,
  defineProposedCalibrationKnowledgeRevision,
  type AdmissionDecisionOutcome,
  type AdmissionPolicyReference,
  type AdmissionStableIdentity,
  type CalibrationKnowledgeAdmissionProposal,
  type PublicationOperation,
} from "./calibrationKnowledgeAdmission.ts";
import { defineCalibrationKnowledgeObject, type CalibrationApplicability, type GovernedVocabularyReference, type QualifiedAssertion } from "./calibrationKnowledge.ts";
import type { CalibrationKnowledgeEvidenceAuthorityAssessment } from "./calibrationKnowledgeEvidenceAuthorityAssessment.ts";
import type { CalibrationIdentityLineageConflictAssessment } from "./calibrationKnowledgeIdentityLineageConflictAssessment.ts";
import type { CalibrationPublicationEligibilityAssessment } from "./calibrationKnowledgePublicationEligibilityAssessment.ts";
import { constructAuthorisedCalibrationKnowledgeAdmissionDecision, type AuthorisedCalibrationKnowledgeAdmissionDecisionInput, type CalibrationAdmissionDecisionAuthorityScope } from "./calibrationKnowledgeAuthorisedAdmissionDecision.ts";
import { CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1, CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1, deriveCalibrationKnowledgeContentDigests } from "./calibrationKnowledgeCanonicalSerialization.ts";
import { constructDeterministicCalibrationKnowledgePublicationInstruction, type DeterministicCalibrationKnowledgePublicationInstructionInput } from "./calibrationKnowledgeDeterministicPublicationInstruction.ts";

const digest=(seed:string):string=>`sha256:${[...seed].map(item=>item.charCodeAt(0).toString(16)).join("").padEnd(64,"0").slice(0,64)}`;
const identity=(id:string,revision="1"):AdmissionStableIdentity=>({id,revision,contentDigest:digest(`${id}:${revision}`)});
const vocabulary=(termId:string):GovernedVocabularyReference=>({vocabularyId:"test",vocabularyVersion:"1",termId,label:termId,recognition:"known"});
const applicability=():CalibrationApplicability=>({scope:vocabulary("universal"),platforms:[],engineFamilies:[],ecuFamilies:[],dmeVariants:[],controlStrategies:[],romFamilies:[],softwareVersions:[],calibrationIds:[],stockVariantIds:[],operatingModes:[],transmissions:[],regions:[],emissionsSpecifications:[],hardwareConfigurations:[],sourceReferenceIds:[],unresolvedReason:null});
function assertion<T>(assertionId:string,value:T):QualifiedAssertion<T>{return{assertionId,value,verificationStatus:"candidate",confidence:"medium",authority:null,provenance:[{sourceType:"fixture",sourceIdentifier:assertionId}],supportingEvidence:[{evidenceId:`evidence:${assertionId}`,sourceType:"fixture",sourceIdentifier:assertionId}],contradictoryEvidence:[],applicability:applicability(),conflictState:"none",unresolvedReason:null,version:"1",lifecycle:{status:"active",version:"1"}};}

const proposalIdentity=identity("proposal:instruction");
const evidencePackageIdentity=identity("evidence:instruction");
function proposal(operation:PublicationOperation="register"):CalibrationKnowledgeAdmissionProposal{
  const stableId="calibration:instruction";
  const knowledge=defineCalibrationKnowledgeObject({identity:assertion("identity",{stableId}),canonicalName:assertion("name","Boost Target Main"),aliases:[],purposes:[assertion("purpose",{summary:"Defines requested manifold pressure."})],engineeringIntents:[],calibrationKind:assertion("kind",vocabulary("target")),primarySubsystem:assertion("subsystem",vocabulary("boost")),relatedSubsystems:[],applicability:assertion("applicability",applicability()),sourceRepresentations:[],directionalBehaviours:[],relationships:[],provenance:[{sourceType:"fixture",sourceIdentifier:"record"}],lifecycle:{status:operation==="deprecate"?"deprecated":"active",version:"2"},version:"2"});
  const kind=operation==="register"?"register_new":operation==="deprecate"?"deprecate":"enrich_existing";
  const changes=operation==="deprecate"?[{changeId:"change:deprecate",sequence:1,operation:"deprecate" as const,targetStableKnowledgeId:stableId,targetKnowledgeVersion:"2",priorStatus:"active" as const,proposedStatus:"deprecated" as const,reason:vocabulary("deprecation"),relatedStableKnowledgeIds:[]}]:[];
  const revision=defineProposedCalibrationKnowledgeRevision({revisionIdentity:identity("revision:instruction","7"),knowledge,proposedStableKnowledgeId:stableId,proposedKnowledgeVersion:"2",expectedPredecessorStableKnowledgeId:operation==="register"?null:stableId,expectedPredecessorKnowledgeVersion:operation==="register"?null:"1",changeManifest:{addedAssertionIds:["identity"],amendedAssertionIds:[],retainedAssertionIds:[],supersededAssertionIds:[],removedFromCurrentAssertionIds:[]},lifecycleChangeManifest:{changes},publicationRationale:"Publish the complete revision."});
  return defineCalibrationKnowledgeAdmissionProposal({proposalIdentity,proposalKind:kind,proposedRevision:revision,evidencePackageIdentity,authorityClaimIds:[],proposer:{authorityType:"engineer",authorityIdentifier:"engineer:1"},proposerSourceRole:vocabulary("proposer"),intendedPublicationClass:vocabulary("candidate"),submittedAt:"2026-08-01T00:00:00Z",contractVersion:"1",previousProposalRevision:null,rationale:"Submit.",unresolvedQuestions:[],lifecycle:{status:"submitted",version:"1"}});
}
function revisionBinding(value:CalibrationKnowledgeAdmissionProposal){const revision=value.proposedRevision;return{revisionIdentity:revision.revisionIdentity,revisionNumber:revision.revisionIdentity.revision,proposedObjectDigest:revision.revisionIdentity.contentDigest,proposedStableKnowledgeId:revision.proposedStableKnowledgeId,proposedKnowledgeVersion:revision.proposedKnowledgeVersion,expectedPredecessorStableKnowledgeId:revision.expectedPredecessorStableKnowledgeId,expectedPredecessorKnowledgeVersion:revision.expectedPredecessorKnowledgeVersion,assertionChangeManifest:revision.changeManifest,lifecycleChangeManifest:revision.lifecycleChangeManifest};}
const admissionPolicy=():AdmissionPolicyReference=>({policyId:"eligibility-policy",policyVersion:"1",effectiveDate:"2026-08-01",applicableProposalKinds:["register_new","enrich_existing","deprecate"],validationRuleVersions:["1"],authorityRuleVersion:"1",publicationRuleVersion:"1"});
const evidenceAssessment=():CalibrationKnowledgeEvidenceAuthorityAssessment=>({assessmentIdentity:identity("assessment:evidence"),proposalIdentity,evidencePackageIdentity,policyId:"evidence-policy",policyVersion:"1",assessmentDate:"2026-08-01",evidenceAssessment:{packageIdentity:evidencePackageIdentity,expectedPackageIdentity:evidencePackageIdentity,state:"complete",references:[],missingEvidenceIds:[],duplicateEvidenceIds:[],staleOrMismatchedIdentity:false,sourceIdentityComplete:true,transformationHistoryComplete:true,chainOfCustodyComplete:true,limitations:[]},assertionEvidenceAssessments:[],authorityAssessments:[],verificationCeilings:[],findings:[]});
const identityAssessment=(operation:PublicationOperation):CalibrationIdentityLineageConflictAssessment=>({assessmentIdentity:identity("assessment:identity"),proposalIdentity,identity:{state:operation==="register"?"new_calibration":operation==="deprecate"?"lifecycle_amendment":"enrichment",proposedStableKnowledgeId:"calibration:instruction",matchedCanonicalKnowledgeIds:[],consideredClaimIds:[],prohibitedClaimIds:[],confidence:"unknown",unresolvedReason:null},lineage:{state:operation==="register"?"new_root":operation==="deprecate"?"deprecation":"enrichment",operation,targetStableKnowledgeId:"calibration:instruction",predecessorVersion:operation==="register"?null:"1",currentCanonicalVersion:operation==="register"?null:"1",historyPreserved:true,unresolvedReason:null},conflict:{status:"none",conflicts:[],ambiguityProposalIds:[]},canonicalHistorySnapshot:[]});
const eligibility=():CalibrationPublicationEligibilityAssessment=>({assessmentIdentity:identity("assessment:eligibility"),proposalIdentity,state:"eligible",policyId:"eligibility-policy",policyVersion:"1",policyCompliant:true,lifecycleCompatible:true,predecessorCompatible:true,versionCompatible:true,operationPermitted:true,blockingConditions:[],unresolvedConditions:[],publicationConstraints:[],requiredFollowUp:[],outstandingEngineeringObligations:[],eligibleForAdmissionDecision:true});
const outcomes:readonly AdmissionDecisionOutcome[]=["invalid","requires_evidence","requires_authority","identity_unresolved","conflict","deferred","rejected","accepted_provisional","accepted_authoritative","accepted_lifecycle_change","superseded_proposal"];
const operations:readonly PublicationOperation[]=["register","enrich","correct","refine_applicability","add_evidence","record_dispute","resolve_conflict","supersede","deprecate","reject","restore"];
const authorityScope=():CalibrationAdmissionDecisionAuthorityScope=>({scopeId:"scope",scopeVersion:"1",authorityId:"founder:beau",permittedOutcomes:outcomes,permittedOperations:operations,permittedPolicyIds:["eligibility-policy"],limitations:[]});
function authorisedDecision(value:CalibrationKnowledgeAdmissionProposal,outcome:AdmissionDecisionOutcome,operation:PublicationOperation,revision="1",superseded:AdmissionStableIdentity|null=null){const source:AuthorisedCalibrationKnowledgeAdmissionDecisionInput={decisionIdentity:identity("decision:instruction",revision),proposal:value,proposalIdentity,evidencePackageIdentity,proposedRevisionBinding:revisionBinding(value),evidenceAuthorityAssessment:evidenceAssessment(),identityLineageConflictAssessment:identityAssessment(operation),eligibilityAssessment:eligibility(),policy:admissionPolicy(),decisionAuthority:{authorityType:"founder",authorityIdentifier:"founder:beau"},decisionAuthorityScope:authorityScope(),outcome,decisionDate:"2026-08-01",decidedAt:"2026-08-01T05:00:00Z",rationale:"Authorise publication.",acceptedFindingIds:[],rejectedFindingIds:[],unresolvedConditions:[],publicationInstructionId:outcome.startsWith("accepted_")?(revision==="1"?"instruction:1":"instruction:2"):null,supersededDecisionIdentity:superseded,contractVersion:"1"};return constructAuthorisedCalibrationKnowledgeAdmissionDecision(source);}

function input(outcome:AdmissionDecisionOutcome="accepted_provisional",operation:PublicationOperation="register"):DeterministicCalibrationKnowledgePublicationInstructionInput{
  const sourceProposal=proposal(operation);
  const decision=authorisedDecision(sourceProposal,outcome,operation);
  const content=deriveCalibrationKnowledgeContentDigests(sourceProposal.proposedRevision.knowledge);
  return{instructionId:"instruction:1",instructionRevision:"1",instructionContractVersion:"1",createdAt:"2026-08-01T06:00:00.000Z",supersededInstructionIdentity:null,authorisedDecision:decision,proposal:sourceProposal,canonicalPayload:content.payload,acceptedKnowledgeDigest:content.acceptedKnowledgeDigest,expectedResultingCanonicalDigest:content.expectedResultingCanonicalDigest,admissionPolicy:admissionPolicy(),publicationPolicy:{policyId:"publication-policy",policyVersion:"1",compatibleAdmissionPolicyId:"eligibility-policy",compatibleAdmissionPolicyVersion:"1"},serializationPolicy:CALIBRATION_KNOWLEDGE_SERIALIZATION_POLICY_V1,digestPolicy:CALIBRATION_KNOWLEDGE_DIGEST_POLICY_V1,operation,assertionChangeManifest:sourceProposal.proposedRevision.changeManifest,lifecycleChangeManifest:sourceProposal.proposedRevision.lifecycleChangeManifest,publicationSourceRequirement:{requirementId:"qualified-source",requirementVersion:"1",qualifiedIdentityRequired:true,immutableRevisionRequired:true}};
}

for(const outcome of ["accepted_provisional","accepted_authoritative"] as const)test(`constructs a deterministic ${outcome} instruction`,()=>{const result=constructDeterministicCalibrationKnowledgePublicationInstruction(input(outcome));assert.equal(result.acceptedDecisionOutcome,outcome);assert.equal(result.instruction.operation,"register");});
test("constructs an accepted lifecycle-change instruction",()=>{const result=constructDeterministicCalibrationKnowledgePublicationInstruction(input("accepted_lifecycle_change","deprecate"));assert.equal(result.instruction.operation,"deprecate");assert.equal(result.lifecycleChangeManifest.changes.length,1);});
for(const outcome of ["deferred","rejected","requires_evidence","requires_authority","identity_unresolved","conflict","superseded_proposal"] as const)test(`rejects ${outcome} decision`,()=>{const base=input();const sourceProposal=proposal();const decision=authorisedDecision(sourceProposal,outcome,"register");assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,authorisedDecision:decision,proposal:sourceProposal}),/cannot produce|requires an accepted/);});
test("binds the exact decision identity revision digest and authorised instruction ID",()=>{const base=input();const result=constructDeterministicCalibrationKnowledgePublicationInstruction(base);assert.deepEqual(result.instruction.acceptedDecisionIdentity,base.authorisedDecision.decision.decisionIdentity);assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,instructionId:"instruction:other"}),/authorised by the decision/);});
test("rejects unrelated proposal and revision",()=>{const base=input();const unrelated=proposal();const changed={...unrelated,proposalIdentity:identity("proposal:other")};assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,proposal:changed}),/exact Admission Proposal/);assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,proposal:{...base.proposal,proposedRevision:{...base.proposal.proposedRevision,revisionIdentity:identity("revision:other","7")}}}),/proposed revision/);});
test("rejects substituted stable identity version predecessor and manifests",()=>{const base=input();assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,proposal:{...base.proposal,proposedRevision:{...base.proposal.proposedRevision,proposedKnowledgeVersion:"99"}}}),/target Knowledge/);assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,assertionChangeManifest:{...base.assertionChangeManifest,addedAssertionIds:["other"]}}),/assertion change manifest/);assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,lifecycleChangeManifest:{changes:[]},operation:"deprecate"}),/lifecycle-change manifest|operation/);});
test("recomputes canonical bytes and rejects byte substitution",()=>{const base=input();const bytes=base.canonicalPayload.canonicalBytes;const changed={...base.canonicalPayload,canonicalBytes:{...bytes,bytes:[...bytes.bytes.slice(0,-1),0]}};assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,canonicalPayload:changed}),/embedded bytes/);});
test("recomputes content digests and rejects substitution",()=>{const base=input();assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,acceptedKnowledgeDigest:digest("other")}),/caller-supplied/i);assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,expectedResultingCanonicalDigest:digest("other")}),/caller-supplied/i);});
test("rejects material Knowledge substitution",()=>{const base=input();const changed={...base.canonicalPayload.knowledge,canonicalName:{...base.canonicalPayload.knowledge.canonicalName,value:"Different"}};assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,canonicalPayload:{...base.canonicalPayload,knowledge:changed}}),/canonical payload/i);});
test("audit metadata cannot alter the Knowledge content digest",()=>{const base=input();const withAudit={...base.proposal.proposedRevision.knowledge,publicationReceiptId:"unrelated"};assert.equal(deriveCalibrationKnowledgeContentDigests(withAudit).acceptedKnowledgeDigest,base.acceptedKnowledgeDigest);});
test("binds exact policies and rejects mismatches or unsupported versions",()=>{const base=input();assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,admissionPolicy:{...base.admissionPolicy,policyVersion:"2"}}),/Admission policy/);assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,publicationPolicy:{...base.publicationPolicy,compatibleAdmissionPolicyVersion:"2"}}),/Publication policy/);assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,serializationPolicy:{...base.serializationPolicy,policyVersion:"2"}}),/supported serialization/);assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,digestPolicy:{...base.digestPolicy,policyVersion:"2"}}),/supported digest/);});
test("enforces operation and predecessor rules",()=>{const base=input();assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,operation:"enrich"}),/operation/);const amendment=input("accepted_provisional","enrich");assert.equal(constructDeterministicCalibrationKnowledgePublicationInstruction(amendment).expectedPredecessorKnowledgeVersion,"1");});
test("derives deterministic instruction identity and idempotency reference",()=>{const first=constructDeterministicCalibrationKnowledgePublicationInstruction(input());const second=constructDeterministicCalibrationKnowledgePublicationInstruction(input());assert.deepEqual(first.instructionIdentity,second.instructionIdentity);assert.deepEqual(first.idempotencyReference,second.idempotencyReference);assert.match(first.instructionContentDigest,/^sha256:[a-f0-9]{64}$/);});
test("set-like admission policy order cannot alter instruction identity",()=>{const first=input();const second={...input(),admissionPolicy:{...input().admissionPolicy,applicableProposalKinds:[...input().admissionPolicy.applicableProposalKinds].reverse(),validationRuleVersions:[...input().admissionPolicy.validationRuleVersions].reverse()}};const left=constructDeterministicCalibrationKnowledgePublicationInstruction(first);const right=constructDeterministicCalibrationKnowledgePublicationInstruction(second);assert.deepEqual(left.instructionIdentity,right.instructionIdentity);assert.deepEqual(left.admissionPolicy,right.admissionPolicy);});
test("changed instruction content changes its digest",()=>{const first=constructDeterministicCalibrationKnowledgePublicationInstruction(input());const changed=constructDeterministicCalibrationKnowledgePublicationInstruction({...input(),createdAt:"2026-08-01T06:01:00.000Z"});assert.notEqual(first.instructionContentDigest,changed.instructionContentDigest);});
test("corrected instruction requires supersession and corrected decision",()=>{const base=input();assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...base,instructionRevision:"2"}),/superseded instruction/);const previousInstruction=constructDeterministicCalibrationKnowledgePublicationInstruction(base);const previousDecision=base.authorisedDecision.decision.decisionIdentity;const sourceProposal=proposal();const correctedDecision=authorisedDecision(sourceProposal,"accepted_provisional","register","2",previousDecision);const corrected={...base,instructionId:"instruction:2",instructionRevision:"2",authorisedDecision:correctedDecision,proposal:sourceProposal,supersededInstructionIdentity:previousInstruction.instructionIdentity};assert.equal(constructDeterministicCalibrationKnowledgePublicationInstruction(corrected).instructionIdentity.revision,"2");});
test("requires a qualified immutable publication-source boundary",()=>{const base=input();assert.throws(()=>Reflect.apply(constructDeterministicCalibrationKnowledgePublicationInstruction,undefined,[{...base,publicationSourceRequirement:{...base.publicationSourceRequirement,qualifiedIdentityRequired:false}}]),/qualified immutable/);});
test("requires canonical explicit creation time",()=>{assert.throws(()=>constructDeterministicCalibrationKnowledgePublicationInstruction({...input(),createdAt:"2026-08-01T06:00:00Z"}),/canonical UTC/);});
test("outputs are recursively frozen and caller-isolated",()=>{const base=input();const added=[...base.assertionChangeManifest.addedAssertionIds];const result=constructDeterministicCalibrationKnowledgePublicationInstruction({...base,assertionChangeManifest:{...base.assertionChangeManifest,addedAssertionIds:added}});added[0]="changed";assert.deepEqual(result.assertionChangeManifest.addedAssertionIds,["identity"]);assert.ok(Object.isFrozen(result));assert.ok(Object.isFrozen(result.canonicalPayload.canonicalBytes.bytes));assert.ok(Object.isFrozen(result.idempotencyReference));});
test("instruction exposes no execution source identity receipt snapshot registry persistence or runtime surface",()=>{const result=constructDeterministicCalibrationKnowledgePublicationInstruction(input());for(const key of ["publicationExecution","publicationSourceIdentity","publicationReceipt","registrySnapshot","registry","persistence","schema","runtime"])assert.equal(Reflect.get(result,key),undefined);});
