import assert from "node:assert/strict";
import test from "node:test";
import type { AdmissionStableIdentity } from "./calibrationKnowledgeAdmission.ts";
import type { ExactEngineeringAssertionRevisionReference } from "./engineeringAssertionAdmissionBinding.ts";
import { defineEngineeringAssertionConflict,defineEngineeringAssertionSupersession,type EngineeringAssertionConflict,type EngineeringAssertionSupersession } from "./engineeringAssertionConflictSupersession.ts";

const sha=(c:string)=>`sha256:${c.repeat(64)}`;
const aid=(id:string,revision="1"):AdmissionStableIdentity=>({id,revision,contentDigest:`identity:${"a".repeat(64)}`});
const ref=(id:string,revision="1",c="a"):ExactEngineeringAssertionRevisionReference=>({stableAssertionId:id,assertionRevision:revision,canonicalAssertionDigest:sha(c),assertionRevisionEnvelopeDigest:sha(c==="f"?"e":String.fromCharCode(c.charCodeAt(0)+1))});
const evidence=()=>[{evidenceId:"evidence:1",evidencePackageIdentity:aid("package:evidence"),role:"supports_conflict" as const}];
const authority=()=>[{authorityClaimIdentity:aid("authority:claim"),role:"establishes" as const}];
const provenance=()=>[{sourceType:"fixture",sourceIdentifier:"wp-004.4.4"}];
const conflict=():EngineeringAssertionConflict=>({conflictIdentity:aid("conflict:one"),firstAssertion:ref("assertion:first","1","a"),secondAssertion:ref("assertion:second","2","c"),materialPaths:[{assertion:ref("assertion:first","1","a"),propositionPaths:["/proposition/object"],scopePaths:[]},{assertion:ref("assertion:second","2","c"),propositionPaths:["/proposition/object"],scopePaths:[]}],classification:"direct_contradiction",evidence:evidence(),authority:authority(),rationale:"Exact propositions disagree.",resolutionState:"unresolved",resolutionSuccessorAssertion:null,lifecycle:{state:"active",lifecycleVersion:"1",supersededByConflictIdentity:null},provenance:provenance(),contractVersion:"1"});
const supersession=(kind:"complete"|"partial"="partial"):EngineeringAssertionSupersession=>{const predecessor=ref("assertion:stable","1","a");return{supersessionIdentity:aid("supersession:one"),kind,predecessor,successor:ref("assertion:stable","2","c"),supersededScope:{scopeId:"scope:superseded",assertion:predecessor,includedScopePaths:["/scope/applicability/platforms"],excludedScopePaths:[],description:"Platforms replaced."},retainedScope:kind==="partial"?{scopeId:"scope:retained",assertion:predecessor,includedScopePaths:["/scope/applicability/engineFamilies"],excludedScopePaths:[],description:"Engine families retained."}:null,scopeComparison:{comparisonId:"comparison:one",basis:kind==="complete"?"equivalent":"predecessor_contains_successor",comparedScopePaths:["/scope/applicability/platforms"],unresolvedOverlapConflictIdentity:null,rationale:"Declarative scope comparison."},evidence:evidence(),authority:authority(),rationale:"Successor replaces only the declared scope.",effectivePublication:{publicationInstructionId:"publication:1",publicationInstructionRevision:"1",publicationInstructionDigest:sha("e")},registrySnapshot:{snapshotId:"snapshot:1",snapshotRevision:"1",snapshotEnvelopeDigest:sha("f")},provenance:provenance(),contractVersion:"1"};};

test("conflict binds exact revisions without changing either assertion",()=>{const input=conflict();const result=defineEngineeringAssertionConflict(input);assert.deepEqual(result.firstAssertion,input.firstAssertion);assert.deepEqual(result.secondAssertion,input.secondAssertion);assert.equal(result.resolutionState,"unresolved");assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.materialPaths));});
test("conflict classifications preserve compatibility, incompleteness, authority disagreement, and ambiguity",()=>{for(const classification of ["scope_separated_compatibility","conditional_compatibility","evidence_incompleteness","authority_conflict","unresolved_conflict","proposal_ambiguity"] as const){const input=conflict();const scoped=classification.includes("compatibility");const result=defineEngineeringAssertionConflict({...input,classification,materialPaths:scoped?input.materialPaths.map(item=>({...item,propositionPaths:[],scopePaths:["/scope/applicability"]})):[]});assert.equal(result.classification,classification);}});
test("direct contradiction requires exact material proposition paths",()=>{assert.throws(()=>defineEngineeringAssertionConflict({...conflict(),materialPaths:[]}),/proposition path/);assert.throws(()=>defineEngineeringAssertionConflict({...conflict(),secondAssertion:conflict().firstAssertion}),/distinct assertion revisions/);});
test("a conflict resolution successor does not imply supersession",()=>{const result=defineEngineeringAssertionConflict({...conflict(),resolutionState:"resolved",resolutionSuccessorAssertion:ref("assertion:resolution","1","e"),lifecycle:{state:"resolved",lifecycleVersion:"2",supersededByConflictIdentity:null}});assert.equal(result.resolutionSuccessorAssertion?.stableAssertionId,"assertion:resolution");assert.ok(!("supersessionIdentity" in result));});
test("complete supersession preserves immutable exact lineage",()=>{const result=defineEngineeringAssertionSupersession(supersession("complete"));assert.equal(result.kind,"complete");assert.equal(result.retainedScope,null);assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.predecessor));});
test("partial supersession explicitly preserves retained scope",()=>{const result=defineEngineeringAssertionSupersession(supersession());assert.equal(result.retainedScope?.scopeId,"scope:retained");assert.notDeepEqual(result.supersededScope.includedScopePaths,result.retainedScope?.includedScopePaths);});
test("partial cannot appear complete and complete cannot retain scope",()=>{const partial=supersession();assert.throws(()=>defineEngineeringAssertionSupersession({...partial,retainedScope:null}),/requires explicit retained scope/);const complete=supersession("complete");assert.throws(()=>defineEngineeringAssertionSupersession({...complete,retainedScope:partial.retainedScope}),/cannot declare retained scope/);});
test("unresolved overlap remains an explicit conflict",()=>{const input=supersession();assert.throws(()=>defineEngineeringAssertionSupersession({...input,scopeComparison:{...input.scopeComparison,basis:"overlap"}}),/requires exactly one conflict/);const result=defineEngineeringAssertionSupersession({...input,scopeComparison:{...input.scopeComparison,basis:"overlap",unresolvedOverlapConflictIdentity:aid("conflict:overlap")}});assert.equal(result.scopeComparison.unresolvedOverlapConflictIdentity?.id,"conflict:overlap");});
test("supersession requires independent Evidence, authority, publication, and Registry references",()=>{const input=supersession();assert.throws(()=>defineEngineeringAssertionSupersession({...input,evidence:[]}),/requires Evidence and authority/);assert.throws(()=>defineEngineeringAssertionSupersession({...input,authority:[]}),/requires Evidence and authority/);assert.throws(()=>defineEngineeringAssertionSupersession({...input,effectivePublication:{...input.effectivePublication,publicationInstructionDigest:"bad"}}),/SHA-256/);});
test("constructors defensively clone and recursively freeze",()=>{const input=supersession();const result=defineEngineeringAssertionSupersession(input);(input.supersededScope.includedScopePaths as string[]).push("/scope/changed");assert.deepEqual(result.supersededScope.includedScopePaths,["/scope/applicability/platforms"]);assert.throws(()=>{(result.evidence as unknown as object[]).push({});},TypeError);});
