import assert from "node:assert/strict";import test from "node:test";
import type { AdmissionStableIdentity } from "./calibrationKnowledgeAdmission.ts";import type { PublicationSourceIdentity } from "./calibrationKnowledgePublicationSourceRegistrySnapshot.ts";
import { compositeEntityKey,defineEngineeringAssertionCompositePublicationUnit,deriveCompositePublicationUnitDigest,type CompositeEntityRevisionReference,type CompositePublicationUnitInput } from "./engineeringAssertionCompositePublicationUnit.ts";
const sha=(c:string)=>`sha256:${c.repeat(64)}`;const id=(value:string):AdmissionStableIdentity=>({id:value,revision:"1",contentDigest:`identity:${"a".repeat(64)}`});
const entity=(kind:CompositeEntityRevisionReference["entityKind"],stableId:string,c="a"):CompositeEntityRevisionReference=>({entityKind:kind,stableId,revision:"1",canonicalPayloadDigest:sha(c),revisionEnvelopeDigest:kind==="calibration_knowledge"?null:sha(c==="f"?"e":String.fromCharCode(c.charCodeAt(0)+1)),lifecycleIdentity:`lifecycle:${stableId}`,provenanceIdentityIds:[`provenance:${stableId}`]});
const source=():PublicationSourceIdentity=>({sourceId:"source:fixture",sourceRevision:"1",sourceContentDigest:sha("a"),sourceEnvelopeDigest:sha("b"),sourceType:{vocabularyId:"source",vocabularyVersion:"1",termId:"fixture",label:"Fixture",recognition:"known"},sourceContractId:"source-contract",sourceContractVersion:"1",authority:{authorityType:"fixture",authorityIdentifier:"fixture"},provenance:[{provenanceId:"p",sourceType:"fixture",sourceIdentifier:"fixture",sourceRevisionOrigin:"1",implementationOrigin:null,sourceContractId:"c",sourceContractVersion:"1",validationAuthority:"fixture",transformationHistory:[]}],lifecycle:{state:"active",lifecycleVersion:"1",supersededBySourceId:null,supersededBySourceRevision:null},capabilities:[],knownLimitations:[]});
function fixture():Omit<CompositePublicationUnitInput,"unitDigest">{const knowledge=entity("calibration_knowledge","knowledge:1","a"),assertion=entity("engineering_assertion","assertion:1","c"),membership=entity("assertion_membership","membership:1","e"),relationship=entity("knowledge_relationship","relationship:1","f"),conflict=entity("assertion_conflict","conflict:1","1"),optional=entity("engineering_assertion","assertion:optional","2");const decision=(e:CompositeEntityRevisionReference)=>({decisionIdentity:id(`decision:${e.stableId}`),entity:e,authorisedOperation:"register" as const,lifecycleEffect:"create" as const});const members=[knowledge,assertion,membership,relationship,conflict].map(e=>({entity:e,requirement:"required" as const,state:"included" as const,admissionDecision:decision(e),dependencyEntityKeys:[],withholdingReason:null,blockingReason:null}));return{unitId:"composite:1",unitRevision:"1",contractVersion:"1",publicationSource:source(),predecessorSnapshot:{snapshotId:"snapshot:before",snapshotRevision:"1",snapshotEnvelopeDigest:sha("9")},operation:"register",members:[...members,{entity:optional,requirement:"optional",state:"withheld",admissionDecision:decision(optional),dependencyEntityKeys:[],withholdingReason:"Not required by the parent.",blockingReason:null}],memberships:[{membership,knowledge,assertion,role:"primary",requirement:"required",admissionDecision:decision(membership)}],relationships:[{relationship,source:assertion,target:conflict,direction:"outgoing",relationshipType:"disputed_by",admissionDecision:decision(relationship)}],dependencies:[],atomicityPolicy:"all_required_or_none"};}
function build(input=fixture()){const unitDigest=deriveCompositePublicationUnitDigest(input);return defineEngineeringAssertionCompositePublicationUnit({...input,unitDigest});}
test("constructs a sealed deterministic composite publication unit",()=>{const result=build();assert.equal(result.entityCount,6);assert.equal(result.requiredEntityKeys.length,5);assert.equal(result.withheldOptionalEntityKeys.length,1);assert.ok(Object.isFrozen(result)&&Object.isFrozen(result.members));});
test("caller order cannot alter canonical bytes digest or idempotency",()=>{const a=fixture(),b={...a,members:[...a.members].reverse().map(m=>({...m,entity:{...m.entity,provenanceIdentityIds:["provenance:z",...m.entity.provenanceIdentityIds].reverse()},admissionDecision:{...m.admissionDecision,entity:{...m.admissionDecision.entity,provenanceIdentityIds:["provenance:z",...m.admissionDecision.entity.provenanceIdentityIds].reverse()}},dependencyEntityKeys:[...m.dependencyEntityKeys].reverse()})),memberships:[...a.memberships].reverse(),relationships:[...a.relationships].reverse()};const aWithProvenance={...a,members:a.members.map(m=>({...m,entity:{...m.entity,provenanceIdentityIds:[...m.entity.provenanceIdentityIds,"provenance:z"]},admissionDecision:{...m.admissionDecision,entity:{...m.admissionDecision.entity,provenanceIdentityIds:[...m.admissionDecision.entity.provenanceIdentityIds,"provenance:z"]}}}))};const left=build(aWithProvenance),right=build(b);assert.equal(left.unitDigest,right.unitDigest);assert.deepEqual(left.canonicalPayload.canonicalBytes,right.canonicalPayload.canonicalBytes);assert.equal(left.idempotencyIdentity,right.idempotencyIdentity);});
test("required optional withheld and blocking states remain distinct",()=>{const input=fixture();assert.throws(()=>build({...input,members:input.members.map((m,i)=>i===0?{...m,state:"withheld",withholdingReason:"bad"}:m)}),/Required member cannot be withheld/);assert.throws(()=>build({...input,members:input.members.map((m,i)=>i===0?{...m,state:"blocking",blockingReason:null}:m)}),/Blocking member requires/);});
test("every entity retains an exact independent Admission Decision",()=>{const input=fixture();const changed=input.members.map((m,i)=>i===1?{...m,admissionDecision:{...m.admissionDecision,entity:input.members[0].entity}}:m);assert.throws(()=>build({...input,members:changed}),/exact entity revision/);});
test("canonical memberships bind exact Knowledge and assertion revisions",()=>{const input=fixture();assert.throws(()=>build({...input,memberships:[{...input.memberships[0],assertion:entity("engineering_assertion","dangling","8") }]}),/dangling entity reference/);assert.throws(()=>build({...input,memberships:[]}),/lacks its canonical required membership/);});
test("governed relationships reject dangling graph substitutes",()=>{const input=fixture();assert.throws(()=>build({...input,relationships:[{...input.relationships[0],target:entity("engineering_assertion","missing","8") }]}),/dangling entity reference/);});
test("conflict and supersession remain first-class entity kinds",()=>{const input=fixture();const supersession=entity("assertion_supersession","supersession:1","7"),decision={decisionIdentity:id("decision:supersession"),entity:supersession,authorisedOperation:"supersede" as const,lifecycleEffect:"supersede" as const};const result=build({...input,members:[...input.members,{entity:supersession,requirement:"context_only",state:"included",admissionDecision:decision,dependencyEntityKeys:[],withholdingReason:null,blockingReason:null}]});assert.ok(result.members.some(m=>m.entity.entityKind==="assertion_conflict"));assert.ok(result.members.some(m=>m.entity.entityKind==="assertion_supersession"));});
test("exact predecessor Snapshot and publication source are mandatory",()=>{const input=fixture();assert.throws(()=>build({...input,predecessorSnapshot:{...input.predecessorSnapshot,snapshotEnvelopeDigest:"bad"}}),/Snapshot digest/);assert.throws(()=>build({...input,publicationSource:{...input.publicationSource,sourceEnvelopeDigest:"bad"}}),/source envelope digest/);});
test("dependencies cannot point to absent or withheld members",()=>{const input=fixture();const withheld=compositeEntityKey(input.members.at(-1)!.entity);assert.throws(()=>build({...input,members:input.members.map((m,i)=>i===0?{...m,dependencyEntityKeys:[withheld]}:m)}),/dangling or unavailable dependency/);});
test("material changes alter digest while execution proof remains absent",()=>{const input=fixture(),first=build(input);const second=build({...input,contractVersion:"2"});assert.notEqual(first.unitDigest,second.unitDigest);assert.ok(!("executionResult" in first));assert.ok(!("receipt" in first));assert.ok(!("resultingSnapshot" in first));});
test("defensive cloning isolates mutable caller input",()=>{const input=fixture(),result=build(input);(input.members as unknown as object[]).push({});assert.equal(result.members.length,6);assert.throws(()=>{(result.members as unknown as object[]).push({});},TypeError);});
