import { createHash } from "node:crypto";
import { defineCalibrationKnowledgeAdmissionDecision, defineCalibrationKnowledgePublicationInstruction, defineCalibrationKnowledgePublicationReceipt } from "./calibrationKnowledgeAdmission.ts";
import { defineCalibrationKnowledgeObject, type CalibrationApplicability, type GovernedVocabularyReference, type QualifiedAssertion } from "./calibrationKnowledge.ts";
import { deriveCalibrationKnowledgeContentDigests } from "./calibrationKnowledgeCanonicalSerialization.ts";
import { createImmutableCalibrationKnowledgeRegistry } from "./calibrationKnowledgeRegistry.ts";
import type { WorkshopKnowledgeRecord, QualifiedSemanticField } from "../calibration-workshop/definitionKnowledgeBinding.ts";

const PUBLISHED_AT = "2026-09-17T00:00:00.000Z";
const SOURCE_REVISION = "founder-calibration-semantic-review:2026-09-17";
const REGISTRY = "calibration-semantic-registry:founder-publication-1";
const sha = (value: unknown) => `sha256:${createHash("sha256").update(JSON.stringify(value)).digest("hex")}`;
const identity = (id: string, material: unknown) => ({ id, revision: `${id}:revision:1`, contentDigest: sha(material) });
const field = <T>(value: T, id: string, limitations: readonly string[] = []): QualifiedSemanticField<T> => Object.freeze({ value, assertionId: id, assertionRevision: "1", authority: "founder-semantic-authority", provenance: Object.freeze([SOURCE_REVISION]), limitations: Object.freeze([...limitations]) });
const vocabulary = (termId: string, label = termId): GovernedVocabularyReference => ({ vocabularyId: "tunesight.calibration-semantics", vocabularyVersion: "1", termId, label, recognition: "known" });
const applicability = (seed: Seed): CalibrationApplicability => ({ scope: vocabulary("exact_rom_definition", "exact ROM and Definition revision"), platforms: [], engineFamilies: [seed.rom === "IJE0S" ? "N54" : "B58 Gen1"], ecuFamilies: [], dmeVariants: [], controlStrategies: [], romFamilies: [], softwareVersions: [seed.rom], calibrationIds: [], stockVariantIds: [], operatingModes: [], transmissions: [], regions: [], emissionsSpecifications: [], hardwareConfigurations: [], sourceReferenceIds: [seed.revision], unresolvedReason: null });
const assertion = <T>(seed: Seed, id: string, value: T): QualifiedAssertion<T> => ({ assertionId: id, value, verificationStatus: "founder_verified", confidence: "high", authority: { authorityType: "founder", authorityIdentifier: "founder-beau-and-bob" }, provenance: [{ sourceType: "founder_semantic_review", sourceIdentifier: SOURCE_REVISION, validationMethod: "explicit review decision", validationAuthority: "Founder", validationDate: "2026-09-17" }], supportingEvidence: [{ evidenceId: `evidence:${id}`, sourceType: "controlled_definition", sourceIdentifier: seed.revision }], contradictoryEvidence: [], applicability: applicability(seed), conflictState: "none", unresolvedReason: null, version: "1", lifecycle: { status: "active", version: "1", effectiveAt: PUBLISHED_AT } });

type Seed = Readonly<{ rom: "IJE0S" | "00003076501103"; revision: string; original: string; english: string; symbol?: string; system: string; related?: readonly string[]; role: string; control: string; axes?: readonly Readonly<{ id: "x" | "y"; meaning: string }>[]; output?: string; limitations: readonly string[]; relationship?: readonly Readonly<{ target: string; kind: string }>[] }>;
const n54 = "qualified-rom-layout-applicability-revision:7bec3ec729b79e57ae9b412e6ac1cf972d9187799a1cb7e6ea90550a9e5af765";
const b58 = "qualified-rom-layout-applicability-revision:f2631e65861257af71b6b2c9c5b67919319c50bb9db16494d2ecfaeaa9603272";
const seeds: readonly Seed[] = Object.freeze([
 {rom:"IJE0S",revision:"xdf-definition-revision:5b4963338364de4b26674037023ac0e79d0c28731abb97198a84b49fe40c90fa",original:"Fuel Scalar Interpolation (Map 1)",english:"Fuel Scalar Blend — Ethanol",system:"Fueling / Lambda",role:"Interpolation / Blend",control:"Blends fuel-scalar calibration paths according to ethanol content.",axes:[{id:"x",meaning:"Ethanol Content"}],output:"Fuel-scalar Blend Percentage",limitations:["Exact IJE0S / Map 1 only.","Endpoint scalar Definitions, interpolation direction and activation state remain unresolved.","Controlled evidence is zeroed."],relationship:[{target:"ethanol-content",kind:"indexed_by"}]},
 {rom:"IJE0S",revision:"xdf-definition-revision:e102deaca5035e06fc326d68f52735b0a1eeceee3a062a9fd8a22750dde88f6d",original:"Timing Interpolation (Map 1)",english:"Ignition Timing Blend — Ethanol",system:"Ignition / Timing",role:"Interpolation / Blend",control:"Blends timing calibration paths according to ethanol content.",axes:[{id:"x",meaning:"Ethanol Content"}],output:"Timing-table Blend Percentage",limitations:["Exact IJE0S / Map 1 only.","Timing endpoints and interpolation direction remain unresolved; this is not asserted as a final spark target.","Controlled evidence is zeroed."],relationship:[{target:"ethanol-content",kind:"indexed_by"}]},
 {rom:"IJE0S",revision:"xdf-definition-revision:562706ea7e03b78d6af5139a90bd8292e833b6c5a345dec905a3d7c13d17770e",original:"Load Interpolation (Map 1)",english:"Load and Boost Blend — Ethanol",system:"Load & Torque",related:["Boost & Air Control"],role:"Interpolation / Blend",control:"Blends load and boost calibration paths according to ethanol content.",axes:[{id:"x",meaning:"Ethanol Content"}],output:"Load-and-boost Blend Percentage",limitations:["Exact IJE0S / Map 1 only.","Endpoint Tables and interpolation direction remain unresolved.","Multi-system membership establishes no target or ceiling relationship.","Controlled evidence is zeroed."],relationship:[{target:"ethanol-content",kind:"indexed_by"}]},
 {rom:"IJE0S",revision:"xdf-definition-revision:ceb0c400ef8c17bd14f009171c91bd135b8720c07ee4e55d7e11dfc039ca7fb4",original:"Boost Ceiling (Relative) (Gear x RPM) (Map 1)",english:"Boost Ceiling — Relative Pressure by Gear and RPM",system:"Boost & Air Control",role:"Ceiling / Limiter",control:"Caps calculated relative boost target by gear and engine speed.",axes:[{id:"x",meaning:"Engine Speed"},{id:"y",meaning:"Gear"}],output:"Relative Boost-pressure Ceiling",limitations:["Exact IJE0S Map 1 and MHD+ custom path only.","Enable Definition and scalar-ceiling relationship remain unbound.","No tuning or safety recommendation is asserted."],relationship:[{target:"calculated-boost-target",kind:"ceiling_for"}]},
 {rom:"IJE0S",revision:"xdf-definition-revision:c3eb6dcd0579c24195011d340101aafd8d7af981bfb908af23c5fb7cf71146ad",original:"WGDC D-Factor (Custom)",english:"Wastegate Duty D-Factor Correction — Custom",system:"Wastegate / WGDC",role:"Correction / Control",control:"Adds to or subtracts from custom wastegate-duty base control.",limitations:["Exact pressure-axis meanings, enabling conditions and complete derivative-controller mathematics remain unresolved.","Controlled evidence is zeroed; custom control path only."],relationship:[{target:"wgdc-base",kind:"correction_to"}]},
 {rom:"IJE0S",revision:"xdf-definition-revision:bd9da4d632d62ad3742125642daae9926023b3a50f140fe22403155f35b8165f",original:"Min Load Threshold for P/D Factors",english:"Minimum Load for WGDC P/D Corrections",system:"Wastegate / WGDC",related:["Load & Torque"],role:"Threshold",control:"Gates custom WGDC P/D corrections above a minimum load threshold.",limitations:["Load unit and normalization, comparison inclusivity and enable hierarchy remain unresolved.","No qualified safety range is asserted."],relationship:[{target:"wgdc-pd-corrections",kind:"activation_threshold_for"}]},
 {rom:"IJE0S",revision:"xdf-definition-revision:c1c2c05ba6ae47773315bf59efbff83d13e5a1d4bfbf66a3392b5396d28432cd",original:"RPM limit during oil pressure limp mode",english:"Low Oil-pressure Limp-mode RPM Limit",system:"Limiters & Safety",related:["Temperature & Protection"],role:"Protection / Limiter",control:"Caps engine speed during an enabled low-oil-pressure limp state.",output:"Engine-speed Limit",limitations:["Exact IJE0S only; limp enable, trigger and hysteresis remain separately governed.","No relationship to the held oil-warning threshold is asserted."],relationship:[{target:"low-oil-pressure-limp-state",kind:"limiter_for"}]},
 {rom:"IJE0S",revision:"xdf-definition-revision:32c413b786dc4389f9c6c1cba6ffe70411a896952cebcc71fdc8be45d7d2f7fe",original:"Base Fuel Pressure",english:"Low-pressure Fuel-system Base Pressure",system:"Fueling / Lambda",role:"Pressure Target / Base",control:"Defines the low-pressure fuel-system base pressure.",output:"Base Fuel Pressure",limitations:["Exact IJE0S Definition only.","Control-loop hierarchy and operating-condition selection remain unresolved."],relationship:[{target:"low-pressure-fuel-system",kind:"base_target_for"}]},
 {rom:"IJE0S",revision:"xdf-definition-revision:8d3f77e689d62002931561dadec2c3d852fc8ad0d174d63596fc979245a784bc",original:"Start-up delay before enabling oil pressure alerts (Oil Temp)",english:"Oil-pressure Alert Enable Delay — Oil Temperature",system:"Limiters & Safety",related:["IAT / Temperature Compensation"],role:"Protection / Enable Delay",control:"Delays oil-pressure alert enablement after engine start according to oil temperature.",axes:[{id:"x",meaning:"Oil Temperature"}],output:"Alert Enable Delay",limitations:["Exact IJE0S Definition only.","Alert thresholds and enable hierarchy remain separately governed.","This record does not publish the held oil-warning pressure Table."],relationship:[{target:"oil-pressure-alerting",kind:"enable_delay_for"}]},
 {rom:"IJE0S",revision:"xdf-definition-revision:681778a9ff67d0bf605f2a9093ac8026725f7d2950df6bc808773f531f8f30b5",original:"Fuel Interpolation (Map 1)",english:"Fuel-table Blend — Ethanol",system:"Fueling / Lambda",role:"Interpolation / Blend",control:"Blends fuel calibration paths according to ethanol content.",axes:[{id:"x",meaning:"Ethanol Content"}],output:"Fuel-table Blend Percentage",limitations:["Exact IJE0S / Map 1 only.","Endpoint Tables, interpolation direction and activation state remain unresolved."],relationship:[{target:"ethanol-content",kind:"indexed_by"}]},
 {rom:"00003076501103",revision:"xdf-definition-revision:619f01621c57bd80b205fe1be9f1689933f034002fbdd965f0359ce124ceed28",original:"Boost Ceiling",english:"Boost Ceiling",symbol:"K_MAX_PSSOLBER",system:"Boost & Air Control",role:"Ceiling",control:"Caps a requested boost-pressure quantity.",output:"Boost-pressure Ceiling",limitations:["Pressure basis and precedence relative to other boost ceilings remain unresolved.","No safety or tuning range is implied."],relationship:[{target:"requested-boost-pressure",kind:"ceiling_for"}]},
 {rom:"00003076501103",revision:"xdf-definition-revision:d4b026fcdf8427fb76d91d76acc07c7927927e6698524565734ae092b5ba8a82",original:"Boost Ceiling (BMW - Absolute Pressure)",english:"Boost Request Ceiling — Absolute Pressure",symbol:"BMWtchsp_p_ReqMax_C",system:"Boost & Air Control",role:"Ceiling",control:"Caps requested absolute charge pressure.",output:"Absolute Charge-pressure Ceiling",limitations:["Exact selection-chain stage and precedence relative to other ceilings remain unresolved."],relationship:[{target:"requested-boost-pressure",kind:"ceiling_for"}]},
 {rom:"00003076501103",revision:"xdf-definition-revision:16ec28ddbae1b6fbbff5dbb2a9db701fa5ccef7575039141e6671237a23a21bb",original:"WGDC P factor",english:"Wastegate P-control Factor",symbol:"BMWtchctr_pwr_CmprGra_M",system:"Wastegate / WGDC",role:"Control",control:"Provides a proportional-family wastegate feedback-control factor.",limitations:["Source kW is preserved as metadata only and is not qualified as physical power.","Engineering output unit and exact controller mathematics remain unresolved."],relationship:[{target:"wastegate-base-feed-forward",kind:"feedback_correction_for"}]},
 {rom:"00003076501103",revision:"xdf-definition-revision:f6899ec3fb38e3d04061287a5610d0b7b0bd5a6d0d2542abd1fb031a5fc582c3",original:"WGDC D-Factor",english:"Wastegate D-control Factor",symbol:"BMWtchctr_pwr_Dp_M",system:"Wastegate / WGDC",role:"Control",control:"Provides a D-family wastegate feedback-control factor.",limitations:["Source kW is metadata only, not physical power.","Engineering output unit, pressure-axis meanings and exact derivative mathematics remain unresolved."],relationship:[{target:"wastegate-base-feed-forward",kind:"feedback_correction_for"}]},
 {rom:"00003076501103",revision:"xdf-definition-revision:a81d669459224dc6509d1ada00f2ff278b84a47f261c2b10f28b811ad460d9e9",original:"Wastegate Position - für Vorsteuerung",english:"Wastegate Base Position — Feed-forward",symbol:"BMWtchctr_pct_WgBasc_M",system:"Wastegate / WGDC",role:"Base / Feed-forward Control",control:"Provides the base feed-forward wastegate-position command.",output:"Base Wastegate-position Command",limitations:["Percentage interpretation is not explicitly qualified by the dimensionless source unit.","Original German terminology must remain preserved."],relationship:[{target:"wgdc-pd-feedback-family",kind:"base_for"}]},
 {rom:"00003076501103",revision:"xdf-definition-revision:28d58f86e930af913190c5719d8a8edb423d523e2072641466ee0ee35c7c3324",original:"Timing Correction Factor (Map 2)",english:"Ignition Timing Correction Factor — Engine Temp × IAT",symbol:"KF_FDZWT_PF1 (map 2)",system:"Ignition / Timing",related:["IAT / Temperature Compensation"],role:"Correction / Compensation",control:"Provides a timing-associated correction factor indexed by engine temperature and IAT.",axes:[{id:"x",meaning:"Engine Temperature"},{id:"y",meaning:"Intake Air Temperature"}],output:"Ignition Timing Correction Factor",limitations:["Exact mathematical operation and correction direction remain unresolved.","Output must not be presented as degrees of timing; exact Map 2 only."],relationship:[{target:"engine-temperature-and-iat",kind:"indexed_by"}]},
 {rom:"00003076501103",revision:"xdf-definition-revision:0b87730fffbf1c56c9eb2ea5e1e8bced511b255ad339d657ac73d15b478bcc1b",original:"Load limit factor by rich for component protection",english:"Load-limit Multiplier for Rich-mixture Component Protection",symbol:"K_FRFMXBS_MN",system:"Limiters & Safety",role:"Protection / Limiter / Multiplier",control:"Scales a load limit within a rich-mixture component-protection strategy.",output:"Load-limit Multiplier",limitations:["Protected component, lambda threshold and enrichment causal relationship remain unresolved.","Fueling / Lambda is not qualified system membership and no Lambda Target relationship is asserted."],relationship:[{target:"rich-component-protection-strategy",kind:"load_limit_multiplier_for"}]}
]);

const record = (seed: Seed): WorkshopKnowledgeRecord => {
 const key = seed.revision.slice(-16), limitations = Object.freeze([...seed.limitations]);
 return Object.freeze({ knowledgeId:`calibration-knowledge:${key}`, knowledgeRevision:"1", lifecycle:"active", verification:"founder_verified", conflict:false, exactWorkshopInstanceIdentities:Object.freeze([]), exactDefinitionIdentities:Object.freeze([]), exactDefinitionRevisions:Object.freeze([seed.revision]), applicability:Object.freeze([seed.rom === "IJE0S" ? n54 : b58]), aliases:Object.freeze([field(seed.english,`assertion:${key}:english`), ...(seed.original !== seed.english ? [field(seed.original,`assertion:${key}:original`)] : []), ...(seed.original.includes("Vorsteuerung") ? [field("Wastegate Pre-control Position",`assertion:${key}:alias`)] : [])]), engineeringSystem:field(seed.system,`assertion:${key}:system`), relatedEngineeringSystems:Object.freeze((seed.related ?? []).map((value,index)=>field(value,`assertion:${key}:related:${index}`))), calibrationRole:field(seed.role,`assertion:${key}:role`), sourceSymbol:seed.symbol ?? null, controls:Object.freeze([field(seed.control,`assertion:${key}:control`)]), whyItMatters:Object.freeze([field("Founder-qualified calibration semantics for current-ROM engineering navigation.",`assertion:${key}:purpose`)]), howToRead:Object.freeze([]), directionalEffects:Object.freeze([]), operatingContexts:Object.freeze([field(`Exact ROM/software ${seed.rom} only.`,`assertion:${key}:scope`)]), engineeringConsiderations:Object.freeze([]), axisMeanings:Object.freeze((seed.axes??[]).map((axis,index)=>field({axisId:axis.id,meaning:axis.meaning},`assertion:${key}:axis:${index}`))), outputMeaning:seed.output?field(seed.output,`assertion:${key}:output`):null, relatedCalibrations:Object.freeze((seed.relationship ?? []).map((item,index)=>field({targetKnowledgeId:item.target,relationship:item.kind},`assertion:${key}:relationship:${index}`))), telemetryRelationships:Object.freeze([]), limitations });
};

const canonicalRecord = (seed: Seed, runtime: WorkshopKnowledgeRecord) => {
 const key=seed.revision.slice(-16), stableId=runtime.knowledgeId, app=applicability(seed);
 return defineCalibrationKnowledgeObject({identity:assertion(seed,`canonical:${key}:identity`,{stableId}),canonicalName:assertion(seed,`canonical:${key}:name`,seed.english),aliases:[assertion(seed,`canonical:${key}:original`,{name:seed.original,sourceReferenceId:seed.revision}),...(seed.original.includes("Vorsteuerung")?[assertion(seed,`canonical:${key}:alias`,{name:"Wastegate Pre-control Position",sourceReferenceId:seed.revision})]:[])],purposes:[assertion(seed,`canonical:${key}:purpose`,{summary:seed.control,controlRole:seed.role})],engineeringIntents:[assertion(seed,`canonical:${key}:intent`,{summary:seed.control,engineeringObjectives:[],participatingSubsystems:[vocabulary(seed.system,seed.system),...(seed.related??[]).map(value=>vocabulary(value,value))],protectedInterests:[],governingConstraints:[...seed.limitations],documentedTradeoffs:[]})],calibrationKind:assertion(seed,`canonical:${key}:kind`,vocabulary(seed.role,seed.role)),primarySubsystem:assertion(seed,`canonical:${key}:system`,vocabulary(seed.system,seed.system)),relatedSubsystems:(seed.related??[]).map((value,index)=>assertion(seed,`canonical:${key}:related:${index}`,vocabulary(value,value))),applicability:assertion(seed,`canonical:${key}:applicability`,app),sourceRepresentations:[assertion(seed,`canonical:${key}:source`,{sourceReferenceId:seed.revision,sourceType:vocabulary("xdf_definition","XDF Definition"),sourceIdentifier:seed.revision,displayedName:seed.original,axes:(seed.axes??[]).map(axis=>axis.meaning),conversionMetadata:{...(seed.symbol?{sourceSymbol:seed.symbol}:{}),...(seed.output?{qualifiedOutputMeaning:seed.output}:{})}})],directionalBehaviours:[],relationships:(seed.relationship??[]).map((item,index)=>assertion(seed,`canonical:${key}:relationship:${index}`,{relationshipId:`${stableId}:relationship:${index}`,sourceCalibrationId:stableId,targetKnowledgeId:item.target,kind:vocabulary(item.kind,item.kind),direction:vocabulary("outbound","outbound"),meaning:item.kind})),provenance:[{sourceType:"founder_semantic_review",sourceIdentifier:SOURCE_REVISION,validationMethod:"explicit review decision",validationAuthority:"Founder",validationDate:"2026-09-17"}],lifecycle:{status:"active",version:"1",effectiveAt:PUBLISHED_AT},version:"1"});
};

export type PublishedCalibrationSemantic = Readonly<{ rom:string; relationshipRevision:string; originalTitle:string; knowledge:WorkshopKnowledgeRecord; canonicalKnowledge:ReturnType<typeof defineCalibrationKnowledgeObject>; decision:ReturnType<typeof defineCalibrationKnowledgeAdmissionDecision>; instruction:ReturnType<typeof defineCalibrationKnowledgePublicationInstruction>; receipt:ReturnType<typeof defineCalibrationKnowledgePublicationReceipt> }>;
export const PUBLISHED_CALIBRATION_SEMANTICS: readonly PublishedCalibrationSemantic[] = Object.freeze(seeds.map(seed=>{
 const knowledge=record(seed),canonicalKnowledge=canonicalRecord(seed,knowledge),digests=deriveCalibrationKnowledgeContentDigests(canonicalKnowledge),material={seed,canonicalKnowledge},digest=digests.acceptedKnowledgeDigest, base=`calibration-semantic:${seed.revision.slice(-16)}`, decisionIdentity=identity(`${base}:decision`,material), instructionIdentity=identity(`${base}:instruction`,material), assessmentIdentity=identity(`${base}:assessment`,material), proposalIdentity=identity(`${base}:proposal`,material);
 const decision=defineCalibrationKnowledgeAdmissionDecision({decisionIdentity,proposalIdentity,assessmentIdentity,outcome:"accepted_authoritative",decisionAuthority:{authorityType:"founder",authorityIdentifier:"founder-beau-and-bob"},decidedAt:PUBLISHED_AT,rationale:"Explicit Founder semantic acceptance with preserved limitations.",acceptedFindingIds:[],rejectedFindingIds:[],unresolvedConditions:knowledge.limitations,contractVersion:"tunesight.calibration-semantic-publication.v1",supersededDecisionId:null,lifecycle:{status:"decided",version:"1",effectiveAt:PUBLISHED_AT},publicationInstructionId:instructionIdentity.id});
 const assertionIds=[knowledge.engineeringSystem!,knowledge.calibrationRole!,...knowledge.aliases,...knowledge.controls,...knowledge.operatingContexts,...knowledge.axisMeanings,...(knowledge.outputMeaning?[knowledge.outputMeaning]:[]),...knowledge.relatedCalibrations].map(item=>item.assertionId);
 const changeManifest={addedAssertionIds:assertionIds,amendedAssertionIds:[],retainedAssertionIds:[],supersededAssertionIds:[],removedFromCurrentAssertionIds:[]};
 const instruction=defineCalibrationKnowledgePublicationInstruction({instructionIdentity,acceptedDecisionIdentity:decisionIdentity,operation:"register",targetStableKnowledgeId:knowledge.knowledgeId,expectedPredecessorKnowledgeVersion:null,acceptedKnowledgeDigest:digest,resultingKnowledgeVersion:"1",changeManifest,policy:{policyId:"founder-calibration-semantic-policy",policyVersion:"1",effectiveDate:"2026-09-17",applicableProposalKinds:["register_new"],validationRuleVersions:["exact-definition-binding-v1","exact-rom-applicability-v1"],authorityRuleVersion:"founder-explicit-semantic-authority-v1",publicationRuleVersion:"immutable-calibration-knowledge-v1"},expectedResultingCanonicalDigest:digest,lifecycle:{status:"publication_ready",version:"1",effectiveAt:PUBLISHED_AT}});
 const receipt=defineCalibrationKnowledgePublicationReceipt({receiptIdentity:identity(`${base}:receipt`,material),instructionIdentity,outcome:"published",resultingStableKnowledgeId:knowledge.knowledgeId,resultingKnowledgeVersion:"1",resultingContentDigest:digest,predecessorKnowledgeVersion:null,publishedAt:PUBLISHED_AT,publicationSourceRevision:SOURCE_REVISION,registrySnapshotReference:REGISTRY,failureReason:null,lifecycle:{status:"published",version:"1",effectiveAt:PUBLISHED_AT}});
 return Object.freeze({rom:seed.rom,relationshipRevision:seed.rom==="IJE0S"?n54:b58,originalTitle:seed.original,knowledge,canonicalKnowledge,decision,instruction,receipt});
}));

export const PUBLISHED_CALIBRATION_KNOWLEDGE_REGISTRY = createImmutableCalibrationKnowledgeRegistry(PUBLISHED_CALIBRATION_SEMANTICS.map(item=>item.canonicalKnowledge));

export const HELD_CALIBRATION_SEMANTICS = Object.freeze([{rom:"IJE0S",definitionRevision:"xdf-definition-revision:c5801ec096075ed64bcc6fe656c0ce5ac664e9a974df3dafa1afcbd2e8c0c51c",originalTitle:"Minimum warning pressure (RPM x Oil Temp)",state:"semantic_representation_investigation",reason:"Materialized RPM, oil-temperature and pressure ranges are physically implausible."}]);
export const calibrationKnowledgeForRelationship = (relationshipRevision:string): readonly WorkshopKnowledgeRecord[] => Object.freeze(PUBLISHED_CALIBRATION_SEMANTICS.filter(item=>item.relationshipRevision===relationshipRevision).map(item=>item.knowledge));
