import assert from "node:assert/strict";
import test from "node:test";
import type { ApplicabilityProposal, ApplicabilityEvidenceAssessmentCode, UnresolvedApplicabilityCollection } from "./applicabilityEvidenceProposal.ts";
import type { ApplicabilityAuthorityAssessment, ApplicabilityDecisionOutcome, ApplicabilityDecisionRecord } from "./applicabilityAuthorityDecision.ts";
import { constructApplicabilityPublicationInstruction, createEmptyApplicabilityRegistrySnapshot, lookupActiveApplicability, publishApplicabilityRelationship } from "./applicabilityPublicationRegistry.ts";

const h = (value: string) => value.repeat(64).slice(0, 64);
function proposal(codes: readonly ApplicabilityEvidenceAssessmentCode[] = ["strong_exact_identity_correspondence"], options: { id?: string; set?: string; revision?: string; source?: string; digest?: string; role?: "stock_original" | "mapswitch"; conflicts?: number } = {}): ApplicabilityProposal { const digest = options.digest ?? h("a"); const revision = options.revision ?? `set-revision:${h("2")}`; const source = options.source ?? `xdf-source:${h("3")}`; return { proposalId: options.id ?? `proposal:${h("1")}`, proposalRevision: `proposal-revision:${h("4")}`, contractVersion: "tunesight.xdf-applicability-proposal.v1", definitionSetRevisionId: revision, xdfSourceArtifactId: source, engineeringBinaryDigest: digest, xdfEvidence: { definitionSet: { definitionSetId: options.set ?? "definition-set:n54", revisionId: revision, sourceArtifactId: source, sourceArtifactDigest: `sha256:${h("5")}`, sourceByteLength: 1, definitionRevisionIds: [], definitionSourceBindingDigests: [], definitionCount: 1 }, sourceArtifact: { artifactId: source, sourceDigest: `sha256:${h("5")}`, byteLength: 1, format: "xdf-xml", observedVersion: "1.60", filename: "fixture.xdf", provenance: "controlled fixture", sourceRevision: null, qualificationState: "source_discovered" }, sourcePath: null, filename: null, explicitHeaderIdentities: ["IJE0S"], duplicateSourceDefinitionSetRevisionIds: [], familyAssociation: "N54", definitionCount: 1, conflictingDefinitionCount: options.conflicts ?? 0, provenance: ["controlled source provenance"], missingProvenance: [] }, binaryEvidence: { binaryDigest: digest, byteLength: 1, containerType: "bin", containerProvenance: ["exact BIN"], sourceFilename: null, internalIdentityObservations: [], romFamilyObservations: ["IJE0S"], softwareCalibrationObservations: ["IJE0S"], stockVariantKnowledge: null, provisionalSourceRole: options.role ?? "stock_original", candidateRelationshipProvenance: ["controlled relationship"], findings: [] }, assessment: { codes, admissionReady: false, authorityDecision: "required", explanation: [] }, unresolvedConditions: [], conflictFindings: [], authorityDecision: "pending" }; }
function assessment(value: ApplicabilityProposal, outcome: ApplicabilityAuthorityAssessment["outcome"] = "reviewable_for_exact_applicability"): ApplicabilityAuthorityAssessment { return { assessmentId: `assessment:${h("6")}`, assessmentRevision: `assessment-revision:${h("7")}`, contractVersion: "tunesight.xdf-applicability-authority-assessment.v1", proposalId: value.proposalId, proposalRevision: value.proposalRevision, outcome, requirements: [], availableAuthorityPathways: ["governed_evidence_review"], reviewableForDecision: true, exactAcceptanceEligible: outcome === "reviewable_for_exact_applicability", unresolvedRequirements: [], conflictFindings: outcome.includes("conflict") ? ["conflict"] : [] }; }
function decision(value: ApplicabilityProposal, assessed: ApplicabilityAuthorityAssessment, outcome: ApplicabilityDecisionOutcome = "accept_exact_applicability"): ApplicabilityDecisionRecord { return { decisionId: `decision:${h("8")}`, decisionRevision: `decision-revision:${h("9")}`, contractVersion: "tunesight.xdf-applicability-decision.v1", proposalId: value.proposalId, proposalRevision: value.proposalRevision, assessmentId: assessed.assessmentId, assessmentRevision: assessed.assessmentRevision, outcome, authority: { authorityId: "authority:fixture", authorityClass: "governed_engineering_authority", authorityRevision: "1", provenance: ["controlled authority provenance"], permittedOutcomes: [outcome], acceptedPathways: ["governed_evidence_review"] }, rationale: "Controlled fixture decision", acceptedEvidenceReferences: [], rejectedOrOverriddenEvidenceReferences: [], unresolvedConditions: [], decidedAt: "2026-08-23T01:00:00.000Z", supersededDecision: null, publicationState: "not_published" }; }
function instruction(value: ApplicabilityProposal, snapshotId: string, options: { outcome?: ApplicabilityDecisionOutcome; assessmentOutcome?: ApplicabilityAuthorityAssessment["outcome"]; supersedes?: string | null; decisionSupersededBy?: ApplicabilityDecisionRecord | null } = {}) { const assessed = assessment(value, options.assessmentOutcome); const decided = decision(value, assessed, options.outcome); return constructApplicabilityPublicationInstruction({ proposal: value, assessment: assessed, decision: decided, decisionSupersededBy: options.decisionSupersededBy ?? null, expectedRegistrySnapshotId: snapshotId, supersedesRelationshipRevision: options.supersedes ?? null, createdAt: "2026-08-23T02:00:00.000Z" }); }

test("accepted exact decision deterministically creates an immutable exact publication instruction", () => { const snapshot = createEmptyApplicabilityRegistrySnapshot("2026-08-23T00:00:00.000Z"); const value = proposal(); const first = instruction(value, snapshot.snapshotId); assert.deepEqual(first, instruction(value, snapshot.snapshotId)); assert.ok(Object.isFrozen(first)); assert.equal(first.binaryDigest, value.engineeringBinaryDigest); assert.equal(first.definitionSetRevisionId, value.definitionSetRevisionId); });

test("nonaccepting, stale, conflicting, wrong-identity and provenance-deficient inputs fail closed", () => { const snapshot = createEmptyApplicabilityRegistrySnapshot("2026-08-23T00:00:00.000Z"); for (const outcome of ["deferred", "more_evidence_required", "reject_inapplicable", "conflict"] as const) assert.throws(() => instruction(proposal(), snapshot.snapshotId, { outcome }), /cannot publish/); const value = proposal(); const assessed = assessment(value); const accepted = decision(value, assessed); assert.throws(() => constructApplicabilityPublicationInstruction({ proposal: { ...value, proposalRevision: "stale" }, assessment: assessed, decision: accepted, decisionSupersededBy: null, expectedRegistrySnapshotId: snapshot.snapshotId, createdAt: "2026-08-23T02:00:00.000Z" }), /Proposal Revision/); assert.throws(() => constructApplicabilityPublicationInstruction({ proposal: value, assessment: { ...assessed, assessmentRevision: "stale" }, decision: accepted, decisionSupersededBy: null, expectedRegistrySnapshotId: snapshot.snapshotId, createdAt: "2026-08-23T02:00:00.000Z" }), /Assessment Revision/); assert.throws(() => constructApplicabilityPublicationInstruction({ proposal: { ...value, binaryEvidence: { ...value.binaryEvidence, binaryDigest: h("b") } }, assessment: assessed, decision: accepted, decisionSupersededBy: null, expectedRegistrySnapshotId: snapshot.snapshotId, createdAt: "2026-08-23T02:00:00.000Z" }), /Binary digest/); assert.throws(() => instruction(proposal(["direct_conflict"]), snapshot.snapshotId), /conflict/); assert.throws(() => constructApplicabilityPublicationInstruction({ proposal: value, assessment: assessed, decision: { ...accepted, authority: { ...accepted.authority, provenance: [] } }, decisionSupersededBy: null, expectedRegistrySnapshotId: snapshot.snapshotId, createdAt: "2026-08-23T02:00:00.000Z" }), /Authority provenance/); assert.throws(() => constructApplicabilityPublicationInstruction({ proposal: value, assessment: assessed, decision: accepted, decisionSupersededBy: accepted, expectedRegistrySnapshotId: snapshot.snapshotId, createdAt: "2026-08-23T02:00:00.000Z" }), /superseded/); });

test("successful publication is atomic, immutable, receipted and exactly queryable", () => { const prior = createEmptyApplicabilityRegistrySnapshot("2026-08-23T00:00:00.000Z"); const value = proposal(); const result = publishApplicabilityRelationship({ instruction: instruction(value, prior.snapshotId), snapshot: prior, publishedAt: "2026-08-23T03:00:00.000Z" }); assert.equal(result.status, "published"); if (result.status !== "published") return; assert.equal(prior.relationships.length, 0); assert.equal(result.resultingSnapshot.relationships.length, 1); assert.equal(result.receipt.priorSnapshotId, prior.snapshotId); assert.equal(result.receipt.resultingSnapshotId, result.resultingSnapshot.snapshotId); assert.equal(lookupActiveApplicability(result.resultingSnapshot, value.engineeringBinaryDigest).outcome, "exact_active"); assert.equal(lookupActiveApplicability(result.resultingSnapshot, h("f")).outcome, "none"); assert.equal(lookupActiveApplicability(result.resultingSnapshot, "invalid").outcome, "invalid"); assert.ok(Object.isFrozen(result.resultingSnapshot)); });

test("failed stale write is atomic and leaves the exact prior snapshot unchanged", () => { const prior = createEmptyApplicabilityRegistrySnapshot("2026-08-23T00:00:00.000Z"); const result = publishApplicabilityRelationship({ instruction: instruction(proposal(), "stale-snapshot"), snapshot: prior, publishedAt: "2026-08-23T03:00:00.000Z" }); assert.equal(result.status, "rejected"); assert.deepEqual(result.resultingSnapshot, prior); assert.equal(prior.relationships.length, 0); });

test("replay is deterministic and creates no duplicate relationship", () => { const prior = createEmptyApplicabilityRegistrySnapshot("2026-08-23T00:00:00.000Z"); const issued = instruction(proposal(), prior.snapshotId); const first = publishApplicabilityRelationship({ instruction: issued, snapshot: prior, publishedAt: "2026-08-23T03:00:00.000Z" }); assert.equal(first.status, "published"); if (first.status !== "published") return; const replay = publishApplicabilityRelationship({ instruction: issued, snapshot: first.resultingSnapshot, publishedAt: "2026-08-23T03:00:00.000Z" }); assert.equal(replay.status, "idempotent_replay"); assert.equal(replay.resultingSnapshot.relationships.length, 1); });

test("supersession preserves historical relationship and activates the corrected revision", () => { const empty = createEmptyApplicabilityRegistrySnapshot("2026-08-23T00:00:00.000Z"); const original = proposal(); const first = publishApplicabilityRelationship({ instruction: instruction(original, empty.snapshotId), snapshot: empty, publishedAt: "2026-08-23T03:00:00.000Z" }); assert.equal(first.status, "published"); if (first.status !== "published") return; const corrected = proposal([], { revision: `set-revision:${h("c")}` }); const secondInstruction = instruction(corrected, first.resultingSnapshot.snapshotId, { supersedes: first.relationship.relationshipRevision }); const second = publishApplicabilityRelationship({ instruction: secondInstruction, snapshot: first.resultingSnapshot, publishedAt: "2026-08-24T03:00:00.000Z" }); assert.equal(second.status, "published"); if (second.status !== "published") return; assert.equal(second.resultingSnapshot.relationships.length, 2); assert.equal(second.resultingSnapshot.relationships.filter((item) => item.lifecycleState === "superseded").length, 1); assert.equal(second.resultingSnapshot.relationships.filter((item) => item.lifecycleState === "active").length, 1); });

test("duplicate source, original and MapSwitch relationships remain independent", () => { let snapshot = createEmptyApplicabilityRegistrySnapshot("2026-08-23T00:00:00.000Z"); const shared = `xdf-source:${h("d")}`; for (const value of [proposal([], { id: `proposal:${h("a")}`, set: "set:a", source: shared, digest: h("a"), role: "stock_original" }), proposal([], { id: `proposal:${h("b")}`, set: "set:b", source: shared, digest: h("b"), role: "mapswitch" })]) { const result = publishApplicabilityRelationship({ instruction: instruction(value, snapshot.snapshotId), snapshot, publishedAt: value.binaryEvidence.provisionalSourceRole === "stock_original" ? "2026-08-23T03:00:00.000Z" : "2026-08-23T04:00:00.000Z" }); assert.equal(result.status, "published"); if (result.status === "published") snapshot = result.resultingSnapshot; } assert.equal(snapshot.relationships.length, 2); assert.equal(snapshot.relationships[0].xdfSourceArtifactId, snapshot.relationships[1].xdfSourceArtifactId); assert.notEqual(snapshot.relationships[0].binaryDigest, snapshot.relationships[1].binaryDigest); assert.deepEqual(new Set(snapshot.relationships.map((item) => item.binaryRole)), new Set(["stock_original", "mapswitch"])); });

test("B58 ambiguity, unpaired sets and 133 conflicts retain truthful boundaries", () => { const snapshot = createEmptyApplicabilityRegistrySnapshot("2026-08-23T00:00:00.000Z"); assert.throws(() => instruction(proposal(["strong_exact_identity_correspondence", "identity_ambiguity", "source_provenance_missing"]), snapshot.snapshotId, { assessmentOutcome: "source_authority_unresolved" }), /Assessment|eligible/); const unresolved: UnresolvedApplicabilityCollection = { outcome: "no_responsible_candidate_binary", definitionSetRevisionId: "set:missing", xdfSourceArtifactId: "source:missing", missingInput: "engineering_binary", authorityDecision: "pending" }; assert.equal(unresolved.outcome, "no_responsible_candidate_binary"); const conflicted = proposal([], { conflicts: 133 }); const result = publishApplicabilityRelationship({ instruction: instruction(conflicted, snapshot.snapshotId), snapshot, publishedAt: "2026-08-23T03:00:00.000Z" }); assert.equal(result.status, "published"); assert.equal(conflicted.xdfEvidence.conflictingDefinitionCount, 133); });
