import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import type { RuntimeStockVariantKnowledgeResponse } from "../knowledge/runtimeStockVariantKnowledge.ts";
import { resolveBinaryContainer } from "../tunes/binaryContainer.ts";
import { defineDefinitionSetRevision } from "./definitionRomApplicability.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import { assessApplicabilityProposalEvidence, buildApplicabilityProposalCoverageReport, collectEngineeringBinaryEvidence, collectInternalIdentityObservations, collectXdfApplicabilityEvidence, constructApplicabilityProposal, unresolvedCandidateBinary } from "./applicabilityEvidenceProposal.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "BMW-XDFs-master");
function parse(relative: string) { const full = path.join(root, relative); const parsed = interpretXdfStructure({ xml: fs.readFileSync(full, "utf8"), filename: path.basename(full), provenance: `BMW master source ${relative}` }); assert.equal(parsed.outcome, "structurally_interpreted"); assert.ok(parsed.sourceArtifact); return { full, relative, parsed, source: parsed.sourceArtifact!, set: defineDefinitionSetRevision({ sourceArtifact: parsed.sourceArtifact!, definitions: parsed.definitions }) }; }
function resolved(bytes: Uint8Array, fileName = "fixture.bin") { const result = resolveBinaryContainer({ bytes, fileName }); assert.equal(result.status, "resolved"); return result.engineeringBinary!; }
function stock(status: "exact_candidate" | "family_only" | "conflict"): RuntimeStockVariantKnowledgeResponse { return { availability: "available", unavailableReason: null, result: { status, explanation: `${status} fixture Evidence` } as RuntimeStockVariantKnowledgeResponse & never }; }
function packages(relativeXdf: string, relativeBin: string, claimed: string, stockVariantKnowledge: RuntimeStockVariantKnowledgeResponse | null = null) { const xdf = parse(relativeXdf); const bytes = fs.readFileSync(path.join(root, relativeBin)); const engineeringBinary = resolved(bytes, path.basename(relativeBin)); const observations = collectInternalIdentityObservations({ binaryBytes: bytes, credibleIdentifiers: [{ identifier: claimed, kind: /^\d/.test(claimed) ? "calibration_identifier" : "ascii_rom_marker", confidence: "candidate_correspondence", reason: "Candidate relationship identifier", encodings: ["ascii", "hex_encoded"] }, { identifier: "00003076501103", kind: "family_marker", confidence: "known_identity", reason: "Known MG1 internal marker", encodings: ["ascii", "hex_encoded"] }] }); const xdfEvidence = collectXdfApplicabilityEvidence({ definitionSet: xdf.set, sourceArtifact: xdf.source, sourcePath: relativeXdf, filename: path.basename(relativeXdf), familyAssociation: relativeXdf.split("/")[0], definitionCount: xdf.parsed.definitions.length, conflictingDefinitionCount: xdf.parsed.definitions.filter((item) => item.identity.status === "conflicting").length, provenance: [xdf.source.provenance], missingProvenance: ["authoritative source chain"] }); const role = /mapswitch/i.test(relativeBin) ? "mapswitch" as const : /original/i.test(relativeBin) ? "stock_original" as const : "other_observed" as const; const binaryEvidence = collectEngineeringBinaryEvidence({ engineeringBinary, containerProvenance: engineeringBinary.source.resolutionEvidence, sourceFilename: path.basename(relativeBin), internalIdentityObservations: observations, romFamilyObservations: [], softwareCalibrationObservations: observations.map((item) => item.normalizedForm), stockVariantKnowledge, provisionalSourceRole: role, candidateRelationshipProvenance: ["deterministic repository co-location"], findings: [] }); const assessment = assessApplicabilityProposalEvidence({ claimedIdentifiers: [claimed], binaryEvidence, xdfEvidence }); return { xdf, binaryEvidence, xdfEvidence, assessment, proposal: constructApplicabilityProposal({ xdfEvidence, binaryEvidence, assessment, unresolvedConditions: ["Authority decision required"] }) }; }

test("bounded identity collection preserves every credible marker, encoding, offset and duplicate occurrence without selecting one", () => { const bytes = Buffer.concat([Buffer.from("noise IJE0S IJE0S 00003076501103 "), Buffer.from("00003076501103", "hex"), Buffer.from(" ARBITRARY_PRINTABLE")]); const collect = () => collectInternalIdentityObservations({ binaryBytes: bytes, credibleIdentifiers: [{ identifier: "IJE0S", kind: "ascii_rom_marker", confidence: "candidate_correspondence", reason: "Definition candidate", encodings: ["ascii"] }, { identifier: "00003076501103", kind: "calibration_identifier", confidence: "known_identity", reason: "Known numeric identity", encodings: ["ascii", "hex_encoded"] }] }); const observations = collect(); assert.deepEqual(observations, collect()); assert.equal(observations.length, 3); assert.equal(observations.find((item) => item.normalizedForm === "IJE0S")?.occurrenceCount, 2); assert.ok(observations.every((item) => item.offsets.length === item.occurrenceCount && item.ambiguity === "multiple_credible_identities")); assert.ok(!observations.some((item) => item.normalizedForm.includes("ARBITRARY"))); assert.ok(Object.isFrozen(observations) && Object.isFrozen(observations[0].offsets)); });

test("proposal binds exact XDF revision and binary digest, is immutable and revisions only change with material Evidence", () => { const first = packages("N54/IJE0S.xdf", "N54/IJE0S_original.bin", "IJE0S", stock("exact_candidate")); const again = packages("N54/IJE0S.xdf", "N54/IJE0S_original.bin", "IJE0S", stock("exact_candidate")); assert.deepEqual(first.proposal, again.proposal); assert.ok(first.assessment.codes.includes("strong_exact_identity_correspondence")); assert.equal(first.proposal.authorityDecision, "pending"); assert.ok(Object.isFrozen(first.proposal) && Object.isFrozen(first.proposal.binaryEvidence)); const presentationOnly = constructApplicabilityProposal({ xdfEvidence: { ...first.xdfEvidence, sourcePath: "renamed/presentation/path.xdf", filename: "renamed.xdf" }, binaryEvidence: { ...first.binaryEvidence, sourceFilename: "renamed.bin" }, assessment: first.assessment, unresolvedConditions: ["Authority decision required"] }); assert.equal(presentationOnly.proposalId, first.proposal.proposalId); assert.equal(presentationOnly.proposalRevision, first.proposal.proposalRevision); const changed = constructApplicabilityProposal({ xdfEvidence: first.xdfEvidence, binaryEvidence: { ...first.binaryEvidence, findings: ["material new Evidence"] }, assessment: first.assessment }); assert.equal(changed.proposalId, first.proposal.proposalId); assert.notEqual(changed.proposalRevision, first.proposal.proposalRevision); });

test("Stock Variant outcomes and original/MapSwitch roles remain Evidence, never authority", () => { for (const status of ["exact_candidate", "family_only", "conflict"] as const) { const item = packages("N54/IJE0S.xdf", "N54/IJE0S_original.bin", "IJE0S", stock(status)); assert.equal(item.binaryEvidence.stockVariantKnowledge?.availability, "available"); assert.equal(item.proposal.authorityDecision, "pending"); if (status === "conflict") assert.ok(item.assessment.codes.includes("stock_variant_conflict")); } const original = packages("N54/IJE0S.xdf", "N54/IJE0S_original.bin", "IJE0S"); const mapSwitch = packages("N54/IJE0S_Legacy.xdf", "N54/IJE0S_MapSwitchBase.bin", "IJE0S"); assert.equal(original.binaryEvidence.provisionalSourceRole, "stock_original"); assert.equal(mapSwitch.binaryEvidence.provisionalSourceRole, "mapswitch"); assert.notEqual(original.binaryEvidence.binaryDigest, mapSwitch.binaryEvidence.binaryDigest); });

test("N54 wrong-ROM direct contradiction and missing provenance remain explicit blockers", () => { const right = packages("N54/IJE0S.xdf", "N54/INA0S_original.bin", "INA0S"); const assessment = assessApplicabilityProposalEvidence({ claimedIdentifiers: ["IJE0S"], binaryEvidence: right.binaryEvidence, xdfEvidence: right.xdfEvidence }); assert.ok(assessment.codes.includes("direct_conflict")); assert.ok(assessment.codes.includes("source_provenance_missing")); assert.equal(assessment.admissionReady, false); });

test("real B58 Gen1/Gen2 preserve candidate-specific and alternative MG1 observations", () => { for (const [xdf, bin, marker] of [["B58gen1/00003076501103.xdf", "B58gen1/00003076501103_original.bin", "00003076501103"], ["B58gen2/00005D5532C808/00005D5532C808.xdf", "B58gen2/00005D5532C808/00005D5532C808_original.bin", "00005D5532C808"]] as const) { const item = packages(xdf, bin, marker, stock("conflict")); assert.ok(item.binaryEvidence.internalIdentityObservations.some((observation) => observation.normalizedForm === marker)); assert.ok(item.assessment.codes.includes("stock_variant_conflict")); assert.equal(item.proposal.authorityDecision, "pending"); } });

test("generic proposal construction covers additional BMW families", () => { const fixtures = [["F series N55 S55 N13/00005BA8134601.xdf", "F series N55 S55 N13/00005BA8134601_original.bin", "00005BA8134601"], ["N55E/98G0B.xdf", "N55E/98G0B_original.bin", "98G0B"], ["s58/00005C640A6405/00005C640A6405.xdf", "s58/00005C640A6405/00005C640A6405_original.bin", "00005C640A6405"], ["S63/00004ACF0A3204/00004ACF0A3204.xdf", "S63/00004ACF0A3204/00004ACF0A3204_original.bin", "00004ACF0A3204"]] as const; for (const fixture of fixtures) assert.equal(packages(fixture[0], fixture[1], fixture[2]).proposal.authorityDecision, "pending"); });

test("complete BMW programme deterministically reports 99 sets, 212 exact relationships, duplicate sources, and four unresolved sets", () => { const xdfs: string[] = []; const walk = (directory: string) => fs.readdirSync(directory, { withFileTypes: true }).forEach((entry) => { const full = path.join(directory, entry.name); if (entry.isDirectory()) walk(full); else if (entry.name.toLowerCase().endsWith(".xdf")) xdfs.push(full); }); walk(root); const parsed = xdfs.sort().map((full) => { const relative = path.relative(root, full); const fixture = parse(relative); return { full, relative, fixture }; }); const digestGroups = new Map<string, number>(); for (const item of parsed) digestGroups.set(item.fixture.source.sourceDigest, (digestGroups.get(item.fixture.source.sourceDigest) ?? 0) + 1); const inspected = parsed.map(({ full, relative, fixture }) => { const stem = path.basename(full, path.extname(full)).replace(/_Legacy$/i, ""); const bins = fs.readdirSync(path.dirname(full), { withFileTypes: true }).filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith(".bin") && path.basename(entry.name, path.extname(entry.name)).toLowerCase().startsWith(stem.toLowerCase())); if (!bins.length) { const unresolved = unresolvedCandidateBinary(fixture.set, fixture.source); assert.equal(unresolved.outcome, "no_responsible_candidate_binary"); } return { family: relative.split(path.sep)[0], proposalCount: bins.length, paired: bins.length > 0, codes: bins.length ? ["source_provenance_missing" as const] : [], duplicateRelationships: (digestGroups.get(fixture.source.sourceDigest) ?? 1) > 1 ? bins.length : 0 }; }); const report = buildApplicabilityProposalCoverageReport({ inspected }); assert.deepEqual(report, buildApplicabilityProposalCoverageReport({ inspected })); console.log(`BMW_APPLICABILITY_PROPOSAL_COVERAGE ${JSON.stringify(report)}`); assert.equal(report.definitionSetsInspected, 99); assert.equal(report.pairedDefinitionSets, 95); assert.equal(report.unpairedDefinitionSets, 4); assert.equal(report.binaryRelationshipsProcessed, 212); assert.equal(report.proposalsGenerated, 212); assert.equal(report.unresolved, 4); assert.equal([...digestGroups.values()].filter((count) => count > 1).length, 5); assert.equal([...digestGroups.values()].filter((count) => count > 1).reduce((a, b) => a + b, 0), 12); });
