import assert from "node:assert/strict";
import test from "node:test";
import type { ApplicabilityProposal, ApplicabilityEvidenceAssessmentCode, UnresolvedApplicabilityCollection } from "./applicabilityEvidenceProposal.ts";
import { assessApplicabilityAuthority, constructApplicabilityDecisionRecord, type ApplicabilityAuthorityAssessment, type ApplicabilityDecisionAuthority, type ApplicabilityDecisionOutcome } from "./applicabilityAuthorityDecision.ts";

const hex = (value: string) => value.repeat(64).slice(0, 64);
function proposal(codes: readonly ApplicabilityEvidenceAssessmentCode[] = ["strong_exact_identity_correspondence"], options: { marker?: string; digest?: string; role?: "stock_original" | "mapswitch"; explicitXdf?: boolean; duplicate?: readonly string[]; conflicts?: number; proposalId?: string } = {}): ApplicabilityProposal { const marker = options.marker ?? "IJE0S"; const digest = options.digest ?? hex("a"); return Object.freeze({ proposalId: options.proposalId ?? `xdf-applicability-proposal:${hex("1")}`, proposalRevision: `xdf-applicability-proposal-revision:${hex("2")}`, contractVersion: "tunesight.xdf-applicability-proposal.v1", definitionSetRevisionId: `xdf-definition-set-revision:${hex("3")}`, xdfSourceArtifactId: `xdf-source:${hex("4")}`, engineeringBinaryDigest: digest, xdfEvidence: { definitionSet: { definitionSetId: "set", revisionId: `xdf-definition-set-revision:${hex("3")}`, sourceArtifactId: `xdf-source:${hex("4")}`, sourceArtifactDigest: "sha256:x", sourceByteLength: 1, definitionRevisionIds: [], definitionSourceBindingDigests: [], definitionCount: 1 }, sourceArtifact: { artifactId: `xdf-source:${hex("4")}`, sourceDigest: "sha256:x", byteLength: 1, format: "xdf-xml", observedVersion: "1.60", filename: "fixture.xdf", provenance: "fixture", sourceRevision: null, qualificationState: "source_discovered" }, sourcePath: "N54/fixture.xdf", filename: "fixture.xdf", explicitHeaderIdentities: options.explicitXdf === false ? [] : [marker], duplicateSourceDefinitionSetRevisionIds: options.duplicate ?? [], familyAssociation: "N54", definitionCount: 1, conflictingDefinitionCount: options.conflicts ?? 0, provenance: ["controlled fixture"], missingProvenance: codes.includes("source_provenance_missing") ? ["accepted authority"] : [] }, binaryEvidence: { binaryDigest: digest, byteLength: 1, containerType: "bin", containerProvenance: ["exact BIN"], sourceFilename: "fixture.bin", internalIdentityObservations: [{ observationId: `observation:${marker}`, kind: "ascii_rom_marker", rawForm: marker, normalizedForm: marker, offsets: [0], occurrenceCount: 1, detector: "bounded_ascii_exact", confidence: "candidate_correspondence", credibilityReason: "fixture", ambiguity: codes.includes("identity_ambiguity") ? "multiple_credible_identities" : "none", binaryDigest: digest }], romFamilyObservations: [marker], softwareCalibrationObservations: [marker], stockVariantKnowledge: null, provisionalSourceRole: options.role ?? "stock_original", candidateRelationshipProvenance: ["controlled relationship"], findings: [] }, assessment: { codes, admissionReady: false, authorityDecision: "required", explanation: [] }, unresolvedConditions: [], conflictFindings: [], authorityDecision: "pending" } as ApplicabilityProposal); }
const pathways = ["governed_evidence_review" as const];
const authority: ApplicabilityDecisionAuthority = Object.freeze({ authorityId: "authority:tunesight-engineering", authorityClass: "governed_engineering_authority", authorityRevision: "1", provenance: ["controlled authority fixture"], permittedOutcomes: ["accept_exact_applicability", "reject_inapplicable", "conflict", "more_evidence_required", "deferred"] as readonly ApplicabilityDecisionOutcome[], acceptedPathways: pathways });
function assessment(value = proposal(), accepted = pathways) { return assessApplicabilityAuthority({ proposal: value, acceptedAuthorityPathways: accepted, duplicateSourceContextUnderstood: true }); }
function decide(value: ApplicabilityProposal, assessed: ApplicabilityAuthorityAssessment, outcome: ApplicabilityDecisionOutcome, extra: Partial<Parameters<typeof constructApplicabilityDecisionRecord>[0]> = {}) { return constructApplicabilityDecisionRecord({ proposal: value, assessment: assessed, outcome, authority, rationale: `Explicit ${outcome} rationale`, acceptedEvidenceReferences: ["evidence:1"], rejectedOrOverriddenEvidenceReferences: [], unresolvedConditions: outcome === "more_evidence_required" ? ["Additional source Evidence required."] : [], decidedAt: "2026-08-23T01:02:03.000Z", ...extra }); }

test("authority assessment is deterministic, immutable, exact-revision-bound and requirement-explicit", () => { const value = proposal(); const first = assessment(value); assert.deepEqual(first, assessment(value)); assert.equal(first.outcome, "reviewable_for_exact_applicability"); assert.equal(first.exactAcceptanceEligible, true); assert.ok(first.requirements.some((item) => item.state === "satisfied")); assert.ok(first.requirements.some((item) => item.state === "not_applicable")); assert.ok(Object.isFrozen(first) && Object.isFrozen(first.requirements)); assert.notEqual(first.assessmentRevision, assessment(proposal(["strong_exact_identity_correspondence"], { role: "mapswitch" })).assessmentRevision); });

test("assessment distinguishes missing Evidence, technical conflict, source authority, Stock conflict, no candidate and invalid", () => { assert.equal(assessment(proposal(["identity_ambiguity"])).outcome, "more_evidence_required"); assert.equal(assessment(proposal(["strong_exact_identity_correspondence", "direct_conflict"])).outcome, "technical_conflict"); assert.equal(assessment(proposal(["strong_exact_identity_correspondence", "source_provenance_missing"])).outcome, "source_authority_unresolved"); assert.equal(assessment(proposal(["strong_exact_identity_correspondence", "stock_variant_conflict"])).outcome, "stock_variant_conflict"); const unresolved: UnresolvedApplicabilityCollection = { outcome: "no_responsible_candidate_binary", definitionSetRevisionId: "set:1", xdfSourceArtifactId: "xdf:1", missingInput: "engineering_binary", authorityDecision: "pending" }; assert.equal(assessApplicabilityAuthority({ proposal: null, unresolvedCandidate: unresolved }).outcome, "no_responsible_candidate"); assert.equal(assessApplicabilityAuthority({ proposal: null }).outcome, "invalid"); });

test("proposal existence, exact_candidate semantics and missing provenance can never auto-accept", () => { const value = proposal(["strong_exact_identity_correspondence", "source_provenance_missing"]); const assessed = assessment(value); assert.equal(value.authorityDecision, "pending"); assert.equal(assessed.exactAcceptanceEligible, false); assert.throws(() => decide(value, assessed, "accept_exact_applicability"), /reviewable and eligible/); });

test("explicit authorised accept, reject, more-Evidence, defer and conflict decisions remain distinct", () => { const clean = proposal(); const ready = assessment(clean); for (const outcome of ["accept_exact_applicability", "reject_inapplicable", "deferred"] as const) { const record = decide(clean, ready, outcome); assert.equal(record.outcome, outcome); assert.equal(record.publicationState, "not_published"); assert.equal(record.authority.authorityId, authority.authorityId); assert.match(record.rationale, /Explicit/); } const missing = proposal(["identity_ambiguity"]); assert.equal(decide(missing, assessment(missing), "more_evidence_required").outcome, "more_evidence_required"); const conflicted = proposal(["strong_exact_identity_correspondence", "direct_conflict"]); assert.equal(decide(conflicted, assessment(conflicted), "conflict").outcome, "conflict"); });

test("wrong-ROM and Stock Variant conflict structurally prohibit exact acceptance", () => { for (const codes of [["direct_conflict"], ["strong_exact_identity_correspondence", "stock_variant_conflict"]] as ApplicabilityEvidenceAssessmentCode[][]) { const value = proposal(codes); const assessed = assessment(value); assert.throws(() => decide(value, assessed, "accept_exact_applicability"), /reviewable and eligible|prohibited/); } });

test("Decision Record is deterministic and material decision, rationale, authority or proposal changes revise identity", () => { const value = proposal(); const assessed = assessment(value); const first = decide(value, assessed, "accept_exact_applicability"); assert.deepEqual(first, decide(value, assessed, "accept_exact_applicability")); assert.ok(Object.isFrozen(first) && Object.isFrozen(first.authority)); assert.notEqual(first.decisionRevision, decide(value, assessed, "deferred").decisionRevision); assert.notEqual(first.decisionRevision, decide(value, assessed, "accept_exact_applicability", { rationale: "Different material rationale" }).decisionRevision); const otherAuthority = { ...authority, authorityRevision: "2" }; assert.notEqual(first.decisionRevision, decide(value, assessed, "accept_exact_applicability", { authority: otherAuthority }).decisionRevision); const otherProposal = proposal(["strong_exact_identity_correspondence"], { proposalId: `xdf-applicability-proposal:${hex("9")}` }); assert.notEqual(first.decisionId, decide(otherProposal, assessment(otherProposal), "accept_exact_applicability").decisionId); });

test("supersession preserves stable lineage and leaves the previous decision immutable", () => { const value = proposal(); const assessed = assessment(value); const first = decide(value, assessed, "deferred"); const second = decide(value, assessed, "accept_exact_applicability", { supersededDecision: first, decidedAt: "2026-08-24T01:02:03.000Z", rationale: "Later explicit authority decision" }); assert.equal(second.decisionId, first.decisionId); assert.notEqual(second.decisionRevision, first.decisionRevision); assert.deepEqual(second.supersededDecision, { decisionId: first.decisionId, decisionRevision: first.decisionRevision }); assert.equal(first.outcome, "deferred"); assert.ok(Object.isFrozen(first)); });

test("N54 current/Legacy and original/MapSwitch relationships remain independently decidable", () => { const current = proposal([], { marker: "IJE0S", digest: hex("a"), role: "stock_original", proposalId: `xdf-applicability-proposal:${hex("1")}` }); const legacyMap = proposal([], { marker: "IJE0S", digest: hex("b"), role: "mapswitch", proposalId: `xdf-applicability-proposal:${hex("2")}` }); assert.notEqual(current.proposalId, legacyMap.proposalId); assert.notEqual(current.engineeringBinaryDigest, legacyMap.engineeringBinaryDigest); assert.equal(decide(proposal(), assessment(proposal()), "reject_inapplicable").publicationState, "not_published"); });

test("B58 ambiguity and combined N55/S55/N13 platform conflict refuse false exact acceptance", () => { const b58 = proposal(["strong_exact_identity_correspondence", "identity_ambiguity", "source_provenance_missing"]); assert.equal(assessment(b58).outcome, "source_authority_unresolved"); const combined = proposal(["strong_exact_identity_correspondence", "stock_variant_conflict"]); assert.equal(assessment(combined).outcome, "stock_variant_conflict"); assert.throws(() => decide(combined, assessment(combined), "accept_exact_applicability")); });

test("duplicate XDF bytes do not transfer a decision between exact binary relationships", () => { const duplicates = ["set:rom-a", "set:rom-b"]; const romA = proposal([], { digest: hex("a"), duplicate: duplicates, proposalId: `xdf-applicability-proposal:${hex("a")}` }); const romB = proposal([], { digest: hex("b"), duplicate: duplicates, proposalId: `xdf-applicability-proposal:${hex("b")}` }); const decisionA = decide(romA, assessment(romA), "deferred"); assert.notEqual(decisionA.proposalId, romB.proposalId); assert.throws(() => constructApplicabilityDecisionRecord({ proposal: romB, assessment: assessment(romA), outcome: "deferred", authority, rationale: "wrong binding", decidedAt: "2026-08-23T01:02:03.000Z" }), /exact assessed/); });

test("133 contained Definition conflicts stay disclosed and do not become representation authority", () => { const value = proposal([], { conflicts: 133 }); const assessed = assessment(value); assert.equal(value.xdfEvidence.conflictingDefinitionCount, 133); assert.ok(assessed.requirements.some((item) => item.requirementId === "definition_conflicts_disclosed" && item.state === "satisfied")); assert.equal(decide(value, assessed, "deferred").publicationState, "not_published"); });
