import { createHash } from "node:crypto";
import type { RuntimeStockVariantKnowledgeResponse } from "../knowledge/runtimeStockVariantKnowledge.ts";
import type { EngineeringBinary } from "../tunes/binaryContainer.ts";
import type { DefinitionSetRevision } from "./definitionRomApplicability.ts";
import type { XdfSourceArtifact } from "./canonicalXdfDefinition.ts";

export const APPLICABILITY_PROPOSAL_LIMITS = Object.freeze({ maximumBinaryBytes: 32 * 1024 * 1024, maximumCredibleIdentifiers: 512, maximumObservations: 512, maximumRelationships: 100_000 });

export type InternalIdentityObservationKind = "ascii_rom_marker" | "encoded_numeric_marker" | "software_identifier" | "calibration_identifier" | "family_marker" | "unknown_pattern_valid";
export type InternalIdentityObservation = Readonly<{ observationId: string; kind: InternalIdentityObservationKind; rawForm: string; normalizedForm: string; offsets: readonly number[]; occurrenceCount: number; detector: "bounded_ascii_exact" | "bounded_hex_encoded_exact"; confidence: "candidate_correspondence" | "known_identity" | "pattern_valid"; credibilityReason: string; ambiguity: "none" | "multiple_credible_identities"; binaryDigest: string }>;
export type XdfApplicabilityEvidencePackage = Readonly<{ definitionSet: DefinitionSetRevision; sourceArtifact: XdfSourceArtifact; sourcePath: string | null; filename: string | null; explicitHeaderIdentities: readonly string[]; duplicateSourceDefinitionSetRevisionIds: readonly string[]; familyAssociation: string | null; definitionCount: number; conflictingDefinitionCount: number; provenance: readonly string[]; missingProvenance: readonly string[] }>;
export type CandidateBinaryRole = "stock_original" | "mapswitch" | "other_observed";
export type EngineeringBinaryEvidencePackage = Readonly<{ binaryDigest: string; byteLength: number; containerType: EngineeringBinary["source"]["containerType"]; containerProvenance: readonly string[]; sourceFilename: string | null; internalIdentityObservations: readonly InternalIdentityObservation[]; romFamilyObservations: readonly string[]; softwareCalibrationObservations: readonly string[]; stockVariantKnowledge: RuntimeStockVariantKnowledgeResponse | null; provisionalSourceRole: CandidateBinaryRole; candidateRelationshipProvenance: readonly string[]; findings: readonly string[] }>;
export type ApplicabilityEvidenceAssessmentCode = "strong_exact_identity_correspondence" | "identity_ambiguity" | "stock_variant_conflict" | "source_provenance_missing" | "candidate_binary_missing" | "direct_conflict";
export type ApplicabilityEvidenceAssessment = Readonly<{ codes: readonly ApplicabilityEvidenceAssessmentCode[]; admissionReady: false; authorityDecision: "required"; explanation: readonly string[] }>;
export type ApplicabilityProposal = Readonly<{ proposalId: string; proposalRevision: string; contractVersion: "tunesight.xdf-applicability-proposal.v1"; definitionSetRevisionId: string; xdfSourceArtifactId: string; engineeringBinaryDigest: string; xdfEvidence: XdfApplicabilityEvidencePackage; binaryEvidence: EngineeringBinaryEvidencePackage; assessment: ApplicabilityEvidenceAssessment; unresolvedConditions: readonly string[]; conflictFindings: readonly string[]; authorityDecision: "pending" }>;
export type UnresolvedApplicabilityCollection = Readonly<{ outcome: "no_responsible_candidate_binary"; definitionSetRevisionId: string; xdfSourceArtifactId: string; missingInput: "engineering_binary"; authorityDecision: "pending" }>;
export type ApplicabilityProposalCoverageReport = Readonly<{ definitionSetsInspected: number; pairedDefinitionSets: number; unpairedDefinitionSets: number; binaryRelationshipsProcessed: number; proposalsGenerated: number; strongExactMarkerCorrespondence: number; detectorAmbiguity: number; stockVariantConflicts: number; duplicateXdfDigestRelationships: number; sourceProvenanceMissing: number; directTechnicalContradictions: number; unresolved: number; proposalGenerationFailures: number; familyDistribution: Readonly<Record<string, number>> }>;

function canonical(value: unknown): string { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isFinite(value) || (Number.isInteger(value) && !Number.isSafeInteger(value))) throw new Error("Proposal identity contains an unsafe number."); return JSON.stringify(Object.is(value, -0) ? 0 : value); } if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (typeof value !== "object" || value === undefined) throw new Error("Proposal identity contains an unsupported value."); const record = value as Readonly<Record<string, unknown>>; return `{${Object.keys(record).filter((key) => record[key] !== undefined).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`; }
function digest(domain: string, value: unknown): string { return createHash("sha256").update(domain).update(Buffer.from([0])).update(canonical(value)).digest("hex"); }
function deepFreeze<T>(value: T): T { if (Array.isArray(value)) return Object.freeze(value.map(deepFreeze)) as T; if (value !== null && typeof value === "object") { const clone: Record<PropertyKey, unknown> = {}; for (const key of Reflect.ownKeys(value)) clone[key] = deepFreeze((value as Record<PropertyKey, unknown>)[key]); return Object.freeze(clone) as T; } return value; }
const normal = (value: string) => value.trim().toUpperCase();
const unique = (values: readonly string[]) => [...new Set(values.map(normal).filter(Boolean))].sort();
function offsets(haystack: Uint8Array, needle: Uint8Array): number[] { const found: number[] = []; if (!needle.byteLength) return found; const bytes = Buffer.from(haystack.buffer, haystack.byteOffset, haystack.byteLength); const target = Buffer.from(needle); for (let at = bytes.indexOf(target); at >= 0; at = bytes.indexOf(target, at + 1)) found.push(at); return found; }

export function collectInternalIdentityObservations(input: { binaryBytes: Uint8Array; credibleIdentifiers: readonly Readonly<{ identifier: string; kind: Exclude<InternalIdentityObservationKind, "encoded_numeric_marker">; confidence: InternalIdentityObservation["confidence"]; reason: string; encodings?: readonly ("ascii" | "hex_encoded")[] }>[] }): readonly InternalIdentityObservation[] {
  if (!input.binaryBytes.byteLength || input.binaryBytes.byteLength > APPLICABILITY_PROPOSAL_LIMITS.maximumBinaryBytes) throw new Error("Binary identity collection is outside its bounded byte limit.");
  if (input.credibleIdentifiers.length > APPLICABILITY_PROPOSAL_LIMITS.maximumCredibleIdentifiers) throw new Error("Credible identity vocabulary exceeds its bounded limit.");
  const binaryDigest = createHash("sha256").update(input.binaryBytes).digest("hex"); const observations: Omit<InternalIdentityObservation, "ambiguity">[] = [];
  for (const candidate of input.credibleIdentifiers) { const normalizedForm = normal(candidate.identifier); if (!candidate.reason.trim() || !/^[A-Z0-9][A-Z0-9._-]{3,63}$/.test(normalizedForm)) continue; for (const encoding of candidate.encodings ?? ["ascii"]) { if (encoding === "hex_encoded" && (!/^[0-9A-F]{12,16}$/.test(normalizedForm) || normalizedForm.length % 2 !== 0)) continue; const raw = encoding === "ascii" ? Buffer.from(candidate.identifier, "ascii") : Buffer.from(normalizedForm, "hex"); const at = offsets(input.binaryBytes, raw); if (!at.length) continue; const kind = encoding === "hex_encoded" ? "encoded_numeric_marker" : candidate.kind; const detector = encoding === "hex_encoded" ? "bounded_hex_encoded_exact" : "bounded_ascii_exact"; observations.push({ observationId: `internal-identity-observation:${digest("tunesight.internal-identity-observation.v1", { binaryDigest, normalizedForm, kind, detector, at })}`, kind, rawForm: encoding === "ascii" ? candidate.identifier : raw.toString("hex"), normalizedForm, offsets: at, occurrenceCount: at.length, detector, confidence: candidate.confidence, credibilityReason: candidate.reason, binaryDigest }); } }
  const ambiguous = new Set(observations.map((item) => item.normalizedForm)).size > 1; return deepFreeze(observations.sort((a, b) => a.normalizedForm.localeCompare(b.normalizedForm) || a.detector.localeCompare(b.detector)).map((item) => ({ ...item, ambiguity: ambiguous ? "multiple_credible_identities" as const : "none" as const })));
}

export function collectXdfApplicabilityEvidence(input: Omit<XdfApplicabilityEvidencePackage, "explicitHeaderIdentities" | "duplicateSourceDefinitionSetRevisionIds" | "provenance" | "missingProvenance"> & { explicitHeaderIdentities?: readonly string[]; duplicateSourceDefinitionSetRevisionIds?: readonly string[]; provenance?: readonly string[]; missingProvenance?: readonly string[] }): XdfApplicabilityEvidencePackage { if (input.definitionSet.sourceArtifactDigest !== input.sourceArtifact.sourceDigest || input.definitionCount !== input.definitionSet.definitionCount) throw new Error("XDF Evidence does not bind the exact Definition Set source."); return deepFreeze({ ...input, explicitHeaderIdentities: unique(input.explicitHeaderIdentities ?? []), duplicateSourceDefinitionSetRevisionIds: unique(input.duplicateSourceDefinitionSetRevisionIds ?? []), provenance: [...new Set((input.provenance ?? []).map((v) => v.trim()).filter(Boolean))].sort(), missingProvenance: [...new Set(input.missingProvenance ?? [])].sort() }); }
export function collectEngineeringBinaryEvidence(input: Omit<EngineeringBinaryEvidencePackage, "binaryDigest" | "byteLength" | "containerType"> & { engineeringBinary: EngineeringBinary }): EngineeringBinaryEvidencePackage { const binaryDigest = createHash("sha256").update(input.engineeringBinary.bytes).digest("hex"); if (input.engineeringBinary.byteLength !== input.engineeringBinary.bytes.byteLength) throw new Error("Engineering Binary Evidence has invalid byte identity."); const { engineeringBinary, ...rest } = input; return deepFreeze({ ...rest, binaryDigest, byteLength: engineeringBinary.byteLength, containerType: engineeringBinary.source.containerType }); }

export function assessApplicabilityProposalEvidence(input: { claimedIdentifiers: readonly string[]; binaryEvidence: EngineeringBinaryEvidencePackage; xdfEvidence: XdfApplicabilityEvidencePackage; directContradictions?: readonly string[] }): ApplicabilityEvidenceAssessment { const claimed = new Set(unique(input.claimedIdentifiers)); const observed = new Set(input.binaryEvidence.internalIdentityObservations.map((item) => item.normalizedForm)); const matches = [...observed].filter((value) => claimed.has(value)); const contradictions = [...(input.directContradictions ?? [])]; if (claimed.size && observed.size && !matches.length) contradictions.push("Credible internal identities do not include any claimed Definition Set identity."); const codes: ApplicabilityEvidenceAssessmentCode[] = []; const explanation: string[] = []; if (matches.length) { codes.push("strong_exact_identity_correspondence"); explanation.push(`Exact internal identity correspondence: ${matches.join(", ")}.`); } if (observed.size > 1) { codes.push("identity_ambiguity"); explanation.push("Multiple credible internal identities are preserved without selection."); } const stock = input.binaryEvidence.stockVariantKnowledge; if (stock?.availability === "available" && stock.result.status === "conflict") { codes.push("stock_variant_conflict"); explanation.push(stock.result.explanation); } if (input.xdfEvidence.missingProvenance.length || !input.xdfEvidence.provenance.length) { codes.push("source_provenance_missing"); explanation.push("Source authority/provenance remains incomplete."); } if (contradictions.length) { codes.push("direct_conflict"); explanation.push(...contradictions); } return deepFreeze({ codes: [...new Set(codes)].sort(), admissionReady: false, authorityDecision: "required", explanation }); }

export function constructApplicabilityProposal(input: { xdfEvidence: XdfApplicabilityEvidencePackage; binaryEvidence: EngineeringBinaryEvidencePackage; assessment: ApplicabilityEvidenceAssessment; unresolvedConditions?: readonly string[]; conflictFindings?: readonly string[] }): ApplicabilityProposal { const relationship = { definitionSetRevisionId: input.xdfEvidence.definitionSet.revisionId, xdfSourceArtifactId: input.xdfEvidence.sourceArtifact.artifactId, engineeringBinaryDigest: input.binaryEvidence.binaryDigest }; const proposalId = `xdf-applicability-proposal:${digest("tunesight.xdf-applicability-proposal-relationship.v1", relationship)}`; const material = { ...relationship, xdfEvidence: input.xdfEvidence, binaryEvidence: input.binaryEvidence, assessment: input.assessment, unresolvedConditions: [...new Set(input.unresolvedConditions ?? [])].sort(), conflictFindings: [...new Set(input.conflictFindings ?? [])].sort(), contractVersion: "tunesight.xdf-applicability-proposal.v1" as const }; const engineeringXdfEvidence = { ...input.xdfEvidence, sourcePath: null, filename: null }; const engineeringBinaryEvidence = { ...input.binaryEvidence, sourceFilename: null }; const proposalRevision = `xdf-applicability-proposal-revision:${digest("tunesight.xdf-applicability-proposal-revision.v1", { ...relationship, xdfEvidence: engineeringXdfEvidence, binaryEvidence: engineeringBinaryEvidence, assessment: input.assessment, unresolvedConditions: material.unresolvedConditions, conflictFindings: material.conflictFindings, contractVersion: material.contractVersion })}`; return deepFreeze({ proposalId, proposalRevision, ...material, authorityDecision: "pending" }); }
export function unresolvedCandidateBinary(definitionSet: DefinitionSetRevision, sourceArtifact: XdfSourceArtifact): UnresolvedApplicabilityCollection { if (definitionSet.sourceArtifactId !== sourceArtifact.artifactId) throw new Error("Unresolved result must bind its exact XDF source."); return deepFreeze({ outcome: "no_responsible_candidate_binary", definitionSetRevisionId: definitionSet.revisionId, xdfSourceArtifactId: sourceArtifact.artifactId, missingInput: "engineering_binary", authorityDecision: "pending" }); }
export function buildApplicabilityProposalCoverageReport(input: { inspected: readonly Readonly<{ family: string; proposalCount: number; paired: boolean; codes: readonly ApplicabilityEvidenceAssessmentCode[]; duplicateRelationships: number }>[]; failures?: number }): ApplicabilityProposalCoverageReport { if (input.inspected.length > APPLICABILITY_PROPOSAL_LIMITS.maximumRelationships) throw new Error("Coverage report exceeds its bounded relationship limit."); const sum = (pick: (item: typeof input.inspected[number]) => number) => input.inspected.reduce((total, item) => total + pick(item), 0); const familyDistribution: Record<string, number> = {}; for (const item of input.inspected) familyDistribution[item.family] = (familyDistribution[item.family] ?? 0) + 1; const paired = input.inspected.filter((item) => item.paired).length; return deepFreeze({ definitionSetsInspected: input.inspected.length, pairedDefinitionSets: paired, unpairedDefinitionSets: input.inspected.length - paired, binaryRelationshipsProcessed: sum((item) => item.proposalCount), proposalsGenerated: sum((item) => item.proposalCount), strongExactMarkerCorrespondence: sum((item) => item.codes.includes("strong_exact_identity_correspondence") ? item.proposalCount : 0), detectorAmbiguity: sum((item) => item.codes.includes("identity_ambiguity") ? item.proposalCount : 0), stockVariantConflicts: sum((item) => item.codes.includes("stock_variant_conflict") ? item.proposalCount : 0), duplicateXdfDigestRelationships: sum((item) => item.duplicateRelationships), sourceProvenanceMissing: sum((item) => item.codes.includes("source_provenance_missing") ? item.proposalCount : 0), directTechnicalContradictions: sum((item) => item.codes.includes("direct_conflict") ? item.proposalCount : 0), unresolved: input.inspected.length - paired, proposalGenerationFailures: input.failures ?? 0, familyDistribution: Object.fromEntries(Object.entries(familyDistribution).sort(([a], [b]) => a.localeCompare(b))) }); }
