import { constructApplicabilityDecisionRecord, type ApplicabilityAuthorityAssessment, type ApplicabilityDecisionAuthority } from "./applicabilityAuthorityDecision.ts";
import type { ApplicabilityProposal } from "./applicabilityEvidenceProposal.ts";
import { B58_GEN1_00007972000705_SOURCE_AUTHORITY } from "./b58Gen1AcceptedSourceAuthority.ts";
import type { ReviewedApplicabilityDecisionCandidate } from "./bmwFounderApplicabilityCandidates.ts";

export const B58_GEN1_00007972000705_ACCEPTED_APPLICABILITY_CANDIDATE_ID = "reviewed-applicability-decision-candidate:1c8f20506e6256d8b9c13d9422a6372311c18bd69a6d9c8f6b4ed2f2177695a4" as const;
export const B58_GEN1_00007972000705_ACCEPTED_APPLICABILITY_CANDIDATE_REVISION = "reviewed-applicability-decision-candidate-revision:53253eb8a7ddebb418ead0000b3b2ad1e224301cf6e96d288b45cd17767a0106" as const;
export const B58_GEN1_00007972000705_APPLICABILITY_DECIDED_AT = "2026-09-07T00:00:00.000Z" as const;
export const B58_GEN1_FOUNDER_APPLICABILITY_AUTHORITY: ApplicabilityDecisionAuthority = Object.freeze({ authorityId: "applicability-decision-authority:tunesight-founder-founder-b58-gen1-00007972000705", authorityClass: "founder", authorityRevision: "applicability-decision-authority-revision:2026-09-07-00007972000705", provenance: Object.freeze(["Founder Founder explicitly accepted the exact immutable applicability Decision Candidate for 00007972000705.", "Acceptance is Definition Set applicability only; Stock, semantic Knowledge and publication remain separate."]), permittedOutcomes: Object.freeze(["accept_exact_applicability"] as const), acceptedPathways: Object.freeze(["governed_evidence_review"] as const) });

export function materializeB58Gen1AcceptedApplicabilityDecision(input: Readonly<{ candidate: ReviewedApplicabilityDecisionCandidate; proposal: ApplicabilityProposal; assessment: ApplicabilityAuthorityAssessment }>) {
  const { candidate } = input;
  if (candidate.candidateId !== B58_GEN1_00007972000705_ACCEPTED_APPLICABILITY_CANDIDATE_ID || candidate.candidateRevision !== B58_GEN1_00007972000705_ACCEPTED_APPLICABILITY_CANDIDATE_REVISION || candidate.romSoftwareIdentity !== "00007972000705" || candidate.eligibility !== "eligible_for_founder_decision") throw new Error("Applicability acceptance requires the exact Founder-reviewed candidate identity and revision.");
  if (candidate.authorityRevision !== B58_GEN1_00007972000705_SOURCE_AUTHORITY.authorityRevision) throw new Error("Applicability acceptance requires the exact accepted Source Authority revision.");
  if (input.assessment.proposalId !== input.proposal.proposalId || input.assessment.proposalRevision !== input.proposal.proposalRevision || candidate.assessmentRevision !== input.assessment.assessmentRevision) throw new Error("Applicability acceptance must bind the exact proposal and assessment revisions.");
  const decision = constructApplicabilityDecisionRecord({ proposal: input.proposal, assessment: input.assessment, outcome: "accept_exact_applicability", authority: B58_GEN1_FOUNDER_APPLICABILITY_AUTHORITY, rationale: `Founder accepts exact Definition Set applicability for 00007972000705 under ${candidate.candidateRevision} and ${candidate.authorityRevision}. Source limitations, unknown upstream authorship/acquisition, Stock separation, semantic Knowledge separation and separate publication remain unchanged.`, acceptedEvidenceReferences: [candidate.candidateRevision, candidate.evidencePackageRevision, candidate.assessmentRevision, candidate.authorityRevision], unresolvedConditions: [], decidedAt: B58_GEN1_00007972000705_APPLICABILITY_DECIDED_AT });
  return Object.freeze({ romSoftwareIdentity: candidate.romSoftwareIdentity, candidateId: candidate.candidateId, candidateRevision: candidate.candidateRevision, sourceAuthorityId: B58_GEN1_00007972000705_SOURCE_AUTHORITY.authorityId, sourceAuthorityRevision: candidate.authorityRevision, decision, stockAuthenticity: "not_assessed" as const, semanticKnowledge: "not_assessed" as const, publicationState: "not_published" as const, workshopAdmission: "not_authorized" as const, publicationSideEffects: Object.freeze([]) as readonly [] });
}
