import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { resolveBinaryContainer, type EngineeringBinary } from "../tunes/binaryContainer.ts";
import { collectInternalIdentityObservations } from "./applicabilityEvidenceProposal.ts";
import { assessBinaryRomLayoutMembership, BINARY_ROM_LAYOUT_MEMBERSHIP_AUTHORITY, verifyQualifiedBinaryLayoutMembership, type BinaryLayoutMembershipResult } from "./binaryRomLayoutMembership.ts";
import { assessDefinitionExtractionCapability, extractRawCalibrationValues } from "./calibrationValueExtraction.ts";
import type { XdfDefinitionRevision } from "./canonicalXdfDefinition.ts";
import { defineDefinitionSetRevision, identifyEngineeringBinary, type DefinitionSetRevision, type EngineeringBinaryIdentity } from "./definitionRomApplicability.ts";
import { constructEngineeringValueConversionRequest, convertQualifiedCalibrationValue } from "./engineeringValueConversion.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import { N54_CURRENT_GOVERNED_REVIEW_REFERENCES, N54_CURRENT_ROM_LAYOUT_REGISTRY } from "./n54GovernedApplicabilityAdmission.ts";
import { compareQualifiedCalibrations, constructQualifiedCalibrationComparisonRequest } from "./qualifiedCalibrationComparison.ts";
import { constructQualifiedCalibrationExtractionRequest, extractQualifiedCalibrationValue } from "./qualifiedCalibrationExtraction.ts";
import { defineRomLayoutIdentity, type RomLayoutIdentity, type RomLayoutMarker } from "./romLayoutApplicability.ts";

const ids=["I8A0S","IJE0S","IKM0S","INA0S"] as const;type Identity=typeof ids[number];const root=path.resolve("BMW-XDFs-master/N54");
type Parsed=Readonly<{definitions:readonly XdfDefinitionRevision[];set:DefinitionSetRevision}>;type Exact=Readonly<{engineering:EngineeringBinary;identity:EngineeringBinaryIdentity;markers:readonly RomLayoutMarker[]}>;const parsedCache=new Map<Identity,Parsed>(),exactCache=new Map<string,Exact>(),layoutCache=new Map<Identity,RomLayoutIdentity>();
function parsed(id:Identity):Parsed{const hit=parsedCache.get(id);if(hit)return hit;const filename=`${id}.xdf`,result=interpretXdfStructure({xml:fs.readFileSync(path.join(root,filename),"utf8"),filename,provenance:`Membership proof ${filename}`});assert.equal(result.outcome,"structurally_interpreted");assert.ok(result.sourceArtifact);const value=Object.freeze({definitions:result.definitions,set:defineDefinitionSetRevision({sourceArtifact:result.sourceArtifact!,definitions:result.definitions})});parsedCache.set(id,value);return value;}
function fromBytes(id:Identity,bytes:Uint8Array,fileName:string):Exact{const resolved=resolveBinaryContainer({bytes,fileName});assert.equal(resolved.status,"resolved");const observations=collectInternalIdentityObservations({binaryBytes:resolved.engineeringBinary!.bytes,credibleIdentifiers:ids.map(identifier=>({identifier,kind:"ascii_rom_marker" as const,confidence:"known_identity" as const,reason:"Credible current N54 ROM identity",encodings:["ascii" as const]}))}),identity=identifyEngineeringBinary({engineeringBinary:resolved.engineeringBinary!,romFamily:"N54",softwareIdentity:id,internalRomIdentifiers:observations.map(value=>value.normalizedForm),identityProvenance:["Exact candidate bytes and bounded marker collection"]}),markers=observations.filter(value=>value.normalizedForm===id).map(value=>({kind:value.kind,normalizedForm:value.normalizedForm,offsets:value.offsets,detector:value.detector}));return Object.freeze({engineering:resolved.engineeringBinary!,identity,markers:Object.freeze(markers)});}
function exact(id:Identity,role:"original"|"MapSwitchBase"):Exact{const key=`${id}_${role}`,hit=exactCache.get(key);if(hit)return hit;const value=fromBytes(id,fs.readFileSync(path.join(root,`${key}.bin`)),`${key}.bin`);exactCache.set(key,value);return value;}
function layout(id:Identity):RomLayoutIdentity{const hit=layoutCache.get(id);if(hit)return hit;const source=parsed(id),original=exact(id,"original"),addresses=source.definitions.map(value=>value.primaryAddress).filter((value):value is number=>value!==null),region=source.definitions[0]!.addressSpace.regions[0]!,value=defineRomLayoutIdentity({romSoftwareIdentifiers:[id],calibrationSoftwareIdentifiers:[id],ecuDmeFamily:id==="I8A0S"?"MSD80":"MSD81",binaryByteLength:original.identity.byteLength,containerTypes:[original.identity.containerType],internalMarkers:original.markers,calibrationAddressSpace:[{startAddress:region.startAddress,size:region.size}],definitionCompatibleAddressRange:{minimum:Math.min(...addresses),maximum:Math.max(...addresses)},xdfSideIdentities:[id],evidenceProvenance:["Accepted current N54 governed layout evidence"]});assert.equal(value.layoutId,N54_CURRENT_GOVERNED_REVIEW_REFERENCES.find(item=>item.identity===id)!.review.romLayoutId);layoutCache.set(id,value);return value;}
function relation(id:Identity){return N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships.find(value=>value.romLayoutId===layout(id).layoutId)!;}
function assess(id:Identity,candidate:Exact,target:RomLayoutIdentity|null=layout(id),options:Partial<{relationship:ReturnType<typeof relation>|null;sourceRole:string;credible:readonly string[]}>= {}):BinaryLayoutMembershipResult{return assessBinaryRomLayoutMembership({engineeringBinary:candidate.engineering,binaryIdentity:candidate.identity,targetLayout:target,relationship:options.relationship===undefined?relation(id):options.relationship,definitionSet:target?parsed(id).set:null,definitions:target?parsed(id).definitions:[],credibleRomIdentifiers:options.credible??ids,sourceRole:options.sourceRole??"user_modified",sourceProvenance:["Controlled immutable membership proof"],qualifiedAt:null});}
function modified(id:Identity,count:number):Exact{const source=parsed(id),base=exact(id,"original"),bytes=base.engineering.bytes,used=new Set<number>();for(const definition of source.definitions){if(used.size>=count)break;if(assessDefinitionExtractionCapability(definition).state!=="extraction_capable")continue;const extraction=extractRawCalibrationValues(base.engineering,definition),offset=extraction.offsets[0];if(extraction.outcome!=="extracted"||offset===undefined||used.has(offset)||base.markers.some(marker=>marker.offsets.some(markerOffset=>offset>=markerOffset&&offset<markerOffset+marker.normalizedForm.length)))continue;bytes[offset]=(bytes[offset]!+used.size+1)&0xff;used.add(offset);}assert.equal(used.size,count);return fromBytes(id,bytes,`${id}_synthetic_${count}.bin`);}

test("all four N54 Original and MapSwitch candidates independently qualify without historical digest reliance",()=>{const report=[];for(const id of ids)for(const role of ["original","MapSwitchBase"] as const){const candidate=exact(id,role),first=assess(id,candidate,layout(id),{sourceRole:role==="original"?"stock_candidate":"mapswitch"}),again=assess(id,candidate,layout(id),{sourceRole:role==="original"?"stock_candidate":"mapswitch"});assert.equal(first.outcome,"qualified_member");assert.deepEqual(first,again);if(first.outcome!=="qualified_member")continue;assert.equal(first.membership.exactBinaryIdentity.digest,candidate.identity.digest);assert.equal(first.membership.romLayoutId,layout(id).layoutId);assert.equal(first.membership.relationshipRevision,relation(id).relationshipRevision);assert.equal(first.membership.qualificationPathway,"automated_under_founder_approved_membership_contract");assert.equal(first.membership.stockAuthenticity,"not_assessed");assert.equal(first.evidence.byteSimilarityUsedAsAuthority,false);assert.equal(first.evidence.structuralValidation!.failedExtractions,0);assert.equal(first.evidence.structuralValidation!.successfulExtractions,first.evidence.structuralValidation!.extractionCapableDefinitions);assert.ok(Object.isFrozen(first)&&Object.isFrozen(first.evidence)&&Object.isFrozen(first.membership));report.push({id,role,digest:candidate.identity.digest,evidence:first.evidence.evidenceId,membership:first.membership.membershipId,definitions:first.evidence.structuralValidation!.definitionsAssessed,extractions:first.evidence.structuralValidation!.successfulExtractions});}console.log(`N54_BINARY_LAYOUT_MEMBERSHIP ${JSON.stringify(report)}`);});
test("new and heavily modified calibration-content digests remain qualified layout members",()=>{for(const count of [1,32]){const candidate=modified("IJE0S",count),original=exact("IJE0S","original");assert.notEqual(candidate.identity.digest,original.identity.digest);const result=assess("IJE0S",candidate);assert.equal(result.outcome,"qualified_member");if(result.outcome!=="qualified_member")continue;assert.deepEqual(result.evidence.observedMarkers.map(value=>[value.normalizedForm,value.offsets]),assess("IJE0S",original).evidence.observedMarkers.map(value=>[value.normalizedForm,value.offsets]));assert.equal(result.evidence.structuralValidation!.failedExtractions,0);assert.equal(result.evidence.byteSimilarityUsedAsAuthority,false);}});
test("wrong ROM, marker tamper and credible contradictory marker fail closed",()=>{const wrong=assess("INA0S",exact("IJE0S","original"));assert.equal(wrong.outcome,"technical_conflict");assert.ok(wrong.evidence.contradictions.some(value=>value.includes("contradictory ROM identifiers")||value.includes("expected ROM")));const base=exact("IJE0S","original"),tamperedBytes=base.engineering.bytes,marker=layout("IJE0S").internalMarkers[0]!;tamperedBytes[marker.offsets[0]!]="Z".charCodeAt(0);const tampered=assess("IJE0S",fromBytes("IJE0S",tamperedBytes,"marker-tampered.bin"));assert.equal(tampered.outcome,"technical_conflict");assert.ok(tampered.evidence.contradictions.some(value=>value.includes("multiplicity or offsets")));const contradictoryBytes=base.engineering.bytes,offset=parsed("IJE0S").definitions.find(value=>value.primaryAddress!==null)!.primaryAddress!;Buffer.from("INA0S","ascii").copy(contradictoryBytes,offset);const contradictory=assess("IJE0S",fromBytes("IJE0S",contradictoryBytes,"contradictory-marker.bin"));assert.equal(contradictory.outcome,"technical_conflict");assert.ok(contradictory.evidence.contradictions.some(value=>value.includes("INA0S")));});
test("truncation, invalid identity and unknown target remain distinct",()=>{const base=exact("IJE0S","original"),truncated=fromBytes("IJE0S",base.engineering.bytes.subarray(0,base.engineering.byteLength-4096),"truncated.bin"),structural=assess("IJE0S",truncated);assert.equal(structural.outcome,"technical_conflict");assert.ok(structural.evidence.contradictions.some(value=>value.includes("byte length")||value.includes("address range")));const invalid=assessBinaryRomLayoutMembership({engineeringBinary:base.engineering,binaryIdentity:{...base.identity,digest:"0".repeat(64),identityId:`engineering-binary:${"0".repeat(64)}`},targetLayout:layout("IJE0S"),relationship:relation("IJE0S"),definitionSet:parsed("IJE0S").set,definitions:parsed("IJE0S").definitions,credibleRomIdentifiers:ids,sourceRole:"invalid",sourceProvenance:["Controlled invalid identity"]});assert.equal(invalid.outcome,"invalid_binary");const unknown=assess("IJE0S",base,null,{relationship:null});assert.equal(unknown.outcome,"unknown_layout");});
test("incomplete authority and MG1-shaped multi-marker ambiguity require review",()=>{const incomplete=assess("IJE0S",exact("IJE0S","original"),layout("IJE0S"),{relationship:null});assert.equal(incomplete.outcome,"more_evidence_required");const bytes=exact("IJE0S","original").engineering.bytes,insertOffset=parsed("IJE0S").definitions.find(value=>value.primaryAddress!==null)!.primaryAddress!;Buffer.from("INA0S","ascii").copy(bytes,insertOffset);const candidate=fromBytes("IJE0S",bytes,"mg1-shaped.bin"),base=layout("IJE0S"),inaOffsets=[insertOffset],ambiguousLayout=defineRomLayoutIdentity({...base,romSoftwareIdentifiers:["IJE0S","INA0S"],internalMarkers:[...base.internalMarkers,{kind:"ascii_rom_marker",normalizedForm:"INA0S",offsets:inaOffsets,detector:"bounded_ascii_exact"}],ecuDmeFamily:"MG1",evidenceProvenance:["Controlled MG1-shaped ambiguity"]}),ambiguous=assess("IJE0S",candidate,ambiguousLayout,{relationship:null,credible:["IJE0S","INA0S"]});assert.equal(ambiguous.outcome,"more_evidence_required");assert.ok(ambiguous.evidence.unresolvedConditions.some(value=>value.includes("Multiple credible")));});
test("new membership authorizes exact-digest raw extraction and engineering conversion",()=>{const candidate=modified("IJE0S",1),qualified=assess("IJE0S",candidate);assert.equal(qualified.outcome,"qualified_member");if(qualified.outcome!=="qualified_member")return;const source=parsed("IJE0S"),definition=source.definitions.find(value=>assessDefinitionExtractionCapability(value).state==="extraction_capable"&&value.axes.some(axis=>axis.axisId.toLowerCase()==="z"&&axis.equationSource!==null))!,relationship=relation("IJE0S"),raw=extractQualifiedCalibrationValue(constructQualifiedCalibrationExtractionRequest({engineeringBinary:candidate.engineering,binaryIdentity:candidate.identity,romLayoutId:layout("IJE0S").layoutId,registrySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,expectedRelationshipId:relationship.relationshipId,expectedRelationshipRevision:relationship.relationshipRevision,definitionSet:source.set,definition,binaryLayoutMembership:qualified.membership}));assert.equal(raw.status,"qualified_extracted");if(raw.status!=="qualified_extracted")return;assert.equal(raw.evidence.exactBinaryDigest,candidate.identity.digest);const axis=definition.axes.find(value=>value.axisId.toLowerCase()==="z")!,engineering=convertQualifiedCalibrationValue(constructEngineeringValueConversionRequest({rawEvidence:raw.evidence,definition,expectedEquationSource:axis.equationSource!,expectedUnits:axis.units}));assert.equal(engineering.status,"converted");if(engineering.status==="converted")assert.equal(engineering.evidence.exactBinaryDigest,candidate.identity.digest);});
test("qualified new membership is comparison-ready without rewriting the historical relationship",()=>{const candidate=modified("IJE0S",1),qualified=assess("IJE0S",candidate);assert.equal(qualified.outcome,"qualified_member");if(qualified.outcome!=="qualified_member")return;const reference=exact("IJE0S","original"),relationship=relation("IJE0S"),source=parsed("IJE0S"),before=relationship.supportingExactBinaries.length,result=compareQualifiedCalibrations(constructQualifiedCalibrationComparisonRequest({reference:{engineeringBinary:reference.engineering,binaryIdentity:reference.identity,role:"stock_candidate",provenance:["Historical exact candidate"]},modified:{engineeringBinary:candidate.engineering,binaryIdentity:candidate.identity,role:"modified_candidate",provenance:["New qualified modified candidate"],binaryLayoutMembership:qualified.membership},romLayoutId:layout("IJE0S").layoutId,registrySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,expectedRelationshipId:relationship.relationshipId,expectedRelationshipRevision:relationship.relationshipRevision,definitionSet:source.set,definitions:source.definitions}));assert.equal(result.status,"compared");assert.equal(relationship.supportingExactBinaries.length,before);assert.ok(!relationship.supportingExactBinaries.some(value=>value.binaryDigest===candidate.identity.digest));});
test("membership lineage is contract-authorized, immutable and never fabricates Stock",()=>{const result=assess("INA0S",modified("INA0S",1));assert.equal(result.outcome,"qualified_member");if(result.outcome!=="qualified_member")return;assert.equal(result.membership.authorityId,BINARY_ROM_LAYOUT_MEMBERSHIP_AUTHORITY.authorityId);assert.equal(result.membership.authorityRevision,BINARY_ROM_LAYOUT_MEMBERSHIP_AUTHORITY.authorityRevision);assert.equal(result.membership.evidenceRevision,result.evidence.evidenceRevision);assert.equal(result.membership.stockAuthenticity,"not_assessed");assert.ok(result.membership.limitations.some(value=>value.includes("Stock authenticity")));assert.ok(!("stock" in result.membership));assert.ok(Object.isFrozen(result.membership.exactBinaryIdentity)&&Object.isFrozen(result.membership.limitations));assert.equal(verifyQualifiedBinaryLayoutMembership({membership:{...result.membership,sourceRole:"forged"},binaryIdentity:result.membership.exactBinaryIdentity,romLayoutId:layout("INA0S").layoutId,relationship:relation("INA0S"),definitionSet:parsed("INA0S").set}),false);});
