import { createHash } from "node:crypto";
import type { EngineeringBinary } from "../tunes/binaryContainer.ts";
import type { XdfDefinitionRevision } from "./canonicalXdfDefinition.ts";
import { extractRawCalibrationValues } from "./calibrationValueExtraction.ts";
import { evaluateParsedXdfEquation, parseXdfEquation } from "./engineeringValueConversion.ts";
import type { SourceAuthorityScopeBinding } from "./sourceAuthorityScope.ts";

export const BMW_MASTER_FULL_VALIDATION_CONTRACT = "tunesight.bmw-master-full-validation.v1" as const;
export type FullValidationBlocker = "identity_ambiguous" | "no_responsible_binary" | "no_responsible_definition_source" | "representation_conflict" | "extraction_failure" | "conversion_failure" | "source_authority_unresolved" | "stock_variant_conflict" | "technical_conflict" | "legacy_out_of_current_scope" | "other_explicit_failure";
export type CompleteBinaryValidation = Readonly<{ validationId: string; validationRevision: string; binaryDigest: string; definitions: number; extractionAttempts: number; extractionSuccess: number; blocked: number; outOfBounds: number; unsupported: number; representationConflicts: number; converted: number; identityNoOp: number; invalidNumeric: number; malformed: number; unavailable: number; unresolvedUnits: number; other: number }>;
export type GovernedEvidenceAuthorityCandidate = Readonly<{ candidateId: string; candidateRevision: string; contractVersion: "tunesight.source-authority-candidate.v1"; scope: SourceAuthorityScopeBinding; romSoftwareIdentity: string; evidenceReferences: readonly string[]; limitations: readonly string[]; state: "pending_founder_authority" }>;

function canonical(value: unknown): string { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isFinite(value)) throw new Error("Validation identity contains a non-finite number."); return JSON.stringify(value); } if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (!value || typeof value !== "object") throw new Error("Validation identity contains unsupported material."); const object = value as Readonly<Record<string, unknown>>; return `{${Object.keys(object).sort().map((key) => `${JSON.stringify(key)}:${canonical(object[key])}`).join(",")}}`; }
function digest(domain: string, value: unknown): string { return createHash("sha256").update(domain).update(Buffer.from([0])).update(canonical(value)).digest("hex"); }
function freeze<T>(value: T): T { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as T; if (value && typeof value === "object") return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, freeze(item)]))) as T; return value; }

export function validateCompleteDefinitionSet(input: Readonly<{ sourceDigest: string; definitionSetRevision: string; binary: EngineeringBinary; binaryDigest: string; definitions: readonly XdfDefinitionRevision[] }>): CompleteBinaryValidation {
  let extractionSuccess = 0, blocked = 0, outOfBounds = 0, unsupported = 0, representationConflicts = 0, converted = 0, identityNoOp = 0, invalidNumeric = 0, malformed = 0, unavailable = 0, unresolvedUnits = 0, other = 0;
  for (const definition of input.definitions) { if (definition.identity.status === "conflicting") representationConflicts += 1; const raw = extractRawCalibrationValues(input.binary, definition); if (raw.outcome !== "extracted") { blocked += 1; if (raw.outcome === "unsupported") unsupported += 1; else if (raw.findings.some((item) => /boundary|out-of-bounds/i.test(item))) outOfBounds += 1; else other += 1; continue; } extractionSuccess += 1; const axis = definition.axes.find((item) => item.axisId.toLowerCase() === "z") ?? definition.axes.at(-1); if (!axis?.equationSource || raw.shape?.values[0] === undefined) { unavailable += 1; continue; } const equation = parseXdfEquation(axis.equationSource); if (equation.outcome === "unsupported_expression") { unavailable += 1; continue; } if (equation.outcome === "malformed_equation") { malformed += 1; continue; } const result = evaluateParsedXdfEquation(equation, raw.shape.values[0]); if (result.outcome === "invalid_numeric_result") invalidNumeric += 1; else if (equation.outcome === "identity") identityNoOp += 1; else converted += 1; if (!axis.units) unresolvedUnits += 1; }
  const identity = { sourceDigest: input.sourceDigest, definitionSetRevision: input.definitionSetRevision, binaryDigest: input.binaryDigest, extractionContract: "tunesight.calibration-value-extractor.v1", conversionContract: "tunesight.engineering-value-conversion.v1" }; const material = { ...identity, definitions: input.definitions.length, extractionAttempts: input.definitions.length, extractionSuccess, blocked, outOfBounds, unsupported, representationConflicts, converted, identityNoOp, invalidNumeric, malformed, unavailable, unresolvedUnits, other, contractVersion: BMW_MASTER_FULL_VALIDATION_CONTRACT }; return freeze({ validationId: `bmw-full-validation:${digest("tunesight.bmw-full-validation-identity.v1", identity)}`, validationRevision: `bmw-full-validation-revision:${digest("tunesight.bmw-full-validation-revision.v1", material)}`, binaryDigest: input.binaryDigest, definitions: input.definitions.length, extractionAttempts: input.definitions.length, extractionSuccess, blocked, outOfBounds, unsupported, representationConflicts, converted, identityNoOp, invalidNumeric, malformed, unavailable, unresolvedUnits, other });
}

export function constructGovernedEvidenceAuthorityCandidate(input: Readonly<{ scope: SourceAuthorityScopeBinding; romSoftwareIdentity: string; validations: readonly CompleteBinaryValidation[]; identityCoherent: boolean; limitations: readonly string[] }>): GovernedEvidenceAuthorityCandidate {
  if (!input.validations.length || !input.identityCoherent || input.validations.some((item) => item.blocked || item.representationConflicts || item.invalidNumeric || item.malformed || item.unavailable)) throw new Error("Authority candidate requires coherent identity and complete conflict-free validation."); const evidenceReferences = input.validations.map((item) => item.validationRevision).sort(); const identity = { scope: input.scope, romSoftwareIdentity: input.romSoftwareIdentity.toUpperCase() }; const material = { ...identity, evidenceReferences, limitations: [...new Set(input.limitations)].sort(), contractVersion: "tunesight.source-authority-candidate.v1" as const, state: "pending_founder_authority" as const }; return freeze({ candidateId: `xdf-source-authority-candidate:${digest("tunesight.source-authority-candidate-identity.v1", identity)}`, candidateRevision: `xdf-source-authority-candidate-revision:${digest("tunesight.source-authority-candidate-revision.v1", material)}`, ...material });
}
