import { createHash } from "node:crypto";
import type { RuntimeStockVariantKnowledgeResponse } from "../knowledge/runtimeStockVariantKnowledge.ts";
import type { EngineeringBinary } from "../tunes/binaryContainer.ts";
import { assessDefinitionExtractionCapability, extractRawCalibrationValues, CALIBRATION_VALUE_EXTRACTOR_CONTRACT } from "./calibrationValueExtraction.ts";
import type { XdfDefinitionRevision, XdfSourceArtifact } from "./canonicalXdfDefinition.ts";
import type { DefinitionSetRevision } from "./definitionRomApplicability.ts";
import { ENGINEERING_VALUE_CONVERSION_CONTRACT, evaluateParsedXdfEquation, parseXdfEquation } from "./engineeringValueConversion.ts";
import { assessApplicabilityProposalEvidence, collectEngineeringBinaryEvidence, collectInternalIdentityObservations, collectXdfApplicabilityEvidence, constructApplicabilityProposal, type ApplicabilityProposal, type CandidateBinaryRole, type InternalIdentityObservation, type InternalIdentityObservationKind } from "./applicabilityEvidenceProposal.ts";

export const CALIBRATION_APPLICABILITY_EVIDENCE_PACKAGE_CONTRACT = "tunesight.calibration-applicability-evidence-package.v1" as const;
export const CALIBRATION_APPLICABILITY_EVIDENCE_AUDIT_LIMIT = 8;

export type EvidenceReadiness = "ready_for_authority_review" | "more_evidence_required" | "technical_conflict" | "source_authority_unresolved" | "no_responsible_candidate" | "invalid";
export type CredibleIdentityCandidate = Readonly<{ identifier: string; kind: Exclude<InternalIdentityObservationKind, "encoded_numeric_marker">; confidence: InternalIdentityObservation["confidence"]; reason: string; encodings?: readonly ("ascii" | "hex_encoded")[]; classification: "candidate_specific" | "common_shared" }>;
export type ApplicabilityCandidateBinary = Readonly<{ engineeringBinary: EngineeringBinary; role: CandidateBinaryRole; provenance: readonly string[]; stockVariantKnowledge: RuntimeStockVariantKnowledgeResponse | null; credibleIdentities: readonly CredibleIdentityCandidate[]; findings?: readonly string[] }>;
export type ApplicabilityEvidenceFactoryInput = Readonly<{ sourceArtifact: XdfSourceArtifact; definitionSet: DefinitionSetRevision; definitions: readonly XdfDefinitionRevision[]; sourcePath: string; sourceFamily: string; sourceStatus: "current" | "legacy" | "unknown"; claimedIdentities: readonly string[]; binaryCandidates: readonly ApplicabilityCandidateBinary[]; sourceProvenance: readonly string[]; sourceAuthority: "established" | "unresolved"; authorityProvenance: readonly string[]; limitations?: readonly string[]; directContradictions?: readonly string[]; platformConflicts?: readonly string[]; sourceAuthorityConflicts?: readonly string[]; duplicateSourceDefinitionSetRevisionIds?: readonly string[] }>;

export type DefinitionStructuralCensus = Readonly<{ total: number; uniqueDefinitionRevisions: number; duplicateRevisionOccurrenceGroups: number; scalar: number; oneDimensional: number; twoDimensional: number; extractionCapable: number; extractionBlocked: number; representationConflicted: number; axisBearing: number; equationBearing: number; engineeringConvertible: number; conversionUnavailable: number; descriptionsAvailable: number; sourceCategories: readonly string[]; units: readonly string[]; representativeBlockers: readonly string[] }>;
export type BinaryExtractionAudit = Readonly<{ attempted: number; successful: number; blocked: number; outOfBounds: number; representationConflicted: number; unsupported: number; unresolved: number; invalid: number; representativeFailures: readonly string[] }>;
export type BinaryConversionAudit = Readonly<{ eligible: number; converted: number; identityNoOp: number; invalidNumeric: number; unsupported: number; malformed: number; missingEquation: number; unitsUnresolved: number; representativeFailures: readonly string[] }>;
export type CandidateBinaryEvidence = Readonly<{ digest: string; byteLength: number; containerType: string; role: CandidateBinaryRole; provenance: readonly string[]; identityObservations: readonly InternalIdentityObservation[]; candidateSpecificMarkers: readonly string[]; commonSharedMarkers: readonly string[]; contradictoryMarkers: readonly string[]; ambiguity: boolean; stockVariantKnowledge: RuntimeStockVariantKnowledgeResponse | null; extraction: BinaryExtractionAudit; conversion: BinaryConversionAudit; proposal: ApplicabilityProposal }>;
export type ApplicabilityConflictModel = Readonly<{ identity: readonly string[]; platformFamily: readonly string[]; stockVariant: readonly string[]; representation: readonly string[]; equationUnit: readonly string[]; sourceAuthority: readonly string[]; duplicateSource: readonly string[]; binaryCandidate: readonly string[] }>;
export type CalibrationApplicabilityEvidencePackage = Readonly<{ packageId: string; packageRevision: string; contractVersion: typeof CALIBRATION_APPLICABILITY_EVIDENCE_PACKAGE_CONTRACT; source: Readonly<{ artifactId: string; digest: string; definitionSetId: string; definitionSetRevision: string; path: string; family: string; status: ApplicabilityEvidenceFactoryInput["sourceStatus"]; provenance: readonly string[]; authority: ApplicabilityEvidenceFactoryInput["sourceAuthority"]; authorityProvenance: readonly string[] }>; structural: DefinitionStructuralCensus; binaries: readonly CandidateBinaryEvidence[]; conflicts: ApplicabilityConflictModel; limitations: readonly string[]; readiness: Readonly<{ outcome: EvidenceReadiness; reasons: readonly string[]; authorityDecision: "required" }>; contracts: Readonly<{ extraction: typeof CALIBRATION_VALUE_EXTRACTOR_CONTRACT; conversion: typeof ENGINEERING_VALUE_CONVERSION_CONTRACT }>; publicationSideEffects: readonly [] }>;

function canonical(value: unknown): string { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isFinite(value)) throw new Error("Evidence identity contains a non-finite number."); return JSON.stringify(Object.is(value, -0) ? 0 : value); } if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (!value || typeof value !== "object") throw new Error("Evidence identity contains an unsupported value."); const record = value as Readonly<Record<string, unknown>>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`; }
function hash(domain: string, value: unknown): string { return createHash("sha256").update(domain).update(Buffer.from([0])).update(canonical(value)).digest("hex"); }
function freeze<T>(value: T): T { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as T; if (value && typeof value === "object") return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, freeze(item)]))) as T; return value; }
const unique = (values: readonly string[]) => [...new Set(values.filter(Boolean))].sort();
function shape(definition: XdfDefinitionRevision): "scalar" | "1d" | "2d" { const value = definition.axes.find((axis) => axis.axisId.toLowerCase() === "z") ?? definition.axes.at(-1); const rows = value?.embeddedData.rowCount ?? 1; const columns = value?.embeddedData.columnCount ?? value?.indexCount ?? 1; return rows > 1 ? "2d" : columns > 1 ? "1d" : "scalar"; }

function structuralCensus(definitions: readonly XdfDefinitionRevision[]): DefinitionStructuralCensus {
  const revisions = new Map<string, number>(); const blockers: string[] = []; let scalar = 0, oneDimensional = 0, twoDimensional = 0, extractionCapable = 0, representationConflicted = 0, equationBearing = 0, engineeringConvertible = 0;
  for (const definition of definitions) { revisions.set(definition.revisionId, (revisions.get(definition.revisionId) ?? 0) + 1); const kind = shape(definition); if (kind === "scalar") scalar += 1; else if (kind === "1d") oneDimensional += 1; else twoDimensional += 1; const capability = assessDefinitionExtractionCapability(definition); if (capability.state === "extraction_capable") extractionCapable += 1; else blockers.push(...capability.reasons); if (definition.identity.status === "conflicting") representationConflicted += 1; const equation = (definition.axes.find((axis) => axis.axisId.toLowerCase() === "z") ?? definition.axes.at(-1))?.equationSource; if (equation) { equationBearing += 1; const parsed = parseXdfEquation(equation); if ((parsed.outcome === "parsed" || parsed.outcome === "identity") && capability.state === "extraction_capable") engineeringConvertible += 1; else if ("finding" in parsed) blockers.push(parsed.finding); } }
  return freeze({ total: definitions.length, uniqueDefinitionRevisions: revisions.size, duplicateRevisionOccurrenceGroups: [...revisions.values()].filter((count) => count > 1).length, scalar, oneDimensional, twoDimensional, extractionCapable, extractionBlocked: definitions.length - extractionCapable, representationConflicted, axisBearing: definitions.filter((item) => item.axes.length > 1).length, equationBearing, engineeringConvertible, conversionUnavailable: definitions.length - engineeringConvertible, descriptionsAvailable: definitions.filter((item) => Boolean(item.description?.trim())).length, sourceCategories: [], units: unique(definitions.flatMap((item) => item.axes.map((axis) => axis.units ?? ""))), representativeBlockers: unique(blockers).slice(0, 20) });
}

function boundedAuditDefinitions(definitions: readonly XdfDefinitionRevision[]): readonly XdfDefinitionRevision[] {
  if (definitions.length <= CALIBRATION_APPLICABILITY_EVIDENCE_AUDIT_LIMIT) return definitions;
  const ordered = [...definitions].sort((left, right) => left.revisionId.localeCompare(right.revisionId));
  const selected = new Map<string, XdfDefinitionRevision>();
  for (const kind of ["scalar", "1d", "2d"] as const) { const item = ordered.find((definition) => shape(definition) === kind); if (item) selected.set(item.revisionId, item); }
  for (const item of ordered.filter((definition) => definition.identity.status === "conflicting")) { if (selected.size >= CALIBRATION_APPLICABILITY_EVIDENCE_AUDIT_LIMIT) break; selected.set(item.revisionId, item); }
  const remaining = CALIBRATION_APPLICABILITY_EVIDENCE_AUDIT_LIMIT - selected.size;
  for (let index = 0; index < remaining; index += 1) { const item = ordered[Math.floor(index * (ordered.length - 1) / Math.max(1, remaining - 1))]; if (item) selected.set(item.revisionId, item); }
  for (const item of ordered) { if (selected.size >= CALIBRATION_APPLICABILITY_EVIDENCE_AUDIT_LIMIT) break; selected.set(item.revisionId, item); }
  return Object.freeze([...selected.values()].sort((left, right) => left.revisionId.localeCompare(right.revisionId)));
}

function auditBinary(binary: EngineeringBinary, definitions: readonly XdfDefinitionRevision[]): { extraction: BinaryExtractionAudit; conversion: BinaryConversionAudit } {
  const extraction = { attempted: definitions.length, successful: 0, blocked: 0, outOfBounds: 0, representationConflicted: 0, unsupported: 0, unresolved: 0, invalid: 0, representativeFailures: [] as string[] };
  const conversion = { eligible: 0, converted: 0, identityNoOp: 0, invalidNumeric: 0, unsupported: 0, malformed: 0, missingEquation: 0, unitsUnresolved: 0, representativeFailures: [] as string[] };
  for (const definition of definitions) {
    const raw = extractRawCalibrationValues(binary, definition);
    if (raw.outcome === "extracted") extraction.successful += 1; else { extraction.blocked += 1; extraction[raw.outcome === "invalid" ? "invalid" : raw.outcome] += 1; if (raw.findings.some((item) => /boundary|out-of-bounds/i.test(item))) extraction.outOfBounds += 1; if (definition.identity.status === "conflicting") extraction.representationConflicted += 1; extraction.representativeFailures.push(...raw.findings); continue; }
    conversion.eligible += 1; const valueAxis = definition.axes.find((axis) => axis.axisId.toLowerCase() === "z") ?? definition.axes.at(-1); const equation = valueAxis?.equationSource; if (!equation) { conversion.missingEquation += 1; conversion.representativeFailures.push("Value equation is unavailable."); continue; } const parsed = parseXdfEquation(equation); if (parsed.outcome === "unsupported_expression") { conversion.unsupported += 1; conversion.representativeFailures.push(parsed.finding); continue; } if (parsed.outcome === "malformed_equation") { conversion.malformed += 1; conversion.representativeFailures.push(parsed.finding); continue; } const first = raw.shape?.values[0]; if (first === undefined) { conversion.invalidNumeric += 1; conversion.representativeFailures.push("Extracted value set is empty."); continue; } const evaluated = evaluateParsedXdfEquation(parsed, first); if (evaluated.outcome === "invalid_numeric_result") { conversion.invalidNumeric += 1; conversion.representativeFailures.push(evaluated.finding); continue; } if (parsed.outcome === "identity") conversion.identityNoOp += 1; else conversion.converted += 1; if (!valueAxis?.units) conversion.unitsUnresolved += 1;
  }
  return { extraction: freeze({ ...extraction, representativeFailures: unique(extraction.representativeFailures).slice(0, 20) }), conversion: freeze({ ...conversion, representativeFailures: unique(conversion.representativeFailures).slice(0, 20) }) };
}

export function constructCalibrationApplicabilityEvidencePackage(input: ApplicabilityEvidenceFactoryInput): CalibrationApplicabilityEvidencePackage {
  if (input.definitionSet.sourceArtifactDigest !== input.sourceArtifact.sourceDigest || input.definitionSet.definitionCount !== input.definitions.length) throw new Error("Evidence factory source does not bind the exact Definition Set.");
  const structural = structuralCensus(input.definitions);
  const auditedDefinitions = boundedAuditDefinitions(input.definitions);
  const xdfEvidence = collectXdfApplicabilityEvidence({ definitionSet: input.definitionSet, sourceArtifact: input.sourceArtifact, sourcePath: input.sourcePath, filename: input.sourceArtifact.filename, explicitHeaderIdentities: input.claimedIdentities, duplicateSourceDefinitionSetRevisionIds: input.duplicateSourceDefinitionSetRevisionIds, familyAssociation: input.sourceFamily, definitionCount: input.definitions.length, conflictingDefinitionCount: structural.representationConflicted, provenance: input.sourceProvenance, missingProvenance: input.sourceAuthority === "unresolved" ? ["authoritative source chain"] : [] });
  const binaries = input.binaryCandidates.map((candidate): CandidateBinaryEvidence => { const observations = collectInternalIdentityObservations({ binaryBytes: candidate.engineeringBinary.bytes, credibleIdentifiers: candidate.credibleIdentities }); const observed = new Set(observations.map((item) => item.normalizedForm)); const claimed = new Set(input.claimedIdentities.map((item) => item.toUpperCase())); const contradictoryMarkers = [...observed].filter((item) => !claimed.has(item) && candidate.credibleIdentities.find((entry) => entry.identifier.toUpperCase() === item)?.classification === "candidate_specific"); const binaryEvidence = collectEngineeringBinaryEvidence({ engineeringBinary: candidate.engineeringBinary, containerProvenance: candidate.engineeringBinary.source.resolutionEvidence, sourceFilename: candidate.engineeringBinary.source.fileName, internalIdentityObservations: observations, romFamilyObservations: [input.sourceFamily], softwareCalibrationObservations: observations.map((item) => item.normalizedForm), stockVariantKnowledge: candidate.stockVariantKnowledge, provisionalSourceRole: candidate.role, candidateRelationshipProvenance: candidate.provenance, findings: candidate.findings ?? [] }); const assessment = assessApplicabilityProposalEvidence({ claimedIdentifiers: input.claimedIdentities, binaryEvidence, xdfEvidence, directContradictions: [...(input.directContradictions ?? []), ...contradictoryMarkers.map((item) => `Contradictory candidate-specific marker ${item}.`)] }); const audits = auditBinary(candidate.engineeringBinary, auditedDefinitions); const proposal = constructApplicabilityProposal({ xdfEvidence, binaryEvidence, assessment, unresolvedConditions: ["Governed authority decision required"], conflictFindings: [...(input.directContradictions ?? []), ...contradictoryMarkers] }); return freeze({ digest: binaryEvidence.binaryDigest, byteLength: binaryEvidence.byteLength, containerType: binaryEvidence.containerType, role: candidate.role, provenance: unique(candidate.provenance), identityObservations: observations, candidateSpecificMarkers: unique(observations.filter((item) => candidate.credibleIdentities.find((entry) => entry.identifier.toUpperCase() === item.normalizedForm)?.classification === "candidate_specific").map((item) => item.normalizedForm)), commonSharedMarkers: unique(observations.filter((item) => candidate.credibleIdentities.find((entry) => entry.identifier.toUpperCase() === item.normalizedForm)?.classification === "common_shared").map((item) => item.normalizedForm)), contradictoryMarkers: unique(contradictoryMarkers), ambiguity: new Set(observations.map((item) => item.normalizedForm)).size > 1, stockVariantKnowledge: candidate.stockVariantKnowledge, ...audits, proposal }); });
  const identityConflicts = unique([...(input.directContradictions ?? []), ...binaries.flatMap((item) => item.contradictoryMarkers)]); const stockConflicts = binaries.filter((item) => item.stockVariantKnowledge?.availability === "available" && item.stockVariantKnowledge.result.status === "conflict").map((item) => `Stock Variant conflict for ${item.digest}.`); const conflicts: ApplicabilityConflictModel = freeze({ identity: identityConflicts, platformFamily: unique(input.platformConflicts ?? []), stockVariant: unique(stockConflicts), representation: structural.representationConflicted ? [`${structural.representationConflicted} Definition representations conflict.`] : [], equationUnit: unique([...structural.representativeBlockers.filter((item) => /equation|unit|numeric/i.test(item)), ...binaries.flatMap((item) => item.conversion.representativeFailures)]), sourceAuthority: unique(input.sourceAuthorityConflicts ?? []), duplicateSource: (input.duplicateSourceDefinitionSetRevisionIds?.length ?? 0) ? ["Duplicate source digest is associated with multiple Definition Set revisions."] : [], binaryCandidate: binaries.length > 2 ? [`${binaries.length} exact binary candidates require role/lineage review.`] : [] });
  const hardConflicts = [...conflicts.identity, ...conflicts.platformFamily, ...conflicts.stockVariant, ...conflicts.sourceAuthority]; let outcome: EvidenceReadiness; const reasons: string[] = []; if (!binaries.length) { outcome = "no_responsible_candidate"; reasons.push("No responsibly prefiltered candidate binary was supplied."); } else if (hardConflicts.length) { outcome = "technical_conflict"; reasons.push(...hardConflicts); } else if (input.sourceAuthority === "unresolved" || !input.authorityProvenance.length) { outcome = "source_authority_unresolved"; reasons.push("Technical Evidence cannot replace missing source authority/provenance."); } else if (binaries.some((item) => item.extraction.invalid > 0 || item.extraction.successful === 0)) { outcome = "more_evidence_required"; reasons.push("One or more binary candidates lack sufficient structural extraction proof."); } else if (!binaries.some((item) => item.identityObservations.some((observation) => input.claimedIdentities.map((value) => value.toUpperCase()).includes(observation.normalizedForm)))) { outcome = "more_evidence_required"; reasons.push("No candidate-specific claimed identity was observed."); } else { outcome = "ready_for_authority_review"; reasons.push("Technical Evidence is complete enough for governed review; no applicability acceptance is implied."); }
  const source = freeze({ artifactId: input.sourceArtifact.artifactId, digest: input.sourceArtifact.sourceDigest, definitionSetId: input.definitionSet.definitionSetId, definitionSetRevision: input.definitionSet.revisionId, path: input.sourcePath, family: input.sourceFamily, status: input.sourceStatus, provenance: unique(input.sourceProvenance), authority: input.sourceAuthority, authorityProvenance: unique(input.authorityProvenance) }); const contracts = freeze({ extraction: CALIBRATION_VALUE_EXTRACTOR_CONTRACT, conversion: ENGINEERING_VALUE_CONVERSION_CONTRACT }); const limitations = unique([...(input.limitations ?? []), ...(input.definitions.length > auditedDefinitions.length ? [`Per-binary extraction/conversion audit is deterministically bounded to ${auditedDefinitions.length} representative Definitions from ${input.definitions.length}; the structural census covers the complete Definition Set.`] : [])]); const packageId = `calibration-applicability-evidence-package:${hash("tunesight.calibration-applicability-evidence-package-relationship.v1", { definitionSetId: input.definitionSet.definitionSetId, binaryDigests: binaries.map((item) => item.digest).sort() })}`; const material = { contractVersion: CALIBRATION_APPLICABILITY_EVIDENCE_PACKAGE_CONTRACT, source, structural, binaries, conflicts, limitations, readiness: freeze({ outcome, reasons: unique(reasons), authorityDecision: "required" as const }), contracts, publicationSideEffects: freeze([]) as readonly [] }; const packageRevision = `calibration-applicability-evidence-package-revision:${hash("tunesight.calibration-applicability-evidence-package-revision.v1", material)}`; return freeze({ packageId, packageRevision, ...material });
}

export type ApplicabilityEvidenceBatchJob = Readonly<{ jobId: string; input: ApplicabilityEvidenceFactoryInput | null; prefilterRejection: string | null }>;
export function constructCalibrationApplicabilityEvidenceBatch(jobs: readonly ApplicabilityEvidenceBatchJob[]): readonly Readonly<{ jobId: string; package: CalibrationApplicabilityEvidencePackage | null; prefilterRejection: string | null }>[] { const ids = new Set<string>(); return freeze([...jobs].sort((a, b) => a.jobId.localeCompare(b.jobId)).map((job) => { if (!job.jobId.trim() || ids.has(job.jobId)) throw new Error("Evidence batch job identities must be unique."); ids.add(job.jobId); if (job.prefilterRejection) return { jobId: job.jobId, package: null, prefilterRejection: job.prefilterRejection }; if (!job.input) throw new Error("Non-rejected Evidence batch job requires factory input."); return { jobId: job.jobId, package: constructCalibrationApplicabilityEvidencePackage(job.input), prefilterRejection: null }; })); }
