import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import type { RuntimeStockVariantKnowledgeResponse } from "../knowledge/runtimeStockVariantKnowledge.ts";
import { resolveBinaryContainer, type EngineeringBinary } from "../tunes/binaryContainer.ts";
import { constructCalibrationApplicabilityEvidenceBatch, constructCalibrationApplicabilityEvidencePackage, type ApplicabilityCandidateBinary, type ApplicabilityEvidenceFactoryInput, type CredibleIdentityCandidate } from "./calibrationApplicabilityEvidenceFactory.ts";
import { defineDefinitionSetRevision } from "./definitionRomApplicability.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "BMW-XDFs-master");
const currentN54 = ["I8A0S", "IJE0S", "IKM0S", "INA0S"] as const;
const stockCandidate: RuntimeStockVariantKnowledgeResponse = Object.freeze({ availability: "available", unavailableReason: null, result: Object.freeze({ status: "exact_candidate", explanation: "Filename role is candidate Evidence only." }) as never });

function parse(relative: string) { const full = path.join(root, relative); const result = interpretXdfStructure({ xml: fs.readFileSync(full, "utf8"), filename: path.basename(full), provenance: `BMW master source ${relative}` }); assert.equal(result.outcome, "structurally_interpreted"); assert.ok(result.sourceArtifact); return { relative, sourceArtifact: result.sourceArtifact!, definitions: result.definitions, definitionSet: defineDefinitionSetRevision({ sourceArtifact: result.sourceArtifact!, definitions: result.definitions }) }; }
function binary(relative: string): EngineeringBinary { const bytes = fs.readFileSync(path.join(root, relative)); const result = resolveBinaryContainer({ bytes, fileName: path.basename(relative) }); assert.equal(result.status, "resolved"); return result.engineeringBinary!; }
function identities(specific: string, common?: string): readonly CredibleIdentityCandidate[] { return Object.freeze([{ identifier: specific, kind: /^\d/.test(specific) ? "calibration_identifier" as const : "ascii_rom_marker" as const, confidence: "candidate_correspondence" as const, reason: "Candidate-specific repository identity", encodings: ["ascii" as const, "hex_encoded" as const], classification: "candidate_specific" as const }, ...(common && common !== specific ? [{ identifier: common, kind: "family_marker" as const, confidence: "candidate_correspondence" as const, reason: "Known common/shared MG1 marker", encodings: ["ascii" as const, "hex_encoded" as const], classification: "common_shared" as const }] : [])]); }
function candidate(relative: string, specific: string, common?: string): ApplicabilityCandidateBinary { const engineeringBinary = binary(relative); return { engineeringBinary, role: /mapswitch/i.test(relative) ? "mapswitch" : /original/i.test(relative) ? "stock_original" : "other_observed", provenance: [`Repository co-location candidate ${relative}`], stockVariantKnowledge: stockCandidate, credibleIdentities: identities(specific, common) }; }
function input(relativeXdf: string, claimed: string, bins: readonly string[], options: Partial<ApplicabilityEvidenceFactoryInput> = {}): ApplicabilityEvidenceFactoryInput { const source = parse(relativeXdf); return { ...source, sourcePath: relativeXdf, sourceFamily: relativeXdf.split("/")[0]!, sourceStatus: /legacy/i.test(relativeXdf) ? "legacy" : "current", claimedIdentities: [claimed], binaryCandidates: bins.map((item) => candidate(item, claimed, /^00005D/.test(claimed) ? "00003076501103" : undefined)), sourceProvenance: [`Repository-held source ${relativeXdf}`], sourceAuthority: "unresolved", authorityProvenance: [], limitations: ["Repository co-location and filenames are not applicability authority."], ...options }; }

test("package identity, revision, bindings, cohort, Stock separation and immutability are deterministic", () => { const base = input("N54/IJE0S.xdf", "IJE0S", ["N54/IJE0S_original.bin", "N54/IJE0S_MapSwitchBase.bin"], { sourceAuthority: "established", authorityProvenance: ["Accepted current N54 Founder authority"] }); const first = constructCalibrationApplicabilityEvidencePackage(base); const again = constructCalibrationApplicabilityEvidencePackage(base); assert.deepEqual(first, again); assert.equal(first.binaries.length, 2); assert.equal(first.binaries[0]?.proposal.authorityDecision, "pending"); assert.deepEqual(first.publicationSideEffects, []); assert.equal(first.source.definitionSetRevision, base.definitionSet.revisionId); assert.equal(first.source.digest, base.sourceArtifact.sourceDigest); assert.ok(first.binaries.every((item) => item.stockVariantKnowledge?.availability === "available")); assert.ok(Object.isFrozen(first) && Object.isFrozen(first.structural) && Object.isFrozen(first.binaries[0])); const authorityChanged = constructCalibrationApplicabilityEvidencePackage({ ...base, authorityProvenance: ["Different material authority"] }); assert.equal(authorityChanged.packageId, first.packageId); assert.notEqual(authorityChanged.packageRevision, first.packageRevision); const changedBinary = constructCalibrationApplicabilityEvidencePackage({ ...base, binaryCandidates: base.binaryCandidates.slice(0, 1) }); assert.notEqual(changedBinary.packageId, first.packageId); });

test("structural, extraction and conversion censuses retain exact minority failures", () => { const packageEvidence = constructCalibrationApplicabilityEvidencePackage(input("N54/IJE0S_Legacy.xdf", "IJE0S", ["N54/IJE0S_original.bin"])); assert.equal(packageEvidence.structural.total, 562); assert.ok(packageEvidence.structural.scalar > 0 && packageEvidence.structural.oneDimensional > 0 && packageEvidence.structural.twoDimensional > 0); assert.ok(packageEvidence.structural.representationConflicted > 0); assert.equal(packageEvidence.structural.extractionCapable + packageEvidence.structural.extractionBlocked, 562); assert.equal(packageEvidence.binaries[0]!.extraction.attempted, 8); assert.equal(packageEvidence.binaries[0]!.extraction.successful + packageEvidence.binaries[0]!.extraction.blocked, 8); assert.equal(packageEvidence.binaries[0]!.conversion.eligible, packageEvidence.binaries[0]!.extraction.successful); assert.ok(packageEvidence.limitations.some((item) => item.includes("deterministically bounded"))); assert.ok(packageEvidence.conflicts.representation.length > 0); });

test("N54 governed cohort is a positive control and wrong-ROM pairing is a negative control", () => { for (const rom of currentN54) { const evidence = constructCalibrationApplicabilityEvidencePackage(input(`N54/${rom}.xdf`, rom, [`N54/${rom}_original.bin`, `N54/${rom}_MapSwitchBase.bin`], { sourceAuthority: "established", authorityProvenance: [`Accepted ${rom} governed authority`] })); assert.equal(evidence.readiness.outcome, "ready_for_authority_review", rom); assert.equal(evidence.binaries.length, 2); assert.ok(evidence.binaries.every((item) => item.identityObservations.some((observation) => observation.normalizedForm === rom))); assert.equal(evidence.publicationSideEffects.length, 0); } const wrong = constructCalibrationApplicabilityEvidencePackage(input("N54/IJE0S.xdf", "IJE0S", ["N54/INA0S_original.bin"], { sourceAuthority: "established", authorityProvenance: ["Accepted N54 authority"], binaryCandidates: [{ ...candidate("N54/INA0S_original.bin", "INA0S"), credibleIdentities: identities("INA0S") }] })); assert.equal(wrong.readiness.outcome, "technical_conflict"); assert.ok(wrong.conflicts.identity.some((item) => item.includes("INA0S") || item.includes("claimed"))); });

function cohort(family: "s58" | "B58gen2") { const familyRoot = path.join(root, family); const xdfs: string[] = []; const walk = (directory: string) => fs.readdirSync(directory, { withFileTypes: true }).forEach((entry) => { const full = path.join(directory, entry.name); if (entry.isDirectory()) walk(full); else if (entry.name.toLowerCase().endsWith(".xdf")) xdfs.push(full); }); walk(familyRoot); return xdfs.sort().map((full) => { const relative = path.relative(root, full).replaceAll("\\", "/"); const claimed = path.basename(full, ".xdf"); const bins = fs.readdirSync(path.dirname(full)).filter((name) => name.toLowerCase().endsWith(".bin") && path.basename(name, ".bin").toLowerCase().startsWith(claimed.toLowerCase())).sort().map((name) => `${path.dirname(relative).replaceAll("\\", "/")}/${name}`); return { claimed, bins, input: input(relative, claimed, bins) }; }); }

test("complete S58 discovery produces ten real source-bound authority-unresolved packages", (context) => { const started = performance.now(); const sources = cohort("s58"); const packages = sources.map((item) => constructCalibrationApplicabilityEvidencePackage(item.input)); assert.equal(sources.length, 10); assert.ok(sources.every((item) => item.bins.length === 2)); assert.ok(packages.every((item) => item.source.family === "s58" && item.readiness.outcome === "source_authority_unresolved" && item.structural.representationConflicted === 0)); assert.equal(packages.reduce((sum, item) => sum + item.structural.total, 0), 12556); assert.equal(packages.reduce((sum, item) => sum + item.binaries.length, 0), 20); assert.ok(packages.every((item) => item.binaries.some((binaryEvidence) => binaryEvidence.candidateSpecificMarkers.length > 0))); context.diagnostic(`S58_EVIDENCE_FACTORY ${JSON.stringify({ sources: packages.length, binaries: 20, milliseconds: Math.round(performance.now() - started), readiness: { source_authority_unresolved: packages.length } })}`); });

test("complete B58 Gen2 discovery preserves observed markers, missing binaries and authority limits", (context) => { const started = performance.now(); const sources = cohort("B58gen2"); const packages = sources.map((item) => constructCalibrationApplicabilityEvidencePackage(item.input)); const noCandidate = packages.filter((item) => item.readiness.outcome === "no_responsible_candidate"); const binaries = packages.flatMap((item) => item.binaries); assert.equal(sources.length, 45); assert.equal(packages.reduce((sum, item) => sum + item.structural.total, 0), 55667); assert.equal(binaries.length, 121); assert.ok(noCandidate.length > 0); assert.ok(packages.filter((item) => item.binaries.length > 0).every((item) => item.readiness.outcome === "source_authority_unresolved")); assert.ok(binaries.some((item) => item.candidateSpecificMarkers.length > 0)); assert.ok(binaries.every((item) => item.commonSharedMarkers.length === 0)); context.diagnostic(`B58_GEN2_EVIDENCE_FACTORY ${JSON.stringify({ sources: packages.length, binaries: binaries.length, noCandidate: noCandidate.length, suppliedCommonMarkerObserved: false, milliseconds: Math.round(performance.now() - started), readiness: { source_authority_unresolved: packages.length - noCandidate.length, no_responsible_candidate: noCandidate.length } })}`); });

test("B58 Gen1 ambiguity and representation conflict fit the generic package without new types", () => { const base = binary("B58gen1/000030765A3C06_original.bin"); const bytes = new Uint8Array(base.bytes); bytes.set(Buffer.from("000030765A3C06", "utf8"), 100); bytes.set(Buffer.from("00003076501103", "utf8"), 200); const resolved = resolveBinaryContainer({ bytes, fileName: "controlled-mg1-shaped.bin" }); assert.equal(resolved.status, "resolved"); const controlledCandidate: ApplicabilityCandidateBinary = { engineeringBinary: resolved.engineeringBinary!, role: "other_observed", provenance: ["Controlled MG1-shaped ambiguity compatibility fixture"], stockVariantKnowledge: stockCandidate, credibleIdentities: identities("000030765A3C06", "00003076501103") }; const evidence = constructCalibrationApplicabilityEvidencePackage(input("B58gen1/000030765A3C06.xdf", "000030765A3C06", [], { binaryCandidates: [controlledCandidate] })); assert.ok(evidence.structural.representationConflicted > 0); assert.ok(evidence.binaries.some((item) => item.ambiguity)); assert.ok(evidence.binaries.some((item) => item.commonSharedMarkers.length > 0)); assert.ok(evidence.conflicts.representation.length > 0); assert.equal(evidence.readiness.outcome, "source_authority_unresolved"); });

test("readiness outcomes and deterministic responsible batch construction remain authority-free", () => { const valid = input("N54/I8A0S.xdf", "I8A0S", ["N54/I8A0S_original.bin"], { sourceAuthority: "established", authorityProvenance: ["Accepted authority"] }); const more = constructCalibrationApplicabilityEvidencePackage({ ...valid, claimedIdentities: ["UNOBSERVED"], binaryCandidates: valid.binaryCandidates.map((item) => ({ ...item, credibleIdentities: identities("UNOBSERVED") })) }); assert.equal(more.readiness.outcome, "more_evidence_required"); const none = constructCalibrationApplicabilityEvidencePackage({ ...valid, binaryCandidates: [] }); assert.equal(none.readiness.outcome, "no_responsible_candidate"); const conflict = constructCalibrationApplicabilityEvidencePackage({ ...valid, directContradictions: ["Known ROM identity contradiction."] }); assert.equal(conflict.readiness.outcome, "technical_conflict"); const jobs = [{ jobId: "z-rejected", input: null, prefilterRejection: "Known container-family incompatibility." }, { jobId: "a-package", input: valid, prefilterRejection: null }] as const; const batch = constructCalibrationApplicabilityEvidenceBatch(jobs); assert.deepEqual(batch.map((item) => item.jobId), ["a-package", "z-rejected"]); assert.equal(batch[0]?.package?.readiness.outcome, "ready_for_authority_review"); assert.equal(batch[1]?.package, null); assert.deepEqual(batch[0]?.package?.publicationSideEffects, []); assert.deepEqual(constructCalibrationApplicabilityEvidenceBatch(jobs), batch); });

test("BMW-generic inputs can represent mixed-family, binary-absent and conflict cohorts", () => { const families = [["F series N55 S55 N13/00005BA8134601.xdf", "00005BA8134601"], ["N55E/98G0B.xdf", "98G0B"], ["S63/000010CA3B8C01.xdf", "000010CA3B8C01"], ["B58gen1/000030765A5005.xdf", "000030765A5005"]] as const; for (const [xdf, identity] of families) { const evidence = constructCalibrationApplicabilityEvidencePackage(input(xdf, identity, [])); assert.equal(evidence.readiness.outcome, "no_responsible_candidate"); assert.equal(evidence.publicationSideEffects.length, 0); } });
