import { createHash } from "node:crypto";
import type { EcuIdentityObservation } from "../vehicle-interface/nativeVehicleData.ts";

export const DEFINITION_COVERAGE_DISCOVERY_CONTRACT = "tunesight.definition-coverage-discovery.v1" as const;
export type DefinitionCoverageOutcome = "EXACT_DEFINITION_COVERAGE" | "CANDIDATE_DEFINITION_COVERAGE" | "ROM_RECOGNIZED_DEFINITIONS_UNAVAILABLE" | "NEW_ROM_DISCOVERED" | "CONFLICT" | "INVALID";
export type ConnectedRomObservation = Readonly<{ observation: EcuIdentityObservation; trust: "qualified_read_only_observation" | "qualified_supplied_evidence"; ecuFamily: string | null; binary: Readonly<{ digest: string; byteLength: number; container: string; markers: readonly Readonly<{ marker: string; offsets: readonly number[] }>[] }> | null; provenance: readonly string[]; limitations: readonly string[] }>;
export type DefinitionCoverageCandidate = Readonly<{ candidateId: string; family: string | null; romSoftwareIdentity: string; calibrationIdentity: string | null; sourceArtifactId: string; sourceArtifactRevision: string; definitionSetRevision: string; coverageState: "exact_qualified" | "candidate_only"; exactIdentityEvidence: readonly string[]; provenance: readonly string[]; limitations: readonly string[] }>;
export type NewRomDiscoveryPackage = Readonly<{ packageId: string; packageRevision: string; contractVersion: "tunesight.new-rom-discovery-evidence.v1"; dmeFamily: string | null; ecuFamily: string | null; softwareIdentity: string | null; calibrationIdentity: string | null; binary: ConnectedRomObservation["binary"]; relatedCandidateIds: readonly string[]; conflicts: readonly string[]; provenance: readonly string[]; limitations: readonly string[]; state: "discovery_evidence_only" }>;
export type DefinitionCoverageResolution = Readonly<{ resolutionId: string; resolutionRevision: string; contractVersion: typeof DEFINITION_COVERAGE_DISCOVERY_CONTRACT; outcome: DefinitionCoverageOutcome; observationId: string; exactDefinitionSetRevision: string | null; candidateIds: readonly string[]; discoveryPackage: NewRomDiscoveryPackage | null; workshopEligible: boolean; workshopMessage: string; findings: readonly string[]; publicationSideEffects: readonly [] }>;
export type CrossRomCorrespondenceEvidence = Readonly<{ evidenceId: string; evidenceRevision: string; newRomIdentity: string; relatedQualifiedRomIdentity: string; signals: readonly Readonly<{ kind: "binary_structure" | "definition_address" | "axis_value_structure" | "rom_lineage" | "neighbouring_software_revision"; evidence: string }>[]; state: "candidate_evidence_only"; applicabilityAccepted: false; tableTransplantAuthorized: false }>;

function canonical(value: unknown): string { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isFinite(value)) throw new Error("Discovery Evidence contains a non-finite number."); return JSON.stringify(value); } if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (!value || typeof value !== "object") throw new Error("Discovery Evidence contains unsupported material."); const object = value as Readonly<Record<string, unknown>>; return `{${Object.keys(object).sort().map((key) => `${JSON.stringify(key)}:${canonical(object[key])}`).join(",")}}`; }
function digest(domain: string, value: unknown): string { return createHash("sha256").update(domain).update(Buffer.from([0])).update(canonical(value)).digest("hex"); }
function freeze<T>(value: T): T { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as T; if (value && typeof value === "object") return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, freeze(item)]))) as T; return value; }
function normal(value: string | null): string | null { const normalized = value?.trim().toUpperCase() ?? ""; return normalized || null; }
function exact(candidate: DefinitionCoverageCandidate, software: string | null, calibration: string | null): boolean { return normal(candidate.romSoftwareIdentity) === software && (candidate.calibrationIdentity === null || normal(candidate.calibrationIdentity) === calibration) && candidate.exactIdentityEvidence.length > 0; }

function discoveryPackage(input: ConnectedRomObservation, candidates: readonly DefinitionCoverageCandidate[], conflicts: readonly string[]): NewRomDiscoveryPackage {
  const stable = { observationId: input.observation.observationId, softwareIdentity: normal(input.observation.softwareIdentity), calibrationIdentity: normal(input.observation.calibrationIdentity), binaryDigest: input.binary?.digest ?? null }; const material = { ...stable, dmeFamily: normal(input.observation.observedDmeFamily), ecuFamily: normal(input.ecuFamily), binary: input.binary, relatedCandidateIds: candidates.map((item) => item.candidateId).sort(), conflicts: [...conflicts].sort(), provenance: [...new Set([input.observation.provenance, ...input.provenance])].sort(), limitations: [...new Set(input.limitations)].sort(), contractVersion: "tunesight.new-rom-discovery-evidence.v1" as const, state: "discovery_evidence_only" as const };
  return freeze({ packageId: `new-rom-discovery-package:${digest("tunesight.new-rom-discovery-package-identity.v1", stable)}`, packageRevision: `new-rom-discovery-package-revision:${digest("tunesight.new-rom-discovery-package-revision.v1", material)}`, ...material });
}

export function resolveDefinitionCoverage(input: Readonly<{ connectedRom: ConnectedRomObservation; recognizedRomIdentities: readonly string[]; candidates: readonly DefinitionCoverageCandidate[]; conflicts?: readonly string[] }>): DefinitionCoverageResolution {
  const software = normal(input.connectedRom.observation.softwareIdentity), calibration = normal(input.connectedRom.observation.calibrationIdentity), conflicts = [...new Set(input.conflicts ?? [])].sort(); const recognized = new Set(input.recognizedRomIdentities.map((item) => item.trim().toUpperCase()).filter(Boolean)); const exactMatches = input.candidates.filter((item) => exact(item, software, calibration)); const exactQualified = exactMatches.filter((item) => item.coverageState === "exact_qualified"); const candidateOnly = exactMatches.filter((item) => item.coverageState === "candidate_only");
  let outcome: DefinitionCoverageOutcome; let chosen: DefinitionCoverageCandidate | null = null; const findings: string[] = [];
  if (!software || !input.connectedRom.observation.observationId || !input.connectedRom.provenance.some((item) => item.trim())) { outcome = "INVALID"; findings.push("A trustworthy observation identity, software identity and provenance are required."); }
  else if (conflicts.length || exactQualified.length > 1 || (exactQualified.length && candidateOnly.length)) { outcome = "CONFLICT"; findings.push("Identity or Definition coverage Evidence contradicts; no Definition Set is selected."); }
  else if (exactQualified.length === 1) { outcome = "EXACT_DEFINITION_COVERAGE"; chosen = exactQualified[0]!; findings.push("One exact identity match has qualified Definition coverage."); }
  else if (candidateOnly.length > 0) { outcome = "CANDIDATE_DEFINITION_COVERAGE"; findings.push("Exact-identity candidate Evidence exists, but applicability is not qualified."); }
  else if (recognized.has(software)) { outcome = "ROM_RECOGNIZED_DEFINITIONS_UNAVAILABLE"; findings.push("ROM identity is recognized, but no responsible exact Definition source exists."); }
  else { outcome = "NEW_ROM_DISCOVERED"; findings.push("The observed ROM/software identity is outside the recognized registry; discovery Evidence only was created."); }
  if (!exactMatches.length && input.candidates.some((item) => normal(item.family) === normal(input.connectedRom.observation.observedDmeFamily))) findings.push("Family-only similarity was rejected as Definition authority.");
  const candidates = outcome === "CANDIDATE_DEFINITION_COVERAGE" ? candidateOnly : outcome === "CONFLICT" ? exactMatches : []; const discovery = ["EXACT_DEFINITION_COVERAGE", "INVALID"].includes(outcome) ? null : discoveryPackage(input.connectedRom, candidates, conflicts); const workshopEligible = outcome === "EXACT_DEFINITION_COVERAGE"; const workshopMessage = workshopEligible ? "Qualified Calibration Tables available" : outcome === "NEW_ROM_DISCOVERED" ? "New ROM discovery awaiting Definition qualification" : outcome === "INVALID" ? "ROM observation invalid" : outcome === "CONFLICT" ? "Calibration Definition Evidence conflict" : "Calibration Tables awaiting qualification"; const identity = { observationId: input.connectedRom.observation.observationId, outcome, exactDefinitionSetRevision: chosen?.definitionSetRevision ?? null }; const material = { ...identity, candidateIds: candidates.map((item) => item.candidateId).sort(), discoveryPackageRevision: discovery?.packageRevision ?? null, findings, workshopEligible, workshopMessage, contractVersion: DEFINITION_COVERAGE_DISCOVERY_CONTRACT };
  return freeze({ resolutionId: `definition-coverage-resolution:${digest("tunesight.definition-coverage-resolution-identity.v1", identity)}`, resolutionRevision: `definition-coverage-resolution-revision:${digest("tunesight.definition-coverage-resolution-revision.v1", material)}`, contractVersion: DEFINITION_COVERAGE_DISCOVERY_CONTRACT, outcome, observationId: input.connectedRom.observation.observationId, exactDefinitionSetRevision: chosen?.definitionSetRevision ?? null, candidateIds: candidates.map((item) => item.candidateId).sort(), discoveryPackage: discovery, workshopEligible, workshopMessage, findings, publicationSideEffects: Object.freeze([]) as readonly [] });
}

export function constructCrossRomCorrespondenceEvidence(input: Readonly<{ newRomIdentity: string; relatedQualifiedRomIdentity: string; signals: CrossRomCorrespondenceEvidence["signals"] }>): CrossRomCorrespondenceEvidence {
  if (!input.newRomIdentity.trim() || !input.relatedQualifiedRomIdentity.trim() || !input.signals.length) throw new Error("Cross-ROM candidate Evidence requires two identities and at least one explicit signal."); const identity = { newRomIdentity: input.newRomIdentity.trim().toUpperCase(), relatedQualifiedRomIdentity: input.relatedQualifiedRomIdentity.trim().toUpperCase() }; const material = { ...identity, signals: input.signals, state: "candidate_evidence_only" as const, applicabilityAccepted: false as const, tableTransplantAuthorized: false as const };
  return freeze({ evidenceId: `cross-rom-correspondence-evidence:${digest("tunesight.cross-rom-correspondence-evidence-identity.v1", identity)}`, evidenceRevision: `cross-rom-correspondence-evidence-revision:${digest("tunesight.cross-rom-correspondence-evidence-revision.v1", material)}`, ...material });
}
