import assert from "node:assert/strict";
import test from "node:test";
import { defineEcuIdentityObservation } from "../vehicle-interface/nativeVehicleData.ts";
import { bindCanonicalDefinitionSet, defineCanonicalDefinitionSource } from "./canonicalDefinitionSource.ts";
import { defineDefinitionSetRevision } from "./definitionRomApplicability.ts";
import { constructCrossRomCorrespondenceEvidence, resolveDefinitionCoverage, type ConnectedRomObservation, type DefinitionCoverageCandidate } from "./definitionCoverageDiscovery.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";

function observation(softwareIdentity: string | null, family = "FUTURE-DME") { return defineEcuIdentityObservation({ sessionId: "session:read-only", endpointId: "dme:1", protocol: "qualified-fixture", observedDmeFamily: family, softwareIdentity, calibrationIdentity: softwareIdentity, vin: null, observedAt: "2026-09-01T00:00:00.000Z", capabilityObservations: ["identification_read"], qualification: "observed_unqualified", provenance: "Controlled read-only identity fixture" }); }
function connected(softwareIdentity: string | null, family = "FUTURE-DME", binary = true): ConnectedRomObservation { return { observation: observation(softwareIdentity, family), trust: "qualified_read_only_observation", ecuFamily: family, binary: binary ? { digest: "a".repeat(64), byteLength: 4096, container: "raw_binary", markers: [{ marker: softwareIdentity ?? "UNKNOWN", offsets: [16, 2048] }] } : null, provenance: ["Qualified read-only Vehicle Interface observation"], limitations: ["Observation is Evidence only."] }; }
function candidate(identity: string, state: DefinitionCoverageCandidate["coverageState"] = "exact_qualified", overrides: Partial<DefinitionCoverageCandidate> = {}): DefinitionCoverageCandidate { return { candidateId: `candidate:${identity}:${state}`, family: "FUTURE-DME", romSoftwareIdentity: identity, calibrationIdentity: identity, sourceArtifactId: `source:${identity}`, sourceArtifactRevision: `source-revision:${identity}`, definitionSetRevision: `set-revision:${identity}`, coverageState: state, exactIdentityEvidence: [`Exact software identity ${identity}`], provenance: ["Controlled candidate"], limitations: ["Fixture only"], ...overrides }; }

test("exact known ROM alone enables exact Definition coverage and Workshop eligibility", () => { const result = resolveDefinitionCoverage({ connectedRom: connected("ROM-1"), recognizedRomIdentities: ["ROM-1"], candidates: [candidate("ROM-1")] }); assert.equal(result.outcome, "EXACT_DEFINITION_COVERAGE"); assert.equal(result.exactDefinitionSetRevision, "set-revision:ROM-1"); assert.equal(result.workshopEligible, true); assert.deepEqual(result.publicationSideEffects, []); });
test("known ROM without Definitions and new unknown ROM remain truthful discovery states", () => { const known = resolveDefinitionCoverage({ connectedRom: connected("ROM-KNOWN", "DME-X", false), recognizedRomIdentities: ["ROM-KNOWN"], candidates: [] }), fresh = resolveDefinitionCoverage({ connectedRom: connected("ROM-NEW", "DME-UNLISTED"), recognizedRomIdentities: [], candidates: [] }); assert.equal(known.outcome, "ROM_RECOGNIZED_DEFINITIONS_UNAVAILABLE"); assert.equal(known.workshopMessage, "Calibration Tables awaiting qualification"); assert.equal(fresh.outcome, "NEW_ROM_DISCOVERED"); assert.equal(fresh.workshopEligible, false); assert.equal(fresh.discoveryPackage?.binary?.digest, "a".repeat(64)); assert.equal(fresh.discoveryPackage?.state, "discovery_evidence_only"); });
test("candidate, ambiguous and conflicting coverage never expose authoritative Tables", () => { const plausible = candidate("ROM-2", "candidate_only"), result = resolveDefinitionCoverage({ connectedRom: connected("ROM-2"), recognizedRomIdentities: ["ROM-2"], candidates: [plausible] }); assert.equal(result.outcome, "CANDIDATE_DEFINITION_COVERAGE"); assert.equal(result.workshopEligible, false); const ambiguous = resolveDefinitionCoverage({ connectedRom: connected("ROM-2"), recognizedRomIdentities: ["ROM-2"], candidates: [plausible, candidate("ROM-2", "candidate_only", { candidateId: "candidate:other" })] }); assert.equal(ambiguous.outcome, "CANDIDATE_DEFINITION_COVERAGE"); assert.equal(ambiguous.candidateIds.length, 2); const conflict = resolveDefinitionCoverage({ connectedRom: connected("ROM-2"), recognizedRomIdentities: ["ROM-2"], candidates: [candidate("ROM-2"), plausible], conflicts: ["Exact candidates disagree"] }); assert.equal(conflict.outcome, "CONFLICT"); assert.equal(conflict.workshopEligible, false); });
test("family, filename-shaped, numeric-neighbour and ECU similarity never create fuzzy authority", () => { for (const related of [candidate("ROM-100"), candidate("ROM-101", "candidate_only", { sourceArtifactId: "ROM-102.xdf" })]) { const result = resolveDefinitionCoverage({ connectedRom: connected("ROM-102", related.family!), recognizedRomIdentities: [], candidates: [related] }); assert.equal(result.outcome, "NEW_ROM_DISCOVERED"); assert.equal(result.exactDefinitionSetRevision, null); assert.ok(result.findings.some((item) => item.includes("Family-only"))); } });
test("invalid observations fail closed", () => { const result = resolveDefinitionCoverage({ connectedRom: connected(null), recognizedRomIdentities: [], candidates: [] }); assert.equal(result.outcome, "INVALID"); assert.equal(result.discoveryPackage, null); assert.equal(result.workshopEligible, false); });
test("discovery package identity is deterministic and material binary changes revise it", () => { const first = resolveDefinitionCoverage({ connectedRom: connected("FUTURE-1"), recognizedRomIdentities: [], candidates: [] }), replay = resolveDefinitionCoverage({ connectedRom: connected("FUTURE-1"), recognizedRomIdentities: [], candidates: [] }), changed = resolveDefinitionCoverage({ connectedRom: { ...connected("FUTURE-1"), binary: { ...connected("FUTURE-1").binary!, digest: "b".repeat(64) } }, recognizedRomIdentities: [], candidates: [] }); assert.equal(first.discoveryPackage?.packageRevision, replay.discoveryPackage?.packageRevision); assert.notEqual(first.discoveryPackage?.packageRevision, changed.discoveryPackage?.packageRevision); assert.equal(Object.isFrozen(first.discoveryPackage), true); });
test("cross-ROM correspondence remains candidate Evidence without acceptance or transplantation", () => { const evidence = constructCrossRomCorrespondenceEvidence({ newRomIdentity: "FUTURE-1", relatedQualifiedRomIdentity: "KNOWN-1", signals: [{ kind: "binary_structure", evidence: "Controlled structural correspondence" }] }); assert.equal(evidence.state, "candidate_evidence_only"); assert.equal(evidence.applicabilityAccepted, false); assert.equal(evidence.tableTransplantAuthorized, false); });
test("canonical Definition abstraction is source-format neutral", () => { const parsed = interpretXdfStructure({ xml: `<?xml version="1.0"?><XDFFORMAT version="1.70"><XDFHEADER><deftitle>Fixture</deftitle></XDFHEADER><XDFTABLE uniqueid="0x1" flags="0x0"><title>Scalar</title><XDFAXIS id="z"><EMBEDDEDDATA mmedaddress="0x10" mmedelementsizebits="8"/><MATH equation="X"/></XDFAXIS></XDFTABLE></XDFFORMAT>`, filename: "fixture.xdf", provenance: "Controlled source adapter" }); assert.equal(parsed.outcome, "structurally_interpreted"); const set = defineDefinitionSetRevision({ sourceArtifact: parsed.sourceArtifact!, definitions: parsed.definitions }), xdf = defineCanonicalDefinitionSource({ format: "xdf_xml", artifactId: parsed.sourceArtifact!.artifactId, artifactDigest: parsed.sourceArtifact!.sourceDigest, provenance: ["XDF adapter"], limitations: [] }), canonical = bindCanonicalDefinitionSet({ source: xdf, definitionSet: set, definitions: parsed.definitions }); assert.equal(canonical.definitions.length, 1); const future = defineCanonicalDefinitionSource({ format: "tunesight_native", artifactId: "native-source:1", artifactDigest: `sha256:${"c".repeat(64)}`, provenance: ["Future native source"], limitations: ["Not admitted"] }); assert.notEqual(xdf.sourceId, future.sourceId); assert.equal(future.format, "tunesight_native"); });
