import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { defineXdfDefinitionRevision, type XdfAxisDefinition, type XdfDefinitionRevision } from "./canonicalXdfDefinition.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import type { QualifiedRawCalibrationValueEvidence } from "./qualifiedCalibrationExtraction.ts";

export const XDF_EQUATION_LIMITS = Object.freeze({ maximumLength: 256, maximumTokens: 128, maximumAstDepth: 16, maximumNumericLiteralMagnitude: 1e100, maximumResultMagnitude: 1e300 });
export const ENGINEERING_VALUE_CONVERSION_CONTRACT = "tunesight.engineering-value-conversion.v1" as const;

export type XdfEquationAst =
  | Readonly<{ kind: "literal"; value: number; source: string }>
  | Readonly<{ kind: "variable"; name: "X" }>
  | Readonly<{ kind: "unary"; operator: "+" | "-"; operand: XdfEquationAst }>
  | Readonly<{ kind: "binary"; operator: "+" | "-" | "*" | "/"; left: XdfEquationAst; right: XdfEquationAst }>;

export type ParsedXdfEquation = Readonly<{ outcome: "parsed" | "identity"; source: string; canonicalSource: string; equationId: string; equationRevision: string; ast: XdfEquationAst; variables: readonly ["X"] | readonly []; tokenCount: number }>;
export type XdfEquationParseResult = ParsedXdfEquation | Readonly<{ outcome: "unsupported_expression"; source: string; finding: string }> | Readonly<{ outcome: "malformed_equation"; source: string; finding: string }>;
type Token = Readonly<{ kind: "number" | "variable" | "operator" | "left" | "right" | "eof"; text: string; value?: number }>;

const hash=(domain:string,value:string)=>createHash("sha256").update(domain).update(Buffer.from([0])).update(value).digest("hex");
function deepFreeze<T>(value:T):T{if(Array.isArray(value))return Object.freeze(value.map(deepFreeze)) as T;if(value&&typeof value==="object"){for(const key of Reflect.ownKeys(value))deepFreeze((value as Record<PropertyKey,unknown>)[key]);return Object.freeze(value);}return value;}
function canonicalAst(node:XdfEquationAst):string{switch(node.kind){case"literal":return Number.isInteger(node.value)?String(node.value):node.value.toString();case"variable":return"X";case"unary":return`(${node.operator}${canonicalAst(node.operand)})`;case"binary":return`(${canonicalAst(node.left)}${node.operator}${canonicalAst(node.right)})`;}}
function tokenize(source:string):Token[]|XdfEquationParseResult{
  if(source.length>XDF_EQUATION_LIMITS.maximumLength)return{outcome:"unsupported_expression",source,finding:"Equation exceeds the expression-length limit."};
  const tokens:Token[]=[];let cursor=0;
  while(cursor<source.length){const char=source[cursor]!;if(/\s/.test(char)){cursor++;continue;}if(/[0-9.]/.test(char)){const match=/^(?:\d+(?:\.\d*)?|\.\d+)/.exec(source.slice(cursor));if(!match)return{outcome:"malformed_equation",source,finding:"Numeric literal is malformed."};const value=Number(match[0]);if(!Number.isFinite(value)||Math.abs(value)>XDF_EQUATION_LIMITS.maximumNumericLiteralMagnitude)return{outcome:"unsupported_expression",source,finding:"Numeric literal is outside the supported finite range."};tokens.push({kind:"number",text:match[0],value});cursor+=match[0].length;}else if(/[A-Za-z_]/.test(char)){const match=/^[A-Za-z_]\w*/.exec(source.slice(cursor))!;if(match[0]!=="X"&&match[0]!=="x")return{outcome:"unsupported_expression",source,finding:`Identifier ${match[0]} is not authorised.`};tokens.push({kind:"variable",text:match[0]});cursor+=match[0].length;}else if("+-*/".includes(char)){tokens.push({kind:"operator",text:char});cursor++;}else if(char==="("){tokens.push({kind:"left",text:char});cursor++;}else if(char===")"){tokens.push({kind:"right",text:char});cursor++;}else{return{outcome:"unsupported_expression",source,finding:`Construct ${JSON.stringify(char)} is not supported.`};}if(tokens.length>XDF_EQUATION_LIMITS.maximumTokens)return{outcome:"unsupported_expression",source,finding:"Equation exceeds the token-count limit."};}
  tokens.push({kind:"eof",text:""});return tokens;
}

export function parseXdfEquation(source:string):XdfEquationParseResult{
  const tokenized=tokenize(source);if(!Array.isArray(tokenized))return deepFreeze(tokenized);const tokens=tokenized;let index=0;let deepest=0;
  const parsePrimary=(depth:number):XdfEquationAst=>{deepest=Math.max(deepest,depth);if(deepest>XDF_EQUATION_LIMITS.maximumAstDepth)throw new Error("Equation exceeds the AST-depth limit.");const token=tokens[index]!;if(token.kind==="number"){index++;return{kind:"literal",value:token.value!,source:token.text};}if(token.kind==="variable"){index++;return{kind:"variable",name:"X"};}if(token.kind==="operator"&&(token.text==="+"||token.text==="-")){index++;return{kind:"unary",operator:token.text,operand:parsePrimary(depth+1)};}if(token.kind==="left"){index++;const value=parseAdditive(depth+1);if(tokens[index]?.kind!=="right")throw new Error("Closing parenthesis is missing.");index++;return value;}throw new Error("Expected a numeric literal, X, unary sign, or parenthesised expression.");};
  const parseMultiplicative=(depth:number):XdfEquationAst=>{let left=parsePrimary(depth);while(tokens[index]?.kind==="operator"&&(tokens[index]!.text==="*"||tokens[index]!.text==="/")){const operator=tokens[index++]!.text as "*"|"/";left={kind:"binary",operator,left,right:parsePrimary(depth+1)};}return left;};
  const parseAdditive=(depth:number):XdfEquationAst=>{let left=parseMultiplicative(depth);while(tokens[index]?.kind==="operator"&&(tokens[index]!.text==="+"||tokens[index]!.text==="-")){const operator=tokens[index++]!.text as "+"|"-";left={kind:"binary",operator,left,right:parseMultiplicative(depth+1)};}return left;};
  try{if(source.trim()==="")throw new Error("Equation is empty.");const ast=deepFreeze(parseAdditive(1));if(tokens[index]?.kind!=="eof")throw new Error("Unexpected trailing equation content.");const canonicalSource=canonicalAst(ast),semantic=canonicalSource==="X"?"identity":"parsed",equationId=`xdf-equation:${hash("tunesight.xdf-equation-semantic-identity.v1",canonicalSource)}`;return deepFreeze({outcome:semantic,source,canonicalSource,equationId,equationRevision:`xdf-equation-revision:${hash("tunesight.xdf-equation-revision.v1",canonicalSource)}`,ast,variables:canonicalSource.includes("X")?["X"]:[],tokenCount:tokens.length-1} as ParsedXdfEquation);}catch(error){return deepFreeze({outcome:error instanceof Error&&error.message.includes("limit")?"unsupported_expression":"malformed_equation",source,finding:error instanceof Error?error.message:"Equation is malformed."});}
}

export type XdfEquationEvaluation = Readonly<{ outcome:"converted"; value:number }> | Readonly<{ outcome:"invalid_numeric_result"; finding:string }>;
export function evaluateParsedXdfEquation(equation:ParsedXdfEquation,input:number):XdfEquationEvaluation{
  if(!Number.isFinite(input))return Object.freeze({outcome:"invalid_numeric_result",finding:"Raw input must be finite."});
  const visit=(node:XdfEquationAst):number=>{switch(node.kind){case"literal":return node.value;case"variable":return input;case"unary":return node.operator==="-"?-visit(node.operand):visit(node.operand);case"binary":{const left=visit(node.left),right=visit(node.right);if(node.operator==="/"&&right===0)throw new Error("Division by zero.");if(node.operator==="+")return left+right;if(node.operator==="-")return left-right;if(node.operator==="*")return left*right;return left/right;}}};
  try{const value=visit(equation.ast);if(!Number.isFinite(value)||Math.abs(value)>XDF_EQUATION_LIMITS.maximumResultMagnitude)return Object.freeze({outcome:"invalid_numeric_result",finding:"Equation result is non-finite or outside the supported range."});return Object.freeze({outcome:"converted",value});}catch(error){return Object.freeze({outcome:"invalid_numeric_result",finding:error instanceof Error?error.message:"Numeric evaluation failed."});}
}

export type EngineeringAxisEvidence=Readonly<{axisId:string;outcome:"converted"|"identity"|"static_literal"|"unavailable"|"unsupported_expression"|"malformed_equation"|"invalid_numeric_result"|"missing_equation";equation:ParsedXdfEquation|null;equationSource:string|null;units:string|null;rawValues:readonly number[];engineeringValues:readonly number[];literalValues:readonly string[];offsets:readonly number[];finding:string|null}>;
export type QualifiedEngineeringCalibrationValueEvidence=Readonly<{evidenceId:string;evidenceRevision:string;contractVersion:"tunesight.qualified-engineering-calibration-value-evidence.v1";outcome:"qualified_engineering_converted";sourceRawEvidenceId:string;sourceRawEvidenceRevision:string;exactBinaryDigest:string;romLayoutId:string;authorityChain:QualifiedRawCalibrationValueEvidence["authorityChain"];definitionSetRevisionId:string;definitionRevisionId:string;definitionIdentity:string;valueEquation:ParsedXdfEquation;equationSource:string;rawValues:readonly number[];engineeringValues:readonly number[];dimensions:QualifiedRawCalibrationValueEvidence["dimensions"];cellTrace:readonly Readonly<{index:number;row:number;column:number;rawOffset:number;rawValue:number;engineeringValue:number}>[];units:string|null;axes:readonly EngineeringAxisEvidence[];conversionFindings:readonly string[];provenance:readonly string[]}>;
export type EngineeringValueConversionRequest=Readonly<{requestId:string;contractVersion:typeof ENGINEERING_VALUE_CONVERSION_CONTRACT;rawEvidence:QualifiedRawCalibrationValueEvidence;definition:XdfDefinitionRevision;expectedEquationSource:string;expectedUnits:string|null}>;
export type EngineeringValueConversionResult=Readonly<{status:"converted";evidence:QualifiedEngineeringCalibrationValueEvidence}>|Readonly<{status:"rejected"|"unsupported_expression"|"malformed_equation"|"invalid_numeric_result"|"missing_equation";errorCode:string;finding:string}>;

export function constructEngineeringValueConversionRequest(input:Omit<EngineeringValueConversionRequest,"requestId"|"contractVersion">):EngineeringValueConversionRequest{const requestId=`engineering-value-conversion-request:${hash("tunesight.engineering-value-conversion-request.v1",JSON.stringify([input.rawEvidence.evidenceRevision,input.definition.revisionId,input.expectedEquationSource,input.expectedUnits]))}`;return Object.freeze({...input,requestId,contractVersion:ENGINEERING_VALUE_CONVERSION_CONTRACT});}
function convertMany(equation:ParsedXdfEquation,values:readonly number[]):readonly number[]|Extract<XdfEquationEvaluation,{outcome:"invalid_numeric_result"}>{const converted:number[]=[];for(const value of values){const result=evaluateParsedXdfEquation(equation,value);if(result.outcome!=="converted")return result;converted.push(result.value);}return Object.freeze(converted);}
function axisFor(definition:XdfDefinitionRevision,id:string):XdfAxisDefinition|undefined{return definition.axes.find(axis=>axis.axisId===id);}
export function convertQualifiedCalibrationValue(request:EngineeringValueConversionRequest):EngineeringValueConversionResult{
  const raw=request.rawEvidence,definition=request.definition;const canonical=defineXdfDefinitionRevision((({revisionId,structuralDigest,sourceBindingDigest,...rest})=>{void revisionId;void structuralDigest;void sourceBindingDigest;return rest;})(definition));
  if(raw.contractVersion!=="tunesight.qualified-raw-calibration-value-evidence.v1"||raw.outcome!=="qualified_raw_extracted"||raw.definitionRevisionId!==definition.revisionId||raw.definitionIdentity!==definition.identity.stableId||raw.definitionSourceBindingDigest!==definition.sourceBindingDigest||canonical.revisionId!==definition.revisionId)return Object.freeze({status:"rejected",errorCode:"raw_definition_authority_mismatch",finding:"Qualified Raw Evidence and canonical Definition Revision do not share exact authority."});
  if(definition.identity.status!=="derived")return Object.freeze({status:"rejected",errorCode:"definition_representation_conflict",finding:"Representation-conflicted or unresolved Definitions cannot produce authoritative engineering Evidence."});
  const valueAxis=definition.axes.find(axis=>axis.axisId.toLowerCase()==="z")??definition.axes.at(-1);if(!valueAxis||valueAxis.equationSource===null)return Object.freeze({status:"missing_equation",errorCode:"value_equation_missing",finding:"The value axis has no conversion equation."});
  if(valueAxis.equationSource!==request.expectedEquationSource||valueAxis.units!==request.expectedUnits)return Object.freeze({status:"rejected",errorCode:"equation_or_unit_binding_mismatch",finding:"Requested equation source or units do not match the Definition Revision."});
  const equation=parseXdfEquation(valueAxis.equationSource);if(equation.outcome==="unsupported_expression"||equation.outcome==="malformed_equation")return Object.freeze({status:equation.outcome,errorCode:equation.outcome,finding:equation.finding});const values=convertMany(equation,raw.rawValues);if("finding" in values)return Object.freeze({status:"invalid_numeric_result",errorCode:"invalid_numeric_result",finding:values.finding});
  const axes:EngineeringAxisEvidence[]=raw.rawAxes.map(rawAxis=>{const definitionAxis=axisFor(definition,rawAxis.axisId);if(!definitionAxis)return deepFreeze({axisId:rawAxis.axisId,outcome:"unavailable",equation:null,equationSource:null,units:null,rawValues:[],engineeringValues:[],literalValues:rawAxis.literalValues,offsets:rawAxis.offsets,finding:"Axis is absent from the bound Definition."});if(rawAxis.outcome==="static_literal")return deepFreeze({axisId:rawAxis.axisId,outcome:"static_literal",equation:null,equationSource:definitionAxis.equationSource,units:definitionAxis.units,rawValues:[],engineeringValues:[],literalValues:rawAxis.literalValues,offsets:rawAxis.offsets,finding:null});if(rawAxis.outcome!=="extracted"||!rawAxis.shape)return deepFreeze({axisId:rawAxis.axisId,outcome:"unavailable",equation:null,equationSource:definitionAxis.equationSource,units:definitionAxis.units,rawValues:[],engineeringValues:[],literalValues:[],offsets:rawAxis.offsets,finding:rawAxis.finding});if(definitionAxis.equationSource===null)return deepFreeze({axisId:rawAxis.axisId,outcome:"missing_equation",equation:null,equationSource:null,units:definitionAxis.units,rawValues:rawAxis.shape.values,engineeringValues:[],literalValues:[],offsets:rawAxis.offsets,finding:"Extracted axis has no conversion equation."});const parsed=parseXdfEquation(definitionAxis.equationSource);if(parsed.outcome==="unsupported_expression"||parsed.outcome==="malformed_equation")return deepFreeze({axisId:rawAxis.axisId,outcome:parsed.outcome,equation:null,equationSource:definitionAxis.equationSource,units:definitionAxis.units,rawValues:rawAxis.shape.values,engineeringValues:[],literalValues:[],offsets:rawAxis.offsets,finding:parsed.finding});const converted=convertMany(parsed,rawAxis.shape.values);if("finding" in converted)return deepFreeze({axisId:rawAxis.axisId,outcome:"invalid_numeric_result",equation:parsed,equationSource:definitionAxis.equationSource,units:definitionAxis.units,rawValues:rawAxis.shape.values,engineeringValues:[],literalValues:[],offsets:rawAxis.offsets,finding:converted.finding});return deepFreeze({axisId:rawAxis.axisId,outcome:parsed.outcome==="identity"?"identity":"converted",equation:parsed,equationSource:definitionAxis.equationSource,units:definitionAxis.units,rawValues:rawAxis.shape.values,engineeringValues:converted,literalValues:[],offsets:rawAxis.offsets,finding:null});});
  const columns=raw.dimensions.columns,cellTrace=values.map((value,index)=>Object.freeze({index,row:Math.floor(index/columns),column:index%columns,rawOffset:raw.exactRawOffsets[index]!,rawValue:raw.rawValues[index]!,engineeringValue:value}));const material=JSON.stringify([raw.evidenceRevision,equation.equationRevision,values,axes]);const evidence=deepFreeze({evidenceId:`qualified-engineering-calibration-evidence:${hash("tunesight.qualified-engineering-calibration-evidence-identity.v1",material)}`,evidenceRevision:`qualified-engineering-calibration-evidence-revision:${hash("tunesight.qualified-engineering-calibration-evidence-revision.v1",material)}`,contractVersion:"tunesight.qualified-engineering-calibration-value-evidence.v1" as const,outcome:"qualified_engineering_converted" as const,sourceRawEvidenceId:raw.evidenceId,sourceRawEvidenceRevision:raw.evidenceRevision,exactBinaryDigest:raw.exactBinaryDigest,romLayoutId:raw.romLayoutId,authorityChain:raw.authorityChain,definitionSetRevisionId:raw.definitionSetRevisionId,definitionRevisionId:raw.definitionRevisionId,definitionIdentity:raw.definitionIdentity,valueEquation:equation,equationSource:valueAxis.equationSource,rawValues:raw.rawValues,engineeringValues:values,dimensions:raw.dimensions,cellTrace,units:valueAxis.units,axes,conversionFindings:[],provenance:[...raw.provenance,`Engineering conversion: ${equation.equationRevision}`].sort()});return Object.freeze({status:"converted",evidence});
}

export type XdfEquationCensus=Readonly<{files:number;definitions:number;definitionsWithEquations:number;equationOccurrences:number;uniqueEquationSources:number;parseableOccurrences:number;supportedOccurrences:number;identityOccurrences:number;unsupportedOccurrences:number;malformedOccurrences:number;axisOccurrences:Readonly<Record<string,number>>;familyOccurrences:Readonly<Record<string,number>>;versionOccurrences:Readonly<Record<string,number>>;declaredVariables:Readonly<Record<string,number>>;unsupportedFindings:Readonly<Record<string,number>>;inverseEquationAttributes:number}>;
export function censusXdfEquations(root:string):XdfEquationCensus{const files:string[]=[];const walk=(directory:string)=>fs.readdirSync(directory,{withFileTypes:true}).forEach(entry=>{const full=path.join(directory,entry.name);if(entry.isDirectory())walk(full);else if(entry.name.toLowerCase().endsWith(".xdf"))files.push(full);});walk(root);files.sort();let definitions=0,definitionsWithEquations=0,equationOccurrences=0,parseableOccurrences=0,identityOccurrences=0,unsupportedOccurrences=0,malformedOccurrences=0,inverseEquationAttributes=0;const unique=new Set<string>(),axisOccurrences:Record<string,number>={},familyOccurrences:Record<string,number>={},versionOccurrences:Record<string,number>={},declaredVariables:Record<string,number>={},unsupportedFindings:Record<string,number>={};for(const file of files){const xml=fs.readFileSync(file,"utf8"),relative=path.relative(root,file),family=relative.split(path.sep)[0]!,parsed=interpretXdfStructure({xml,filename:path.basename(file),provenance:"Deterministic XDF equation census"}),version=parsed.sourceArtifact?.observedVersion??"unknown";definitions+=parsed.definitions.length;for(const definition of parsed.definitions){const axes=definition.axes.filter(axis=>axis.equationSource!==null);if(axes.length)definitionsWithEquations++;for(const axis of axes){equationOccurrences++;unique.add(axis.equationSource!);axisOccurrences[axis.axisId]=(axisOccurrences[axis.axisId]??0)+1;familyOccurrences[family]=(familyOccurrences[family]??0)+1;versionOccurrences[version]=(versionOccurrences[version]??0)+1;for(const variable of axis.equationVariables)declaredVariables[variable]=(declaredVariables[variable]??0)+1;const result=parseXdfEquation(axis.equationSource!);if(result.outcome==="parsed")parseableOccurrences++;else if(result.outcome==="identity"){parseableOccurrences++;identityOccurrences++;}else if("finding" in result){if(result.outcome==="unsupported_expression")unsupportedOccurrences++;else malformedOccurrences++;unsupportedFindings[result.finding]=(unsupportedFindings[result.finding]??0)+1;}}}inverseEquationAttributes+=(xml.match(/\b(?:inverse|reverse|inv)[\w.-]*\s*=/gi)??[]).length;}const sorted=(record:Record<string,number>)=>Object.freeze(Object.fromEntries(Object.entries(record).sort(([a],[b])=>a.localeCompare(b))));return deepFreeze({files:files.length,definitions,definitionsWithEquations,equationOccurrences,uniqueEquationSources:unique.size,parseableOccurrences,supportedOccurrences:parseableOccurrences,identityOccurrences,unsupportedOccurrences,malformedOccurrences,axisOccurrences:sorted(axisOccurrences),familyOccurrences:sorted(familyOccurrences),versionOccurrences:sorted(versionOccurrences),declaredVariables:sorted(declaredVariables),unsupportedFindings:sorted(unsupportedFindings),inverseEquationAttributes});}
