import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { resolveBinaryContainer, type EngineeringBinary } from "../tunes/binaryContainer.ts";
import { assessDefinitionExtractionCapability } from "./calibrationValueExtraction.ts";
import { defineXdfDefinitionRevision, type XdfAxisDefinition, type XdfDefinitionRevision } from "./canonicalXdfDefinition.ts";
import { defineDefinitionSetRevision, identifyEngineeringBinary, type DefinitionSetRevision, type EngineeringBinaryIdentity } from "./definitionRomApplicability.ts";
import { censusXdfEquations, constructEngineeringValueConversionRequest, convertQualifiedCalibrationValue, evaluateParsedXdfEquation, parseXdfEquation, XDF_EQUATION_LIMITS } from "./engineeringValueConversion.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import { N54_CURRENT_GOVERNED_REVIEW_REFERENCES, N54_CURRENT_ROM_LAYOUT_REGISTRY } from "./n54GovernedApplicabilityAdmission.ts";
import { constructQualifiedCalibrationExtractionRequest, extractQualifiedCalibrationValue, type QualifiedRawCalibrationValueEvidence } from "./qualifiedCalibrationExtraction.ts";

const identities=["I8A0S","IJE0S","IKM0S","INA0S"] as const;type Identity=typeof identities[number];const n54Root=path.resolve("BMW-XDFs-master/N54");
const cache=new Map<Identity,{definitions:readonly XdfDefinitionRevision[];set:DefinitionSetRevision}>();
function parsed(identity:Identity){const hit=cache.get(identity);if(hit)return hit;const filename=`${identity}.xdf`,result=interpretXdfStructure({xml:fs.readFileSync(path.join(n54Root,filename),"utf8"),filename,provenance:"Engineering conversion proof"});assert.equal(result.outcome,"structurally_interpreted");assert.ok(result.sourceArtifact);const value={definitions:result.definitions,set:defineDefinitionSetRevision({sourceArtifact:result.sourceArtifact!,definitions:result.definitions})};cache.set(identity,value);return value;}
function binary(identity:Identity):{engineering:EngineeringBinary;identity:EngineeringBinaryIdentity}{const filename=`${identity}_original.bin`,resolved=resolveBinaryContainer({bytes:fs.readFileSync(path.join(n54Root,filename)),fileName:filename});assert.equal(resolved.status,"resolved");return{engineering:resolved.engineeringBinary!,identity:identifyEngineeringBinary({engineeringBinary:resolved.engineeringBinary!,romFamily:"N54",softwareIdentity:identity,internalRomIdentifiers:[identity],identityProvenance:["Exact current N54 conversion proof"]})};}
function qualified(identity:Identity,shape?:"scalar"|"array_1d"|"table_2d"){const source=parsed(identity),exact=binary(identity),relationship=N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships.find(item=>item.romLayoutId===N54_CURRENT_GOVERNED_REVIEW_REFERENCES.find(item=>item.identity===identity)!.review.romLayoutId)!;const definition=source.definitions.find(item=>{const z=item.axes.find(axis=>axis.axisId.toLowerCase()==="z")??item.axes.at(-1);const rows=z?.embeddedData.rowCount??1,columns=z?.embeddedData.columnCount??z?.indexCount??1,actual=rows===1&&columns===1?"scalar":rows===1?"array_1d":"table_2d";return assessDefinitionExtractionCapability(item).state==="extraction_capable"&&z?.equationSource!==null&&(!shape||shape===actual);});assert.ok(definition);const extraction=extractQualifiedCalibrationValue(constructQualifiedCalibrationExtractionRequest({engineeringBinary:exact.engineering,binaryIdentity:exact.identity,romLayoutId:relationship.romLayoutId,registrySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,expectedRelationshipId:relationship.relationshipId,expectedRelationshipRevision:relationship.relationshipRevision,definitionSet:source.set,definition}));assert.equal(extraction.status,"qualified_extracted");if(extraction.status!=="qualified_extracted")throw new Error("Qualified extraction failed.");return{definition,evidence:extraction.evidence};}
function convert(definition:XdfDefinitionRevision,evidence:QualifiedRawCalibrationValueEvidence){const z=definition.axes.find(axis=>axis.axisId.toLowerCase()==="z")??definition.axes.at(-1)!;return convertQualifiedCalibrationValue(constructEngineeringValueConversionRequest({rawEvidence:evidence,definition,expectedEquationSource:z.equationSource!,expectedUnits:z.units}));}

test("tokenizer/parser implement only the discovered deterministic arithmetic grammar",()=>{for(const [source,input,expected] of [["2",9,2],["X",7,7],["-X",3,-3],["X+2",3,5],["X-2",3,1],["X*2",3,6],["X/2",3,1.5],["(X+2)*3",4,18],["X+2*3",4,10]] as const){const parsed=parseXdfEquation(source);assert.ok(parsed.outcome==="parsed"||parsed.outcome==="identity");if(parsed.outcome==="parsed"||parsed.outcome==="identity")assert.deepEqual(evaluateParsedXdfEquation(parsed,input),{outcome:"converted",value:expected});}});
test("semantic identity is whitespace and X-case stable but changes materially",()=>{const a=parseXdfEquation(" ( X * 2 ) + 1 "),b=parseXdfEquation("(x*2)+1"),c=parseXdfEquation("X*2+2");assert.ok("equationId" in a&&"equationId" in b&&"equationId" in c);if("equationId" in a&&"equationId" in b&&"equationId" in c){assert.equal(a.equationId,b.equationId);assert.equal(a.equationRevision,b.equationRevision);assert.notEqual(a.equationRevision,c.equationRevision);assert.equal(a.source," ( X * 2 ) + 1 ");assert.ok(Object.isFrozen(a)&&Object.isFrozen(a.ast));}});
test("numeric failures and hostile constructs fail explicitly without dynamic execution",()=>{const divide=parseXdfEquation("X/0");assert.ok("ast" in divide);if("ast" in divide)assert.equal(evaluateParsedXdfEquation(divide,1).outcome,"invalid_numeric_result");for(const source of ["NaN","Infinity","globalThis.x","X=1","f(X)","X^2","X?1:0","X[0]","1e3"])assert.equal(parseXdfEquation(source).outcome,"unsupported_expression",source);assert.equal(parseXdfEquation("(X+1").outcome,"malformed_equation");assert.equal(parseXdfEquation("X+").outcome,"malformed_equation");assert.equal(parseXdfEquation("X".padEnd(XDF_EQUATION_LIMITS.maximumLength+1," ")).outcome,"unsupported_expression");assert.equal(parseXdfEquation(Array.from({length:65},()=>"X").join("+")).outcome,"unsupported_expression");assert.equal(parseXdfEquation("(".repeat(17)+"X"+")".repeat(17)).outcome,"unsupported_expression");assert.equal((globalThis as Record<string,unknown>).__xdfEngineeringExecuted,undefined);});
test("all four current N54 ROMs convert real qualified raw Evidence deterministically",()=>{const report=[];for(const identity of identities){const proof=qualified(identity),first=convert(proof.definition,proof.evidence),again=convert(proof.definition,proof.evidence);assert.equal(first.status,"converted");assert.deepEqual(first,again);if(first.status!=="converted")continue;assert.equal(first.evidence.sourceRawEvidenceId,proof.evidence.evidenceId);assert.equal(first.evidence.exactBinaryDigest,proof.evidence.exactBinaryDigest);assert.equal(first.evidence.romLayoutId,proof.evidence.romLayoutId);assert.equal(first.evidence.authorityChain.relationshipRevision,proof.evidence.authorityChain.relationshipRevision);assert.deepEqual(first.evidence.rawValues,proof.evidence.rawValues);assert.equal(first.evidence.cellTrace.length,proof.evidence.rawValues.length);const independentlyExpected=identity==="I8A0S"?proof.evidence.rawValues[0]!*2.653360799573*0.0145038:proof.evidence.rawValues[0]!*0.001;assert.equal(first.evidence.engineeringValues[0],independentlyExpected);assert.ok(Object.isFrozen(first.evidence)&&Object.isFrozen(first.evidence.engineeringValues));assert.ok(!("recommendation" in first.evidence));report.push({identity,rawEvidence:proof.evidence.evidenceId,engineeringEvidence:first.evidence.evidenceId,equation:first.evidence.equationSource,units:first.evidence.units,raw:first.evidence.rawValues[0],engineering:first.evidence.engineeringValues[0]});}console.log(`N54_ENGINEERING_VALUE_PROOF ${JSON.stringify(report)}`);});
test("scalar, 1D and 2D output retain dimensions, offsets and per-cell trace",()=>{for(const shape of ["scalar","array_1d","table_2d"] as const){const proof=qualified("IJE0S",shape),result=convert(proof.definition,proof.evidence);assert.equal(result.status,"converted",shape);if(result.status!=="converted")continue;assert.equal(result.evidence.dimensions.kind,shape);assert.equal(result.evidence.cellTrace.length,proof.evidence.exactRawOffsets.length);result.evidence.cellTrace.forEach((cell,index)=>{assert.equal(cell.index,index);assert.equal(cell.rawOffset,proof.evidence.exactRawOffsets[index]);assert.equal(cell.rawValue,proof.evidence.rawValues[index]);});}});
test("axis equations, raw axis values, units and provenance remain separate",()=>{const source=parsed("IJE0S"),exact=binary("IJE0S"),candidate=source.definitions.find(definition=>definition.axes.some(axis=>axis.axisId.toLowerCase()!=="z"&&axis.embeddedData.address!==null&&axis.equationSource!==null)&&assessDefinitionExtractionCapability(definition).state==="extraction_capable");assert.ok(candidate);const base=qualified("IJE0S"),relationship=N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships.find(item=>item.romLayoutId===base.evidence.romLayoutId)!;const extraction=extractQualifiedCalibrationValue(constructQualifiedCalibrationExtractionRequest({engineeringBinary:exact.engineering,binaryIdentity:exact.identity,romLayoutId:relationship.romLayoutId,registrySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,expectedRelationshipId:relationship.relationshipId,expectedRelationshipRevision:relationship.relationshipRevision,definitionSet:source.set,definition:candidate!}));assert.equal(extraction.status,"qualified_extracted");if(extraction.status!=="qualified_extracted")return;const result=convert(candidate!,extraction.evidence);assert.equal(result.status,"converted");if(result.status!=="converted")return;assert.ok(result.evidence.axes.some(axis=>axis.outcome==="converted"||axis.outcome==="identity"));for(const axis of result.evidence.axes){const definitionAxis:XdfAxisDefinition=candidate!.axes.find(item=>item.axisId===axis.axisId)!;assert.equal(axis.units,definitionAxis.units);assert.equal(axis.equationSource,definitionAxis.equationSource);}});
test("missing, unsupported, invalid and representation-conflicted conversions do not fall back to raw",()=>{const proof=qualified("IJE0S"),zIndex=proof.definition.axes.findIndex(axis=>axis.axisId.toLowerCase()==="z"),replace=(equationSource:string|null)=>defineXdfDefinitionRevision({...proof.definition,axes:proof.definition.axes.map((axis,index)=>index===zIndex?{...axis,equationSource}:axis)});const missing=replace(null),unsupported=replace("f(X)"),invalid=replace("X/0");for(const [definition,status] of [[missing,"missing_equation"],[unsupported,"unsupported_expression"],[invalid,"invalid_numeric_result"]] as const){const raw={...proof.evidence,definitionRevisionId:definition.revisionId,definitionSourceBindingDigest:definition.sourceBindingDigest,definitionIdentity:definition.identity.stableId!};const result=convert(definition,raw);assert.equal(result.status,status);}const conflicting=defineXdfDefinitionRevision({...proof.definition,identity:{status:"conflicting",stableId:null,derivationBasis:null,unresolvedReason:"Controlled conflict"}}),raw={...proof.evidence,definitionRevisionId:conflicting.revisionId,definitionSourceBindingDigest:conflicting.sourceBindingDigest,definitionIdentity:null as unknown as string};assert.equal(convert(conflicting,raw).status,"rejected");});
test("master-library census is exact, bounded and fully covered by the discovered grammar",()=>{const census=censusXdfEquations(path.resolve("BMW-XDFs-master"));assert.deepEqual({files:census.files,definitions:census.definitions,definitionsWithEquations:census.definitionsWithEquations,equationOccurrences:census.equationOccurrences,uniqueEquationSources:census.uniqueEquationSources,parseableOccurrences:census.parseableOccurrences,identityOccurrences:census.identityOccurrences,unsupportedOccurrences:census.unsupportedOccurrences,malformedOccurrences:census.malformedOccurrences,inverseEquationAttributes:census.inverseEquationAttributes},{files:99,definitions:105335,definitionsWithEquations:105335,equationOccurrences:216243,uniqueEquationSources:272,parseableOccurrences:216243,identityOccurrences:90896,unsupportedOccurrences:0,malformedOccurrences:0,inverseEquationAttributes:0});assert.deepEqual(census.axisOccurrences,{x:55454,y:55454,z:105335});assert.deepEqual(census.versionOccurrences,{"1.60":22825,"1.70":144788,"1.80":48630});assert.deepEqual(census.declaredVariables,{x:129,X:216114});assert.ok(Object.isFrozen(census));console.log(`BMW_XDF_EQUATION_CENSUS ${JSON.stringify(census)}`);});
