import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { resolveBinaryContainer, type EngineeringBinary } from "../tunes/binaryContainer.ts";
import { defineXdfDefinitionRevision, type XdfDefinitionRevision } from "./canonicalXdfDefinition.ts";
import { defineDefinitionSetRevision, identifyEngineeringBinary, type DefinitionSetRevision, type EngineeringBinaryIdentity } from "./definitionRomApplicability.ts";
import type { QualifiedEngineeringCalibrationValueEvidence } from "./engineeringValueConversion.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import { N54_CURRENT_GOVERNED_REVIEW_REFERENCES, N54_CURRENT_ROM_LAYOUT_REGISTRY } from "./n54GovernedApplicabilityAdmission.ts";
import { calculatePercentageDelta, compareEngineeringAxes, compareEngineeringCell, compareQualifiedCalibrations, constructQualifiedCalibrationComparisonRequest, deriveChangedRegions, type ChangedCellEvidence, type DefinitionComparisonEvidence, type QualifiedCalibrationComparisonRequest, type QualifiedCalibrationComparisonResult } from "./qualifiedCalibrationComparison.ts";

const identities=["I8A0S","IJE0S","IKM0S","INA0S"] as const;type Identity=typeof identities[number];const root=path.resolve("BMW-XDFs-master/N54");
const parsedCache=new Map<string,{definitions:readonly XdfDefinitionRevision[];set:DefinitionSetRevision}>(),binaryCache=new Map<string,{engineering:EngineeringBinary;identity:EngineeringBinaryIdentity}>(),comparisonCache=new Map<Identity,QualifiedCalibrationComparisonResult>();
function parsed(identity:Identity,legacy=false){const filename=`${identity}${legacy?"_Legacy":""}.xdf`,hit=parsedCache.get(filename);if(hit)return hit;const result=interpretXdfStructure({xml:fs.readFileSync(path.join(root,filename),"utf8"),filename,provenance:`Qualified comparison ${filename}`});assert.equal(result.outcome,"structurally_interpreted");assert.ok(result.sourceArtifact);const value={definitions:result.definitions,set:defineDefinitionSetRevision({sourceArtifact:result.sourceArtifact!,definitions:result.definitions})};parsedCache.set(filename,value);return value;}
function binary(identity:Identity,role:"original"|"MapSwitchBase"){const filename=`${identity}_${role}.bin`,hit=binaryCache.get(filename);if(hit)return hit;const resolved=resolveBinaryContainer({bytes:fs.readFileSync(path.join(root,filename)),fileName:filename});assert.equal(resolved.status,"resolved");const value={engineering:resolved.engineeringBinary!,identity:identifyEngineeringBinary({engineeringBinary:resolved.engineeringBinary!,romFamily:"N54",softwareIdentity:identity,internalRomIdentifiers:[identity],identityProvenance:[`Exact ${role} comparison fixture`]})};binaryCache.set(filename,value);return value;}
function request(identity:Identity,options:Partial<{reference:ReturnType<typeof binary>;modified:ReturnType<typeof binary>;source:ReturnType<typeof parsed>;definitions:readonly XdfDefinitionRevision[]}>= {}):QualifiedCalibrationComparisonRequest{const source=options.source??parsed(identity),reference=options.reference??binary(identity,"original"),modified=options.modified??binary(identity,"MapSwitchBase"),layout=N54_CURRENT_GOVERNED_REVIEW_REFERENCES.find(value=>value.identity===identity)!.review.romLayoutId,relationship=N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships.find(value=>value.romLayoutId===layout)!;return constructQualifiedCalibrationComparisonRequest({reference:{engineeringBinary:reference.engineering,binaryIdentity:reference.identity,role:"stock_candidate",provenance:["Original source role; Stock Variant remains exact_candidate."]},modified:{engineeringBinary:modified.engineering,binaryIdentity:modified.identity,role:"mapswitch",provenance:["MapSwitch subordinate layout Evidence; no safety or recommendation claim."]},romLayoutId:layout,registrySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,expectedRelationshipId:relationship.relationshipId,expectedRelationshipRevision:relationship.relationshipRevision,definitionSet:source.set,definitions:options.definitions??source.definitions});}
function compare(identity:Identity){const hit=comparisonCache.get(identity);if(hit)return hit;const result=compareQualifiedCalibrations(request(identity));comparisonCache.set(identity,result);return result;}

test("all four current N54 Definition Sets compare completely and deterministically",()=>{const report=[];for(const identity of identities){const first=compare(identity);assert.equal(first.status,"compared");if(first.status!=="compared")continue;const e=first.evidence;assert.equal(e.totalDefinitionsConsidered,parsed(identity).set.definitionCount);assert.equal(e.changedDefinitions+e.unchangedDefinitions+e.axisChangedDefinitions+e.valueAndAxisChangedDefinitions+e.unavailableDefinitions+e.conflictedDefinitions,e.totalDefinitionsConsidered);assert.ok(e.changedDefinitions+e.valueAndAxisChangedDefinitions>0);assert.ok(e.unchangedDefinitions>0);assert.equal(e.conflictedDefinitions,0);assert.ok(Object.isFrozen(e)&&Object.isFrozen(e.definitions)&&Object.isFrozen(e.definitions[0]));assert.ok(!("recommendation" in e));const examples=e.definitions.filter(value=>value.changedCellCount>0).slice(0,3).map(value=>({title:value.title,identity:value.definitionIdentity,dimensions:value.dimensions,units:value.units,changedCells:value.changedCellCount,firstDelta:value.changedCells[0]?.signedDelta}));report.push({identity,comparisonId:e.comparisonId,definitions:e.totalDefinitionsConsidered,changed:e.changedDefinitions,unchanged:e.unchangedDefinitions,axisChanged:e.axisChangedDefinitions,valueAndAxisChanged:e.valueAndAxisChangedDefinitions,unavailable:e.unavailableDefinitions,conflicts:e.conflictedDefinitions,changedCells:e.totalChangedCells,examples});}assert.deepEqual(compare("IJE0S"),compareQualifiedCalibrations(request("IJE0S")));console.log(`N54_QUALIFIED_CALIBRATION_COMPARISON ${JSON.stringify(report)}`);});
test("request and comparison identities are deterministic and directional",()=>{const forward=request("IJE0S"),same=request("IJE0S"),reverse=request("IJE0S",{reference:binary("IJE0S","MapSwitchBase"),modified:binary("IJE0S","original")});assert.equal(forward.requestId,same.requestId);assert.notEqual(forward.requestId,reverse.requestId);const a=compare("IJE0S"),b=compareQualifiedCalibrations(reverse);assert.equal(a.status,"compared");assert.equal(b.status,"compared");if(a.status==="compared"&&b.status==="compared"){assert.notEqual(a.evidence.comparisonId,b.evidence.comparisonId);assert.notEqual(a.evidence.comparisonRevision,b.evidence.comparisonRevision);const cell=a.evidence.definitions.flatMap(value=>value.changedCells)[0]!;const reverseDefinition=b.evidence.definitions.find(value=>value.definitionRevisionId===a.evidence.definitions.find(item=>item.changedCells.includes(cell))!.definitionRevisionId)!;assert.equal(reverseDefinition.changedCells.find(value=>value.index===cell.index)!.signedDelta,-cell.signedDelta);}});
test("scalar primitive and real changed 1D/2D cells preserve trace and signed deltas",()=>{const scalar=compareEngineeringCell({index:0,row:0,column:0,referenceRawOffset:10,modifiedRawOffset:10,referenceRawValue:2,modifiedRawValue:5,referenceEngineeringValue:4,modifiedEngineeringValue:10,units:"fixture",equationRevision:"fixture-equation"});assert.ok(scalar);assert.equal(scalar.signedDelta,6);assert.equal(scalar.absoluteDeltaMagnitude,6);const cohort=identities.flatMap(identity=>{const result=compare(identity);return result.status==="compared"?result.evidence.definitions:[];});for(const kind of ["array_1d","table_2d"] as const){const definition:DefinitionComparisonEvidence|undefined=cohort.find(value=>value.dimensions?.kind===kind&&value.changedCellCount>0);assert.ok(definition,kind);const cell:ChangedCellEvidence=definition!.changedCells[0]!;assert.equal(cell.signedDelta,cell.modifiedEngineeringValue-cell.referenceEngineeringValue);assert.equal(cell.absoluteDeltaMagnitude,Math.abs(cell.signedDelta));assert.equal(cell.referenceRawOffset,definition!.referenceEngineeringEvidence!.cellTrace[cell.index]!.rawOffset);assert.equal(cell.modifiedRawOffset,definition!.modifiedEngineeringEvidence!.cellTrace[cell.index]!.rawOffset);assert.equal(definition!.changedCellCount+definition!.unchangedCellCount,definition!.totalCells);assert.ok(definition!.changedRegions.length>0);}});
test("positive, negative and zero-reference percentage outcomes are explicit",()=>{const evidence=compare("IJE0S");assert.equal(evidence.status,"compared");if(evidence.status!=="compared")return;const deltas=evidence.evidence.definitions.flatMap(value=>value.changedCells.map(cell=>cell.signedDelta));assert.ok(deltas.some(value=>value>0));assert.ok(deltas.some(value=>value<0));assert.deepEqual(calculatePercentageDelta(0,5),{outcome:"reference_zero",value:null});assert.deepEqual(calculatePercentageDelta(10,5),{outcome:"available",value:50});assert.deepEqual(calculatePercentageDelta(Number.NaN,1),{outcome:"invalid_numeric",value:null});});
test("changed regions are bounded geometric four-neighbour components",()=>{const cell=(index:number,row:number,column:number)=>({index,row,column} as ChangedCellEvidence),regions=deriveChangedRegions([cell(0,0,0),cell(1,0,1),cell(5,1,1),cell(15,3,3)],4,4);assert.equal(regions.length,2);assert.deepEqual(regions[0]!.cellIndices,[0,1,5]);assert.deepEqual([regions[0]!.rowStart,regions[0]!.rowEnd,regions[0]!.columnStart,regions[0]!.columnEnd],[0,1,0,1]);assert.deepEqual(regions[1]!.cellIndices,[15]);});
test("axis comparison distinguishes unchanged, changed and unavailable representations",()=>{const result=compare("IJE0S");assert.equal(result.status,"compared");if(result.status!=="compared")return;const definition=result.evidence.definitions.find(value=>value.referenceEngineeringEvidence?.axes.some(axis=>axis.engineeringValues.length>0));assert.ok(definition);const reference=definition!.referenceEngineeringEvidence!,unchanged=compareEngineeringAxes(reference,reference);assert.ok(unchanged.every(axis=>axis.outcome==="unchanged"));const axisIndex=reference.axes.findIndex(axis=>axis.engineeringValues.length>0),axis=reference.axes[axisIndex]!,changedAxis={...axis,engineeringValues:Object.freeze(axis.engineeringValues.map((value,index)=>index===0?value+1:value))},modified={...reference,axes:Object.freeze(reference.axes.map((value,index)=>index===axisIndex?changedAxis:value))} as QualifiedEngineeringCalibrationValueEvidence;assert.equal(compareEngineeringAxes(reference,modified).find(value=>value.axisId===axis.axisId)!.outcome,"changed");const unavailable={...reference,axes:Object.freeze(reference.axes.map((value,index)=>index===axisIndex?{...value,units:"different-unit"}:value))} as QualifiedEngineeringCalibrationValueEvidence;assert.equal(compareEngineeringAxes(reference,unavailable).find(value=>value.axisId===axis.axisId)!.outcome,"comparison_unavailable");});
test("identical exact inputs produce deterministic explicit no-difference Evidence",()=>{const original=binary("IJE0S","original"),identicalRequest=request("IJE0S",{reference:original,modified:original}),first=compareQualifiedCalibrations(identicalRequest);assert.equal(first.status,"identical_inputs");assert.equal(identicalRequest.requestId,request("IJE0S",{reference:original,modified:original}).requestId);if(first.status!=="identical_inputs")return;assert.equal(first.evidence.changedDefinitions,0);assert.equal(first.evidence.valueAndAxisChangedDefinitions,0);assert.equal(first.evidence.totalChangedCells,0);assert.equal(first.evidence.unchangedDefinitions+first.evidence.unavailableDefinitions,first.evidence.totalDefinitionsConsidered);assert.match(first.evidence.findings[0]!,/same exact digest/);});
test("wrong-ROM and Legacy authority are rejected without family fallback",()=>{const wrong=compareQualifiedCalibrations(request("IJE0S",{modified:binary("INA0S","MapSwitchBase")}));assert.equal(wrong.status,"rejected");if(wrong.status==="rejected")assert.equal(wrong.errorCode,"authority_mismatch");const legacy=parsed("IJE0S",true),legacyResult=compareQualifiedCalibrations(request("IJE0S",{source:legacy}));assert.equal(legacyResult.status,"rejected");if(legacyResult.status==="rejected")assert.equal(legacyResult.errorCode,"authority_mismatch");const legacyConflicts=identities.reduce((sum,identity)=>sum+parsed(identity,true).definitions.filter(value=>value.identity.status==="conflicting").length,0);assert.equal(legacyConflicts,63);});
test("conflicts and unavailable Definitions are explicit rather than omitted",()=>{const base=parsed("IJE0S"),first=base.definitions[0]!,second=base.definitions[1]!,conflicting=defineXdfDefinitionRevision({...first,identity:{status:"conflicting",stableId:null,derivationBasis:null,unresolvedReason:"Controlled representation conflict"}}),forged={...second,axes:second.axes.map((axis,index)=>index===second.axes.length-1?{...axis,equationSource:null}:axis)},definitions=base.definitions.map(value=>value===first?conflicting:value===second?forged:value),result=compareQualifiedCalibrations(request("IJE0S",{definitions}));assert.equal(result.status,"compared");if(result.status==="compared"){assert.equal(result.evidence.conflictedDefinitions,1);assert.ok(result.evidence.unavailableDefinitions>=1);}});
test("unchanged real Definition proves different binary digests do not imply every table changed",()=>{const result=compare("IJE0S");assert.equal(result.status,"compared");if(result.status!=="compared")return;const unchanged=result.evidence.definitions.find(value=>value.outcome==="unchanged");assert.ok(unchanged);assert.equal(unchanged!.changedCellCount,0);assert.equal(unchanged!.unchangedCellCount,unchanged!.totalCells);assert.notEqual(result.evidence.reference.exactBinaryDigest,result.evidence.modified.exactBinaryDigest);console.log(`IJE0S_UNCHANGED_DEFINITION ${JSON.stringify({title:unchanged!.title,identity:unchanged!.definitionIdentity,dimensions:unchanged!.dimensions,units:unchanged!.units})}`);});
