import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { resolveBinaryContainer, type EngineeringBinary } from "../tunes/binaryContainer.ts";
import { assessDefinitionExtractionCapability, extractRawCalibrationValues } from "./calibrationValueExtraction.ts";
import { defineXdfDefinitionRevision, type XdfDefinitionRevision } from "./canonicalXdfDefinition.ts";
import { defineDefinitionSetRevision, identifyEngineeringBinary, type DefinitionSetRevision, type EngineeringBinaryIdentity } from "./definitionRomApplicability.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import { N54_CURRENT_GOVERNED_REVIEW_REFERENCES, N54_CURRENT_ROM_LAYOUT_REGISTRY } from "./n54GovernedApplicabilityAdmission.ts";
import { constructQualifiedCalibrationExtractionRequest, extractQualifiedCalibrationValue } from "./qualifiedCalibrationExtraction.ts";
import { createEmptyRomLayoutApplicabilityRegistry, type QualifiedRomLayoutApplicabilityRelationship, type RomLayoutApplicabilityRegistrySnapshot } from "./romLayoutApplicabilityPublication.ts";

const root=path.resolve("BMW-XDFs-master/N54");const identities=["I8A0S","IJE0S","IKM0S","INA0S"] as const;type Identity=typeof identities[number];
type Parsed=Readonly<{definitions:readonly XdfDefinitionRevision[];set:DefinitionSetRevision}>;const parsedCache=new Map<string,Parsed>();
function parsed(identity:Identity,legacy=false):Parsed{const filename=`${identity}${legacy?"_Legacy":""}.xdf`;const cached=parsedCache.get(filename);if(cached)return cached;const result=interpretXdfStructure({xml:fs.readFileSync(path.join(root,filename),"utf8"),filename,provenance:`Qualified extraction test ${filename}`});assert.equal(result.outcome,"structurally_interpreted");assert.ok(result.sourceArtifact);const value=Object.freeze({definitions:result.definitions,set:defineDefinitionSetRevision({sourceArtifact:result.sourceArtifact!,definitions:result.definitions})});parsedCache.set(filename,value);return value;}
function binary(identity:Identity,role:"original"|"MapSwitchBase"):Readonly<{engineering:EngineeringBinary;identity:EngineeringBinaryIdentity}>{const filename=`${identity}_${role}.bin`;const result=resolveBinaryContainer({bytes:fs.readFileSync(path.join(root,filename)),fileName:filename});assert.equal(result.status,"resolved");const exact=identifyEngineeringBinary({engineeringBinary:result.engineeringBinary!,romFamily:"N54",softwareIdentity:identity,internalRomIdentifiers:[identity],identityProvenance:["Exact accepted N54 binary fixture"]});return Object.freeze({engineering:result.engineeringBinary!,identity:exact});}
function relationship(identity:Identity):QualifiedRomLayoutApplicabilityRelationship{const layout=N54_CURRENT_GOVERNED_REVIEW_REFERENCES.find((item)=>item.identity===identity)!.review.romLayoutId;const value=N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships.find((item)=>item.romLayoutId===layout);assert.ok(value);return value;}
function extractable(definitions:readonly XdfDefinitionRevision[],engineering:EngineeringBinary):XdfDefinitionRevision{const value=definitions.find((definition)=>assessDefinitionExtractionCapability(definition).state==="extraction_capable"&&extractRawCalibrationValues(engineering,definition).outcome==="extracted");assert.ok(value);return value;}
function request(identity:Identity,role:"original"|"MapSwitchBase"="original",options:Partial<{layout:string;snapshot:RomLayoutApplicabilityRegistrySnapshot;relationship:QualifiedRomLayoutApplicabilityRelationship;set:DefinitionSetRevision;definition:XdfDefinitionRevision;binary:ReturnType<typeof binary>}>= {}){const exact=options.binary??binary(identity,role),set=options.set??parsed(identity).set,relation=options.relationship??relationship(identity),definition=options.definition??extractable(parsed(identity).definitions,exact.engineering);return constructQualifiedCalibrationExtractionRequest({engineeringBinary:exact.engineering,binaryIdentity:exact.identity,romLayoutId:options.layout??relation.romLayoutId,registrySnapshot:options.snapshot??N54_CURRENT_ROM_LAYOUT_REGISTRY,expectedRelationshipId:relation.relationshipId,expectedRelationshipRevision:relation.relationshipRevision,definitionSet:set,definition});}

test("all four current N54 layouts produce deterministic immutable qualified raw Evidence",()=>{const report=[];for(const identity of identities){const qualifiedRequest=request(identity),first=extractQualifiedCalibrationValue(qualifiedRequest),again=extractQualifiedCalibrationValue(request(identity));assert.ok(Object.isFrozen(qualifiedRequest));assert.equal(first.status,"qualified_extracted",first.status==="rejected"?`${first.errorCode}: ${first.explanation}`:first.status);assert.deepEqual(first,again);if(first.status!=="qualified_extracted")continue;assert.equal(first.evidence.exactBinaryDigest,binary(identity,"original").identity.digest);assert.equal(first.evidence.romLayoutId,relationship(identity).romLayoutId);assert.equal(first.evidence.authorityChain.relationshipRevision,relationship(identity).relationshipRevision);assert.equal(first.evidence.authorityChain.qualificationProvenance,"tunesight_qualified_through_governed_engineering_evidence");assert.match(first.evidence.authorityChain.decisionId,/^rom-layout-applicability-decision:/);assert.ok(first.evidence.exactRawOffsets.length>0);assert.ok(Object.isFrozen(first)&&Object.isFrozen(first.evidence)&&Object.isFrozen(first.evidence.rawValues));report.push({identity,evidenceId:first.evidence.evidenceId,definitionRevision:first.evidence.definitionRevisionId,offsets:first.evidence.exactRawOffsets.length});}console.log(`N54_QUALIFIED_RAW_EXTRACTION ${JSON.stringify(report)}`);});

test("exact active relationship is required and none multiple and invalid remain distinct",()=>{const base=request("IJE0S"),empty=createEmptyRomLayoutApplicabilityRegistry("2026-08-23T03:00:00.000Z");const none=extractQualifiedCalibrationValue({...base,registrySnapshot:empty});assert.equal(none.status,"rejected");if(none.status==="rejected"){assert.equal(none.lookup.outcome,"none");assert.equal(none.errorCode,"layout_unqualified");}const rel=relationship("IJE0S"),duplicate={...rel,relationshipId:rel.relationshipId+":duplicate",relationshipRevision:rel.relationshipRevision+":duplicate"};const multipleSnapshot={...N54_CURRENT_ROM_LAYOUT_REGISTRY,relationships:Object.freeze([...N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships,duplicate])};const multiple=extractQualifiedCalibrationValue({...base,registrySnapshot:multipleSnapshot});assert.equal(multiple.status,"rejected");if(multiple.status==="rejected")assert.equal(multiple.lookup.outcome,"multiple_conflict");const invalid=extractQualifiedCalibrationValue({...base,romLayoutId:"N54"});assert.equal(invalid.status,"rejected");if(invalid.status==="rejected")assert.equal(invalid.lookup.outcome,"invalid");});

test("request relationship identity and Definition Set membership are exact",()=>{const base=request("IJE0S"),wrongRelationship=extractQualifiedCalibrationValue({...base,expectedRelationshipRevision:"qualified-rom-layout-applicability-revision:"+"0".repeat(64)});assert.equal(wrongRelationship.status,"rejected");if(wrongRelationship.status==="rejected")assert.equal(wrongRelationship.errorCode,"relationship_mismatch");const ina=parsed("INA0S"),wrongSet=extractQualifiedCalibrationValue(request("IJE0S","original",{set:ina.set,definition:extractable(ina.definitions,binary("IJE0S","original").engineering)}));assert.equal(wrongSet.status,"rejected");if(wrongSet.status==="rejected")assert.equal(wrongSet.errorCode,"definition_set_mismatch");const valid=request("IJE0S"),forged={...valid.definition,primaryAddress:valid.definition.primaryAddress!+1};const forgedResult=extractQualifiedCalibrationValue({...valid,definition:forged});assert.equal(forgedResult.status,"rejected");if(forgedResult.status==="rejected")assert.equal(forgedResult.errorCode,"definition_invalid");});

test("Legacy Definition authority is rejected although raw extraction may technically succeed",()=>{const exact=binary("IJE0S","original"),legacy=parsed("IJE0S",true),definition=extractable(legacy.definitions,exact.engineering);assert.equal(extractRawCalibrationValues(exact.engineering,definition).outcome,"extracted");const result=extractQualifiedCalibrationValue(request("IJE0S","original",{set:legacy.set,definition,binary:exact}));assert.equal(result.status,"rejected");if(result.status==="rejected")assert.equal(result.errorCode,"definition_set_mismatch");});

test("representation-conflicted Definition is rejected independently",()=>{const valid=request("IJE0S"),conflicting=defineXdfDefinitionRevision({...valid.definition,identity:{status:"conflicting",stableId:null,derivationBasis:null,unresolvedReason:"Controlled representation conflict."}});assert.equal(conflicting.revisionId,valid.definition.revisionId);const result=extractQualifiedCalibrationValue({...valid,definition:conflicting});assert.equal(result.status,"rejected");if(result.status==="rejected")assert.equal(result.errorCode,"definition_conflicting");});

test("wrong-ROM Definition Set cannot bypass applicability through readable offsets",()=>{const wrong=parsed("INA0S"),ije=binary("IJE0S","original"),definition=extractable(wrong.definitions,ije.engineering);assert.equal(extractRawCalibrationValues(ije.engineering,definition).outcome,"extracted");const result=extractQualifiedCalibrationValue(request("IJE0S","original",{set:wrong.set,definition,binary:ije}));assert.equal(result.status,"rejected");if(result.status==="rejected")assert.equal(result.errorCode,"definition_set_mismatch");});

test("unknown and byte-substituted exact binaries fail closed",()=>{const known=binary("IJE0S","original"),bytes=known.engineering.bytes;bytes[1]=(bytes[1]!+1)&0xff;const resolved=resolveBinaryContainer({bytes,fileName:"unknown-IJE0S.bin"});assert.equal(resolved.status,"resolved");const unknown={engineering:resolved.engineeringBinary!,identity:identifyEngineeringBinary({engineeringBinary:resolved.engineeringBinary!,romFamily:"N54",softwareIdentity:"IJE0S",internalRomIdentifiers:["IJE0S"],identityProvenance:["Controlled unknown binary"]})};const result=extractQualifiedCalibrationValue(request("IJE0S","original",{binary:unknown}));assert.equal(result.status,"rejected");if(result.status==="rejected")assert.equal(result.errorCode,"binary_layout_membership_unqualified");const substituted=extractQualifiedCalibrationValue({...request("IJE0S"),binaryIdentity:binary("IJE0S","MapSwitchBase").identity});assert.equal(substituted.status,"rejected");if(substituted.status==="rejected")assert.equal(substituted.errorCode,"binary_identity_mismatch");});

test("IJE0S original and MapSwitch produce independent exact-binary Evidence under one layout",()=>{const current=parsed("IJE0S"),original=binary("IJE0S","original"),map=binary("IJE0S","MapSwitchBase");const definition=current.definitions.find((item)=>{if(assessDefinitionExtractionCapability(item).state!=="extraction_capable")return false;const a=extractRawCalibrationValues(original.engineering,item),b=extractRawCalibrationValues(map.engineering,item);return a.outcome==="extracted"&&b.outcome==="extracted"&&JSON.stringify(a.shape?.values)!==JSON.stringify(b.shape?.values);})??extractable(current.definitions,original.engineering);const first=extractQualifiedCalibrationValue(request("IJE0S","original",{definition,binary:original})),second=extractQualifiedCalibrationValue(request("IJE0S","MapSwitchBase",{definition,binary:map}));assert.equal(first.status,"qualified_extracted");assert.equal(second.status,"qualified_extracted");if(first.status!=="qualified_extracted"||second.status!=="qualified_extracted")return;assert.equal(first.evidence.romLayoutId,second.evidence.romLayoutId);assert.equal(first.evidence.definitionRevisionId,second.evidence.definitionRevisionId);assert.notEqual(first.evidence.exactBinaryDigest,second.evidence.exactBinaryDigest);assert.notEqual(first.evidence.evidenceId,second.evidence.evidenceId);});

test("applicability remains valid when raw extraction fails",()=>{const base=request("IJE0S"),axisIndex=base.definition.axes.findIndex((axis)=>axis.axisId.toLowerCase()==="z");const axes=base.definition.axes.map((axis,index)=>index===axisIndex?{...axis,embeddedData:{...axis.embeddedData,address:base.engineeringBinary.byteLength-1,elementSizeBits:32}}:axis);const failing=defineXdfDefinitionRevision({...base.definition,axes});const set=defineDefinitionSetRevision({sourceArtifact:{artifactId:relationship("IJE0S").sourceArtifactId,sourceDigest:base.definitionSet.sourceArtifactDigest,byteLength:base.definitionSet.sourceByteLength,format:"xdf-xml",observedVersion:"1.60",filename:"controlled-failure.xdf",provenance:"Controlled extraction-failure fixture",sourceRevision:null,qualificationState:"source_discovered"},definitions:[failing]});const rel={...relationship("IJE0S"),definitionSetId:set.definitionSetId,definitionSetRevisionId:set.revisionId,relationshipId:"qualified-rom-layout-applicability:"+"e".repeat(64),relationshipRevision:"qualified-rom-layout-applicability-revision:"+"e".repeat(64)};const snapshot={...N54_CURRENT_ROM_LAYOUT_REGISTRY,relationships:Object.freeze([rel])};const result=extractQualifiedCalibrationValue(request("IJE0S","original",{set,definition:failing,relationship:rel,snapshot}));assert.equal(result.status,"extraction_failed");if(result.status==="extraction_failed"){assert.equal(result.lookup.outcome,"exact_active");assert.equal(result.errorCode,"raw_extraction_failed");assert.equal(result.applicabilityRelationship.relationshipRevision,rel.relationshipRevision);}});

test("equation source remains inert metadata and no semantic claim is produced",()=>{const exact=binary("IJE0S","original"),definition=parsed("IJE0S").definitions.find((item)=>assessDefinitionExtractionCapability(item).state==="extraction_capable"&&item.axes.some((axis)=>axis.equationSource!==null))!;assert.ok(definition);const result=extractQualifiedCalibrationValue(request("IJE0S","original",{definition,binary:exact}));assert.equal(result.status,"qualified_extracted");if(result.status!=="qualified_extracted")return;assert.deepEqual(result.evidence.inertEquationSources,[...new Set(definition.axes.map((axis)=>axis.equationSource).filter((value):value is string=>value!==null))].sort());assert.ok(!("engineeringValue" in result.evidence));assert.ok(!("recommendation" in result.evidence));});
