import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { resolveBinaryContainer, type EngineeringBinary } from "../tunes/binaryContainer.ts";
import { collectInternalIdentityObservations, type InternalIdentityObservation } from "./applicabilityEvidenceProposal.ts";
import { assessDefinitionExtractionCapability, extractRawCalibrationValues } from "./calibrationValueExtraction.ts";
import type { XdfDefinitionRevision } from "./canonicalXdfDefinition.ts";
import { defineDefinitionSetRevision, identifyEngineeringBinary, type DefinitionSetRevision, type EngineeringBinaryIdentity } from "./definitionRomApplicability.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import { N54_CURRENT_GOVERNED_REVIEW_REFERENCES, N54_CURRENT_ROM_LAYOUT_REGISTRY } from "./n54GovernedApplicabilityAdmission.ts";
import {
  compareQualifiedCalibrationDatasets,
  compareQualifiedCalibrations,
  constructQualifiedCalibrationComparisonRequest,
  constructQualifiedCalibrationDatasetComparisonRequest,
} from "./qualifiedCalibrationComparison.ts";
import {
  classifyUnmaterializableDatasetDefinition,
  constructQualifiedCalibrationDatasetRequest,
  materializeQualifiedCalibrationDataset,
  type CalibrationDatasetSourceRole,
  type QualifiedCalibrationDataset,
} from "./qualifiedCalibrationDataset.ts";
import { defineRomLayoutIdentity, type RomLayoutIdentity, type RomLayoutMarker } from "./romLayoutApplicability.ts";
import { constructQualifiedRomLayoutDiscoveryRegistry, type QualifiedRomLayoutDiscoveryRegistry, type RomLayoutMembershipAuthority } from "./romLayoutDiscovery.ts";

const ids=["I8A0S","IJE0S","IKM0S","INA0S"] as const;type Identity=typeof ids[number];type Parsed=Readonly<{definitions:readonly XdfDefinitionRevision[];set:DefinitionSetRevision}>;type Exact=Readonly<{engineering:EngineeringBinary;identity:EngineeringBinaryIdentity;observations:readonly InternalIdentityObservation[];markers:readonly RomLayoutMarker[]}>;const root=path.resolve("BMW-XDFs-master/N54"),parsedCache=new Map<Identity,Parsed>(),exactCache=new Map<string,Exact>(),layoutCache=new Map<Identity,RomLayoutIdentity>(),datasetCache=new Map<string,QualifiedCalibrationDataset>();
function parsed(id:Identity):Parsed{const hit=parsedCache.get(id);if(hit)return hit;const filename=`${id}.xdf`,result=interpretXdfStructure({xml:fs.readFileSync(path.join(root,filename),"utf8"),filename,provenance:`Dataset proof ${filename}`});assert.equal(result.outcome,"structurally_interpreted");const value=Object.freeze({definitions:result.definitions,set:defineDefinitionSetRevision({sourceArtifact:result.sourceArtifact!,definitions:result.definitions})});parsedCache.set(id,value);return value;}
function observe(bytes:Uint8Array,vocabulary:readonly string[]=ids){return collectInternalIdentityObservations({binaryBytes:bytes,credibleIdentifiers:vocabulary.map((identifier)=>({identifier,kind:"ascii_rom_marker" as const,confidence:"known_identity" as const,reason:"Qualified Dataset identity vocabulary",encodings:["ascii" as const]}))});}
function fromBytes(id:Identity,bytes:Uint8Array,fileName:string,vocabulary:readonly string[]=ids):Exact{const resolved=resolveBinaryContainer({bytes,fileName});assert.equal(resolved.status,"resolved");const observations=observe(resolved.engineeringBinary!.bytes,vocabulary),identity=identifyEngineeringBinary({engineeringBinary:resolved.engineeringBinary!,romFamily:"N54",softwareIdentity:id,internalRomIdentifiers:observations.map((value)=>value.normalizedForm),identityProvenance:["Exact Dataset candidate bytes"]}),markers=observations.filter((value)=>value.normalizedForm===id).map((value)=>({kind:value.kind,normalizedForm:value.normalizedForm,offsets:value.offsets,detector:value.detector}));return Object.freeze({engineering:resolved.engineeringBinary!,identity,observations,markers:Object.freeze(markers)});}
function exact(id:Identity,role:"original"|"MapSwitchBase"):Exact{const key=`${id}_${role}`,hit=exactCache.get(key);if(hit)return hit;const value=fromBytes(id,fs.readFileSync(path.join(root,`${key}.bin`)),`${key}.bin`);exactCache.set(key,value);return value;}
function layout(id:Identity):RomLayoutIdentity{const hit=layoutCache.get(id);if(hit)return hit;const source=parsed(id),original=exact(id,"original"),addresses=source.definitions.map((value)=>value.primaryAddress).filter((value):value is number=>value!==null),region=source.definitions[0]!.addressSpace.regions[0]!,value=defineRomLayoutIdentity({romSoftwareIdentifiers:[id],calibrationSoftwareIdentifiers:[id],ecuDmeFamily:id==="I8A0S"?"MSD80":"MSD81",binaryByteLength:original.identity.byteLength,containerTypes:[original.identity.containerType],internalMarkers:original.markers,calibrationAddressSpace:[{startAddress:region.startAddress,size:region.size}],definitionCompatibleAddressRange:{minimum:Math.min(...addresses),maximum:Math.max(...addresses)},xdfSideIdentities:[id],evidenceProvenance:["Accepted current N54 governed layout evidence"]});assert.equal(value.layoutId,N54_CURRENT_GOVERNED_REVIEW_REFERENCES.find((item)=>item.identity===id)!.review.romLayoutId);layoutCache.set(id,value);return value;}
function relationship(id:Identity){return N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships.find((value)=>value.romLayoutId===layout(id).layoutId)!;}
function authorities():readonly RomLayoutMembershipAuthority[]{return ids.map((id)=>({layout:layout(id),relationship:relationship(id),definitionSet:parsed(id).set,definitions:parsed(id).definitions}));}
let discoveryRegistryCache:QualifiedRomLayoutDiscoveryRegistry|null=null;function discoveryRegistry(){return discoveryRegistryCache??=constructQualifiedRomLayoutDiscoveryRegistry({authoritySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,layouts:ids.map(layout)});}
function request(candidate:Exact,role:CalibrationDatasetSourceRole,membershipAuthorities=authorities(),applicabilityRegistry=N54_CURRENT_ROM_LAYOUT_REGISTRY){return constructQualifiedCalibrationDatasetRequest({engineeringBinary:candidate.engineering,binaryIdentity:candidate.identity,observations:candidate.observations,discoveryRegistry:discoveryRegistry(),applicabilityRegistry,membershipAuthorities,sourceRole:role,sourceProvenance:["Controlled qualified Dataset proof"],independentlyQualifiedEcuFamily:null});}
function dataset(id:Identity,role:"original"|"MapSwitchBase"):QualifiedCalibrationDataset{const key=`${id}_${role}`,hit=datasetCache.get(key);if(hit)return hit;const result=materializeQualifiedCalibrationDataset(request(exact(id,role),role==="original"?"stock_candidate":"mapswitch"));assert.ok(result.status==="materialized"||result.status==="dataset_partial");const value=result.dataset;datasetCache.set(key,value);return value;}
function modified(id:Identity):Exact{const source=parsed(id),base=exact(id,"original"),bytes=base.engineering.bytes;for(const definition of source.definitions){if(assessDefinitionExtractionCapability(definition).state!=="extraction_capable")continue;const extraction=extractRawCalibrationValues(base.engineering,definition),offset=extraction.offsets[0];if(extraction.outcome!=="extracted"||offset===undefined||base.markers.some((marker)=>marker.offsets.some((at)=>offset>=at&&offset<at+marker.normalizedForm.length)))continue;bytes[offset]=(bytes[offset]!+1)&0xff;return fromBytes(id,bytes,`${id}_dataset_modified.bin`);}throw new Error("No safe modification point found.");}

test("Dataset request, identity and revision are deterministic and exact-binary-bound",()=>{const candidate=exact("IJE0S","original"),a=request(candidate,"stock_candidate"),b=request(candidate,"stock_candidate");assert.deepEqual(a,b);const first=materializeQualifiedCalibrationDataset(a),second=materializeQualifiedCalibrationDataset(b);assert.equal(first.status,"dataset_partial");assert.deepEqual(first,second);if(!first.dataset||!second.dataset)return;assert.equal(first.dataset.datasetId,second.dataset.datasetId);assert.equal(first.dataset.datasetRevision,second.dataset.datasetRevision);assert.equal(first.dataset.exactBinaryIdentity.digest,candidate.identity.digest);});

test("all four current N54 originals produce complete-universe immutable Datasets",()=>{const report=[];for(const id of ids){const started=performance.now(),value=dataset(id,"original"),summary=value.summary;assert.equal(summary.totalDefinitions,parsed(id).set.definitionCount);assert.equal(value.definitions.length,summary.totalDefinitions);assert.equal(summary.availableQualifiedDefinitions+summary.unavailableDefinitions,summary.totalDefinitions);assert.equal(summary.scalars+summary.oneDimensionalTables+summary.twoDimensionalTables,summary.availableQualifiedDefinitions);assert.equal(summary.conflictedDefinitions,0);assert.equal(summary.unavailableDefinitions,1);assert.ok(summary.unitsRepresented.length>0);assert.ok(Object.isFrozen(value)&&Object.isFrozen(value.definitions)&&Object.isFrozen(value.definitions[0])&&Object.isFrozen(value.summary)&&Object.isFrozen(value.provenance));report.push({id,datasetId:value.datasetId,total:summary.totalDefinitions,available:summary.availableQualifiedDefinitions,unavailable:summary.unavailableDefinitions,conflicts:summary.conflictedDefinitions,scalar:summary.scalars,oneD:summary.oneDimensionalTables,twoD:summary.twoDimensionalTables,axes:summary.axesAvailable,units:summary.unitsRepresented.length,milliseconds:Math.round(performance.now()-started)});}console.log(`N54_QUALIFIED_CALIBRATION_DATASETS ${JSON.stringify(report)}`);});

test("available scalar, 1D and 2D records preserve values, axes, units and cell trace",()=>{const value=dataset("IJE0S","original");for(const kind of ["scalar","array_1d","table_2d"] as const){const record=value.definitions.find((item)=>item.dimensions?.kind===kind&&item.engineeringEvidence!==null);assert.ok(record?.engineeringEvidence&&record.rawEvidence);assert.equal(record.engineeringEvidence.exactBinaryDigest,value.exactBinaryIdentity.digest);assert.equal(record.engineeringEvidence.cellTrace.length,record.engineeringEvidence.engineeringValues.length);assert.equal(record.rawEvidence.exactRawOffsets.length,record.engineeringEvidence.engineeringValues.length);assert.ok(Object.isFrozen(record.engineeringEvidence.engineeringValues)&&Object.isFrozen(record.engineeringEvidence.axes));}assert.ok(value.definitions.some((item)=>item.engineeringEvidence?.axes.some((axis)=>axis.outcome==="converted"||axis.outcome==="identity"||axis.outcome==="static_literal")));assert.ok(value.definitions.some((item)=>item.units!==null));});

test("unavailable and representation-conflict records remain explicit",()=>{const value=dataset("IJE0S","original"),unavailable=value.definitions.filter((item)=>item.engineeringEvidence===null);assert.equal(unavailable.length,1);assert.equal(unavailable[0]!.state,"invalid_numeric_conversion");assert.equal(unavailable[0]!.unavailableStage,"conversion");assert.ok(unavailable[0]!.findings.length>0);const definition=parsed("IJE0S").definitions[0]!,conflicted={...definition,identity:{status:"conflicting" as const,stableId:null,derivationBasis:null,unresolvedReason:"Controlled representation conflict"}},record=classifyUnmaterializableDatasetDefinition(conflicted);assert.equal(record?.state,"representation_conflict");assert.equal(record?.unavailableStage,"representation");assert.equal(record?.engineeringEvidence,null);});

test("IJE0S Original, MapSwitch and new modified digest share authority but have distinct Dataset identities",()=>{const original=dataset("IJE0S","original"),mapswitch=dataset("IJE0S","MapSwitchBase"),candidate=modified("IJE0S"),result=materializeQualifiedCalibrationDataset(request(candidate,"user_modified"));assert.equal(result.status,"dataset_partial");if(!result.dataset)return;for(const value of [mapswitch,result.dataset]){assert.equal(value.romLayoutId,original.romLayoutId);assert.equal(value.relationshipRevision,original.relationshipRevision);assert.equal(value.definitionSetRevisionId,original.definitionSetRevisionId);assert.notEqual(value.exactBinaryIdentity.digest,original.exactBinaryIdentity.digest);assert.notEqual(value.datasetId,original.datasetId);}assert.notEqual(mapswitch.datasetId,result.dataset.datasetId);assert.ok(result.dataset.definitions.some((record,index)=>record.engineeringEvidence?.engineeringValues.some((value,cell)=>value!==original.definitions[index]?.engineeringEvidence?.engineeringValues[cell])));});

test("discovery, membership, active applicability and Definition Set gates fail atomically",()=>{const candidate=exact("IJE0S","original"),unknownBytes=new Uint8Array(candidate.engineering.byteLength);Buffer.from("ZZZ9_UNKNOWN","ascii").copy(unknownBytes,2048);const unknown=fromBytes("IJE0S",unknownBytes,"unknown-dataset.bin",["ZZZ9_UNKNOWN"]),discoveryFailed=materializeQualifiedCalibrationDataset(request(unknown,"other_observed"));assert.equal(discoveryFailed.status,"discovery_failed");assert.equal(discoveryFailed.dataset,null);const invalid=materializeQualifiedCalibrationDataset(constructQualifiedCalibrationDatasetRequest({...request(candidate,"reference"),binaryIdentity:{...candidate.identity,digest:"0".repeat(64),identityId:`engineering-binary:${"0".repeat(64)}`}}));assert.equal(invalid.status,"invalid");const authority=authorities().map((value)=>value.layout.layoutId===layout("IJE0S").layoutId?{...value,definitionSet:{...value.definitionSet,revisionId:"invalid-definition-set-revision"}}:value),membershipFailed=materializeQualifiedCalibrationDataset(request(candidate,"reference",authority));assert.equal(membershipFailed.status,"membership_failed");const noActive={...N54_CURRENT_ROM_LAYOUT_REGISTRY,relationships:N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships.filter((value)=>value.romLayoutId!==layout("IJE0S").layoutId)},authorityFailed=materializeQualifiedCalibrationDataset(request(candidate,"reference",authorities(),noActive));assert.equal(authorityFailed.status,"authority_unavailable");for(const result of [membershipFailed,authorityFailed])assert.equal(result.dataset,null);});

test("Dataset-based comparison is consistent with direct qualified comparison",()=>{const reference=dataset("IJE0S","original"),mapswitch=dataset("IJE0S","MapSwitchBase"),datasetComparison=compareQualifiedCalibrationDatasets(constructQualifiedCalibrationDatasetComparisonRequest({reference,modified:mapswitch})),relation=relationship("IJE0S"),direct=compareQualifiedCalibrations(constructQualifiedCalibrationComparisonRequest({reference:{engineeringBinary:exact("IJE0S","original").engineering,binaryIdentity:exact("IJE0S","original").identity,role:"stock_candidate",provenance:reference.provenance},modified:{engineeringBinary:exact("IJE0S","MapSwitchBase").engineering,binaryIdentity:exact("IJE0S","MapSwitchBase").identity,role:"mapswitch",provenance:mapswitch.provenance},romLayoutId:layout("IJE0S").layoutId,registrySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,expectedRelationshipId:relation.relationshipId,expectedRelationshipRevision:relation.relationshipRevision,definitionSet:parsed("IJE0S").set,definitions:parsed("IJE0S").definitions}));assert.equal(datasetComparison.status,"compared");assert.equal(direct.status,"compared");if(datasetComparison.status!=="compared"||direct.status!=="compared")return;for(const key of ["comparisonId","comparisonRevision","changedDefinitions","unchangedDefinitions","axisChangedDefinitions","valueAndAxisChangedDefinitions","unavailableDefinitions","conflictedDefinitions","totalChangedCells"] as const)assert.deepEqual(datasetComparison.evidence[key],direct.evidence[key]);assert.deepEqual(datasetComparison.evidence.definitions.map((value)=>[value.definitionRevisionId,value.outcome,value.changedCellCount,value.changedCells[0]?.signedDelta??null]),direct.evidence.definitions.map((value)=>[value.definitionRevisionId,value.outcome,value.changedCellCount,value.changedCells[0]?.signedDelta??null]));});

test("Dataset is reusable Evidence without Stock, semantic or recommendation fabrication",()=>{const value=dataset("INA0S","original"),source=fs.readFileSync(path.resolve("lib/xdf/qualifiedCalibrationDataset.ts"),"utf8");assert.equal(value.stockAuthenticity,"not_assessed");assert.equal(value.semanticKnowledge,"not_assessed");assert.equal(value.recommendation,"not_assessed");assert.ok(!("stock" in value)&&!("meaning" in value)&&!("safe" in value));assert.ok(!ids.some((id)=>source.includes(`\"${id}\"`)));assert.ok(value.definitions.every((record)=>record.sourceArtifactDigest===value.sourceArtifactDigest));});
