import assert from "node:assert/strict";
import test from "node:test";
import type { CompleteBinaryValidation } from "./bmwMasterFullValidation.ts";
import { FOUNDER_00003076501103_APPLICABILITY_CANDIDATE } from "./b58PhysicalApplicabilityCandidate.ts";
import { FOUNDER_00003076501103_SOURCE_AUTHORITY } from "./b58PhysicalAcceptedSourceAuthority.ts";
import { FOUNDER_00003076501103_INJECTOR_SCALAR_QUARANTINE, FOUNDER_00003076501103_INJECTOR_SCALAR_SAFETY_ASSESSMENT } from "./b58PhysicalTableQuarantine.ts";
import { constructQuarantineAwareApplicabilityCandidate, type AcceptedQuarantineBinding } from "./quarantineAwareApplicabilityCandidate.ts";

const authority = FOUNDER_00003076501103_SOURCE_AUTHORITY, scope = authority.scope[0]!;
function validation(overrides: Partial<CompleteBinaryValidation> = {}): CompleteBinaryValidation { return { validationId: "validation:test", validationRevision: "validation-revision:test", binaryDigest: "a".repeat(64), definitions: 3, extractionAttempts: 3, extractionSuccess: 3, blocked: 0, outOfBounds: 0, unsupported: 0, representationConflicts: 0, converted: 2, identityNoOp: 1, invalidNumeric: 0, malformed: 0, unavailable: 0, unresolvedUnits: 0, other: 0, ...overrides }; }
function candidate(validations: readonly CompleteBinaryValidation[], bindings: readonly AcceptedQuarantineBinding[] = []) { return constructQuarantineAwareApplicabilityCandidate({ sourceAuthority: authority, romSoftwareIdentity: "00003076501103", definitionSetId: scope.definitionSetId, definitionSetRevision: scope.definitionSetRevision, totalDefinitions: 3, validations, quarantineBindings: bindings, limitations: ["Stock authenticity remains not assessed."] }); }
function syntheticBinding(binaryDigest: string, definitionRevisionId: string, occurrence: number): AcceptedQuarantineBinding {
  const safetyAssessment = { ...FOUNDER_00003076501103_INJECTOR_SCALAR_SAFETY_ASSESSMENT, assessmentRevision: `assessment:${definitionRevisionId}:${occurrence}`, definitionRevisionId, binaryDigest, outcome: "dependency_safe_for_quarantine" as const };
  const quarantine = { ...FOUNDER_00003076501103_INJECTOR_SCALAR_QUARANTINE, quarantineId: `quarantine:${definitionRevisionId}:${occurrence}`, quarantineRevision: `quarantine-revision:${definitionRevisionId}:${occurrence}`, relationship: { romSoftwareIdentity: "00003076501103", sourceArtifactId: scope.sourceArtifactId, definitionSetRevision: scope.definitionSetRevision }, occurrence: { ...FOUNDER_00003076501103_INJECTOR_SCALAR_QUARANTINE.occurrence, definitionRevisionId, occurrence }, affectedBinary: { digest: binaryDigest, role: "observed", validationRevision: `validation-revision:${binaryDigest}` }, safetyAssessmentRevision: safetyAssessment.assessmentRevision };
  return { quarantine, safetyAssessment };
}

test("all-valid coverage is eligible without quarantine", () => { const result = candidate([validation()]); assert.equal(result.coverageClass, "fully_valid"); assert.equal(result.qualifiedDefinitions, 3); assert.equal(result.quarantinedDefinitions, 0); assert.equal(result.unresolvedDefinitions, 0); });
test("one or multiple exact dependency-safe quarantines remain reviewable", () => { const digest = "b".repeat(64), first = syntheticBinding(digest, "definition:one", 0), second = syntheticBinding(digest, "definition:two", 0); const one = candidate([validation({ binaryDigest: digest, validationRevision: `validation-revision:${digest}`, converted: 1, identityNoOp: 1, invalidNumeric: 1 })], [first]); assert.equal(one.coverageClass, "valid_with_accepted_quarantine"); assert.equal(one.quarantinedDefinitions, 1); const multiple = candidate([validation({ binaryDigest: digest, validationRevision: `validation-revision:${digest}`, converted: 1, identityNoOp: 0, invalidNumeric: 2 })], [first, second]); assert.equal(multiple.relationshipEligibility, "eligible_for_founder_review"); assert.equal(multiple.quarantinedDefinitions, 2); });
test("mismatch, wrong occurrence, unsafe dependency, uncovered failure and conflict fail closed", () => { const digest = "c".repeat(64), exact = syntheticBinding(digest, "definition:one", 0), invalid = validation({ binaryDigest: digest, validationRevision: `validation-revision:${digest}`, converted: 1, identityNoOp: 1, invalidNumeric: 1 }); const mismatch = { ...exact, quarantine: { ...exact.quarantine, safetyAssessmentRevision: "wrong" } }; assert.equal(candidate([invalid], [mismatch]).relationshipEligibility, "ineligible"); const wrongOccurrence = { ...exact, safetyAssessment: { ...exact.safetyAssessment, definitionRevisionId: "definition:other" } }; assert.equal(candidate([invalid], [wrongOccurrence]).relationshipEligibility, "ineligible"); const unsafe = { ...exact, safetyAssessment: { ...exact.safetyAssessment, outcome: "whole_relationship_blocked" as const } }; assert.equal(candidate([invalid], [unsafe]).relationshipEligibility, "ineligible"); assert.equal(candidate([invalid]).relationshipEligibility, "ineligible"); assert.equal(candidate([validation({ representationConflicts: 1 })]).relationshipEligibility, "ineligible"); });
test("authority-bearing dependency changes revise the candidate deterministically", () => { const base = candidate([validation()]), changed = candidate([validation({ validationRevision: "validation-revision:changed" })]); assert.notEqual(base.candidateRevision, changed.candidateRevision); assert.equal(base.candidateId, changed.candidateId); assert.deepEqual(base, candidate([validation()])); assert.ok(Object.isFrozen(base)); });
test("00003076501103 materializes an unpublished exact review candidate from accepted Evidence", (context) => { const result = FOUNDER_00003076501103_APPLICABILITY_CANDIDATE; assert.equal(result.coverageClass, "valid_with_accepted_quarantine"); assert.equal(result.relationshipEligibility, "eligible_for_founder_review"); assert.equal(result.totalDefinitions, 1175); assert.equal(result.qualifiedDefinitions, 1174); assert.equal(result.quarantinedDefinitions, 1); assert.equal(result.unresolvedDefinitions, 0); assert.equal(result.representationConflicts, 0); assert.equal(result.publicationState, "not_authorized"); assert.deepEqual(result.publicationSideEffects, []); context.diagnostic(`B58_00003076501103_QUARANTINE_AWARE_APPLICABILITY ${JSON.stringify(result)}`); });
