import assert from "node:assert/strict";
import test from "node:test";
import { FOUNDER_00003076501103_ACCEPTED_APPLICABILITY_CANDIDATE_ID, FOUNDER_00003076501103_ACCEPTED_APPLICABILITY_CANDIDATE_REVISION, FOUNDER_00003076501103_ACCEPTED_APPLICABILITY_DECISION, FOUNDER_00003076501103_WORKSHOP_ADMISSION_ASSESSMENT } from "./b58PhysicalAcceptedApplicabilityDecision.ts";
import { FOUNDER_00003076501103_APPLICABILITY_CANDIDATE } from "./b58PhysicalApplicabilityCandidate.ts";
import { FOUNDER_00003076501103_COMPLETE_VALIDATIONS, FOUNDER_00003076501103_INJECTOR_SCALAR_QUARANTINE, FOUNDER_00003076501103_INJECTOR_SCALAR_SAFETY_ASSESSMENT } from "./b58PhysicalTableQuarantine.ts";
import { constructAcceptedQuarantineAwareApplicabilityDecision } from "./quarantineAwareApplicabilityDecision.ts";

const input = { candidate: FOUNDER_00003076501103_APPLICABILITY_CANDIDATE, acceptedCandidateId: FOUNDER_00003076501103_ACCEPTED_APPLICABILITY_CANDIDATE_ID, acceptedCandidateRevision: FOUNDER_00003076501103_ACCEPTED_APPLICABILITY_CANDIDATE_REVISION, validations: FOUNDER_00003076501103_COMPLETE_VALIDATIONS, quarantines: [FOUNDER_00003076501103_INJECTOR_SCALAR_QUARANTINE], safetyAssessments: [FOUNDER_00003076501103_INJECTOR_SCALAR_SAFETY_ASSESSMENT], authority: { authorityId: "applicability-decision-authority:test", authorityRevision: "authority-revision:test", authorityClass: "founder" as const, provenance: ["Explicit controlled Founder acceptance."] }, decidedAt: "2026-09-13T00:00:00.000Z" };

test("exact Founder acceptance materializes an immutable unpublished decision", (context) => { const decision = FOUNDER_00003076501103_ACCEPTED_APPLICABILITY_DECISION; assert.equal(decision.outcome, "accept_exact_applicability_with_quarantine"); assert.equal(decision.qualifiedDefinitions, 1174); assert.equal(decision.quarantinedDefinitions, 1); assert.equal(decision.unresolvedDefinitions, 0); assert.equal(decision.publicationState, "not_published"); assert.deepEqual(decision.publicationSideEffects, []); assert.ok(Object.isFrozen(decision)); context.diagnostic(`B58_00003076501103_ACCEPTED_APPLICABILITY ${JSON.stringify(decision)}`); });
test("substituted candidate and dependency revisions cannot inherit acceptance", () => { assert.throws(() => constructAcceptedQuarantineAwareApplicabilityDecision({ ...input, acceptedCandidateRevision: "substituted" }), /exact Founder-accepted/); assert.throws(() => constructAcceptedQuarantineAwareApplicabilityDecision({ ...input, validations: [{ ...input.validations[0]!, validationRevision: "substituted" }, input.validations[1]!] }), /dependencies/); assert.throws(() => constructAcceptedQuarantineAwareApplicabilityDecision({ ...input, safetyAssessments: [{ ...input.safetyAssessments[0]!, assessmentRevision: "substituted" }] }), /dependencies/); });
test("quarantine permissions and publication remain fail closed", () => { const unsafe = { ...input.quarantines[0]!, permissions: { ...input.quarantines[0]!.permissions, editable: true as false } }; assert.throws(() => constructAcceptedQuarantineAwareApplicabilityDecision({ ...input, quarantines: [unsafe] }), /cannot make/); assert.equal(FOUNDER_00003076501103_WORKSHOP_ADMISSION_ASSESSMENT.publicationEligibility, "pending_separate_founder_decision"); assert.equal(FOUNDER_00003076501103_WORKSHOP_ADMISSION_ASSESSMENT.workshopAdmission, "not_authorized"); assert.equal(FOUNDER_00003076501103_WORKSHOP_ADMISSION_ASSESSMENT.referenceAuthority, "not_established"); assert.equal(FOUNDER_00003076501103_WORKSHOP_ADMISSION_ASSESSMENT.comparisonEligibility, "unavailable_without_reference"); assert.equal(FOUNDER_00003076501103_WORKSHOP_ADMISSION_ASSESSMENT.subscriberProviderOutcome, "coverage_unavailable"); });
