import { createHash } from "node:crypto";
import type { CompleteBinaryValidation } from "./bmwMasterFullValidation.ts";
import type { AcceptedQuarantineAwareApplicabilityDecision } from "./quarantineAwareApplicabilityDecision.ts";
import type { TableQuarantineRecord, TableQuarantineSafetyAssessment } from "./tableQuarantine.ts";

export type QuarantineAwarePublicationCandidate = Readonly<{ candidateId: string; candidateRevision: string; contractVersion: "tunesight.quarantine-aware-rom-layout-publication-candidate.v1"; romSoftwareIdentity: string; romLayoutId: string; sourceAuthorityId: string; sourceAuthorityRevision: string; definitionSetId: string; definitionSetRevision: string; applicabilityDecisionId: string; applicabilityDecisionRevision: string; validationIds: readonly string[]; validationRevisions: readonly string[]; quarantineIds: readonly string[]; quarantineRevisions: readonly string[]; quarantineSafetyAssessmentRevisions: readonly string[]; qualifiedDefinitions: number; quarantinedDefinitions: number; unresolvedDefinitions: number; representationConflicts: number; stockReferenceAuthority: "not_established"; eligibility: "eligible_for_founder_publication_review" | "publication_ineligible"; blockers: readonly string[]; publicationState: "candidate_only_not_published"; publicationSideEffects: readonly []; limitations: readonly string[] }>;
function hash(value: unknown) { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
const freeze = <T>(value: T): T => { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as T; if (value && typeof value === "object") return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, freeze(item)]))) as T; return value; };
export function constructQuarantineAwarePublicationCandidate(input: Readonly<{ decision: AcceptedQuarantineAwareApplicabilityDecision; romLayoutId: string; validations: readonly CompleteBinaryValidation[]; quarantines: readonly TableQuarantineRecord[]; safetyAssessments: readonly TableQuarantineSafetyAssessment[] }>): QuarantineAwarePublicationCandidate {
  const { decision } = input, blockers: string[] = [];
  if (!/^rom-layout:[a-f0-9]{64}$/.test(input.romLayoutId)) blockers.push("Exact ROM Layout identity is missing or invalid.");
  if (decision.publicationState !== "not_published" || decision.outcome !== "accept_exact_applicability_with_quarantine") blockers.push("Exact accepted applicability is required.");
  const validationIds = input.validations.map((item) => item.validationId).sort(), validationRevisions = input.validations.map((item) => item.validationRevision).sort(), quarantineIds = input.quarantines.map((item) => item.quarantineId).sort(), quarantineRevisions = input.quarantines.map((item) => item.quarantineRevision).sort(), quarantineSafetyAssessmentRevisions = input.safetyAssessments.map((item) => item.assessmentRevision).sort();
  if (JSON.stringify(validationIds) !== JSON.stringify(decision.validationIds) || JSON.stringify(validationRevisions) !== JSON.stringify(decision.validationRevisions)) blockers.push("Physical binary membership validation binding is incomplete.");
  if (JSON.stringify(quarantineIds) !== JSON.stringify(decision.quarantineIds) || JSON.stringify(quarantineRevisions) !== JSON.stringify(decision.quarantineRevisions) || JSON.stringify(quarantineSafetyAssessmentRevisions) !== JSON.stringify(decision.quarantineSafetyAssessmentRevisions)) blockers.push("Accepted quarantine binding is incomplete.");
  if (decision.unresolvedDefinitions || input.validations.some((item) => item.representationConflicts)) blockers.push("Unresolved Definitions or representation conflicts prohibit publication review.");
  if (input.quarantines.some((item) => item.permissions.editable || item.permissions.suggestedCalibrationEligible || item.permissions.reconstructionMutationEligible || item.permissions.flashingEligible)) blockers.push("Quarantine permissions are not fail-closed.");
  const identity = { romSoftwareIdentity: decision.romSoftwareIdentity, romLayoutId: input.romLayoutId, definitionSetId: decision.definitionSetId };
  const material = { ...identity, sourceAuthorityId: decision.sourceAuthorityId, sourceAuthorityRevision: decision.sourceAuthorityRevision, definitionSetRevision: decision.definitionSetRevision, applicabilityDecisionId: decision.decisionId, applicabilityDecisionRevision: decision.decisionRevision, validationIds, validationRevisions, quarantineIds, quarantineRevisions, quarantineSafetyAssessmentRevisions, qualifiedDefinitions: decision.qualifiedDefinitions, quarantinedDefinitions: decision.quarantinedDefinitions, unresolvedDefinitions: decision.unresolvedDefinitions, representationConflicts: input.validations.reduce((sum, item) => sum + item.representationConflicts, 0), stockReferenceAuthority: "not_established" as const, eligibility: blockers.length ? "publication_ineligible" as const : "eligible_for_founder_publication_review" as const, blockers: [...blockers].sort(), publicationState: "candidate_only_not_published" as const, publicationSideEffects: [] as const, limitations: [...new Set([...decision.limitations, "Publication does not establish authoritative Stock or Reference status.", "Current-only Workshop activation requires a separate accepted publication decision."])].sort(), contractVersion: "tunesight.quarantine-aware-rom-layout-publication-candidate.v1" as const };
  return freeze({ candidateId: `quarantine-aware-rom-layout-publication-candidate:${hash(identity)}`, candidateRevision: `quarantine-aware-rom-layout-publication-candidate-revision:${hash(material)}`, ...material, publicationSideEffects: Object.freeze([]) as readonly [] });
}
