import { createHash } from "node:crypto";
import type { CompleteBinaryValidation } from "./bmwMasterFullValidation.ts";
import type { QuarantineAwareApplicabilityCandidate } from "./quarantineAwareApplicabilityCandidate.ts";
import type { TableQuarantineRecord, TableQuarantineSafetyAssessment } from "./tableQuarantine.ts";

export const QUARANTINE_AWARE_APPLICABILITY_DECISION_CONTRACT = "tunesight.quarantine-aware-applicability-decision.v1" as const;
export type QuarantineAwareApplicabilityDecisionAuthority = Readonly<{ authorityId: string; authorityRevision: string; authorityClass: "founder"; provenance: readonly string[] }>;
export type AcceptedQuarantineAwareApplicabilityDecision = Readonly<{
  decisionId: string; decisionRevision: string; contractVersion: typeof QUARANTINE_AWARE_APPLICABILITY_DECISION_CONTRACT;
  outcome: "accept_exact_applicability_with_quarantine"; candidateId: string; candidateRevision: string; romSoftwareIdentity: string;
  sourceAuthorityId: string; sourceAuthorityRevision: string; definitionSetId: string; definitionSetRevision: string;
  validationIds: readonly string[]; validationRevisions: readonly string[]; quarantineIds: readonly string[]; quarantineRevisions: readonly string[];
  quarantineSafetyAssessmentRevisions: readonly string[]; qualifiedDefinitions: number; quarantinedDefinitions: number; unresolvedDefinitions: 0;
  limitations: readonly string[]; authority: QuarantineAwareApplicabilityDecisionAuthority; decidedAt: string;
  publicationState: "not_published"; publicationSideEffects: readonly [];
}>;

function canonical(value: unknown): string { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isSafeInteger(value)) throw new Error("Decision contains an unsafe number."); return JSON.stringify(value); } if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (!value || typeof value !== "object") throw new Error("Decision contains unsupported material."); const record = value as Readonly<Record<string, unknown>>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`; }
const digest = (domain: string, value: unknown) => createHash("sha256").update(domain).update(Buffer.from([0])).update(canonical(value)).digest("hex");
function freeze<T>(value: T): T { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as T; if (value && typeof value === "object") return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, freeze(item)]))) as T; return value; }

export function constructAcceptedQuarantineAwareApplicabilityDecision(input: Readonly<{ candidate: QuarantineAwareApplicabilityCandidate; acceptedCandidateId: string; acceptedCandidateRevision: string; validations: readonly CompleteBinaryValidation[]; quarantines: readonly TableQuarantineRecord[]; safetyAssessments: readonly TableQuarantineSafetyAssessment[]; authority: QuarantineAwareApplicabilityDecisionAuthority; decidedAt: string }>): AcceptedQuarantineAwareApplicabilityDecision {
  const { candidate } = input, decidedAt = new Date(input.decidedAt);
  if (candidate.candidateId !== input.acceptedCandidateId || candidate.candidateRevision !== input.acceptedCandidateRevision) throw new Error("Applicability acceptance requires the exact Founder-accepted candidate identity and revision.");
  if (candidate.relationshipEligibility !== "eligible_for_founder_review" || candidate.coverageClass !== "valid_with_accepted_quarantine" || candidate.unresolvedDefinitions !== 0 || candidate.representationConflicts !== 0) throw new Error("Only an exact eligible quarantine-aware candidate can be accepted.");
  if (!Number.isFinite(decidedAt.valueOf()) || decidedAt.toISOString() !== input.decidedAt || !input.authority.authorityId.trim() || !input.authority.authorityRevision.trim() || !input.authority.provenance.length) throw new Error("Acceptance requires explicit Founder authority and canonical decision time.");
  const validationIds = input.validations.map((item) => item.validationId).sort(), validationRevisions = input.validations.map((item) => item.validationRevision).sort(), quarantineIds = input.quarantines.map((item) => item.quarantineId).sort(), quarantineRevisions = input.quarantines.map((item) => item.quarantineRevision).sort(), quarantineSafetyAssessmentRevisions = input.safetyAssessments.map((item) => item.assessmentRevision).sort();
  if (canonical(validationRevisions) !== canonical(candidate.validationRevisions) || canonical(quarantineRevisions) !== canonical(candidate.quarantineRevisions) || canonical(quarantineSafetyAssessmentRevisions) !== canonical(candidate.quarantineSafetyAssessmentRevisions)) throw new Error("Accepted decision dependencies must exactly match the reviewed candidate.");
  if (input.quarantines.some((item) => item.state !== "unavailable_quarantined" || item.permissions.editable || item.permissions.suggestedCalibrationEligible || item.permissions.reconstructionMutationEligible || item.permissions.flashingEligible)) throw new Error("Accepted applicability cannot make a quarantined Table usable.");
  const authority = freeze({ ...input.authority, provenance: [...new Set(input.authority.provenance)].sort() }), identity = { candidateId: candidate.candidateId, authorityId: authority.authorityId };
  const material = { ...identity, outcome: "accept_exact_applicability_with_quarantine" as const, candidateRevision: candidate.candidateRevision, romSoftwareIdentity: candidate.romSoftwareIdentity, sourceAuthorityId: candidate.sourceAuthorityId, sourceAuthorityRevision: candidate.sourceAuthorityRevision, definitionSetId: candidate.definitionSetId, definitionSetRevision: candidate.definitionSetRevision, validationIds, validationRevisions, quarantineIds, quarantineRevisions, quarantineSafetyAssessmentRevisions, qualifiedDefinitions: candidate.qualifiedDefinitions, quarantinedDefinitions: candidate.quarantinedDefinitions, unresolvedDefinitions: 0 as const, limitations: candidate.limitations, authority, decidedAt: input.decidedAt, publicationState: "not_published" as const, publicationSideEffects: [] as const, contractVersion: QUARANTINE_AWARE_APPLICABILITY_DECISION_CONTRACT };
  return freeze({ decisionId: `quarantine-aware-applicability-decision:${digest("tunesight.quarantine-aware-applicability-decision-identity.v1", identity)}`, decisionRevision: `quarantine-aware-applicability-decision-revision:${digest("tunesight.quarantine-aware-applicability-decision-revision.v1", material)}`, ...material, publicationSideEffects: Object.freeze([]) as readonly [] });
}

export function assessCurrentOnlyWorkshopAdmission(decision: AcceptedQuarantineAwareApplicabilityDecision) {
  return freeze({ assessmentId: `workshop-admission-assessment:${digest("tunesight.current-only-workshop-admission-assessment.v1", { decisionRevision: decision.decisionRevision })}`, decisionId: decision.decisionId, decisionRevision: decision.decisionRevision, applicability: "accepted" as const, referenceAuthority: "not_established" as const, requiredWorkshopMode: "current_only" as const, currentDatasetEligibility: "requires_separate_rom_layout_publication" as const, comparisonEligibility: "unavailable_without_reference" as const, publicationEligibility: "pending_separate_founder_decision" as const, subscriberProviderOutcome: "coverage_unavailable" as const, workshopAdmission: "not_authorized" as const, requiredGenericExtension: "A Current-only View Model must make Reference and all comparison-derived states unavailable while retaining qualified Current values and unavailable/quarantined Tables." });
}
