import assert from "node:assert/strict";
import test from "node:test";
import { FOUNDER_00003076501103_ACCEPTED_APPLICABILITY_DECISION } from "./b58PhysicalAcceptedApplicabilityDecision.ts";
import { FOUNDER_00003076501103_PUBLICATION_CANDIDATE, FOUNDER_00003076501103_ROM_LAYOUT_ID } from "./b58PhysicalPublicationCandidate.ts";
import { FOUNDER_00003076501103_COMPLETE_VALIDATIONS, FOUNDER_00003076501103_INJECTOR_SCALAR_QUARANTINE, FOUNDER_00003076501103_INJECTOR_SCALAR_SAFETY_ASSESSMENT } from "./b58PhysicalTableQuarantine.ts";
import { constructQuarantineAwarePublicationCandidate } from "./quarantineAwarePublicationCandidate.ts";
const base = { decision: FOUNDER_00003076501103_ACCEPTED_APPLICABILITY_DECISION, romLayoutId: FOUNDER_00003076501103_ROM_LAYOUT_ID, validations: FOUNDER_00003076501103_COMPLETE_VALIDATIONS, quarantines: [FOUNDER_00003076501103_INJECTOR_SCALAR_QUARANTINE], safetyAssessments: [FOUNDER_00003076501103_INJECTOR_SCALAR_SAFETY_ASSESSMENT] };
test("exact B58 relationship produces an immutable unpublished publication candidate", (context) => { const candidate = FOUNDER_00003076501103_PUBLICATION_CANDIDATE; assert.equal(candidate.eligibility, "eligible_for_founder_publication_review"); assert.equal(candidate.blockers.length, 0); assert.equal(candidate.qualifiedDefinitions, 1174); assert.equal(candidate.quarantinedDefinitions, 1); assert.equal(candidate.stockReferenceAuthority, "not_established"); assert.equal(candidate.publicationState, "candidate_only_not_published"); assert.deepEqual(candidate.publicationSideEffects, []); context.diagnostic(`B58_PUBLICATION_CANDIDATE ${JSON.stringify(candidate)}`); });
test("missing or changed authority dependencies fail closed or revise the candidate", () => { const invalid = constructQuarantineAwarePublicationCandidate({ ...base, romLayoutId: "invalid" }); assert.equal(invalid.eligibility, "publication_ineligible"); const changed = constructQuarantineAwarePublicationCandidate({ ...base, validations: [{ ...base.validations[0]!, validationRevision: "changed" }, base.validations[1]!] }); assert.equal(changed.eligibility, "publication_ineligible"); assert.notEqual(changed.candidateRevision, FOUNDER_00003076501103_PUBLICATION_CANDIDATE.candidateRevision); });
