import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { resolveBinaryContainer, type EngineeringBinary } from "../tunes/binaryContainer.ts";
import { collectInternalIdentityObservations, type InternalIdentityObservation } from "./applicabilityEvidenceProposal.ts";
import { assessDefinitionExtractionCapability, extractRawCalibrationValues } from "./calibrationValueExtraction.ts";
import type { XdfDefinitionRevision } from "./canonicalXdfDefinition.ts";
import { defineDefinitionSetRevision, identifyEngineeringBinary, type DefinitionSetRevision, type EngineeringBinaryIdentity } from "./definitionRomApplicability.ts";
import { constructEngineeringValueConversionRequest, convertQualifiedCalibrationValue } from "./engineeringValueConversion.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import { N54_CURRENT_GOVERNED_REVIEW_REFERENCES, N54_CURRENT_ROM_LAYOUT_REGISTRY } from "./n54GovernedApplicabilityAdmission.ts";
import { compareQualifiedCalibrations, constructQualifiedCalibrationComparisonRequest } from "./qualifiedCalibrationComparison.ts";
import { constructQualifiedCalibrationExtractionRequest, extractQualifiedCalibrationValue } from "./qualifiedCalibrationExtraction.ts";
import { defineRomLayoutIdentity, type RomLayoutIdentity, type RomLayoutMarker } from "./romLayoutApplicability.ts";
import {
  constructQualifiedRomLayoutDiscoveryRegistry,
  constructRomLayoutDiscoveryRequest,
  discoverAndQualifyBinaryRomLayout,
  discoverQualifiedRomLayout,
  type QualifiedRomLayoutDescriptor,
  type QualifiedRomLayoutDiscoveryRegistry,
} from "./romLayoutDiscovery.ts";

const ids = ["I8A0S", "IJE0S", "IKM0S", "INA0S"] as const;
type Identity = typeof ids[number];
type Parsed = Readonly<{ definitions: readonly XdfDefinitionRevision[]; set: DefinitionSetRevision }>;
type Exact = Readonly<{ engineering: EngineeringBinary; identity: EngineeringBinaryIdentity; observations: readonly InternalIdentityObservation[]; markers: readonly RomLayoutMarker[] }>;
const root = path.resolve("BMW-XDFs-master/N54"), parsedCache = new Map<Identity, Parsed>(), exactCache = new Map<string, Exact>(), layoutCache = new Map<Identity, RomLayoutIdentity>();

function parsed(id: Identity): Parsed { const hit=parsedCache.get(id); if(hit)return hit; const filename=`${id}.xdf`, result=interpretXdfStructure({xml:fs.readFileSync(path.join(root,filename),"utf8"),filename,provenance:`Discovery proof ${filename}`}); assert.equal(result.outcome,"structurally_interpreted"); const value=Object.freeze({definitions:result.definitions,set:defineDefinitionSetRevision({sourceArtifact:result.sourceArtifact!,definitions:result.definitions})}); parsedCache.set(id,value); return value; }
function observe(bytes: Uint8Array, vocabulary: readonly string[]=ids): readonly InternalIdentityObservation[] { return collectInternalIdentityObservations({binaryBytes:bytes,credibleIdentifiers:vocabulary.map((identifier)=>({identifier,kind:"ascii_rom_marker" as const,confidence:"known_identity" as const,reason:"Qualified discovery identity vocabulary",encodings:["ascii" as const]}))}); }
function fromBytes(id: Identity, bytes: Uint8Array, fileName: string, vocabulary: readonly string[]=ids): Exact { const resolved=resolveBinaryContainer({bytes,fileName}); assert.equal(resolved.status,"resolved"); const observations=observe(resolved.engineeringBinary!.bytes,vocabulary), identity=identifyEngineeringBinary({engineeringBinary:resolved.engineeringBinary!,romFamily:"N54",softwareIdentity:id,internalRomIdentifiers:observations.map((value)=>value.normalizedForm),identityProvenance:["Exact candidate and bounded observations"]}), markers=observations.filter((value)=>value.normalizedForm===id).map((value)=>({kind:value.kind,normalizedForm:value.normalizedForm,offsets:value.offsets,detector:value.detector})); return Object.freeze({engineering:resolved.engineeringBinary!,identity,observations,markers:Object.freeze(markers)}); }
function exact(id: Identity, role:"original"|"MapSwitchBase"): Exact { const key=`${id}_${role}`, hit=exactCache.get(key); if(hit)return hit; const value=fromBytes(id,fs.readFileSync(path.join(root,`${key}.bin`)),`${key}.bin`); exactCache.set(key,value); return value; }
function layout(id: Identity): RomLayoutIdentity { const hit=layoutCache.get(id); if(hit)return hit; const source=parsed(id), original=exact(id,"original"), addresses=source.definitions.map((value)=>value.primaryAddress).filter((value):value is number=>value!==null), region=source.definitions[0]!.addressSpace.regions[0]!, value=defineRomLayoutIdentity({romSoftwareIdentifiers:[id],calibrationSoftwareIdentifiers:[id],ecuDmeFamily:id==="I8A0S"?"MSD80":"MSD81",binaryByteLength:original.identity.byteLength,containerTypes:[original.identity.containerType],internalMarkers:original.markers,calibrationAddressSpace:[{startAddress:region.startAddress,size:region.size}],definitionCompatibleAddressRange:{minimum:Math.min(...addresses),maximum:Math.max(...addresses)},xdfSideIdentities:[id],evidenceProvenance:["Accepted current N54 governed layout evidence"]}); assert.equal(value.layoutId,N54_CURRENT_GOVERNED_REVIEW_REFERENCES.find((item)=>item.identity===id)!.review.romLayoutId); layoutCache.set(id,value); return value; }
function relationship(id: Identity) { return N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships.find((value)=>value.romLayoutId===layout(id).layoutId)!; }
function registry(): QualifiedRomLayoutDiscoveryRegistry { return constructQualifiedRomLayoutDiscoveryRegistry({authoritySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,layouts:ids.map(layout)}); }
function request(candidate: Exact, qualifiedRegistry=registry(), family:string|null=null) { return constructRomLayoutDiscoveryRequest({engineeringBinary:candidate.engineering,binaryIdentity:candidate.identity,observations:candidate.observations,qualifiedRegistry,independentlyQualifiedEcuFamily:family,provenance:["Controlled discovery domain proof"]}); }
function authorities() { return ids.map((id)=>({layout:layout(id),relationship:relationship(id),definitionSet:parsed(id).set,definitions:parsed(id).definitions})); }
function modified(id: Identity, count=1): Exact { const source=parsed(id), base=exact(id,"original"), bytes=base.engineering.bytes, used=new Set<number>(); for(const definition of source.definitions){if(used.size>=count)break;if(assessDefinitionExtractionCapability(definition).state!=="extraction_capable")continue;const extraction=extractRawCalibrationValues(base.engineering,definition),offset=extraction.offsets[0];if(extraction.outcome!=="extracted"||offset===undefined||used.has(offset)||base.markers.some((marker)=>marker.offsets.some((at)=>offset>=at&&offset<at+marker.normalizedForm.length)))continue;bytes[offset]=(bytes[offset]!+used.size+1)&0xff;used.add(offset);}assert.equal(used.size,count);return fromBytes(id,bytes,`${id}_discovery_modified.bin`); }
function descriptorClone(base: QualifiedRomLayoutDescriptor, suffix:string, changes:Partial<QualifiedRomLayoutDescriptor>): QualifiedRomLayoutDescriptor { return Object.freeze({...base,descriptorId:`${base.descriptorId}:${suffix}`,descriptorRevision:`${base.descriptorRevision}:${suffix}`,romLayoutId:`rom-layout:${suffix.padEnd(64,"0").slice(0,64)}`,...changes}); }
function registryWith(descriptors:readonly QualifiedRomLayoutDescriptor[], suffix:string): QualifiedRomLayoutDiscoveryRegistry { return Object.freeze({snapshotId:`qualified-rom-layout-discovery-registry:${suffix.padEnd(64,"0").slice(0,64)}`,contractVersion:"tunesight.qualified-rom-layout-discovery-registry.v1",authoritySnapshotId:`authority:${suffix}`,descriptors:Object.freeze([...descriptors])}); }

test("descriptor, request and result identities are deterministic, immutable and registry-order independent",()=>{const first=registry(), reversed=constructQualifiedRomLayoutDiscoveryRegistry({authoritySnapshot:{...N54_CURRENT_ROM_LAYOUT_REGISTRY,relationships:[...N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships].reverse()},layouts:[...ids].reverse().map(layout)});assert.deepEqual(first,reversed);const candidate=exact("IJE0S","original"),a=request(candidate,first),b=request(candidate,reversed),ra=discoverQualifiedRomLayout(a),rb=discoverQualifiedRomLayout(b);assert.deepEqual(a,b);assert.deepEqual(ra,rb);assert.ok(Object.isFrozen(first)&&Object.isFrozen(first.descriptors[0])&&Object.isFrozen(ra)&&Object.isFrozen(ra.candidateAssessments));assert.equal(ra.bestMatchHeuristicUsed,false);assert.equal(ra.membershipQualified,false);});

test("all four current N54 Original and MapSwitch binaries discover one exact qualified layout",()=>{const proof=[];for(const id of ids)for(const role of ["original","MapSwitchBase"] as const){const candidate=exact(id,role),result=discoverQualifiedRomLayout(request(candidate));assert.equal(result.outcome,"exact_candidate");assert.equal(result.selectedRomLayoutId,layout(id).layoutId);assert.deepEqual(result.ambiguitySet,[]);assert.equal(result.candidateAssessments.find((value)=>value.romLayoutId===layout(id).layoutId)!.evidenceState,"strong_candidate");proof.push({id,role,digest:candidate.identity.digest,result:result.resultRevision});}console.log(`N54_ROM_LAYOUT_DISCOVERY ${JSON.stringify(proof)}`);});

test("modified calibration content discovers the same layout then qualifies membership",()=>{const candidate=modified("IJE0S",32),result=discoverAndQualifyBinaryRomLayout({request:request(candidate),membershipAuthorities:authorities(),credibleRomIdentifiers:ids,sourceRole:"user_modified",sourceProvenance:["Modified discovery proof"],qualifiedAt:null});assert.equal(result.discovery.outcome,"exact_candidate");assert.equal(result.discovery.selectedRomLayoutId,layout("IJE0S").layoutId);assert.equal(result.membership?.outcome,"qualified_member");assert.notEqual(candidate.identity.digest,exact("IJE0S","original").identity.digest);assert.notStrictEqual(result.discovery,result.membership);});

test("wrong qualified ROM marker, offset conflict, container and length fail without false selection",()=>{const wrong=discoverQualifiedRomLayout(request(exact("IJE0S","original"),registry(),"MSD80"));assert.notEqual(wrong.outcome,"exact_candidate");const base=exact("IJE0S","original"), marker=base.markers[0]!, bytes=base.engineering.bytes, movedTo=parsed("IJE0S").definitions.find((value)=>value.primaryAddress!==null)!.primaryAddress!;bytes.fill(0,marker.offsets[0]!,marker.offsets[0]!+marker.normalizedForm.length);Buffer.from(marker.normalizedForm,"ascii").copy(bytes,movedTo);const moved=fromBytes("IJE0S",bytes,"offset-conflict.bin"),conflict=discoverQualifiedRomLayout(request(moved));assert.equal(conflict.outcome,"conflict");assert.equal(conflict.selectedRomLayoutId,null);assert.ok(conflict.candidateAssessments.some((value)=>value.contradictions.some((finding)=>finding.includes("multiplicity or offsets"))));const short=fromBytes("IJE0S",base.engineering.bytes.subarray(0,base.engineering.byteLength-1024),"short.bin");assert.notEqual(discoverQualifiedRomLayout(request(short)).outcome,"exact_candidate");});

test("same size, family-only Evidence and unknown identity never manufacture an exact candidate",()=>{const bytes=new Uint8Array(exact("IJE0S","original").engineering.byteLength);Buffer.from("ZZZ9_UNKNOWN","ascii").copy(bytes,4096);const unknown=fromBytes("IJE0S",bytes,"unknown.bin",["ZZZ9_UNKNOWN"]), result=discoverQualifiedRomLayout(request(unknown,registry(),"MSD81"));assert.equal(result.outcome,"unknown");assert.equal(result.selectedRomLayoutId,null);assert.ok(result.candidateAssessments.every((value)=>value.containerAndLengthUsedAsFilterOnly&&value.familyEvidenceUsedAsFilterOnly));});

test("multiple materially plausible qualified layouts remain ambiguous regardless of registry order",()=>{const baseRegistry=registry(), candidate=exact("IJE0S","original"), original=baseRegistry.descriptors.find((value)=>value.romLayoutId===layout("IJE0S").layoutId)!, overlap=descriptorClone(original,"a",{}), first=registryWith([original,overlap],"b"), second=registryWith([overlap,original],"b");const a=discoverQualifiedRomLayout(request(candidate,first)),b=discoverQualifiedRomLayout(request(candidate,second));assert.equal(a.outcome,"ambiguous");assert.deepEqual(a.ambiguitySet,b.ambiguitySet);assert.equal(a.selectedRomLayoutId,null);});

test("MG1-shaped common and candidate-specific numeric observations preserve ambiguity and incomplete authority",()=>{const base=registry().descriptors[0]!,bytes=new Uint8Array(4096);Buffer.from("1234567890AB","hex").copy(bytes,100);Buffer.from("ABCDEF123456","hex").copy(bytes,200);const resolved=resolveBinaryContainer({bytes,fileName:"mg1.bin"});assert.equal(resolved.status,"resolved");const observations=collectInternalIdentityObservations({binaryBytes:resolved.engineeringBinary!.bytes,credibleIdentifiers:[{identifier:"1234567890AB",kind:"software_identifier",confidence:"candidate_correspondence",reason:"Ubiquitous MG1 numeric marker",encodings:["hex_encoded"]},{identifier:"ABCDEF123456",kind:"calibration_identifier",confidence:"candidate_correspondence",reason:"Candidate-specific MG1 marker",encodings:["hex_encoded"]}]}),identity=identifyEngineeringBinary({engineeringBinary:resolved.engineeringBinary!,romFamily:"B58",softwareIdentity:null,internalRomIdentifiers:observations.map((value)=>value.normalizedForm),identityProvenance:["Synthetic MG1-shaped proof"]});const common={kind:"encoded_numeric_marker" as const,normalizedForm:"1234567890AB",offsets:[100],detector:"bounded_hex_encoded_exact" as const},specific={kind:"encoded_numeric_marker" as const,normalizedForm:"ABCDEF123456",offsets:[200],detector:"bounded_hex_encoded_exact" as const};const one=descriptorClone(base,"1",{binaryByteLength:4096,containerTypes:[identity.containerType.toUpperCase()],ecuDmeFamily:"MG1",romSoftwareIdentifiers:["1234567890AB","ABCDEF123456"],calibrationSoftwareIdentifiers:[],internalMarkers:[common,specific]}),two=descriptorClone(base,"2",{binaryByteLength:4096,containerTypes:[identity.containerType.toUpperCase()],ecuDmeFamily:"MG1",romSoftwareIdentifiers:["1234567890AB","ABCDEF123456"],calibrationSoftwareIdentifiers:[],internalMarkers:[common,specific]});const synthetic=Object.freeze({engineering:resolved.engineeringBinary!,identity,observations,markers:[]}),result=discoverQualifiedRomLayout(request(synthetic,registryWith([one,two],"mg1"),"MG1"));assert.equal(result.outcome,"ambiguous",JSON.stringify(result.candidateAssessments));assert.equal(result.ambiguitySet.length,2);assert.ok(observations.every((value)=>value.detector==="bounded_hex_encoded_exact"&&value.ambiguity==="multiple_credible_identities"));});

test("registry evolution can change exact discovery to ambiguity and changes result identity",()=>{const candidate=exact("IJE0S","original"),today=registry(),exactResult=discoverQualifiedRomLayout(request(candidate,today)),descriptor=today.descriptors.find((value)=>value.romLayoutId===layout("IJE0S").layoutId)!,tomorrow=registryWith([...today.descriptors,descriptorClone(descriptor,"e",{})],"evolved"),ambiguous=discoverQualifiedRomLayout(request(candidate,tomorrow));assert.equal(exactResult.outcome,"exact_candidate");assert.equal(ambiguous.outcome,"ambiguous");assert.notEqual(exactResult.resultId,ambiguous.resultId);assert.notEqual(exactResult.resultRevision,ambiguous.resultRevision);});

test("invalid exact binary binding fails closed",()=>{const candidate=exact("INA0S","original"),invalid={...candidate,identity:{...candidate.identity,digest:"0".repeat(64),identityId:`engineering-binary:${"0".repeat(64)}`}};assert.equal(discoverQualifiedRomLayout(request(invalid)).outcome,"invalid");});

test("discover to qualify to extract to convert to comparison preserves separate Evidence",()=>{const candidate=modified("IJE0S"),orchestrated=discoverAndQualifyBinaryRomLayout({request:request(candidate),membershipAuthorities:authorities(),credibleRomIdentifiers:ids,sourceRole:"modified_candidate",sourceProvenance:["Full discovery pipeline proof"],qualifiedAt:null});assert.equal(orchestrated.membership?.outcome,"qualified_member");if(orchestrated.membership?.outcome!=="qualified_member")return;const source=parsed("IJE0S"),definition=source.definitions.find((value)=>assessDefinitionExtractionCapability(value).state==="extraction_capable"&&value.axes.some((axis)=>axis.axisId.toLowerCase()==="z"&&axis.equationSource!==null))!,relation=relationship("IJE0S"),raw=extractQualifiedCalibrationValue(constructQualifiedCalibrationExtractionRequest({engineeringBinary:candidate.engineering,binaryIdentity:candidate.identity,romLayoutId:layout("IJE0S").layoutId,registrySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,expectedRelationshipId:relation.relationshipId,expectedRelationshipRevision:relation.relationshipRevision,definitionSet:source.set,definition,binaryLayoutMembership:orchestrated.membership.membership}));assert.equal(raw.status,"qualified_extracted");if(raw.status!=="qualified_extracted")return;const axis=definition.axes.find((value)=>value.axisId.toLowerCase()==="z")!,engineering=convertQualifiedCalibrationValue(constructEngineeringValueConversionRequest({rawEvidence:raw.evidence,definition,expectedEquationSource:axis.equationSource!,expectedUnits:axis.units}));assert.equal(engineering.status,"converted");const reference=exact("IJE0S","original"),comparison=compareQualifiedCalibrations(constructQualifiedCalibrationComparisonRequest({reference:{engineeringBinary:reference.engineering,binaryIdentity:reference.identity,role:"stock_candidate",provenance:["Qualified reference"]},modified:{engineeringBinary:candidate.engineering,binaryIdentity:candidate.identity,role:"modified_candidate",provenance:["Discovered modified candidate"],binaryLayoutMembership:orchestrated.membership.membership},romLayoutId:layout("IJE0S").layoutId,registrySnapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,expectedRelationshipId:relation.relationshipId,expectedRelationshipRevision:relation.relationshipRevision,definitionSet:source.set,definitions:source.definitions}));assert.equal(comparison.status,"compared");assert.equal(orchestrated.discovery.membershipQualified,false);assert.ok(!("stock" in orchestrated.discovery)&&!("vin" in orchestrated.discovery)&&!("vehicleIdentity" in orchestrated.discovery));});
