import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { resolveBinaryContainer } from "../tunes/binaryContainer.ts";
import { assessDefinitionExtractionCapability, extractRawCalibrationValues } from "./calibrationValueExtraction.ts";
import { collectInternalIdentityObservations } from "./applicabilityEvidenceProposal.ts";
import { defineDefinitionSetRevision, identifyEngineeringBinary } from "./definitionRomApplicability.ts";
import { interpretXdfStructure, type XdfStructuralInterpretation } from "./interpretXdfStructure.ts";
import { assessLayoutEquivalence, assessWrongLayoutNegativeControl, constructGovernedRomLayoutReviewPackage, defineRomLayoutIdentity, exactBinaryLayoutEvidence, type ExactBinaryLayoutEvidence, type GovernedRomLayoutReviewPackage, type RomLayoutIdentity, type RomLayoutMarker } from "./romLayoutApplicability.ts";
import type { XdfSourceArtifact } from "./canonicalXdfDefinition.ts";
import type { DefinitionSetRevision } from "./definitionRomApplicability.ts";

const root = path.resolve("BMW-XDFs-master/N54");
const ids = ["I8A0S", "IJE0S", "IKM0S", "INA0S"] as const;
type N54Id = typeof ids[number];
type Fixture = { xml: string; interpretation: XdfStructuralInterpretation; source: XdfSourceArtifact; set: DefinitionSetRevision };
const parsed = new Map<string, Fixture>();
const extractionSummaries = new Map<string, ReturnType<typeof extractionSummary>>();

function fixture(filename: string): Fixture {
  const cached = parsed.get(filename); if (cached) return cached;
  const xml = fs.readFileSync(path.join(root, filename), "utf8");
  const interpretation = interpretXdfStructure({ xml, filename, provenance: `BMW master source N54/${filename}` });
  assert.equal(interpretation.outcome, "structurally_interpreted"); assert.ok(interpretation.sourceArtifact);
  const value = { xml, interpretation, source: interpretation.sourceArtifact!, set: defineDefinitionSetRevision({ sourceArtifact: interpretation.sourceArtifact!, definitions: interpretation.definitions }) };
  parsed.set(filename, value); return value;
}
function binary(id: N54Id, role: "original" | "MapSwitchBase") {
  const filename = `${id}_${role}.bin`; const bytes = fs.readFileSync(path.join(root, filename)); const resolved = resolveBinaryContainer({ bytes, fileName: filename }); assert.equal(resolved.status, "resolved");
  const observations = collectInternalIdentityObservations({ binaryBytes: bytes, credibleIdentifiers: ids.map((identifier) => ({ identifier, kind:"ascii_rom_marker" as const, confidence:"known_identity" as const, reason:"Expected N54 software identity", encodings:["ascii" as const] })) });
  const identity = identifyEngineeringBinary({ engineeringBinary: resolved.engineeringBinary!, romFamily:"N54", softwareIdentity:id, internalRomIdentifiers:observations.map((item) => item.normalizedForm), identityProvenance:["Bounded exact internal marker collection"] });
  const markerEvidence: RomLayoutMarker[] = observations.map((item) => ({ kind:item.kind, normalizedForm:item.normalizedForm, offsets:item.offsets, detector:item.detector }));
  return { filename, bytes, engineering:resolved.engineeringBinary!, identity, markerEvidence };
}
function exact(item: ReturnType<typeof binary>, role: "stock_original" | "mapswitch"): ExactBinaryLayoutEvidence { return exactBinaryLayoutEvidence({ binaryIdentity:item.identity, sourceRole:role, internalMarkers:item.markerEvidence, evidenceProvenance:["Exact N54 repository binary and bounded internal-marker observations"] }); }
function extractionSummary(definitions: ReturnType<typeof fixture>["interpretation"]["definitions"], binaries: readonly ReturnType<typeof binary>[]) {
  let capable=0, success=0, failed=0, unsupported=0, unresolved=0;
  for (const definition of definitions) for (const item of binaries) { const capability=assessDefinitionExtractionCapability(definition); if (capability.state === "extraction_capable") { capable++; const result=extractRawCalibrationValues(item.engineering,definition); if (result.outcome === "extracted") success++; else failed++; } else if (capability.state === "unsupported") unsupported++; else unresolved++; }
  return { definitionsAssessed:definitions.length*binaries.length, extractionCapableDefinitions:capable, successfulExtractions:success, failedExtractions:failed, unsupportedDefinitions:unsupported, unresolvedDefinitions:unresolved };
}
function layoutFor(id: N54Id, current: ReturnType<typeof fixture>, original: ReturnType<typeof binary>): RomLayoutIdentity {
  const addresses=current.interpretation.definitions.map((item)=>item.primaryAddress).filter((value):value is number=>value!==null); const region=current.interpretation.definitions[0]!.addressSpace.regions[0]!;
  return defineRomLayoutIdentity({ romSoftwareIdentifiers:[id], calibrationSoftwareIdentifiers:[id], ecuDmeFamily:id === "I8A0S" ? "MSD80" : "MSD81", binaryByteLength:original.identity.byteLength, containerTypes:[original.identity.containerType], internalMarkers:original.markerEvidence, calibrationAddressSpace:[{startAddress:region.startAddress,size:region.size}], definitionCompatibleAddressRange:{minimum:Math.min(...addresses),maximum:Math.max(...addresses)}, xdfSideIdentities:[id], evidenceProvenance:["Explicit XDF deftitle", "Exact internal ROM marker and offsets", "Deterministically interpreted XDF address space"] });
}
function packageFor(id: N54Id, pathway: "external_source_authority" | "tunesight_governed_engineering_evidence" = "tunesight_governed_engineering_evidence"): GovernedRomLayoutReviewPackage {
  const current=fixture(`${id}.xdf`), original=binary(id,"original"), map=binary(id,"MapSwitchBase"), layout=layoutFor(id,current,original); const originalEvidence=exact(original,"stock_original"), mapEvidence=exact(map,"mapswitch"); const wrongId=ids[(ids.indexOf(id)+1)%ids.length]!; const negative=assessWrongLayoutNegativeControl({expectedLayout:layout,challengedBinary:binary(wrongId,"original").identity});
  let extraction=extractionSummaries.get(id); if(!extraction){ extraction=extractionSummary(current.interpretation.definitions,[original,map]); extractionSummaries.set(id,extraction); }
  return constructGovernedRomLayoutReviewPackage({ authorityPathway:pathway, sourceAuthorityDisposition:pathway === "external_source_authority" ? "authoritative" : "disclosed_non_authoritative", sourceArtifact:current.source, definitionSet:current.set, explicitXdfRomIdentities:[id], romLayoutIdentity:layout, binaryEvidence:[originalEvidence,mapEvidence], layoutEquivalenceAssessments:[assessLayoutEquivalence({layout,first:originalEvidence,second:mapEvidence})], negativeControls:[negative], structurallyReadable:true, extractionValidation:extraction, representationConflictCount:current.interpretation.definitions.filter((item)=>item.identity.status === "conflicting").length, stockVariantDisclosures:[{binaryDigest:original.identity.digest,status:"exact_candidate",sourceRole:"stock_original"},{binaryDigest:map.identity.digest,status:"family_only",sourceRole:"mapswitch"}], currentLegacyClassification:"current", provenanceDisclosure:pathway === "external_source_authority" ? ["Controlled authoritative source relationship fixture"] : ["Repository import and N54 README are disclosed but do not constitute BMW or original-author authority.","Applicability would be TuneSight-qualified through governed engineering Evidence."], limitations:["Applicability qualification does not establish stock authenticity.","Calibration Value Evidence remains bound to the exact Engineering Binary digest.","No relationship is admitted without a separate authorised reviewer decision."] });
}

test("ROM Layout Identity is deterministic, immutable and distinct from exact binary identity",()=>{ const current=fixture("IJE0S.xdf"), original=binary("IJE0S","original"); const a=layoutFor("IJE0S",current,original), b=layoutFor("IJE0S",current,original); assert.deepEqual(a,b); assert.ok(Object.isFrozen(a)&&Object.isFrozen(a.internalMarkers)); assert.notEqual(a.layoutId,original.identity.identityId); });
test("real N54 original and MapSwitch remain exact-distinct while proving the same layout",()=>{ const review=packageFor("IJE0S"); assert.notEqual(review.binaryEvidence[0]!.binaryIdentity.digest,review.binaryEvidence[1]!.binaryIdentity.digest); assert.equal(review.layoutEquivalenceAssessments[0]!.outcome,"same_layout"); assert.equal(review.binaryEvidence[0]!.sourceRole,"stock_original"); assert.equal(review.binaryEvidence[1]!.sourceRole,"mapswitch"); });
test("different-ROM and same-size wrong-ROM binaries are rejected by the negative control",()=>{ const current=fixture("IJE0S.xdf"), original=binary("IJE0S","original"), wrong=binary("INA0S","original"); assert.equal(original.identity.byteLength,wrong.identity.byteLength); assert.equal(assessWrongLayoutNegativeControl({expectedLayout:layoutFor("IJE0S",current,original),challengedBinary:wrong.identity}).outcome,"wrong_layout_rejected"); });
test("current and Legacy Definition Set revisions remain independent",()=>{ const current=fixture("IJE0S.xdf"), legacy=fixture("IJE0S_Legacy.xdf"); assert.notEqual(current.set.revisionId,legacy.set.revisionId); assert.notEqual(current.source.sourceDigest,legacy.source.sourceDigest); });
test("governed Evidence and source-authority pathways remain provenance-distinct",()=>{ const governed=packageFor("I8A0S"), source=packageFor("I8A0S","external_source_authority"); assert.equal(governed.assessment.outcome,"evidence_sufficient_for_governed_review"); assert.equal(source.assessment.outcome,"evidence_sufficient_for_governed_review"); assert.notEqual(governed.authorityPathway,source.authorityPathway); assert.notEqual(governed.packageId,source.packageId); assert.equal(governed.sourceAuthorityDisposition,"disclosed_non_authoritative"); assert.equal(source.sourceAuthorityDisposition,"authoritative"); });
test("explicit reviewer remains required and sufficient Evidence never auto-admits",()=>{ const review=packageFor("IKM0S"); assert.equal(review.assessment.reviewEligible,true); assert.equal(review.assessment.exactAcceptanceEligible,true); assert.equal(review.assessment.explicitAuthorisedReviewerRequired,true); assert.equal(review.assessment.decisionState,"pending_explicit_authorised_reviewer"); assert.ok(!("decision" in review)); });
test("incomplete and contradictory technical proof fail closed",()=>{ const valid=packageFor("INA0S"); const incomplete=constructGovernedRomLayoutReviewPackage({...valid, extractionValidation:{...valid.extractionValidation,successfulExtractions:0,failedExtractions:valid.extractionValidation.extractionCapableDefinitions}}); assert.equal(incomplete.assessment.outcome,"more_evidence_required"); const conflict=constructGovernedRomLayoutReviewPackage({...valid, explicitXdfRomIdentities:["IJE0S"]}); assert.equal(conflict.assessment.outcome,"technical_conflict"); });
test("missing exact binary Evidence is invalid rather than reviewable",()=>{ const valid=packageFor("INA0S"); const invalid=constructGovernedRomLayoutReviewPackage({...valid,binaryEvidence:[],layoutEquivalenceAssessments:[]}); assert.equal(invalid.assessment.outcome,"invalid"); assert.equal(invalid.assessment.reviewEligible,false); });
test("multi-marker layout model remains compatible with future MG1 ambiguity preservation",()=>{ const current=fixture("IJE0S.xdf"), original=binary("IJE0S","original"); const base=layoutFor("IJE0S",current,original); const mg1=defineRomLayoutIdentity({...base,romSoftwareIdentifiers:["00003076501103","00003076501104"],calibrationSoftwareIdentifiers:["00003076501103"],ecuDmeFamily:"MG1",internalMarkers:[...base.internalMarkers,{kind:"calibration_identifier",normalizedForm:"00003076501103",offsets:[64],detector:"bounded_ascii_exact"}],xdfSideIdentities:["00003076501103"]}); assert.equal(mg1.internalMarkers.length,2); assert.equal(mg1.romSoftwareIdentifiers.length,2); });
test("four current N54 ROMs produce immutable deterministic Founder-review-eligible packages",()=>{ const report=[]; for(const id of ids){ const first=packageFor(id),again=packageFor(id); assert.deepEqual(first,again); assert.ok(Object.isFrozen(first)&&Object.isFrozen(first.assessment)&&Object.isFrozen(first.binaryEvidence)); assert.equal(first.representationConflictCount,0); assert.equal(first.assessment.outcome,"evidence_sufficient_for_governed_review"); assert.equal(first.assessment.reviewEligible,true); assert.equal(first.extractionValidation.failedExtractions,0); assert.ok(first.extractionValidation.successfulExtractions>0); report.push({id,packageId:first.packageId,packageRevision:first.packageRevision,layoutId:first.romLayoutIdentity.layoutId,definitionSetRevision:first.definitionSet.revisionId,extraction:first.extractionValidation,negativeControl:first.negativeControls[0]!.outcome}); } console.log(`N54_GOVERNED_ROM_LAYOUT_REVIEW ${JSON.stringify(report)}`); });
