import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { N54_CURRENT_GOVERNED_REVIEW_REFERENCES, N54_CURRENT_QUALIFIED_ROM_LAYOUT_RELATIONSHIPS, N54_CURRENT_ROM_LAYOUT_DECISIONS, N54_CURRENT_ROM_LAYOUT_PUBLICATION_INSTRUCTIONS, N54_CURRENT_ROM_LAYOUT_PUBLICATION_RECEIPTS, N54_CURRENT_ROM_LAYOUT_REGISTRY, N54_FOUNDER_GOVERNED_EVIDENCE_AUTHORITY } from "./n54GovernedApplicabilityAdmission.ts";
import { constructRomLayoutApplicabilityDecision, lookupActiveRomLayoutApplicability, publishRomLayoutApplicability } from "./romLayoutApplicabilityPublication.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import { defineDefinitionSetRevision } from "./definitionRomApplicability.ts";

const identities=["I8A0S","IJE0S","IKM0S","INA0S"] as const;
const legacyRevisions=new Set(identities.map((identity)=>{const filename=`${identity}_Legacy.xdf`;const xml=fs.readFileSync(path.resolve("BMW-XDFs-master/N54",filename),"utf8");const parsed=interpretXdfStructure({xml,filename,provenance:"Legacy exclusion proof"});assert.equal(parsed.outcome,"structurally_interpreted");assert.ok(parsed.sourceArtifact);return defineDefinitionSetRevision({sourceArtifact:parsed.sourceArtifact!,definitions:parsed.definitions}).revisionId;}));

test("four real immutable accepted Decision Records bind exact Founder authority and governed pathway",()=>{assert.equal(N54_CURRENT_ROM_LAYOUT_DECISIONS.length,4);assert.equal(new Set(N54_CURRENT_ROM_LAYOUT_DECISIONS.map((item)=>item.decisionId)).size,4);for(const decision of N54_CURRENT_ROM_LAYOUT_DECISIONS){assert.equal(decision.outcome,"accept_rom_layout_applicability");assert.equal(decision.authority.authorityId,N54_FOUNDER_GOVERNED_EVIDENCE_AUTHORITY.authorityId);assert.equal(decision.authority.authorityClass,"founder");assert.equal(decision.authorityPathway,"tunesight_governed_engineering_evidence");assert.equal(decision.publicationState,"not_published");assert.match(decision.rationale,/combined governed engineering Evidence package/);assert.ok(decision.provenanceLimitations.some((item)=>item.includes("No BMW factory")));assert.ok(Object.isFrozen(decision)&&Object.isFrozen(decision.authority)&&Object.isFrozen(decision.provenanceLimitations));}});

test("real local publication contains exactly four current layout relationships, instructions and receipts",()=>{assert.equal(N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships.length,4);assert.equal(N54_CURRENT_ROM_LAYOUT_REGISTRY.receipts.length,4);assert.equal(N54_CURRENT_ROM_LAYOUT_PUBLICATION_INSTRUCTIONS.length,4);assert.equal(N54_CURRENT_ROM_LAYOUT_PUBLICATION_RECEIPTS.length,4);assert.deepEqual(new Set(N54_CURRENT_QUALIFIED_ROM_LAYOUT_RELATIONSHIPS.map((item)=>item.romLayoutId)),new Set(N54_CURRENT_GOVERNED_REVIEW_REFERENCES.map((item)=>item.review.romLayoutId)));for(const relationship of N54_CURRENT_QUALIFIED_ROM_LAYOUT_RELATIONSHIPS){assert.equal(relationship.lifecycleState,"active");assert.equal(relationship.publicationScope,"local_domain_only");assert.equal(relationship.qualificationProvenance,"tunesight_qualified_through_governed_engineering_evidence");assert.equal(relationship.representationConflictCount,0);assert.ok(Object.isFrozen(relationship)&&Object.isFrozen(relationship.supportingExactBinaries));}});

test("pure exact-layout lookup returns the correct current Definition Set for every N54 ROM",()=>{for(const cohort of N54_CURRENT_GOVERNED_REVIEW_REFERENCES){const lookup=lookupActiveRomLayoutApplicability(N54_CURRENT_ROM_LAYOUT_REGISTRY,cohort.review.romLayoutId);assert.equal(lookup.outcome,"exact_active");assert.equal(lookup.relationships.length,1);assert.equal(lookup.relationships[0]!.definitionSetRevisionId,cohort.review.definitionSetRevisionId);assert.equal(lookup.relationships[0]!.romLayoutId,cohort.review.romLayoutId);}});

test("wrong-ROM, family-shaped and invalid lookups fail closed without fallback",()=>{const ije=N54_CURRENT_GOVERNED_REVIEW_REFERENCES[1]!,ina=N54_CURRENT_GOVERNED_REVIEW_REFERENCES[3]!;const lookup=lookupActiveRomLayoutApplicability(N54_CURRENT_ROM_LAYOUT_REGISTRY,ije.review.romLayoutId);assert.equal(lookup.outcome,"exact_active");assert.notEqual(lookup.relationships[0]!.definitionSetRevisionId,ina.review.definitionSetRevisionId);assert.equal(lookupActiveRomLayoutApplicability(N54_CURRENT_ROM_LAYOUT_REGISTRY,"rom-layout:"+"f".repeat(64)).outcome,"none");assert.equal(lookupActiveRomLayoutApplicability(N54_CURRENT_ROM_LAYOUT_REGISTRY,"N54").outcome,"invalid");});

test("Legacy remains excluded and its 63 conflicts are unchanged",()=>{assert.ok(N54_CURRENT_QUALIFIED_ROM_LAYOUT_RELATIONSHIPS.every((item)=>!legacyRevisions.has(item.definitionSetRevisionId)));let conflicts=0;for(const identity of identities){const filename=`${identity}_Legacy.xdf`;const parsed=interpretXdfStructure({xml:fs.readFileSync(path.resolve("BMW-XDFs-master/N54",filename),"utf8"),filename,provenance:"Legacy conflict proof"});conflicts+=parsed.definitions.filter((item)=>item.identity.status==="conflicting").length;}assert.equal(conflicts,63);});

test("original and MapSwitch remain exact-instance Evidence and Stock authenticity is not promoted",()=>{for(const relationship of N54_CURRENT_QUALIFIED_ROM_LAYOUT_RELATIONSHIPS){assert.equal(relationship.supportingExactBinaries.length,2);assert.equal(new Set(relationship.supportingExactBinaries.map((item)=>item.binaryDigest)).size,2);assert.deepEqual(new Set(relationship.supportingExactBinaries.map((item)=>item.sourceRole)),new Set(["stock_original","mapswitch"]));assert.ok(!("stockVerification" in relationship));assert.ok(!("extractedValues" in relationship));}});

test("Calibration extraction provenance remains exact-binary-scoped",()=>{for(const relationship of N54_CURRENT_QUALIFIED_ROM_LAYOUT_RELATIONSHIPS){for(const binary of relationship.supportingExactBinaries)assert.match(binary.binaryDigest,/^[a-f0-9]{64}$/);assert.ok(!("binaryDigest" in relationship));assert.ok(!("calibrationValues" in relationship));}});

test("repeat publication is idempotent with no duplicate history or receipts",()=>{for(let index=0;index<4;index++){const replay=publishRomLayoutApplicability({instruction:N54_CURRENT_ROM_LAYOUT_PUBLICATION_INSTRUCTIONS[index]!,snapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,publishedAt:`2026-08-23T01:0${index}:00.000Z`});assert.equal(replay.status,"idempotent_replay");assert.deepEqual(replay.resultingSnapshot,N54_CURRENT_ROM_LAYOUT_REGISTRY);assert.equal(replay.resultingSnapshot.relationships.length,4);assert.equal(replay.resultingSnapshot.receipts.length,4);}});

test("independent atomic publication failure preserves the complete prior Snapshot",()=>{const stale={...N54_CURRENT_ROM_LAYOUT_PUBLICATION_INSTRUCTIONS[0]!,instructionId:"rom-layout-applicability-publication:"+"0".repeat(64)};const result=publishRomLayoutApplicability({instruction:stale,snapshot:N54_CURRENT_ROM_LAYOUT_REGISTRY,publishedAt:"2026-08-23T02:00:00.000Z"});assert.equal(result.status,"rejected");assert.deepEqual(result.priorSnapshot,result.resultingSnapshot);assert.equal(result.resultingSnapshot.relationships.length,4);});

test("decision construction rejects substituted source, layout, review or authority bindings",()=>{const cohort=N54_CURRENT_GOVERNED_REVIEW_REFERENCES[0]!,authority=N54_FOUNDER_GOVERNED_EVIDENCE_AUTHORITY,base={review:cohort.review,authority,acceptedEvidenceThreshold:["complete governed technical Evidence"],rationale:"Combined governed engineering Evidence is accepted.",provenanceLimitations:["No OEM authority is claimed."],decidedAt:"2026-08-23T00:00:00.000Z",decisionReference:"Founder controlled fixture"};assert.throws(()=>constructRomLayoutApplicabilityDecision({...base,review:{...cohort.review,romLayoutId:"rom-layout:invalid"}}),/ROM Layout Identity/);assert.throws(()=>constructRomLayoutApplicabilityDecision({...base,authority:{...authority,acceptedPathways:[]}}),/authority pathway/);});

test("real cohort identities and history are deterministic",()=>{console.log(`N54_REAL_ROM_LAYOUT_ADMISSION ${JSON.stringify(N54_CURRENT_GOVERNED_REVIEW_REFERENCES.map((item,index)=>({identity:item.identity,decisionId:N54_CURRENT_ROM_LAYOUT_DECISIONS[index]!.decisionId,decisionRevision:N54_CURRENT_ROM_LAYOUT_DECISIONS[index]!.decisionRevision,relationshipId:N54_CURRENT_QUALIFIED_ROM_LAYOUT_RELATIONSHIPS[index]!.relationshipId,relationshipRevision:N54_CURRENT_QUALIFIED_ROM_LAYOUT_RELATIONSHIPS[index]!.relationshipRevision,instructionId:N54_CURRENT_ROM_LAYOUT_PUBLICATION_INSTRUCTIONS[index]!.instructionId,receiptId:N54_CURRENT_ROM_LAYOUT_PUBLICATION_RECEIPTS[index]!.receiptId})))}`);assert.ok(Object.isFrozen(N54_CURRENT_ROM_LAYOUT_REGISTRY)&&Object.isFrozen(N54_CURRENT_ROM_LAYOUT_REGISTRY.relationships)&&Object.isFrozen(N54_CURRENT_ROM_LAYOUT_REGISTRY.receipts));});
