import { constructApplicabilityDecisionRecord, type ApplicabilityAuthorityAssessment, type ApplicabilityDecisionAuthority, type ApplicabilityDecisionRecord } from "./applicabilityAuthorityDecision.ts";
import type { ApplicabilityProposal } from "./applicabilityEvidenceProposal.ts";
import type { ApplicabilityDecisionCandidate } from "./applicabilityDecisionCandidate.ts";
import { S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY } from "./s58GovernedEvidenceAuthority.ts";

export const S58_FOUNDER_APPLICABILITY_DECISION_AUTHORITY: ApplicabilityDecisionAuthority = Object.freeze({ authorityId: "applicability-decision-authority:tunesight-founder-founder-s58", authorityClass: "founder", authorityRevision: "applicability-decision-authority-revision:2026-08-30-s58-ten-exact", provenance: Object.freeze(["Founder Founder explicitly accepted all ten exact S58 applicability decision candidates recorded in WP-004.3.21 under the exact governed-Evidence Source Authority revision.", "Acceptance is Definition Set to ROM-layout applicability only; no Stock, OEM, semantic Knowledge, publication or Workshop authority is implied."]), permittedOutcomes: Object.freeze(["accept_exact_applicability"] as const), acceptedPathways: Object.freeze(["governed_evidence_review"] as const) });
export const S58_FOUNDER_DECIDED_AT = "2026-08-30T01:00:00.000Z" as const;

export type S58AcceptedApplicabilityDecision = Readonly<{ romSoftwareIdentity: string; candidateId: string; candidateRevision: string; sourceAuthorityId: string; sourceAuthorityRevision: string; decision: ApplicabilityDecisionRecord; stockVariantStates: readonly Readonly<{ digest: string; role: string; state: string }>[]; limitations: readonly string[]; publicationState: "not_published"; publicationSideEffects: readonly [] }>;

export function materializeS58AcceptedApplicabilityDecision(input: Readonly<{ candidate: ApplicabilityDecisionCandidate; proposal: ApplicabilityProposal; assessment: ApplicabilityAuthorityAssessment }>): S58AcceptedApplicabilityDecision {
  const candidate = input.candidate;
  if (candidate.eligibility !== "eligible_for_founder_decision" || candidate.decisionState !== "candidate_only_pending_founder_review") throw new Error("S58 acceptance requires an eligible exact decision candidate pending Founder review.");
  if (candidate.authorityId !== S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.authorityId || candidate.authorityRevision !== S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.authorityRevision) throw new Error("S58 acceptance requires the exact Founder-authorized Source Authority revision.");
  if (candidate.primaryProposalId !== input.proposal.proposalId || candidate.primaryProposalRevision !== input.proposal.proposalRevision || candidate.assessmentId !== input.assessment.assessmentId || candidate.assessmentRevision !== input.assessment.assessmentRevision) throw new Error("S58 acceptance must bind the exact candidate Proposal and Assessment revisions.");
  const decision = constructApplicabilityDecisionRecord({ proposal: input.proposal, assessment: input.assessment, outcome: "accept_exact_applicability", authority: S58_FOUNDER_APPLICABILITY_DECISION_AUTHORITY, rationale: `Founder accepts the exact governed Definition Set Revision as applicable to S58 ROM/software layout ${candidate.romSoftwareIdentity} under decision candidate ${candidate.candidateRevision} and Source Authority revision ${candidate.authorityRevision}. Unknown upstream provenance, candidate-grade Stock, semantic Knowledge separation, and separate publication remain explicit limitations.`, acceptedEvidenceReferences: [candidate.candidateRevision, candidate.evidencePackageRevision, candidate.completeValidation.evidenceRevision, candidate.authorityRevision], unresolvedConditions: [], decidedAt: S58_FOUNDER_DECIDED_AT });
  return Object.freeze({ romSoftwareIdentity: candidate.romSoftwareIdentity, candidateId: candidate.candidateId, candidateRevision: candidate.candidateRevision, sourceAuthorityId: candidate.authorityId, sourceAuthorityRevision: candidate.authorityRevision, decision, stockVariantStates: Object.freeze(candidate.exactBinaryEvidence.map((item) => Object.freeze({ digest: item.digest, role: item.role, state: item.stockVariantState }))), limitations: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.limitations, publicationState: "not_published", publicationSideEffects: Object.freeze([]) as readonly [] });
}
