import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import type { RuntimeStockVariantKnowledgeResponse } from "../knowledge/runtimeStockVariantKnowledge.ts";
import { resolveBinaryContainer } from "../tunes/binaryContainer.ts";
import { assessApplicabilityAuthority } from "./applicabilityAuthorityDecision.ts";
import { constructCalibrationApplicabilityEvidencePackage, type ApplicabilityCandidateBinary, type CredibleIdentityCandidate } from "./calibrationApplicabilityEvidenceFactory.ts";
import { constructApplicabilityDecisionCandidate, type CompleteRelationshipValidation } from "./applicabilityDecisionCandidate.ts";
import { defineDefinitionSetRevision } from "./definitionRomApplicability.ts";
import { interpretXdfStructure } from "./interpretXdfStructure.ts";
import { S58_GOVERNED_EVIDENCE_SCOPE, S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY } from "./s58GovernedEvidenceAuthority.ts";
import { materializeS58AcceptedApplicabilityDecision } from "./s58AcceptedApplicabilityDecisions.ts";
import { assessSourceAuthorityScope, constructSourceAuthorityRecord } from "./sourceAuthorityScope.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "BMW-XDFs-master");
const stockCandidate: RuntimeStockVariantKnowledgeResponse = Object.freeze({ availability: "available", unavailableReason: null, result: Object.freeze({ status: "exact_candidate", explanation: "Repository role remains candidate Evidence." }) as never });
const conversions: Readonly<Record<string, readonly [number, number]>> = Object.freeze({ "00005C640A6405": [893, 313], "00005C640A8205": [893, 313], "00005C640A8C05": [893, 313], "00005C64143206": [939, 338], "00005C64143C05": [941, 336], "00005C64144606": [939, 338], "00005C64145007": [940, 336], "00005C64145A05": [942, 335], "00005C64146E06": [942, 335], "00005C64148205": [942, 335] });
const credible = (id: string): readonly CredibleIdentityCandidate[] => Object.freeze([{ identifier: id, kind: "calibration_identifier", confidence: "candidate_correspondence", reason: "Candidate-specific repository identity", encodings: ["ascii", "hex_encoded"], classification: "candidate_specific" }]);

function candidate(id: string, role: "stock_original" | "mapswitch"): ApplicabilityCandidateBinary { const suffix = role === "stock_original" ? "original" : "MapSwitchBase"; const relative = `s58/${id}/${id}_${suffix}.bin`; const resolved = resolveBinaryContainer({ bytes: fs.readFileSync(path.join(root, relative)), fileName: `${id}_${suffix}.bin` }); assert.equal(resolved.status, "resolved"); return { engineeringBinary: resolved.engineeringBinary!, role, provenance: [`Exact repository import ${relative}; upstream acquisition unknown.`], stockVariantKnowledge: stockCandidate, credibleIdentities: credible(id) }; }
function relationship(index: number) { const scope = S58_GOVERNED_EVIDENCE_SCOPE[index]!; const id = scope.romSoftwareIdentity; const relative = `s58/${id}/${id}.xdf`; const parsed = interpretXdfStructure({ xml: fs.readFileSync(path.join(root, relative), "utf8"), filename: `${id}.xdf`, provenance: `Exact governed S58 source ${relative}` }); assert.equal(parsed.outcome, "structurally_interpreted"); const sourceArtifact = parsed.sourceArtifact!; const definitionSet = defineDefinitionSetRevision({ sourceArtifact, definitions: parsed.definitions }); assert.equal(sourceArtifact.artifactId, scope.sourceArtifactId); assert.equal(definitionSet.revisionId, scope.definitionSetRevision); const evidencePackage = constructCalibrationApplicabilityEvidencePackage({ sourceArtifact, definitionSet, definitions: parsed.definitions, sourcePath: relative, sourceFamily: "s58", sourceStatus: "current", claimedIdentities: [id], binaryCandidates: [candidate(id, "stock_original"), candidate(id, "mapswitch")], sourceProvenance: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.provenance, sourceAuthority: "established", authorityProvenance: [S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.authorityRevision], limitations: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.limitations }); const original = evidencePackage.binaries.find((item) => item.role === "stock_original")!; const assessment = assessApplicabilityAuthority({ proposal: original.proposal, acceptedAuthorityPathways: ["governed_evidence_review"], xdfIdentityAvailable: true, sourceRelationshipKnown: true }); const [converted, identity] = conversions[id]!; const validation: CompleteRelationshipValidation = Object.freeze({ evidenceRevision: `s58-complete-validation:${scope.definitionSetRevision}`, definitions: parsed.definitions.length, originalExtractionSuccessful: parsed.definitions.length, mapSwitchExtractionSuccessful: parsed.definitions.length, originalConverted: converted, originalIdentityNoOp: identity, mapSwitchConverted: converted, mapSwitchIdentityNoOp: identity, unavailable: 0, invalid: 0, unsupported: 0, malformed: 0, representationConflicts: 0 }); return { scope, evidencePackage, assessment, validation, candidate: constructApplicabilityDecisionCandidate({ romSoftwareIdentity: id, scopeBinding: scope, authority: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY, evidencePackage, primaryAssessment: assessment, completeValidation: validation, contraryOrSupersedingDecision: false }) }; }

test("Founder governed-Evidence authority binds exactly ten immutable sources and preserves every limitation", () => { const authority = S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY; assert.equal(authority.scope.length, 10); assert.equal(authority.founderAuthorityId, "tunesight-founder:founder"); assert.equal(authority.authorityClass, "governed_evidence_review"); assert.equal(authority.authorizedAt, "2026-08-30T00:00:00.000Z"); assert.equal(new Set(authority.scope.map((item) => item.sourceArtifactDigest)).size, 10); assert.equal(new Set(authority.scope.map((item) => item.definitionSetRevision)).size, 10); assert.ok(authority.limitations.some((item) => item.includes("unknown"))); assert.ok(authority.limitations.some((item) => item.includes("not BMW"))); assert.ok(authority.limitations.some((item) => item.includes("Stock"))); assert.ok(authority.limitations.some((item) => item.includes("Semantic"))); assert.ok(authority.limitations.some((item) => item.includes("decision"))); assert.ok(authority.limitations.some((item) => item.includes("Publication"))); assert.ok(Object.isFrozen(authority) && Object.isFrozen(authority.scope)); });

test("wrong digest, revision, unlisted S58, B58 and wrong-family scope fail closed", () => { const authority = S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY; const exact = authority.scope[0]!; assert.equal(assessSourceAuthorityScope(authority, exact).outcome, "in_scope"); assert.equal(assessSourceAuthorityScope(authority, { ...exact, sourceArtifactDigest: `sha256:${"a".repeat(64)}` }).outcome, "out_of_scope"); assert.equal(assessSourceAuthorityScope(authority, { ...exact, definitionSetRevision: `${exact.definitionSetRevision}:revised` }).outcome, "out_of_scope"); assert.equal(assessSourceAuthorityScope(authority, { ...exact, sourceArtifactId: "xdf-source:unlisted-s58", sourceArtifactDigest: `sha256:${"b".repeat(64)}` }).outcome, "out_of_scope"); for (const family of ["B58gen1", "B58gen2", "N55", "S55", "S63", "future-bmw"]) assert.equal(assessSourceAuthorityScope(authority, { ...exact, family }).outcome, "out_of_scope", family); });

test("ten exact proposals assess independently and produce ten immutable Founder decision candidates", (context) => { const records = S58_GOVERNED_EVIDENCE_SCOPE.map((_, index) => relationship(index)); assert.equal(records.length, 10); assert.ok(records.every((item) => item.assessment.outcome === "reviewable_for_exact_applicability" && item.assessment.exactAcceptanceEligible)); assert.ok(records.every((item) => item.candidate.eligibility === "eligible_for_founder_decision")); assert.equal(new Set(records.map((item) => item.candidate.candidateId)).size, 10); assert.equal(new Set(records.map((item) => item.candidate.relationshipId)).size, 10); assert.ok(records.every((item) => item.candidate.hardGates.every((gate) => gate.passed))); assert.ok(records.every((item) => item.candidate.exactBinaryEvidence.length === 2 && item.candidate.exactBinaryEvidence.every((binary) => binary.stockVariantState === "exact_candidate"))); assert.ok(records.every((item) => item.candidate.limitations.join(" ") === S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.limitations.join(" "))); assert.ok(records.every((item) => item.candidate.decisionState === "candidate_only_pending_founder_review" && item.candidate.publicationState === "not_authorized" && item.candidate.publicationSideEffects.length === 0)); assert.ok(records.every((item) => Object.isFrozen(item.candidate))); context.diagnostic(`S58_DECISION_CANDIDATES ${JSON.stringify(records.map((item) => ({ rom: item.scope.romSoftwareIdentity, packageRevision: item.evidencePackage.packageRevision, proposalRevision: item.candidate.primaryProposalRevision, assessmentRevision: item.candidate.assessmentRevision, candidateId: item.candidate.candidateId, candidateRevision: item.candidate.candidateRevision, eligibility: item.candidate.eligibility })))}`); });

test("complete extraction, conversion, scope and assessment gates cannot be bypassed", () => { const value = relationship(0); const incompleteExtraction = constructApplicabilityDecisionCandidate({ romSoftwareIdentity: value.scope.romSoftwareIdentity, scopeBinding: value.scope, authority: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY, evidencePackage: value.evidencePackage, primaryAssessment: value.assessment, completeValidation: { ...value.validation, originalExtractionSuccessful: value.validation.definitions - 1 }, contraryOrSupersedingDecision: false }); assert.equal(incompleteExtraction.eligibility, "ineligible"); const incompleteConversion = constructApplicabilityDecisionCandidate({ romSoftwareIdentity: value.scope.romSoftwareIdentity, scopeBinding: value.scope, authority: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY, evidencePackage: value.evidencePackage, primaryAssessment: value.assessment, completeValidation: { ...value.validation, invalid: 1 }, contraryOrSupersedingDecision: false }); assert.equal(incompleteConversion.eligibility, "ineligible"); const otherScope = S58_GOVERNED_EVIDENCE_SCOPE[1]!; const wrongRelationship = constructApplicabilityDecisionCandidate({ romSoftwareIdentity: value.scope.romSoftwareIdentity, scopeBinding: otherScope, authority: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY, evidencePackage: value.evidencePackage, primaryAssessment: value.assessment, completeValidation: value.validation, contraryOrSupersedingDecision: false }); assert.equal(wrongRelationship.eligibility, "ineligible"); });

test("authority revision requires reassessment and one candidate never authorizes another", () => { const first = relationship(0); const second = relationship(1); assert.notEqual(first.candidate.relationshipId, second.candidate.relationshipId); assert.notEqual(first.candidate.candidateId, second.candidate.candidateId); const authorityRevision = constructSourceAuthorityRecord({ authorityClass: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.authorityClass, founderAuthorityId: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.founderAuthorityId, authorizedAt: "2026-08-30T01:00:00.000Z", lineage: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.lineage, scope: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.scope, evidenceBasis: [...S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.evidenceBasis, "Controlled later correction"], provenance: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.provenance, limitations: S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.limitations }); assert.equal(authorityRevision.authorityId, S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.authorityId); assert.notEqual(authorityRevision.authorityRevision, S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.authorityRevision); const reassessed = constructApplicabilityDecisionCandidate({ romSoftwareIdentity: first.scope.romSoftwareIdentity, scopeBinding: first.scope, authority: authorityRevision, evidencePackage: first.evidencePackage, primaryAssessment: first.assessment, completeValidation: first.validation, contraryOrSupersedingDecision: false }); assert.equal(reassessed.candidateId, first.candidate.candidateId); assert.notEqual(reassessed.candidateRevision, first.candidate.candidateRevision); assert.deepEqual(reassessed.publicationSideEffects, []); });

test("Founder acceptance materializes ten independent exact S58 decisions without publication", (context) => { const accepted = S58_GOVERNED_EVIDENCE_SCOPE.map((_, index) => { const item = relationship(index); const proposal = item.evidencePackage.binaries.find((binary) => binary.role === "stock_original")!.proposal; return materializeS58AcceptedApplicabilityDecision({ candidate: item.candidate, proposal, assessment: item.assessment }); }); assert.equal(accepted.length, 10); assert.equal(new Set(accepted.map((item) => item.decision.decisionId)).size, 10); assert.equal(new Set(accepted.map((item) => item.decision.decisionRevision)).size, 10); assert.ok(accepted.every((item) => item.decision.outcome === "accept_exact_applicability")); assert.ok(accepted.every((item) => item.sourceAuthorityRevision === S58_GOVERNED_EVIDENCE_SOURCE_AUTHORITY.authorityRevision)); assert.ok(accepted.every((item) => item.stockVariantStates.length === 2 && item.stockVariantStates.every((stock) => stock.state === "exact_candidate"))); assert.ok(accepted.every((item) => item.publicationState === "not_published" && item.publicationSideEffects.length === 0)); assert.ok(accepted.every((item) => Object.isFrozen(item) && Object.isFrozen(item.decision))); context.diagnostic(`S58_ACCEPTED_DECISIONS ${JSON.stringify(accepted.map((item) => ({ rom: item.romSoftwareIdentity, candidateRevision: item.candidateRevision, decisionId: item.decision.decisionId, decisionRevision: item.decision.decisionRevision, publicationState: item.publicationState })))}`); });

test("S58 Founder acceptance fails closed on mismatched proposal and assessment revisions", () => { const first = relationship(0); const second = relationship(1); const firstProposal = first.evidencePackage.binaries.find((binary) => binary.role === "stock_original")!.proposal; const secondProposal = second.evidencePackage.binaries.find((binary) => binary.role === "stock_original")!.proposal; assert.throws(() => materializeS58AcceptedApplicabilityDecision({ candidate: first.candidate, proposal: secondProposal, assessment: first.assessment })); assert.throws(() => materializeS58AcceptedApplicabilityDecision({ candidate: first.candidate, proposal: firstProposal, assessment: second.assessment })); });
