import assert from "node:assert/strict";
import test from "node:test";
import { constructGovernedEvidenceAuthorityCandidate, type CompleteBinaryValidation } from "./bmwMasterFullValidation.ts";
import { constructFounderReviewCohort, constructSourceAuthorityFounderReviewRow } from "./sourceAuthorityFounderReview.ts";

function validation(seed: string): CompleteBinaryValidation { return Object.freeze({ validationId: `validation:${seed}`, validationRevision: `validation-revision:${seed}`, binaryDigest: seed.padEnd(64, "0"), definitions: 10, extractionAttempts: 10, extractionSuccess: 10, blocked: 0, outOfBounds: 0, unsupported: 0, representationConflicts: 0, converted: 8, identityNoOp: 2, invalidNumeric: 0, malformed: 0, unavailable: 0, unresolvedUnits: 0, other: 0 }); }
function row(family: string, rom: string, binaries = 2) { const validations = Array.from({ length: binaries }, (_, index) => validation(`${rom}-${index}`)), scope = { sourceArtifactId: `source:${rom}`, sourceArtifactDigest: `sha256:${rom.padEnd(64, "0").slice(0, 64)}`, definitionSetId: `set:${rom}`, definitionSetRevision: `set-revision:${rom}`, family }, candidate = constructGovernedEvidenceAuthorityCandidate({ scope, romSoftwareIdentity: rom, validations, identityCoherent: true, limitations: ["Upstream provenance unknown."] }); return constructSourceAuthorityFounderReviewRow({ candidate, sourceArtifactRevision: `source-revision:${rom}`, definitionCount: 10, validations, identityEvidenceSummary: [`Exact marker ${rom} observed deterministically.`], stockReferenceState: "stock_candidate" }); }

test("54-candidate Founder review is deterministic, contextual and authority-free", () => { const rows = [...Array.from({ length: 42 }, (_, index) => row("B58gen2", `B58-${index.toString().padStart(2, "0")}`, index % 3 === 0 ? 4 : 2)), row("N55E", "9E60B"), ...Array.from({ length: 11 }, (_, index) => row("S63", `S63-${index.toString().padStart(2, "0")}`, 1))], first = constructFounderReviewCohort(rows), replay = constructFounderReviewCohort([...rows].reverse()); assert.equal(first.rows.length, 54); assert.deepEqual(first.familyCounts, { B58gen2: 42, N55E: 1, S63: 11 }); assert.equal(first.cohortRevision, replay.cohortRevision); assert.ok(first.rows.every((item) => item.completeExtraction.successful === item.completeExtraction.attempts && item.completeConversion.invalidNumeric === 0 && item.representationConflicts === 0 && item.qualificationReason.length > 40)); assert.ok(first.outliers.length > 0); assert.equal(first.authorityGranted, false); assert.deepEqual(first.publicationSideEffects, []); });
test("incomplete or conflicted validation cannot enter Founder authority review", () => { const valid = validation("blocked"), scope = { sourceArtifactId: "source", sourceArtifactDigest: `sha256:${"a".repeat(64)}`, definitionSetId: "set", definitionSetRevision: "set-revision", family: "future" }, candidate = constructGovernedEvidenceAuthorityCandidate({ scope, romSoftwareIdentity: "FUTURE", validations: [valid], identityCoherent: true, limitations: [] }); assert.throws(() => constructSourceAuthorityFounderReviewRow({ candidate, sourceArtifactRevision: "source-revision", definitionCount: 10, validations: [{ ...valid, blocked: 1, extractionSuccess: 9 }], identityEvidenceSummary: ["Exact marker"], stockReferenceState: "not_assessed" })); });
