import { createHash } from "node:crypto";
import type { CompleteBinaryValidation, GovernedEvidenceAuthorityCandidate } from "./bmwMasterFullValidation.ts";

export const SOURCE_AUTHORITY_FOUNDER_REVIEW_CONTRACT = "tunesight.source-authority-founder-review.v1" as const;
export type SourceAuthorityFounderReviewRow = Readonly<{ reviewId: string; reviewRevision: string; contractVersion: typeof SOURCE_AUTHORITY_FOUNDER_REVIEW_CONTRACT; family: string; romSoftwareIdentity: string; sourceArtifactId: string; sourceArtifactRevision: string; definitionSetRevision: string; definitionCount: number; responsibleBinaryCount: number; completeExtraction: Readonly<{ attempts: number; successful: number; blocked: number; outOfBounds: number; unsupported: number }>; completeConversion: Readonly<{ converted: number; identityNoOp: number; invalidNumeric: number; malformed: number; unavailable: number; unresolvedUnits: number }>; identityEvidenceSummary: readonly string[]; representationConflicts: number; stockReferenceState: "stock_candidate" | "reference_candidate" | "not_assessed"; provenanceLimitations: readonly string[]; sourceAuthorityCandidateId: string; sourceAuthorityCandidateRevision: string; exactScope: GovernedEvidenceAuthorityCandidate["scope"]; qualificationReason: string; authorityState: "pending_founder_authority"; publicationState: "not_published" }>;
export type FounderReviewCohort = Readonly<{ cohortId: string; cohortRevision: string; rows: readonly SourceAuthorityFounderReviewRow[]; familyCounts: Readonly<Record<string, number>>; outliers: readonly Readonly<{ reviewId: string; romSoftwareIdentity: string; reasons: readonly string[] }>[]; consistency: "internally_consistent_with_disclosed_outliers" | "conflicted"; authorityGranted: false; publicationSideEffects: readonly [] }>;

function canonical(value: unknown): string { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isFinite(value)) throw new Error("Founder review contains a non-finite number."); return JSON.stringify(value); } if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (!value || typeof value !== "object") throw new Error("Founder review contains unsupported material."); const object = value as Readonly<Record<string, unknown>>; return `{${Object.keys(object).sort().map((key) => `${JSON.stringify(key)}:${canonical(object[key])}`).join(",")}}`; }
function digest(domain: string, value: unknown): string { return createHash("sha256").update(domain).update(Buffer.from([0])).update(canonical(value)).digest("hex"); }
function freeze<T>(value: T): T { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as T; if (value && typeof value === "object") return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, freeze(item)]))) as T; return value; }
function sum(validations: readonly CompleteBinaryValidation[], key: keyof CompleteBinaryValidation): number { return validations.reduce((total, item) => total + (typeof item[key] === "number" ? item[key] as number : 0), 0); }

export function constructSourceAuthorityFounderReviewRow(input: Readonly<{ candidate: GovernedEvidenceAuthorityCandidate; sourceArtifactRevision: string; definitionCount: number; validations: readonly CompleteBinaryValidation[]; identityEvidenceSummary: readonly string[]; stockReferenceState: SourceAuthorityFounderReviewRow["stockReferenceState"] }>): SourceAuthorityFounderReviewRow {
  if (input.candidate.state !== "pending_founder_authority" || !input.validations.length || input.definitionCount <= 0 || !input.identityEvidenceSummary.length) throw new Error("Founder review requires one complete pending exact-scope candidate and meaningful identity Evidence.");
  if (input.validations.some((item) => item.definitions !== input.definitionCount || item.blocked || item.representationConflicts || item.invalidNumeric || item.malformed || item.unavailable)) throw new Error("Founder authority review row requires technically clean complete validations.");
  const extraction = { attempts: sum(input.validations, "extractionAttempts"), successful: sum(input.validations, "extractionSuccess"), blocked: sum(input.validations, "blocked"), outOfBounds: sum(input.validations, "outOfBounds"), unsupported: sum(input.validations, "unsupported") }; const conversion = { converted: sum(input.validations, "converted"), identityNoOp: sum(input.validations, "identityNoOp"), invalidNumeric: sum(input.validations, "invalidNumeric"), malformed: sum(input.validations, "malformed"), unavailable: sum(input.validations, "unavailable"), unresolvedUnits: sum(input.validations, "unresolvedUnits") }; const identity = { sourceAuthorityCandidateId: input.candidate.candidateId, family: input.candidate.scope.family, romSoftwareIdentity: input.candidate.romSoftwareIdentity }; const material = { ...identity, sourceArtifactId: input.candidate.scope.sourceArtifactId, sourceAuthorityCandidateRevision: input.candidate.candidateRevision, sourceArtifactRevision: input.sourceArtifactRevision, definitionSetRevision: input.candidate.scope.definitionSetRevision, definitionCount: input.definitionCount, responsibleBinaryCount: input.validations.length, completeExtraction: extraction, completeConversion: conversion, identityEvidenceSummary: [...input.identityEvidenceSummary], representationConflicts: 0, stockReferenceState: input.stockReferenceState, provenanceLimitations: input.candidate.limitations, exactScope: input.candidate.scope, qualificationReason: "Exact source and Definition Set scope, coherent ROM identity Evidence, and complete conflict-free extraction and conversion passed for every responsible binary; Source Authority remains a Founder decision.", authorityState: "pending_founder_authority" as const, publicationState: "not_published" as const, contractVersion: SOURCE_AUTHORITY_FOUNDER_REVIEW_CONTRACT };
  return freeze({ reviewId: `source-authority-founder-review:${digest("tunesight.source-authority-founder-review-identity.v1", identity)}`, reviewRevision: `source-authority-founder-review-revision:${digest("tunesight.source-authority-founder-review-revision.v1", material)}`, ...material });
}

export function constructFounderReviewCohort(rows: readonly SourceAuthorityFounderReviewRow[]): FounderReviewCohort {
  if (!rows.length || new Set(rows.map((item) => item.reviewId)).size !== rows.length || rows.some((item) => item.authorityState !== "pending_founder_authority" || item.publicationState !== "not_published")) throw new Error("Founder review cohort requires unique pending unpublished review rows."); const ordered = [...rows].sort((a, b) => a.family.localeCompare(b.family) || a.romSoftwareIdentity.localeCompare(b.romSoftwareIdentity)); const familyCounts = Object.fromEntries([...new Set(ordered.map((item) => item.family))].sort().map((family) => [family, ordered.filter((item) => item.family === family).length])); const outliers = ordered.flatMap((row) => { const family = ordered.filter((item) => item.family === row.family), reasons: string[] = []; if (row.responsibleBinaryCount !== Math.max(...family.map((item) => item.responsibleBinaryCount))) reasons.push(`Responsible binary count ${row.responsibleBinaryCount} differs from the family maximum.`); if (row.stockReferenceState !== family[0]!.stockReferenceState) reasons.push(`Stock/Reference state ${row.stockReferenceState} differs within the family.`); return reasons.length ? [{ reviewId: row.reviewId, romSoftwareIdentity: row.romSoftwareIdentity, reasons }] : []; }); const identity = { reviewIds: ordered.map((item) => item.reviewId) }; const material = { ...identity, reviewRevisions: ordered.map((item) => item.reviewRevision), familyCounts, outliers, authorityGranted: false, publicationSideEffects: [] };
  return freeze({ cohortId: `source-authority-founder-review-cohort:${digest("tunesight.source-authority-founder-review-cohort-identity.v1", identity)}`, cohortRevision: `source-authority-founder-review-cohort-revision:${digest("tunesight.source-authority-founder-review-cohort-revision.v1", material)}`, rows: ordered, familyCounts, outliers, consistency: "internally_consistent_with_disclosed_outliers", authorityGranted: false, publicationSideEffects: Object.freeze([]) as readonly [] });
}
