import { createHash } from "node:crypto";
import type { EngineeringBinary } from "../tunes/binaryContainer.ts";
import { extractRawCalibrationValues } from "./calibrationValueExtraction.ts";
import type { XdfDefinitionRevision } from "./canonicalXdfDefinition.ts";
import { evaluateParsedXdfEquation, parseXdfEquation } from "./engineeringValueConversion.ts";
import type { CompleteBinaryValidation, GovernedEvidenceAuthorityCandidate } from "./bmwMasterFullValidation.ts";
import type { SourceAuthorityScopeBinding } from "./sourceAuthorityScope.ts";

export const TABLE_QUARANTINE_CONTRACT = "tunesight.calibration-table-quarantine.v1" as const;
export type TableQuarantineFailureClass = "invalid_engineering_conversion" | "unresolved_representation_conflict" | "unsupported_representation" | "dependency_unresolved" | "other_governed_non_usable";
export type TableQuarantineSafetyAssessment = Readonly<{ assessmentId: string; assessmentRevision: string; definitionRevisionId: string; occurrence: number; binaryDigest: string; gates: readonly Readonly<{ gate: "exact_occurrence" | "failure_preserved" | "axis_independence" | "conversion_independence" | "storage_non_overlap" | "representation_unambiguous" | "dataset_coherence"; passed: boolean; finding: string }>[]; outcome: "dependency_safe_for_quarantine" | "whole_relationship_blocked"; targetOffsets: readonly number[]; overlappingDefinitionRevisions: readonly string[] }>;
export type TableQuarantineRecord = Readonly<{ quarantineId: string; quarantineRevision: string; contractVersion: typeof TABLE_QUARANTINE_CONTRACT; relationship: Readonly<{ romSoftwareIdentity: string; sourceArtifactId: string; definitionSetRevision: string }>; occurrence: Readonly<{ definitionIdentity: string; definitionRevisionId: string; sourceBindingDigest: string; occurrence: number }>; affectedBinary: Readonly<{ digest: string; role: string; validationRevision: string }>; failureClass: TableQuarantineFailureClass; failureEvidence: Readonly<{ rawOffsets: readonly number[]; rawBytes: readonly number[]; rawValues: readonly number[]; equation: string | null; outcome: string; finding: string }>; safetyAssessmentRevision: string; provenance: readonly string[]; limitations: readonly string[]; authority: Readonly<{ reviewerId: string; authorityRevision: string }>; quarantinedAt: string; state: "unavailable_quarantined"; permissions: Readonly<{ engineeringValueValid: false; editable: false; suggestedCalibrationEligible: false; reconstructionMutationEligible: false; flashingEligible: false }> }>;

const canonical = (value: unknown): string => { if (value === null || typeof value === "boolean" || typeof value === "string") return JSON.stringify(value); if (typeof value === "number") { if (!Number.isFinite(value) || !Number.isSafeInteger(value)) throw new Error("Quarantine material contains an unsafe number."); return JSON.stringify(value); } if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; if (!value || typeof value !== "object") throw new Error("Quarantine material is unsupported."); const record = value as Readonly<Record<string, unknown>>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`; };
const hash = (domain: string, value: unknown) => createHash("sha256").update(domain).update(Buffer.from([0])).update(canonical(value)).digest("hex");
const freeze = <T>(value: T): T => { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as T; if (value && typeof value === "object") return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, freeze(item)]))) as T; return value; };
const byteOffsets = (offsets: readonly number[], widthBits: number | null) => offsets.flatMap((offset) => Array.from({ length: Math.max(1, (widthBits ?? 8) / 8) }, (_, index) => offset + index));

export function auditTableQuarantineSafety(input: Readonly<{ definitions: readonly XdfDefinitionRevision[]; engineeringBinary: EngineeringBinary; definitionRevisionId: string; occurrence: number; expectedFailureClass: TableQuarantineFailureClass }>): TableQuarantineSafetyAssessment {
  const matches = input.definitions.filter((item) => item.revisionId === input.definitionRevisionId), target = matches[input.occurrence];
  const targetExtraction = target ? extractRawCalibrationValues(input.engineeringBinary, target) : null;
  const targetAxis = target?.axes.find((axis) => axis.axisId.toLowerCase() === "z") ?? target?.axes.at(-1);
  const equation = targetAxis?.equationSource ? parseXdfEquation(targetAxis.equationSource) : null;
  const evaluated = equation && equation.outcome !== "unsupported_expression" && equation.outcome !== "malformed_equation" && targetExtraction?.outcome === "extracted" && targetExtraction.shape?.values[0] !== undefined ? evaluateParsedXdfEquation(equation, targetExtraction.shape.values[0]) : null;
  const targetBytes = targetExtraction?.outcome === "extracted" ? new Set([...byteOffsets(targetExtraction.offsets, targetExtraction.widthBits), ...targetExtraction.axes.flatMap((axis, index) => byteOffsets(axis.offsets, target.axes[index]?.embeddedData.elementSizeBits ?? target.defaultDataLayout.elementSizeBits))]) : new Set<number>();
  const overlaps = input.definitions.flatMap((definition) => { if (definition === target) return []; const extracted = extractRawCalibrationValues(input.engineeringBinary, definition); if (extracted.outcome !== "extracted") return []; const offsets = [...byteOffsets(extracted.offsets, extracted.widthBits), ...extracted.axes.flatMap((axis, index) => byteOffsets(axis.offsets, definition.axes[index]?.embeddedData.elementSizeBits ?? definition.defaultDataLayout.elementSizeBits))]; return offsets.some((offset) => targetBytes.has(offset)) ? [definition.revisionId] : []; });
  const axisSafe = Boolean(target) && target.axes.every((axis) => axis.representation !== "external_reference" && axis.representation !== "calculated");
  const conversionSafe = Boolean(target) && target.axes.every((axis) => axis.equationVariables.every((variable) => variable.toUpperCase() === "X"));
  const failurePreserved = input.expectedFailureClass === "invalid_engineering_conversion" ? evaluated?.outcome === "invalid_numeric_result" : input.expectedFailureClass === "unresolved_representation_conflict" ? target?.identity.status === "conflicting" : true;
  const gates = freeze([
    { gate: "exact_occurrence" as const, passed: Boolean(target) && matches.length > input.occurrence, finding: target ? `Exact Definition revision occurrence ${input.occurrence} resolved.` : "Exact Definition occurrence is absent." },
    { gate: "failure_preserved" as const, passed: failurePreserved, finding: failurePreserved ? `Observed ${input.expectedFailureClass} remains unchanged.` : "Expected failure Evidence was not reproduced." },
    { gate: "axis_independence" as const, passed: axisSafe, finding: axisSafe ? "No calculated or external-reference axis dependency is declared." : "An axis dependency is unresolved." },
    { gate: "conversion_independence" as const, passed: conversionSafe, finding: conversionSafe ? "Equations reference only their local raw X value." : "A cross-value conversion dependency is unresolved." },
    { gate: "storage_non_overlap" as const, passed: overlaps.length === 0, finding: overlaps.length ? `Storage overlaps ${[...new Set(overlaps)].sort().join(", ")}.` : "No target value or axis byte overlaps another Definition occurrence." },
    { gate: "representation_unambiguous" as const, passed: target?.identity.status === "derived", finding: target?.identity.status === "derived" ? "The quarantined occurrence has one derived representation." : "The quarantined occurrence representation is unresolved or conflicting." },
    { gate: "dataset_coherence" as const, passed: Boolean(targetExtraction?.outcome === "extracted") && overlaps.length === 0 && axisSafe && conversionSafe, finding: "All other Definitions remain independently extracted and converted; the occurrence can remain as unavailable Evidence." },
  ]);
  const identity = { definitionRevisionId: input.definitionRevisionId, occurrence: input.occurrence, binaryDigest: createHash("sha256").update(input.engineeringBinary.bytes).digest("hex") };
  const material = { ...identity, gates, targetOffsets: [...targetBytes].sort((a, b) => a - b), overlappingDefinitionRevisions: [...new Set(overlaps)].sort() };
  return freeze({ assessmentId: `table-quarantine-safety-assessment:${hash("tunesight.table-quarantine-safety-identity.v1", identity)}`, assessmentRevision: `table-quarantine-safety-assessment-revision:${hash("tunesight.table-quarantine-safety-revision.v1", material)}`, ...identity, gates, outcome: gates.every((gate) => gate.passed) ? "dependency_safe_for_quarantine" : "whole_relationship_blocked", targetOffsets: material.targetOffsets, overlappingDefinitionRevisions: material.overlappingDefinitionRevisions });
}

export function constructTableQuarantineRecord(input: Omit<TableQuarantineRecord, "quarantineId" | "quarantineRevision" | "contractVersion" | "state" | "permissions"> & Readonly<{ safetyAssessment: TableQuarantineSafetyAssessment }>): TableQuarantineRecord {
  if (input.safetyAssessment.outcome !== "dependency_safe_for_quarantine" || input.safetyAssessment.definitionRevisionId !== input.occurrence.definitionRevisionId || input.safetyAssessment.binaryDigest !== input.affectedBinary.digest) throw new Error("Quarantine requires an exact dependency-safe assessment binding.");
  if (!input.failureEvidence.finding.trim() || !input.failureEvidence.outcome.trim() || !input.provenance.length || !input.limitations.length || !input.authority.reviewerId.trim() || !input.authority.authorityRevision.trim()) throw new Error("Quarantine requires explicit failure, provenance, limitations and reviewer authority.");
  const timestamp = new Date(input.quarantinedAt); if (!Number.isFinite(timestamp.valueOf()) || timestamp.toISOString() !== input.quarantinedAt) throw new Error("Quarantine timestamp must be canonical UTC.");
  const identity = { relationship: input.relationship, occurrence: input.occurrence, affectedBinary: input.affectedBinary };
  const material = { ...identity, failureClass: input.failureClass, failureEvidence: input.failureEvidence, safetyAssessmentRevision: input.safetyAssessment.assessmentRevision, provenance: [...new Set(input.provenance)].sort(), limitations: [...new Set(input.limitations)].sort(), authority: input.authority, quarantinedAt: input.quarantinedAt, state: "unavailable_quarantined" as const, permissions: { engineeringValueValid: false as const, editable: false as const, suggestedCalibrationEligible: false as const, reconstructionMutationEligible: false as const, flashingEligible: false as const }, contractVersion: TABLE_QUARANTINE_CONTRACT };
  return freeze({ quarantineId: `table-quarantine:${hash("tunesight.table-quarantine-identity.v1", identity)}`, quarantineRevision: `table-quarantine-revision:${hash("tunesight.table-quarantine-revision.v1", material)}`, ...material });
}

export function constructQuarantinedTablePresentation(record: TableQuarantineRecord) { return freeze({ title: "Unavailable / Quarantined", definitionRevisionId: record.occurrence.definitionRevisionId, affectedBinaryRole: record.affectedBinary.role, state: record.state, reason: record.failureEvidence.finding, rawEvidence: { offsets: record.failureEvidence.rawOffsets, bytes: record.failureEvidence.rawBytes, values: record.failureEvidence.rawValues }, engineeringValues: Object.freeze([]), provenance: record.provenance, limitations: record.limitations, ...record.permissions }); }

export type QuarantineAwareSourceAuthorityCandidate = GovernedEvidenceAuthorityCandidate & Readonly<{ quarantineRevisions: readonly string[] }>;
export function constructQuarantineAwareSourceAuthorityCandidate(input: Readonly<{ scope: SourceAuthorityScopeBinding; romSoftwareIdentity: string; validations: readonly CompleteBinaryValidation[]; quarantines: readonly TableQuarantineRecord[]; identityCoherent: boolean; limitations: readonly string[] }>): QuarantineAwareSourceAuthorityCandidate {
  if (!input.validations.length || !input.quarantines.length || !input.identityCoherent) throw new Error("Quarantine-aware authority requires exact validations, quarantine Evidence and coherent identity.");
  if (input.validations.some((item) => item.blocked || item.outOfBounds || item.unsupported || item.representationConflicts || item.malformed || item.unavailable || item.other)) throw new Error("Quarantine cannot cover extraction, representation, unsupported, malformed or unspecified failures.");
  for (const validation of input.validations) {
    const bound = input.quarantines.filter((record) => record.affectedBinary.digest === validation.binaryDigest && record.affectedBinary.validationRevision === validation.validationRevision);
    if (bound.length !== validation.invalidNumeric || bound.some((record) => record.failureClass !== "invalid_engineering_conversion")) throw new Error("Every invalid numeric result must have one exact, independently safe quarantine binding.");
    if (validation.converted + validation.identityNoOp + bound.length !== validation.definitions) throw new Error("Quarantine-aware conversion census is incomplete.");
  }
  const quarantineRevisions = input.quarantines.map((item) => item.quarantineRevision).sort(), evidenceReferences = [...input.validations.map((item) => item.validationRevision), ...quarantineRevisions].sort();
  const identity = { scope: input.scope, romSoftwareIdentity: input.romSoftwareIdentity.toUpperCase() };
  const material = { ...identity, evidenceReferences, quarantineRevisions, limitations: [...new Set(input.limitations)].sort(), contractVersion: "tunesight.source-authority-candidate.v1" as const, state: "pending_founder_authority" as const };
  return freeze({ candidateId: `xdf-source-authority-candidate:${hash("tunesight.source-authority-candidate-identity.v1", identity)}`, candidateRevision: `xdf-source-authority-candidate-revision:${hash("tunesight.source-authority-candidate-revision.v1", material)}`, ...material });
}
