import type { ChannelDefinition, ChannelObservation } from "./nativeVehicleData.ts";

export const BMW_LIVE_TELEMETRY_CONTRACT = "tunesight.bmw-live-telemetry.v1" as const;
export type TelemetryQualification = "qualified_available" | "available_unqualified" | "unsupported" | "transport_unavailable" | "rom_not_qualified" | "conversion_unavailable" | "conflict" | "invalid";
export type TelemetryRole = "actual" | "target" | "observation";
export type GaugeKind = "numeric" | "dial" | "temperature" | "pressure" | "paired" | "trace";
export type BmwTelemetryChannel = Readonly<{ key: string; concept: string; role: TelemetryRole; pairKey: string | null; unit: string | null; qualification: TelemetryQualification; nativeDefinition: ChannelDefinition | null; supportedPresentations: readonly GaugeKind[]; dmeFamilies: readonly string[]; romSoftwareIdentities: readonly string[]; provenance: readonly string[]; limitations: readonly string[] }>;

const desired = [
  ["engine.speed", "Engine speed", "observation", null, "rpm"], ["boost.actual", "Boost", "actual", "boost", "kPa"], ["boost.target", "Boost", "target", "boost", "kPa"], ["coolant.temperature", "Coolant temperature", "observation", null, "°C"], ["oil.temperature", "Oil temperature", "observation", null, "°C"], ["charge.temperature", "Charge-air temperature", "observation", null, "°C"], ["rail-pressure.actual", "Rail pressure", "actual", "rail-pressure", "kPa"], ["rail-pressure.target", "Rail pressure", "target", "rail-pressure", "kPa"], ["lambda.actual", "Lambda", "actual", "lambda", "λ"], ["lambda.target", "Lambda", "target", "lambda", "λ"], ["load.actual", "Load", "actual", "load", "%"], ["load.target", "Load", "target", "load", "%"], ["torque.actual", "Torque", "actual", "torque", "Nm"], ["torque.target", "Torque", "target", "torque", "Nm"], ["throttle.position", "Throttle", "observation", null, "%"], ["accelerator.position", "Accelerator pedal", "observation", null, "%"], ["battery.voltage", "Battery voltage", "observation", null, "V"], ["vehicle.speed", "Vehicle speed", "observation", null, "km/h"],
] as const;

export const F30_00003076501103_CHANNEL_CATALOGUE: readonly BmwTelemetryChannel[] = Object.freeze(desired.map(([key, concept, role, pairKey, unit]) => Object.freeze({ key, concept, role, pairKey, unit, qualification: "rom_not_qualified" as const, nativeDefinition: null, supportedPresentations: Object.freeze(pairKey ? ["numeric", "paired", "trace"] as GaugeKind[] : ["numeric", unit === "°C" ? "temperature" : "dial", "trace"] as GaugeKind[]), dmeFamilies: Object.freeze(["B58 Gen1"]), romSoftwareIdentities: Object.freeze(["00003076501103"]), provenance: Object.freeze(["Founder-supplied BIN establishes expected offline ROM context only; no governed runtime request/address evidence is present."]), limitations: Object.freeze(["Calibration XDF coverage is not telemetry authority.", "A native request, datatype and conversion must be qualified from live/protocol evidence before this channel can become a subscriber gauge."]) })));

export function qualifiedGaugeChannels(channels: readonly BmwTelemetryChannel[]): readonly BmwTelemetryChannel[] { return Object.freeze(channels.filter((channel) => channel.qualification === "qualified_available" && channel.nativeDefinition !== null)); }
export function selectGauges(channels: readonly BmwTelemetryChannel[], keys: readonly string[]): readonly BmwTelemetryChannel[] { const qualified = new Map(qualifiedGaugeChannels(channels).map((channel) => [channel.key, channel])); return Object.freeze([...new Set(keys)].map((key) => qualified.get(key)).filter((value): value is BmwTelemetryChannel => Boolean(value))); }
export function actualTargetPairs(channels: readonly BmwTelemetryChannel[]): readonly Readonly<{ pairKey: string; actual: BmwTelemetryChannel; target: BmwTelemetryChannel }>[] { const pairs = new Map<string, Partial<Record<"actual" | "target", BmwTelemetryChannel>>>(); for (const channel of channels) if (channel.pairKey && (channel.role === "actual" || channel.role === "target")) pairs.set(channel.pairKey, { ...pairs.get(channel.pairKey), [channel.role]: channel }); return Object.freeze([...pairs].flatMap(([pairKey, pair]) => pair.actual && pair.target ? [Object.freeze({ pairKey, actual: pair.actual, target: pair.target })] : [])); }
export function compareLiveIdentity(input: { expectedRomSoftwareIdentity: string; observedRomSoftwareIdentity: string | null }): "match" | "mismatch" | "unavailable" { return input.observedRomSoftwareIdentity === null ? "unavailable" : input.observedRomSoftwareIdentity === input.expectedRomSoftwareIdentity ? "match" : "mismatch"; }
export type LiveSample = Readonly<{ channelRevisionId: string; sequence: number; acquiredAt: string; receivedAt: string; latencyMs: number; droppedSincePrevious: number; observation: ChannelObservation }>;
export function createLiveSample(input: { observation: ChannelObservation; receivedAt: string; previousSequence: number | null }): LiveSample { const received = Date.parse(input.receivedAt), acquired = Date.parse(input.observation.acquiredAt); if (!Number.isFinite(received) || !Number.isFinite(acquired) || received < acquired) throw new Error("Live sample timestamps are invalid."); return Object.freeze({ channelRevisionId: input.observation.channelRevisionId, sequence: input.observation.sequence, acquiredAt: input.observation.acquiredAt, receivedAt: input.receivedAt, latencyMs: received - acquired, droppedSincePrevious: input.previousSequence === null ? 0 : Math.max(0, input.observation.sequence - input.previousSequence - 1), observation: input.observation }); }
