import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { actualTargetPairs, compareLiveIdentity, createLiveSample, F30_00003076501103_CHANNEL_CATALOGUE, qualifiedGaugeChannels, selectGauges } from "./bmwLiveTelemetry.ts";
import { defineChannelDefinition, defineChannelObservation } from "./nativeVehicleData.ts";
import { BMW_ENET_CABLE_PROFILE, GENERIC_USB_DIAGNOSTIC_PROFILE, MHD_ORANGE_PROFILE, THOR_WIFI_PROFILE } from "./adapterProfiles.ts";

test("BMW-generic catalogue preserves concepts, actual-target pairs, and exact unresolved ROM scope", () => { assert.ok(F30_00003076501103_CHANNEL_CATALOGUE.length >= 18); assert.deepEqual(actualTargetPairs(F30_00003076501103_CHANNEL_CATALOGUE).map((pair) => pair.pairKey), ["boost", "rail-pressure", "lambda", "load", "torque"]); assert.ok(F30_00003076501103_CHANNEL_CATALOGUE.every((channel) => channel.romSoftwareIdentities.includes("00003076501103") && channel.qualification === "rom_not_qualified" && channel.nativeDefinition === null)); assert.deepEqual(qualifiedGaugeChannels(F30_00003076501103_CHANNEL_CATALOGUE), []); assert.deepEqual(selectGauges(F30_00003076501103_CHANNEL_CATALOGUE, ["engine.speed"]), []); });
test("live identity is compared and never inferred from expected BIN context", () => { assert.equal(compareLiveIdentity({ expectedRomSoftwareIdentity: "00003076501103", observedRomSoftwareIdentity: null }), "unavailable"); assert.equal(compareLiveIdentity({ expectedRomSoftwareIdentity: "00003076501103", observedRomSoftwareIdentity: "00003076501103" }), "match"); assert.equal(compareLiveIdentity({ expectedRomSoftwareIdentity: "00003076501103", observedRomSoftwareIdentity: "DIFFERENT" }), "mismatch"); });
test("sample envelope preserves sequence, timestamp, measured latency and dropped samples", () => { const channel = defineChannelDefinition({ channelKey: "future.engine.speed", sourceEndpointId: "future-dme", protocol: "future-qualified", serviceId: "read", requestId: "rpm", rawDataType: "uint16", decoding: { kind: "identity", scale: 1, offset: 0, qualification: "qualified" }, unit: "rpm", applicability: { state: "qualified", dmeFamilies: ["future-bmw"] }, expectedRateHz: null, provenance: "controlled future-platform fixture" }); const observation = defineChannelObservation({ channel, sessionId: "session", sequence: 4, acquiredAt: "2026-09-07T00:00:00.000Z", sourceTimestamp: null, rawValue: 800, validity: "valid", finding: null, provenance: "fixture" }); const sample = createLiveSample({ observation, receivedAt: "2026-09-07T00:00:00.025Z", previousSequence: 1 }); assert.equal(sample.latencyMs, 25); assert.equal(sample.droppedSincePrevious, 2); assert.equal(sample.observation.convertedValue, 800); });
test("transport audit keeps ENET, USB and WiFi capabilities separate", () => { assert.equal(BMW_ENET_CABLE_PROFILE.transport, "wired_ethernet"); assert.deepEqual(BMW_ENET_CABLE_PROFILE.protocolCapabilities, ["enet_hsfz"]); assert.equal(GENERIC_USB_DIAGNOSTIC_PROFILE.protocolCapabilities[0], "unknown"); for (const adapter of [MHD_ORANGE_PROFILE, THOR_WIFI_PROFILE]) { assert.deepEqual(adapter.protocolCapabilities, ["k_dcan"]); assert.ok(adapter.unknownProperties.some((item) => item.includes("B58/ENET"))); } });
test("Garage vehicle route exposes a dedicated telemetry workspace with no synthetic fallback", () => { const vehicle = readFileSync(new URL("../../app/dashboard/vehicles/[id]/page.tsx", import.meta.url), "utf8"); const page = readFileSync(new URL("../../app/dashboard/vehicles/[id]/telemetry/page.tsx", import.meta.url), "utf8"); const workspace = readFileSync(new URL("../../components/LiveTelemetryWorkspace.tsx", import.meta.url), "utf8"); assert.match(vehicle, /vehicles\/\$\{vehicle\.id\}\/telemetry/); assert.match(page, /LiveTelemetryWorkspace/); assert.match(workspace, /Values are never simulated/); assert.doesNotMatch(workspace, /SyntheticReadOnlyVehicleTransport|Math\.random/); });
