import { defineChannelObservation, defineEcuIdentityObservation, definePhysicalAdapter, defineVehicleInterfaceSession, type ChannelDefinition, type ChannelObservation, type EcuIdentityObservation, type PhysicalAdapter, type ReadOnlyVehicleTransport, type VehicleInterfaceSession } from "./nativeVehicleData.ts";

export type SyntheticTransportFixture = Readonly<{ endpointId: string; protocol: string; dmeFamily: string; softwareIdentity: string; calibrationIdentity: string; vin: string; rawValuesByChannelKey: Readonly<Record<string, readonly number[]>>; unsupportedChannelKeys: readonly string[]; failAtSequence: number | null; failureCode?: "synthetic_transport_failure" | "synthetic_transport_timeout" }>;

export class SyntheticReadOnlyVehicleTransport implements ReadOnlyVehicleTransport {
  readonly adapter: PhysicalAdapter = definePhysicalAdapter({ adapterId: "synthetic-adapter", adapterRevision: "1.0", manufacturer: "TuneSight", model: "Deterministic Read-Only Harness", transportKinds: ["synthetic"], provenance: "Founder-authorised synthetic validation fixture" });
  private session: VehicleInterfaceSession | null = null;
  private sessionReference: string | null = null;
  private readonly fixture: SyntheticTransportFixture;
  constructor(fixture: SyntheticTransportFixture) { this.fixture = fixture; }
  async discover() { return Object.freeze([this.adapter.adapterId]); }
  async open(input: { sessionReference: string; startedAt: string }) { this.sessionReference = input.sessionReference; this.session = defineVehicleInterfaceSession({ sessionReference: input.sessionReference, adapterId: this.adapter.adapterId, adapterRevision: this.adapter.adapterRevision, transportKind: "synthetic", state: "open", startedAt: input.startedAt, endedAt: null, disconnectReason: null, failureCode: null, provenance: "synthetic transport open" }); return this.session; }
  async connect() { if (!this.session || this.session.state !== "open" || !this.sessionReference) throw new Error("Synthetic transport must be open before connection."); this.session = defineVehicleInterfaceSession({ sessionReference: this.sessionReference, adapterId: this.adapter.adapterId, adapterRevision: this.adapter.adapterRevision, transportKind: "synthetic", state: "connected", startedAt: this.session.startedAt, endedAt: null, disconnectReason: null, failureCode: null, provenance: "synthetic transport connection" }); return this.session; }
  async identify(input: { observedAt: string }): Promise<EcuIdentityObservation> { if (!this.session || this.session.state !== "connected") throw new Error("Synthetic transport is not connected."); return defineEcuIdentityObservation({ sessionId: this.session.sessionId, endpointId: this.fixture.endpointId, protocol: this.fixture.protocol, observedDmeFamily: this.fixture.dmeFamily, softwareIdentity: this.fixture.softwareIdentity, calibrationIdentity: this.fixture.calibrationIdentity, vin: this.fixture.vin, observedAt: input.observedAt, capabilityObservations: ["read_channel", "identify"], qualification: "synthetic", provenance: "deterministic synthetic ECU response" }); }
  async read(channel: ChannelDefinition, input: { acquiredAt: string; sequence: number }): Promise<ChannelObservation> { if (!this.session || this.session.state !== "connected") throw new Error("Synthetic transport is not connected."); if (this.fixture.failAtSequence === input.sequence) throw new Error(this.fixture.failureCode ?? "synthetic_transport_failure"); const unsupported = this.fixture.unsupportedChannelKeys.includes(channel.channelKey); const values = this.fixture.rawValuesByChannelKey[channel.channelKey]; const candidate = values?.[input.sequence]; if (!unsupported && candidate === undefined) throw new Error("Synthetic fixture has no value for sequence."); return defineChannelObservation({ sessionId: this.session.sessionId, channel, sequence: input.sequence, acquiredAt: input.acquiredAt, sourceTimestamp: input.sequence, rawValue: candidate ?? 0, validity: unsupported ? "unsupported" : "valid", finding: unsupported ? "Channel is unsupported by the synthetic endpoint." : null, provenance: "deterministic synthetic channel read" }); }
  async stream(channel: ChannelDefinition, inputs: readonly Readonly<{ acquiredAt: string; sequence: number }>[]) { const observations: ChannelObservation[] = []; let previous = -1; for (const input of inputs) { if (input.sequence <= previous) throw new Error("Stream sequence must increase strictly."); observations.push(await this.read(channel, input)); previous = input.sequence; } return Object.freeze(observations); }
  async disconnect(input: { endedAt: string; reason: string }) { if (!this.session || !this.sessionReference) throw new Error("Synthetic transport has no session."); this.session = defineVehicleInterfaceSession({ sessionReference: this.sessionReference, adapterId: this.adapter.adapterId, adapterRevision: this.adapter.adapterRevision, transportKind: "synthetic", state: "disconnected", startedAt: this.session.startedAt, endedAt: input.endedAt, disconnectReason: input.reason, failureCode: null, provenance: "synthetic transport disconnect" }); return this.session; }
}
