import assert from "node:assert/strict";
import test from "node:test";
import { MHD_ORANGE_PROFILE, THOR_WIFI_PROFILE } from "./adapterProfiles.ts";
import { createCanonicalLiveRecording } from "./liveRecording.ts";
import { markRecordingExported, retainRecording } from "./offlineRecordingQueue.ts";
import { assessTabletCapability, createAdapterDiscoveryReport } from "./tabletAdapterDiagnostics.ts";

test("MHD Orange remains distinct from ENET and Universal generations and is explicitly excluded for B58", () => { assert.deepEqual(MHD_ORANGE_PROFILE.wifiSsids, ["MHD CAN"]); assert.deepEqual(MHD_ORANGE_PROFILE.protocolCapabilities, ["k_dcan"]); assert.ok(MHD_ORANGE_PROFILE.externallySupportedVehicleScopes.some((scope) => /B58 explicitly excluded/.test(scope))); assert.equal(MHD_ORANGE_PROFILE.endpoints.length, 0); });
test("THOR remains a separately evidenced DCAN endpoint with no B58 DME qualification", () => { assert.deepEqual(THOR_WIFI_PROFILE.endpoints, [{ host: "192.168.4.1", port: 23, protocol: "tcp", state: "strongly_evidenced" }]); assert.deepEqual(THOR_WIFI_PROFILE.protocolCapabilities, ["k_dcan"]); assert.ok(THOR_WIFI_PROFILE.externallySupportedVehicleScopes.some((scope) => /B58 DME telemetry explicitly excluded/.test(scope))); });
test("tablet capability never fabricates browser TCP UDP or gateway access", () => { assert.deepEqual(assessTabletCapability({ hasCellularData: false }), { browserRawTcpUdp: false, browserGatewayInspection: false, companionRequired: true, internetDuringAdapterWifi: "unavailable_on_wifi_only_tablet" }); assert.equal(assessTabletCapability({ hasCellularData: true }).internetDuringAdapterWifi, "cellular_may_remain"); });
test("companion discovery evidence accepts only exact profile endpoints and read-only operations", () => { const report = createAdapterDiscoveryReport({ profile: THOR_WIFI_PROFILE, observedSsid: "observed-at-test", localAddress: "192.168.4.100", gateway: null, endpointResults: [{ host: "192.168.4.1", port: 23, protocol: "tcp", reachable: true }], protocolHandshake: "accepted", finding: "Controlled discovery fixture; no vehicle command." }); assert.equal(report.reachableEndpoints[0]?.reachable, true); assert.deepEqual(report.operations, ["discover", "connect", "identify", "read", "stream", "disconnect"]); assert.throws(() => createAdapterDiscoveryReport({ profile: THOR_WIFI_PROFILE, endpointResults: [{ host: "8.8.8.8", port: 53, protocol: "udp", reachable: null }], finding: "invalid" }), /allowlisted/); });
test("canonical recording retains adapter provenance offline and transitions only to exported", () => { const recording = createCanonicalLiveRecording({ recordingId: "recording", vehicleId: "vehicle", sessionId: "session", transport: "controlled", dmeIdentity: null, romSoftwareIdentity: null, startedAt: "2026-09-07T00:00:00.000Z", stoppedAt: "2026-09-07T00:00:01.000Z", samples: [{ channelKey: "engine.speed", channelRevisionId: "revision", sequence: 0, acquiredAt: "2026-09-07T00:00:00.000Z", receivedAt: "2026-09-07T00:00:00.010Z", latencyMs: 10, droppedSincePrevious: 0, value: 800, unit: "rpm", provenance: "controlled" }] }); const retained = retainRecording({ recording, adapterProfileReference: THOR_WIFI_PROFILE.profileRevision, retainedAt: "2026-09-07T00:00:02.000Z" }); assert.equal(retained.synchronization, "pending_export"); assert.equal(markRecordingExported(retained).synchronization, "exported"); assert.equal(retained.recording, recording); });
