import { randomBytes, randomUUID } from "node:crypto";
import dgram from "node:dgram";
import http from "node:http";
import net from "node:net";
import { ENET_DISCOVERY_PORT, ENET_HSFZ_PORT, ENET_OBD_CHANNELS, decodeHsfzFrames, encodeDmeRequest, encodeHsfzFrame, parseObdResponse, supportedPids } from "../lib/vehicle-interface/enetObd.ts";

const bind = "127.0.0.1", port = 57631, token = process.env.TUNESIGHT_BRIDGE_TOKEN ?? randomBytes(24).toString("base64url");
const origins = new Set((process.env.TUNESIGHT_BRIDGE_ALLOWED_ORIGINS ?? "http://localhost:3000,http://127.0.0.1:3000").split(",").map((v) => v.trim()).filter(Boolean));
let socket: net.Socket | null = null, session: { id: string; host: string; identity: Record<string, string | null>; supported: Set<number>; nextSequenceByKey: Map<string, number>; lastDeliveredByKey: Map<string, number> } | null = null, remainder: Buffer<ArrayBufferLike> = Buffer.alloc(0);
function cors(req: http.IncomingMessage, res: http.ServerResponse) { const origin = req.headers.origin; if (origin && origins.has(origin)) { res.setHeader("Access-Control-Allow-Origin", origin); res.setHeader("Vary", "Origin"); res.setHeader("Access-Control-Allow-Private-Network", "true"); } res.setHeader("Access-Control-Allow-Headers", "authorization,content-type"); res.setHeader("Access-Control-Allow-Methods", "GET,POST,OPTIONS"); }
function json(res: http.ServerResponse, status: number, body: unknown) { res.writeHead(status, { "Content-Type": "application/json", "Cache-Control": "no-store" }); res.end(JSON.stringify(body)); }
async function body(req: http.IncomingMessage) { const chunks: Buffer[] = []; let size = 0; for await (const chunk of req) { const value = Buffer.from(chunk); size += value.length; if (size > 16_384) throw new Error("payload_too_large"); chunks.push(value); } return chunks.length ? JSON.parse(Buffer.concat(chunks).toString("utf8")) as Record<string, unknown> : {}; }
function authorised(req: http.IncomingMessage) { return req.headers.authorization === `Bearer ${token}`; }
async function discover(): Promise<string> { const configured = process.env.TUNESIGHT_ENET_HOST; if (configured) return configured; return new Promise((resolve, reject) => { const udp = dgram.createSocket("udp4"), timer = setTimeout(() => { udp.close(); reject(new Error("vehicle_discovery_timeout")); }, 3500); udp.once("error", reject); udp.once("message", (_message, remote) => { clearTimeout(timer); udp.close(); resolve(remote.address); }); udp.bind(() => { udp.setBroadcast(true); udp.send(encodeHsfzFrame(0x0011, new Uint8Array()), ENET_DISCOVERY_PORT, "255.255.255.255"); }); }); }
function transact(request: Buffer, timeoutMs = 2500): Promise<Uint8Array> { if (!socket) return Promise.reject(new Error("vehicle_not_connected")); return new Promise((resolve, reject) => { const timer = setTimeout(() => { cleanup(); reject(new Error("vehicle_response_timeout")); }, timeoutMs); const cleanup = () => { clearTimeout(timer); socket?.off("data", onData); socket?.off("error", onError); }; const onError = (error: Error) => { cleanup(); reject(error); }; const onData = (chunk: Buffer) => { remainder = Buffer.concat([remainder, chunk]); const decoded = decodeHsfzFrames(remainder); remainder = decoded.remainder; const frame = decoded.frames.find((value) => value.type === 0x0001); if (frame) { cleanup(); resolve(frame.payload); } }; socket!.on("data", onData); socket!.once("error", onError); socket!.write(request); }); }
async function connect() { disconnect(); const host = await discover(); socket = net.createConnection({ host, port: ENET_HSFZ_PORT }); await new Promise<void>((resolve, reject) => { const timer = setTimeout(() => { socket?.destroy(); reject(new Error("vehicle_connect_timeout")); }, 3500); socket!.once("connect", () => { clearTimeout(timer); resolve(); }); socket!.once("error", (error) => { clearTimeout(timer); reject(error); }); }); const supported = new Set<number>(); for (const base of [0x00, 0x20, 0x40]) { try { for (const pid of supportedPids(base, await transact(encodeDmeRequest(0x01, [base])))) supported.add(pid); } catch { /* an unsupported range remains unavailable */ } } const identity: Record<string, string | null> = { dme: "BMW DME logical address 0x12", vin: null, applicationSoftwareVersion: null, sparePartNumber: null, romSoftwareIdentity: null }; for (const [name, did] of [["vin", 0xf190], ["applicationSoftwareVersion", 0xf189], ["sparePartNumber", 0xf187]] as const) { try { const response = await transact(encodeDmeRequest(0x22, [did >> 8, did & 0xff])); if (response[2] === 0x62 && response[3] === (did >> 8) && response[4] === (did & 0xff)) identity[name] = Buffer.from(response.slice(5)).toString("ascii").replaceAll("\0", "").trim() || null; } catch { identity[name] = null; } } identity.romSoftwareIdentity = [identity.applicationSoftwareVersion, identity.sparePartNumber].find((value) => value === "00003076501103") ?? null; session = { id: randomUUID(), host, identity, supported, nextSequenceByKey: new Map(), lastDeliveredByKey: new Map() }; return session; }
async function sample(keys: readonly string[]) { if (!session) throw new Error("vehicle_not_connected"); const acquiredAt = new Date().toISOString(), rows = []; for (const key of [...new Set(keys)].slice(0, 16)) { const definition = ENET_OBD_CHANNELS.find((value) => value.channel.channelKey === key); if (!definition || !session.supported.has(definition.pid)) { rows.push({ key, state: "unsupported" }); continue; } const sequence = session.nextSequenceByKey.get(key) ?? 0; session.nextSequenceByKey.set(key, sequence + 1); const started = performance.now(); try { const value = parseObdResponse({ pid: definition, payload: await transact(encodeDmeRequest(0x01, [definition.pid])) }); const previous = session.lastDeliveredByKey.get(key); session.lastDeliveredByKey.set(key, sequence); rows.push({ key, state: "valid", value, unit: definition.channel.unit, channelRevisionId: definition.channel.revisionId, sequence, acquiredAt, receivedAt: new Date().toISOString(), latencyMs: Math.round(performance.now() - started), droppedSincePrevious: previous === undefined ? 0 : Math.max(0, sequence - previous - 1) }); } catch (error) { rows.push({ key, state: "invalid", sequence, acquiredAt, receivedAt: new Date().toISOString(), latencyMs: Math.round(performance.now() - started), finding: error instanceof Error ? error.message : "read_failed" }); } } return rows; }
function disconnect() { socket?.destroy(); socket = null; session = null; remainder = Buffer.alloc(0); }
const server = http.createServer(async (req, res) => { cors(req, res); if (req.method === "OPTIONS") return res.writeHead(204).end(); if (!req.headers.origin || !origins.has(req.headers.origin)) return json(res, 403, { error: "origin_not_allowed" }); if (!authorised(req)) return json(res, 401, { error: "authentication_failed" }); try { if (req.method === "GET" && req.url === "/v1/status") return json(res, 200, { state: session ? "connected" : "ready", authenticatedSession: Boolean(session), session }); if (req.method === "POST" && req.url === "/v1/connect") return json(res, 200, { session: await connect(), channels: ENET_OBD_CHANNELS.map((value) => ({ key: value.channel.channelKey, unit: value.channel.unit, revisionId: value.channel.revisionId, state: session!.supported.has(value.pid) ? "qualified_available" : "unsupported" })) }); if (req.method === "POST" && req.url === "/v1/sample") { const input = await body(req); return json(res, 200, { samples: await sample(Array.isArray(input.channels) ? input.channels.filter((v): v is string => typeof v === "string") : []) }); } if (req.method === "POST" && req.url === "/v1/disconnect") { disconnect(); return json(res, 200, { state: "disconnected" }); } return json(res, 404, { error: "operation_not_allowed" }); } catch (error) { disconnect(); return json(res, 503, { error: error instanceof Error ? error.message : "bridge_failure" }); } });
server.listen(port, bind, () => { console.log(`TuneSight read-only ENET bridge: http://${bind}:${port}`); console.log(`Session token: ${token}`); console.log(`Allowed origins: ${[...origins].join(", ")}`); console.log("No write, flash, coding, DTC-clear, adaptation, actuator, or raw-proxy route exists."); });
process.on("SIGINT", () => { disconnect(); server.close(() => process.exit(0)); });
