import assert from "node:assert/strict";
import test from "node:test";
import type { MasterCalibrationResolution, MasterCalibrationResolutionOutcome } from "../calibration-workshop/masterCalibrationResolver.ts";
import { admitVehicleIdentity, deriveVehicleCapabilityEnvelope, type IdentityField, type VehicleIdentityEvidence } from "./vehicleAdmission.ts";

const field = (value: string | null, state: IdentityField["state"]): IdentityField => Object.freeze({ value, state, evidence: Object.freeze(value ? ["Controlled identity evidence"] : []) });
const identity = (overrides: Partial<VehicleIdentityEvidence> = {}): VehicleIdentityEvidence => Object.freeze({ vehicle: field("vehicle-1", "exact_verified"), chassisPlatform: field("F30", "qualified_classification"), engineFamily: field("B58 Gen1", "qualified_classification"), ecuDmeFamily: field("MG1CS003", "qualified_classification"), romSoftware: field("ROM-KNOWN", "exact_verified"), romFamily: field("ROM-FAMILY", "qualified_classification"), ...overrides });
function calibration(outcome: MasterCalibrationResolutionOutcome, discovery = false): MasterCalibrationResolution { return Object.freeze({ contractVersion: "tunesight.master-calibration-resolver.v1", outcome, catalogEntry: null, findings: Object.freeze([]), coverage: Object.freeze({ resolutionId: "resolution", resolutionRevision: "resolution-revision", contractVersion: "tunesight.definition-coverage-discovery.v1", outcome: outcome === "EXACT_QUALIFIED_MATCH" ? "EXACT_DEFINITION_COVERAGE" : outcome === "MATCH_REQUIRES_QUALIFICATION" ? "CANDIDATE_DEFINITION_COVERAGE" : outcome === "ROM_RECOGNIZED_DEFINITION_MISSING" ? "ROM_RECOGNIZED_DEFINITIONS_UNAVAILABLE" : outcome === "ROM_UNKNOWN" ? "NEW_ROM_DISCOVERED" : outcome === "INVALID_BINARY" ? "INVALID" : "CONFLICT", observationId: "observation", exactDefinitionSetRevision: outcome === "EXACT_QUALIFIED_MATCH" ? "definition-set" : null, candidateIds: Object.freeze([]), discoveryPackage: discovery ? Object.freeze({ packageId: "new-rom", packageRevision: "new-rom-revision", contractVersion: "tunesight.new-rom-discovery-evidence.v1", dmeFamily: "MG1CS003", ecuFamily: "MG1", softwareIdentity: "ROM-NEW", calibrationIdentity: null, binary: null, relatedCandidateIds: Object.freeze([]), conflicts: Object.freeze([]), provenance: Object.freeze(["Controlled identity evidence"]), limitations: Object.freeze([]), state: "discovery_evidence_only" }) : null, workshopEligible: outcome === "EXACT_QUALIFIED_MATCH", workshopMessage: "controlled", findings: Object.freeze([]), publicationSideEffects: Object.freeze([]) as readonly [] }) }); }

test("exact known identity and Calibration capabilities remain independently available", () => { const admission = admitVehicleIdentity(identity()), envelope = deriveVehicleCapabilityEnvelope({ admission, calibration: calibration("EXACT_QUALIFIED_MATCH"), editQualified: true, reconstructionQualified: true, checksumQualified: false, analysisEvidence: "qualified", telemetryAuthority: "qualified" }); assert.equal(admission.outcome, "ADMITTED"); assert.equal(admission.confidence, "exact_vehicle_and_rom"); assert.deepEqual(envelope, { vehicleWorkspace: "AVAILABLE", analysis: "AVAILABLE", telemetry: "AVAILABLE", calibrationView: "AVAILABLE", calibrationAddresses: "QUALIFIED", definitionSet: "QUALIFIED", calibrationEdit: "AVAILABLE", calibrationReconstruct: "AVAILABLE", calibrationExport: "CHECKSUM_UNKNOWN", flash: "NOT_QUALIFIED", acquiredXdfContribution: "NOT_APPLICABLE", newRomEvidenceRevision: null }); });

test("known legitimate platform with a newly observed ROM is admitted without Calibration authority", () => { const admission = admitVehicleIdentity(identity({ romSoftware: field("ROM-NEW", "observed_unqualified"), romFamily: field(null, "unresolved") })), envelope = deriveVehicleCapabilityEnvelope({ admission, calibration: calibration("ROM_UNKNOWN", true), editQualified: false, reconstructionQualified: false, checksumQualified: false, analysisEvidence: "qualified", telemetryAuthority: "qualified" }); assert.equal(admission.outcome, "ADMITTED"); assert.equal(admission.confidence, "exact_vehicle"); assert.equal(envelope.vehicleWorkspace, "AVAILABLE"); assert.equal(envelope.analysis, "AVAILABLE"); assert.equal(envelope.telemetry, "AVAILABLE"); assert.equal(envelope.calibrationView, "DEFINITIONS_UNAVAILABLE"); assert.equal(envelope.calibrationAddresses, "UNAVAILABLE"); assert.equal(envelope.definitionSet, "UNAVAILABLE"); assert.equal(envelope.calibrationEdit, "BLOCKED_DEPENDENCY"); assert.equal(envelope.calibrationReconstruct, "BLOCKED_DEPENDENCY"); assert.equal(envelope.calibrationExport, "BLOCKED_DEPENDENCY"); assert.equal(envelope.flash, "NOT_QUALIFIED"); assert.equal(envelope.acquiredXdfContribution, "CANDIDATE_EVIDENCE_ALLOWED"); assert.equal(envelope.newRomEvidenceRevision, "new-rom-revision"); });

test("recognized ROM without Definitions and acquired candidates do not reject the vehicle or grant capability", () => { const admission = admitVehicleIdentity(identity()); for (const outcome of ["ROM_RECOGNIZED_DEFINITION_MISSING", "MATCH_REQUIRES_QUALIFICATION"] as const) { const envelope = deriveVehicleCapabilityEnvelope({ admission, calibration: calibration(outcome, true), editQualified: true, reconstructionQualified: true, checksumQualified: true, analysisEvidence: "unavailable", telemetryAuthority: "unavailable" }); assert.equal(envelope.vehicleWorkspace, "AVAILABLE"); assert.equal(envelope.calibrationView, "DEFINITIONS_UNAVAILABLE"); assert.equal(envelope.calibrationEdit, "BLOCKED_DEPENDENCY"); assert.equal(envelope.calibrationReconstruct, "BLOCKED_DEPENDENCY"); assert.equal(envelope.calibrationExport, "BLOCKED_DEPENDENCY"); assert.equal(envelope.flash, "NOT_QUALIFIED"); } });

test("Analysis and telemetry are governed by their own evidence rather than Calibration coverage", () => { const admission = admitVehicleIdentity(identity({ romSoftware: field(null, "unresolved") })); const available = deriveVehicleCapabilityEnvelope({ admission, calibration: calibration("ROM_UNKNOWN"), editQualified: false, reconstructionQualified: false, checksumQualified: false, analysisEvidence: "qualified", telemetryAuthority: "qualified" }), unavailable = deriveVehicleCapabilityEnvelope({ admission, calibration: calibration("EXACT_QUALIFIED_MATCH"), editQualified: true, reconstructionQualified: true, checksumQualified: true, analysisEvidence: "invalid", telemetryAuthority: "invalid" }); assert.equal(available.analysis, "AVAILABLE"); assert.equal(available.telemetry, "AVAILABLE"); assert.equal(unavailable.analysis, "EVIDENCE_REQUIRED"); assert.equal(unavailable.telemetry, "QUALIFICATION_REQUIRED"); });

test("ambiguous or insufficient vehicle identity remains fail-closed", () => { const conflicted = admitVehicleIdentity(identity({ ecuDmeFamily: field("conflict", "conflict") })), insufficient = admitVehicleIdentity(identity({ vehicle: field(null, "unresolved"), chassisPlatform: field(null, "unresolved"), engineFamily: field(null, "unresolved") })); assert.equal(conflicted.outcome, "REJECTED_CONFLICT"); assert.equal(insufficient.outcome, "REJECTED_INSUFFICIENT_IDENTITY"); for (const admission of [conflicted, insufficient]) assert.equal(deriveVehicleCapabilityEnvelope({ admission, calibration: calibration("EXACT_QUALIFIED_MATCH"), editQualified: true, reconstructionQualified: true, checksumQualified: true, analysisEvidence: "qualified", telemetryAuthority: "qualified" }).vehicleWorkspace, "BLOCKED_IDENTITY"); });
