import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import manifestJson from "../../engineering/calibration/bmw-master-bulk-view-admissions.json" with { type: "json" };
import { defineDefinitionSetRevision } from "../xdf/definitionRomApplicability.ts";
import { interpretXdfStructure } from "../xdf/interpretXdfStructure.ts";
import { defineRomLayoutIdentity } from "../xdf/romLayoutApplicability.ts";
import type { QualifiedRomLayoutApplicabilityRelationship, RomLayoutApplicabilityRegistrySnapshot } from "../xdf/romLayoutApplicabilityPublication.ts";
import type { TableQuarantineRecord } from "../xdf/tableQuarantine.ts";
import { constructQualifiedRomLayoutDiscoveryRegistry, type RomLayoutMembershipAuthority } from "../xdf/romLayoutDiscovery.ts";
import type { DefinitionCatalog, DefinitionCatalogEntry, DefinitionCatalogIdentity } from "./masterCalibrationResolver.ts";

type Admission = Readonly<{ relativePath: string; family: string; romSoftwareIdentity: string; sourceArtifactId: string; sourceArtifactDigest: string; definitionSetId: string; definitionSetRevision: string; definitionCount: number; binaryByteLength: number; containerType: "bin"; marker: Readonly<{ normalizedForm: string; detector: "bounded_ascii_exact" | "bounded_hex_encoded_exact"; offsets: readonly number[] }>; calibrationAddressSpace: readonly Readonly<{ startAddress: number; size: number }>[]; definitionCompatibleAddressRange: Readonly<{ minimum: number; maximum: number }>; supportingExactBinaries: readonly Readonly<{ digest: string; byteLength: number; containerType: "bin"; sourceRole: "stock_original" | "mapswitch"; validationRevision: string }>[]; quarantines?: readonly TableQuarantineRecord[] }>;
type Manifest = Readonly<{ contractVersion: "tunesight.bmw-bulk-current-view-admission.v1"; authorizedAt: string; authority: string; admitted: readonly Admission[]; rejected: readonly Readonly<{ relativePath: string; reason: string }>[]; revision: string }>;
const manifest = manifestJson as Manifest;
const LEGACY_AUTHORITY_REVISION = "bmw-bulk-current-view-admission-revision:a6917653043482497f59d1655ed1529d3f2a3ea97d3225d8b28e0f50cc6883ee";
const B58_GEN1_EXPANSION_AUTHORITY_REVISION = "b58-gen1-current-view-expansion-revision:2026-09-15";
const LEGACY_AUTHORITY = "Founder Beau and Bob bulk Current VIEW admission; no EDIT, EXPORT, FLASH, Stock, or Reference authority.";
const LEGACY_PUBLISHED_AT = "2026-09-14T00:00:00.000Z";
const isExpansion = (admission: Admission) => ["00003076501D02", "00003081501102", "00003081501D04"].includes(admission.romSoftwareIdentity);
const authorityRevision = (admission: Admission) => isExpansion(admission) ? B58_GEN1_EXPANSION_AUTHORITY_REVISION : LEGACY_AUTHORITY_REVISION;
const authorityText = (admission: Admission) => isExpansion(admission) ? manifest.authority : LEGACY_AUTHORITY;
const publishedAt = (admission: Admission) => isExpansion(admission) ? manifest.authorizedAt : LEGACY_PUBLISHED_AT;
type Materialized = Readonly<{ authority: RomLayoutMembershipAuthority; registry: RomLayoutApplicabilityRegistrySnapshot }>;
const root = path.resolve("BMW-XDFs-master"), cache = new Map<string, Materialized>();
const hash = (domain: string, value: unknown) => createHash("sha256").update(domain).update(Buffer.from([0])).update(JSON.stringify(value)).digest("hex");

function materialize(admission: Admission): Materialized {
  const prior = cache.get(admission.romSoftwareIdentity); if (prior) return prior;
  const full = path.join(root, ...admission.relativePath.split("/"));
  const admissionAuthorityRevision = authorityRevision(admission), parsed = interpretXdfStructure({ xml: fs.readFileSync(full, "utf8"), filename: path.basename(full), provenance: admissionAuthorityRevision });
  if (!parsed.sourceArtifact || parsed.outcome !== "structurally_interpreted") throw new Error("Bulk VIEW Definition source is unavailable.");
  const definitionSet = defineDefinitionSetRevision({ sourceArtifact: parsed.sourceArtifact, definitions: parsed.definitions });
  if (parsed.sourceArtifact.artifactId !== admission.sourceArtifactId || parsed.sourceArtifact.sourceDigest !== admission.sourceArtifactDigest || definitionSet.definitionSetId !== admission.definitionSetId || definitionSet.revisionId !== admission.definitionSetRevision || parsed.definitions.length !== admission.definitionCount) throw new Error("Bulk VIEW admission evidence changed after authorization.");
  const marker = { kind: "calibration_identifier" as const, normalizedForm: admission.marker.normalizedForm, detector: admission.marker.detector, offsets: admission.marker.offsets };
  const layout = defineRomLayoutIdentity({ romSoftwareIdentifiers: [admission.romSoftwareIdentity], calibrationSoftwareIdentifiers: [admission.romSoftwareIdentity], ecuDmeFamily: "BMW-REPOSITORY-QUALIFIED-LAYOUT", binaryByteLength: admission.binaryByteLength, containerTypes: [admission.containerType], internalMarkers: [marker], calibrationAddressSpace: admission.calibrationAddressSpace, definitionCompatibleAddressRange: admission.definitionCompatibleAddressRange, xdfSideIdentities: [admission.romSoftwareIdentity], evidenceProvenance: [admissionAuthorityRevision, ...admission.supportingExactBinaries.map((item) => item.validationRevision)] });
  const identity = { definitionSetId: admission.definitionSetId, romLayoutId: layout.layoutId, authorityRevision: admissionAuthorityRevision };
  const relationshipMaterial = { sourceArtifactId: admission.sourceArtifactId, sourceArtifactDigest: admission.sourceArtifactDigest, definitionSetId: admission.definitionSetId, definitionSetRevisionId: admission.definitionSetRevision, romLayoutId: layout.layoutId, authorityPathway: "tunesight_governed_engineering_evidence" as const, qualificationProvenance: "tunesight_qualified_through_governed_engineering_evidence" as const, supportingExactBinaries: admission.supportingExactBinaries.map((item) => ({ binaryDigest: item.digest, sourceRole: item.sourceRole, byteLength: item.byteLength, internalRomIdentifiers: [admission.romSoftwareIdentity] })), decisionId: `bulk-current-view-decision:${hash("tunesight.bulk-current-view-decision.v1", identity)}`, decisionRevision: `bulk-current-view-decision-revision:${hash("tunesight.bulk-current-view-decision-revision.v1", { ...identity, validations: admission.supportingExactBinaries.map((item) => item.validationRevision) })}`, instructionId: `bulk-current-view-publication:${hash("tunesight.bulk-current-view-publication.v1", identity)}`, instructionRevision: `bulk-current-view-publication-revision:${hash("tunesight.bulk-current-view-publication-revision.v1", { ...identity, manifest: admissionAuthorityRevision })}`, authorityProvenance: [authorityText(admission), admissionAuthorityRevision], sourceProvenanceDisclosure: ["Repository-controlled BMW Master XDF and exact responsible binary validation."], provenanceLimitations: ["Stock and Reference authority are not established.", "EDIT, EXPORT and FLASH capabilities are not authorized."], representationConflictCount: 0, lifecycleState: "active" as const, publicationScope: "local_domain_only" as const, publishedAt: publishedAt(admission), contractVersion: "tunesight.qualified-rom-layout-applicability-relationship.v1" as const };
  const relationship: QualifiedRomLayoutApplicabilityRelationship = Object.freeze({ relationshipId: `qualified-rom-layout-applicability:${hash("tunesight.qualified-rom-layout-applicability-identity.v1", identity)}`, relationshipRevision: `qualified-rom-layout-applicability-revision:${hash("tunesight.qualified-rom-layout-applicability-revision.v1", relationshipMaterial)}`, ...relationshipMaterial });
  const registry: RomLayoutApplicabilityRegistrySnapshot = Object.freeze({ snapshotId: `rom-layout-applicability-registry:${hash("tunesight.bulk-current-view-registry.v1", relationship.relationshipRevision)}`, contractVersion: "tunesight.rom-layout-applicability-registry-snapshot.v1", relationships: Object.freeze([relationship]), receipts: Object.freeze([]), createdAt: manifest.authorizedAt });
  const result = Object.freeze({ authority: Object.freeze({ layout, relationship, definitionSet, definitions: parsed.definitions }), registry });
  cache.set(admission.romSoftwareIdentity, result); return result;
}

const identities: readonly DefinitionCatalogIdentity[] = Object.freeze(manifest.admitted.map((item) => Object.freeze({ romSoftwareIdentity: item.romSoftwareIdentity, family: item.family, ecuDmeFamily: null, encodings: Object.freeze([item.marker.detector === "bounded_ascii_exact" ? "ascii" as const : "hex_encoded" as const]), markerProfile: Object.freeze({ identity: item.romSoftwareIdentity, detector: item.marker.detector, requiredOffsets: Object.freeze([...item.marker.offsets]) }) })));
const entries: readonly DefinitionCatalogEntry[] = Object.freeze(manifest.admitted.map((item) => {
  const base = { catalogEntryId: `repository-bulk-view:${item.definitionSetRevision}`, sourceKind: "repository" as const, lifecycleState: "active" as const, sourceAuthorityState: "qualified" as const, applicabilityState: "published" as const, identity: identities.find((identity) => identity.romSoftwareIdentity === item.romSoftwareIdentity)!, coverageCandidate: Object.freeze({ candidateId: `bulk-view-coverage:${item.romSoftwareIdentity}:${item.definitionSetRevision}`, family: item.family, romSoftwareIdentity: item.romSoftwareIdentity, calibrationIdentity: item.romSoftwareIdentity, sourceArtifactId: item.sourceArtifactId, sourceArtifactRevision: item.sourceArtifactDigest, definitionSetRevision: item.definitionSetRevision, coverageState: "exact_qualified" as const, exactIdentityEvidence: Object.freeze([authorityRevision(item), ...item.supportingExactBinaries.map((binary) => binary.validationRevision)]), provenance: Object.freeze([authorityText(item)]), limitations: Object.freeze(["Current VIEW only; no Stock, Reference, EXPORT or FLASH authority. EDIT is derived only by the generic EDIT authority contract."]) }), quarantines: Object.freeze(item.quarantines ?? []), referenceCapability: Object.freeze({ state: "reference_unavailable" as const }) };
  return Object.freeze({ ...base, get authority() { return materialize(item).authority; }, get applicabilityRegistry() { return materialize(item).registry; }, get discoveryRegistry() { const value = materialize(item); return constructQualifiedRomLayoutDiscoveryRegistry({ authoritySnapshot: value.registry, layouts: [value.authority.layout] }); } });
}));

export const BulkViewAdmissionCatalog: DefinitionCatalog = Object.freeze({ catalogId: manifest.revision, listIdentities: () => identities, listEntries: () => entries });
export const BMW_BULK_VIEW_ADMISSION_MANIFEST = manifest;
