import { createHash } from "node:crypto";
import { RepositoryDefinitionCatalog } from "./repositoryDefinitionCatalog.ts";
import { classifyEntryEditCapabilities } from "./editAuthority.ts";

export function buildCalibrationReconstructionCensus() {
  const entries = RepositoryDefinitionCatalog.listEntries().filter((entry) => entry.lifecycleState === "active" && entry.applicabilityState === "published");
  const rows = entries.map((entry) => { const capabilities = classifyEntryEditCapabilities(entry), qualified = capabilities.filter((item) => item.state === "EDIT_QUALIFIED").length; return Object.freeze({ family: entry.identity.family, relationshipRevision: entry.authority.relationship.relationshipRevision, tables: capabilities.length, reconstructQualifiedTables: qualified, reconstructionBlockedTables: capabilities.length - qualified, roundTripBlocked: capabilities.filter((item) => item.state === "EDIT_BLOCKED_NON_INVERTIBLE").length, representationBlocked: capabilities.filter((item) => item.state === "EDIT_BLOCKED_REPRESENTATION").length, quarantineBlocked: capabilities.filter((item) => item.state === "EDIT_BLOCKED_QUARANTINE").length, relationshipReconstruction: qualified ? "RECONSTRUCT_CAPABLE" as const : "RECONSTRUCT_BLOCKED" as const, integrity: "CHECKSUM_UNKNOWN" as const, export: "EXPORT_BLOCKED_CHECKSUM_UNKNOWN" as const, flash: "FLASH_NOT_QUALIFIED" as const }); });
  const material = JSON.stringify(rows); return Object.freeze({ contractVersion: "tunesight.calibration-reconstruction-census.v1", revision: `calibration-reconstruction-census-revision:${createHash("sha256").update(material).digest("hex")}`, relationships: rows.length, tables: rows.reduce((sum, row) => sum + row.tables, 0), reconstructQualifiedTables: rows.reduce((sum, row) => sum + row.reconstructQualifiedTables, 0), reconstructionBlockedTables: rows.reduce((sum, row) => sum + row.reconstructionBlockedTables, 0), roundTripBlocked: rows.reduce((sum, row) => sum + row.roundTripBlocked, 0), representationBlocked: rows.reduce((sum, row) => sum + row.representationBlocked, 0), quarantineBlocked: rows.reduce((sum, row) => sum + row.quarantineBlocked, 0), reconstructCapableRelationships: rows.filter((row) => row.relationshipReconstruction === "RECONSTRUCT_CAPABLE").length, exportQualifiedRelationships: 0, exportBlockedChecksumUnknown: rows.length, rows: Object.freeze(rows) });
}
