import test from "node:test";
import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { resolveBinaryContainer } from "../tunes/binaryContainer.ts";
import type { XdfDefinitionRevision } from "../xdf/canonicalXdfDefinition.ts";
import type { QualifiedCalibrationDataset } from "../xdf/qualifiedCalibrationDataset.ts";
import { applyWorkingEdit, createWorkingCalibration, type WorkingCellAddress } from "./workingCalibration.ts";
import { buildRawMutationPlan, decideExportCapability, reconstructCalibrationBinary, validateRawMutationConflicts } from "./calibrationReconstruction.ts";
import { buildCalibrationReconstructionCensus } from "./calibrationReconstructionCensus.ts";

const time = (value: number) => `2026-09-15T00:00:${String(value).padStart(2, "0")}.000Z`;
function fixture(options: { width?: 8 | 16; signed?: boolean; little?: boolean; offset?: number; values?: number[]; scale?: number; inverseOffset?: number } = {}) {
  const width = options.width ?? 8, signed = options.signed ?? false, little = options.little ?? false, offset = options.offset ?? 2, values = options.values ?? [10, 20], scale = options.scale ?? 1, inverseOffset = options.inverseOffset ?? 0;
  const source = Buffer.alloc(16, 0xaa); values.forEach((value, index) => { const at = offset + index * (width / 8); if (width === 8) { if (signed) source.writeInt8(value, at); else source.writeUInt8(value, at); } else if (signed) { if (little) source.writeInt16LE(value, at); else source.writeInt16BE(value, at); } else if (little) source.writeUInt16LE(value, at); else source.writeUInt16BE(value, at); });
  const resolved = resolveBinaryContainer({ bytes: source, fileName: "subscriber.bin" }); assert.equal(resolved.status, "resolved"); if (resolved.status !== "resolved") throw new Error("fixture"); const original = resolved.engineeringBinary, digest = createHash("sha256").update(original.bytes).digest("hex"), revision = "xdf-definition-revision:test", stableId = "xdf-definition:test";
  const definition = { identity: { status: "derived", stableId, derivationBasis: "kind-primary-address-storage-layout", unresolvedReason: null }, revisionId: revision, structuralDigest: "structure", sourceArtifactDigest: "source", sourceBindingDigest: "binding", definitionKind: "table", title: "Fixture", description: null, primaryAddress: offset, addressSpace: { baseOffset: 0, subtractBaseOffset: false, regions: [] }, defaultDataLayout: { elementSizeBits: width, signed, floatingPoint: false, outputType: null }, byteOrderMetadata: { lsbFirst: little, source: null }, axes: [{ axisId: "z", indexCount: values.length, dataType: "0", dataTypeMetadata: { kind: "integer", resolution: "explicit", sourceValue: "0" }, representation: "address_backed", literalLabels: [], units: "u", embeddedData: { address: offset, addressSource: null, elementSizeBits: width, rowCount: 1, columnCount: values.length, majorStrideBits: 0, minorStrideBits: 0, typeFlags: null }, equationSource: `X*${scale}+${inverseOffset}`, equationVariables: ["X"] }], qualificationState: "structurally_interpreted" } as XdfDefinitionRevision;
  const engineering = values.map((value) => value * scale + inverseOffset), offsets = values.map((_, index) => offset + index * (width / 8));
  const rawEvidence = { widthBits: width, signed, endianness: little ? "little" : "big", exactRawOffsets: offsets, rawValues: values };
  const dataset = { datasetId: "dataset", datasetRevision: "dataset-revision", exactBinaryIdentity: { digest, byteLength: original.byteLength }, romLayoutId: "layout", relationshipRevision: "relationship", definitionSetRevisionId: "set", definitions: [{ definitionRevisionId: revision, rawEvidence, engineeringEvidence: { cellTrace: engineering.map((engineeringValue, index) => ({ rawOffset: offsets[index], rawValue: values[index], engineeringValue })) } }] } as unknown as QualifiedCalibrationDataset;
  const cells = engineering.map((currentValue, index) => ({ definitionRevision: revision, occurrence: 0, index, row: 0, column: index, currentValue, units: "u" })), working = createWorkingCalibration({ ownerScope: "owner", vehicleId: "vehicle", currentDatasetId: dataset.datasetId, currentDatasetRevision: dataset.datasetRevision, romLayoutId: dataset.romLayoutId, relationshipRevision: dataset.relationshipRevision, definitionSetRevision: dataset.definitionSetRevisionId, createdAt: time(0), definitions: [{ definitionRevision: revision, occurrence: 0, rows: 1, columns: values.length, availability: "available", capability: { state: "EDIT_QUALIFIED", revision: "edit", inverse: { scale, offset: inverseOffset, rawMinimum: signed ? -(2 ** (width - 1)) : 0, rawMaximum: signed ? 2 ** (width - 1) - 1 : 2 ** width - 1 }, engineeringMinimum: null, engineeringMaximum: null, warnings: [], blockers: [] }, cells }] });
  return { original, dataset, definition, working, source, address: (index: number): WorkingCellAddress => ({ definitionRevision: revision, occurrence: 0, index, row: 0, column: index }) };
}
type Fixture = ReturnType<typeof fixture>;
const apply = (subject: Fixture, operation: "assign" | "delta" | "percentage", operand: number, targets: WorkingCellAddress[]) => { const result = applyWorkingEdit(subject.working, { operation, operand, targets, updatedAt: time(1) }); assert.equal(result.status, "applied"); if (result.status !== "applied") throw new Error("edit blocked"); return result.calibration; };

test("single-cell plan round-trips, reconstructs a copy and preserves every unrelated byte", () => { const f = fixture(), working = apply(f, "assign", 15, [f.address(0)]), plan = buildRawMutationPlan({ original: f.original, dataset: f.dataset, working, definitions: [f.definition] }); assert.equal(plan.validation, "VALID"); assert.equal(plan.mutations[0]!.rawTargetValue, 15); const result = reconstructCalibrationBinary({ original: f.original, plan, validate: ({ bytes }) => bytes.length === 16 }); assert.equal(result.changedByteCount, 1); assert.equal(result.unexplainedChangedBytes, 0); assert.equal(result.bytes[2], 15); assert.deepEqual(f.original.bytes, f.source); assert.equal(result.unchangedByteCount, 15); });

test("region assignment, delta and percentage plans are deterministic", () => { for (const [operation, operand, expected] of [["assign", 30, [30, 30]], ["delta", 5, [15, 25]], ["percentage", 10, [11, 22]]] as const) { const f = fixture(), working = apply(f, operation, operand, [f.address(0), f.address(1)]), first = buildRawMutationPlan({ original: f.original, dataset: f.dataset, working, definitions: [f.definition] }), second = buildRawMutationPlan({ original: f.original, dataset: f.dataset, working, definitions: [f.definition] }); assert.equal(first.planRevision, second.planRevision); assert.deepEqual(first.mutations.map((item) => item.rawTargetValue), expected); } });

test("signed little-endian and unsigned big-endian boundaries reconstruct exactly", () => { const signed = fixture({ width: 16, signed: true, little: true, values: [-2] }), signedWorking = apply(signed, "assign", -32768, [signed.address(0)]), signedPlan = buildRawMutationPlan({ original: signed.original, dataset: signed.dataset, working: signedWorking, definitions: [signed.definition] }), signedResult = reconstructCalibrationBinary({ original: signed.original, plan: signedPlan, validate: () => true }); assert.deepEqual([...signedResult.bytes.subarray(2, 4)], [0, 128]); const unsigned = fixture({ width: 16, values: [2] }), unsignedWorking = apply(unsigned, "assign", 65535, [unsigned.address(0)]), unsignedPlan = buildRawMutationPlan({ original: unsigned.original, dataset: unsigned.dataset, working: unsignedWorking, definitions: [unsigned.definition] }), unsignedResult = reconstructCalibrationBinary({ original: unsigned.original, plan: unsignedPlan, validate: () => true }); assert.deepEqual([...unsignedResult.bytes.subarray(2, 4)], [255, 255]); });

test("binding, quarantine, range, source-byte and inverse failures remain closed", () => { const f = fixture({ scale: 0.5 }), validWorking = apply(f, "assign", 6, [f.address(0)]); const mismatch = buildRawMutationPlan({ original: f.original, dataset: { ...f.dataset, datasetRevision: "wrong" }, working: validWorking, definitions: [f.definition] }); assert.equal(mismatch.validation, "BLOCKED"); const tampered = resolveBinaryContainer({ bytes: Buffer.from(f.source).fill(0, 2, 3), fileName: "subscriber.bin" }); assert.equal(tampered.status, "resolved"); if (tampered.status === "resolved") assert.equal(buildRawMutationPlan({ original: tampered.engineeringBinary, dataset: f.dataset, working: validWorking, definitions: [f.definition] }).validation, "BLOCKED"); const rejected = applyWorkingEdit(f.working, { operation: "assign", operand: 6.1, targets: [f.address(0)], updatedAt: time(1) }); assert.equal(rejected.status, "blocked"); assert.throws(() => reconstructCalibrationBinary({ original: f.original, plan: mismatch, validate: () => true }), /blocked/); });

test("post-reconstruction membership validation and checksum authority are independent fail-closed gates", () => { const f = fixture(), working = apply(f, "delta", 1, [f.address(0)]), plan = buildRawMutationPlan({ original: f.original, dataset: f.dataset, working, definitions: [f.definition] }); assert.throws(() => reconstructCalibrationBinary({ original: f.original, plan, validate: () => false }), /validation failed/); assert.deepEqual(decideExportCapability(true, { state: "CHECKSUM_UNKNOWN", strategyRevision: null, findings: ["No qualified checksum strategy."] }), { reconstruct: "RECONSTRUCT_QUALIFIED", export: "EXPORT_BLOCKED_CHECKSUM_UNKNOWN", flash: "FLASH_NOT_QUALIFIED", findings: ["No qualified checksum strategy."] }); });

test("overlapping writes fail unless every canonical target byte is identical", () => { assert.deepEqual(validateRawMutationConflicts([{ binaryOffset: 4, targetBytes: [1, 2] }, { binaryOffset: 5, targetBytes: [2] }]), []); assert.deepEqual(validateRawMutationConflicts([{ binaryOffset: 4, targetBytes: [1, 2] }, { binaryOffset: 5, targetBytes: [3] }]), [{ blocker: "CONFLICTING_WRITE", finding: "Different canonical writes target the same byte." }]); });

test("BMW-wide census grants reconstruction only to EDIT-qualified Tables and grants no EXPORT", { timeout: 180_000 }, (context) => { const census = buildCalibrationReconstructionCensus(); assert.equal(census.relationships, 68); assert.equal(census.tables, 74_220); assert.equal(census.reconstructQualifiedTables, 74_165); assert.equal(census.reconstructionBlockedTables, 55); assert.equal(census.roundTripBlocked, 51); assert.equal(census.quarantineBlocked, 4); assert.equal(census.representationBlocked, 0); assert.equal(census.reconstructCapableRelationships, 68); assert.equal(census.exportQualifiedRelationships, 0); assert.equal(census.exportBlockedChecksumUnknown, 68); context.diagnostic(`BMW_RECONSTRUCTION_CENSUS ${JSON.stringify(census)}`); });
