import assert from "node:assert/strict";
import test from "node:test";
import { buildCalibrationTerminology } from "./calibrationTerminology.ts";
import { bindDefinitionKnowledge, type WorkshopKnowledgeRecord } from "./definitionKnowledgeBinding.ts";

const base = (overrides: Partial<WorkshopKnowledgeRecord> = {}): WorkshopKnowledgeRecord => ({ knowledgeId:"knowledge",knowledgeRevision:"1",lifecycle:"active",verification:"founder_verified",conflict:false,exactWorkshopInstanceIdentities:[],exactDefinitionIdentities:[],exactDefinitionRevisions:["revision"],applicability:[],aliases:[{value:"Qualified English",assertionId:"alias",assertionRevision:"1",authority:"Founder",provenance:["accepted"],limitations:[]}],engineeringSystem:null,relatedEngineeringSystems:[],calibrationRole:{value:"Control factor",assertionId:"role",assertionRevision:"1",authority:"Founder",provenance:["accepted"],limitations:[]},sourceSymbol:"SOURCE_SYMBOL",controls:[],whyItMatters:[],howToRead:[],directionalEffects:[],operatingContexts:[],engineeringConsiderations:[],axisMeanings:[],relatedCalibrations:[],telemetryRelationships:[],limitations:[],...overrides });
const field = (axisId:string,meaning:string) => ({value:{axisId,meaning},assertionId:`axis-${axisId}`,assertionRevision:"1",authority:"Founder",provenance:["accepted"],limitations:[]});
const make = (mode:"standard"|"engineer", semantic = bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:"revision"},[base({axisMeanings:[field("x","Engine Speed"),field("y","Airflow")]})]), units:string|null="%") => buildCalibrationTerminology({mode,sourceTitle:"Original German",shape:"2D",rows:2,columns:2,axes:[{id:"x",units:"RPM",values:[1000,2000]},{id:"y",units:"g/s",values:[10,20]}],semantic,outputUnits:units});

test("Standard is concise while Engineer preserves source evidence",()=>{const standard=make("standard"),engineer=make("engineer");assert.equal(standard.tableName,"Qualified English");assert.equal(standard.x?.label,"RPM");assert.equal(standard.y?.label,"Airflow");assert.equal(standard.output.label,"Control factor");assert.equal(engineer.tableName,"Original German");assert.equal(engineer.x?.label,"Source X Axis");assert.equal(engineer.x?.sourceLabel,"x");assert.equal(engineer.sourceTitle,"Original German");assert.equal(engineer.sourceSymbol,"SOURCE_SYMBOL");assert.deepEqual(standard.grid,engineer.grid)});
test("unresolved axes and output remain concise and explicit without changing structural values",()=>{const semantic=bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:"missing"},[]),result=make("standard",semantic,null);assert.equal(result.x?.label,"Not yet identified");assert.equal(result.y?.label,"Not yet identified");assert.equal(result.output.label,"Not yet identified");assert.deepEqual(result.grid.x?.values,[1000,2000])});
test("qualified concepts are platform-neutral and never inferred from title or unit",()=>{const rpm=base({axisMeanings:[field("x","Engine Speed")]}),semantic=bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:"revision"},[rpm]),build=(title:string)=>buildCalibrationTerminology({mode:"standard",sourceTitle:title,shape:"1D",rows:1,columns:2,axes:[{id:"x",units:"RPM",values:[1,2]}],semantic,outputUnits:"%"}),unknown=buildCalibrationTerminology({mode:"standard",sourceTitle:"Engine Speed Boost Target",shape:"1D",rows:1,columns:2,axes:[{id:"x",units:"RPM",values:[1,2]}],semantic:bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:"missing"},[]),outputUnits:"kW"});assert.equal(build("N54 source").x?.label,"RPM");assert.equal(build("B58 source").x?.label,"RPM");assert.equal(unknown.x?.label,"Not yet identified");assert.equal(unknown.output.label,"Not yet identified")});
test("an expressly unqualified source kW unit is retained only as Engineer source evidence",()=>{const semantic=bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:"revision"},[base({limitations:["Source kW is preserved as metadata only and is not qualified as physical power."]})]);const standard=make("standard",semantic,"kW"),engineer=make("engineer",semantic,"kW");assert.equal(standard.output.units,null);assert.equal(standard.output.qualified,false);assert.equal(engineer.output.units,"kW");assert.match(engineer.limitations[0]!,/not qualified as physical power/) });
