import { createHash } from "node:crypto";
import { RepositoryDefinitionCatalog } from "./repositoryDefinitionCatalog.ts";

export const CHECKSUM_INTEGRITY_AUTHORITY_CONTRACT = "tunesight.checksum-integrity-authority.v1" as const;
export type ChecksumCapabilityState = "CHECKSUM_NOT_REQUIRED" | "CHECKSUM_KNOWN_VALIDATION_ONLY" | "CHECKSUM_REPAIR_QUALIFIED" | "CHECKSUM_UNKNOWN" | "CHECKSUM_UNSUPPORTED" | "INTEGRITY_CONTAINER_REQUIRED";

export function discoverBmwChecksumIntegrityAuthority() {
  const entries = RepositoryDefinitionCatalog.listEntries().filter((entry) => entry.lifecycleState === "active" && entry.applicabilityState === "published");
  const relationships = entries.map((entry) => { const binaries = entry.authority.relationship.supportingExactBinaries, referenceContainer = entry.referenceCapability.state === "authoritative_reference_available" ? entry.referenceCapability.datasetInput.engineeringBinary.source.containerType : null; return Object.freeze({ relationshipRevision: entry.authority.relationship.relationshipRevision, family: entry.identity.family, ecuDmeFamily: entry.identity.ecuDmeFamily ?? "UNRESOLVED", containerTypes: Object.freeze(referenceContainer ? [referenceContainer] : ["UNRESOLVED"]), binaryByteLengths: Object.freeze([...new Set(binaries.map((item) => item.byteLength))].sort((a, b) => a - b)), checksumState: "CHECKSUM_UNKNOWN" as const, algorithm: null, checksumRegions: Object.freeze([]), integrityFields: Object.freeze([]), excludedRanges: Object.freeze([]), externalFlasherEvidence: Object.freeze([]), exportState: "EXPORT_BLOCKED_CHECKSUM_UNKNOWN" as const, flashState: "FLASH_NOT_QUALIFIED" as const, findings: Object.freeze(["No repository-controlled qualified checksum algorithm, region, integrity-field strategy, or authoritative external-flasher correction contract binds this exact relationship."]) }); });
  const groups = [...new Map(relationships.map((row) => [`${row.family}\0${row.ecuDmeFamily}`, { family: row.family, ecuDmeFamily: row.ecuDmeFamily }])).values()].map((group) => { const rows = relationships.filter((row) => row.family === group.family && row.ecuDmeFamily === group.ecuDmeFamily); return Object.freeze({ ...group, relationships: rows.length, checksumStates: Object.freeze({ CHECKSUM_UNKNOWN: rows.length }), exportQualified: 0, exportBlocked: rows.length, containerTypes: Object.freeze([...new Set(rows.flatMap((row) => row.containerTypes))].sort()), binaryByteLengths: Object.freeze([...new Set(rows.flatMap((row) => row.binaryByteLengths))].sort((a, b) => a - b)) }); }).sort((a, b) => `${a.family}:${a.ecuDmeFamily}`.localeCompare(`${b.family}:${b.ecuDmeFamily}`));
  const material = JSON.stringify(relationships); return Object.freeze({ contractVersion: CHECKSUM_INTEGRITY_AUTHORITY_CONTRACT, revision: `checksum-integrity-authority-census-revision:${createHash("sha256").update(material).digest("hex")}`, relationships: relationships.length, checksumRepairQualified: 0, checksumValidationOnly: 0, checksumNotRequired: 0, checksumUnknown: relationships.length, checksumUnsupported: 0, integrityContainerRequired: 0, exportQualified: 0, exportBlocked: relationships.length, externalFlasherAuthoritativeEvidence: 0, groups: Object.freeze(groups), rows: Object.freeze(relationships) });
}
