import { createHash } from "node:crypto";

export const CALIBRATION_COMPLETION_PROGRAMME_CONTRACT = "tunesight.calibration-completion-programme.v1" as const;
export type CalibrationCapabilityState = "foundation_available" | "partial" | "blocked" | "not_started" | "later_after_prerequisites";
export type CalibrationCompletionCapability = Readonly<{ capability: string; state: CalibrationCapabilityState; progress: "substantial" | "partial" | "early" | "blocked"; blockers: readonly string[]; dependencies: readonly string[]; physicalValidation: "not_required" | "founder_localhost" | "f30_thor_mhd" | "platform_vehicle"; nextSlice: string; completionGate: string }>;
export type CalibrationCompletionProgramme = Readonly<{ programmeId: string; programmeRevision: string; contractVersion: typeof CALIBRATION_COMPLETION_PROGRAMME_CONTRACT; objective: string; primaryProgramme: true; subscriberPriority: true; capabilities: readonly CalibrationCompletionCapability[]; v1Gate: readonly string[]; laterEnhancements: readonly string[] }>;

const capability = (capability: string, state: CalibrationCapabilityState, progress: CalibrationCompletionCapability["progress"], blockers: readonly string[], dependencies: readonly string[], physicalValidation: CalibrationCompletionCapability["physicalValidation"], nextSlice: string, completionGate: string): CalibrationCompletionCapability => Object.freeze({ capability, state, progress, blockers: Object.freeze([...blockers]), dependencies: Object.freeze([...dependencies]), physicalValidation, nextSlice, completionGate });
const CAPABILITIES = Object.freeze([
  capability("BMW Coverage", "partial", "partial", ["B58 Gen1 and mixed N55/S55/N13 identity/conflict blockers", "Most accepted relationships remain unpublished"], ["Exact authority", "Applicability decisions", "Dataset qualification"], "platform_vehicle", "Resolve B58 Gen1 and N55 evidence classes while advancing the exact 54 candidates.", "Every advertised ROM is exact-scope Workshop-ready with truthful unsupported states."),
  capability("Real Calibration Loading", "partial", "early", ["Development fixture is still the provider"], ["Binary upload", "ROM resolution", "Qualified registry", "Dataset materialization"], "founder_localhost", "Implement uploaded BIN to exact resolution to Dataset to generic Workshop before connected acquisition.", "A subscriber-owned supported BIN opens the Workshop without fixture paths or inferred authority."),
  capability("Connected DME Resolution", "foundation_available", "early", ["No physically validated F30 acquisition"], ["Read-only vehicle session", "Coverage discovery", "Qualified registry"], "f30_thor_mhd", "Bind observed DME/software identity to the six-outcome discovery contract.", "A live read-only session resolves exact, candidate, unavailable, new, conflict and invalid states truthfully."),
  capability("Calibration Explorer", "foundation_available", "substantial", ["Provider coverage", "Sparse governed Knowledge"], ["Qualified Dataset", "Knowledge binding"], "founder_localhost", "Replace fixture provider input and add engineering-system organization.", "All qualified Tables are searchable, grouped and selectable without platform branches."),
  capability("Table Information & Education", "partial", "early", ["Semantic Knowledge is mostly unavailable"], ["Exact Definition Knowledge authority", "Evidence-backed relationships"], "founder_localhost", "Deliver structural explanations now and governed semantic sections incrementally.", "Every Table shows what/why/read/axes/context/effects/related telemetry/limits, with unavailable truth where unqualified."),
  capability("Grid", "foundation_available", "substantial", ["Production editing and large-table QA"], ["Qualified Dataset", "Working Calibration"], "founder_localhost", "Harden exact formatting, selection and large-grid behavior.", "Exact values, axes and selection remain deterministic across representative scalar/1D/2D Tables."),
  capability("2D", "foundation_available", "substantial", ["Slice controls and production QA"], ["Qualified Dataset"], "founder_localhost", "Complete deterministic slice selection and comparison presentation.", "All representable 1D and 2D slices render exact values and truthful unavailable states."),
  capability("3D", "foundation_available", "substantial", ["Production interaction/accessibility QA"], ["Qualified Dataset"], "founder_localhost", "Harden orbit, focus, comparison and dense-surface behavior.", "Representative surfaces remain exact, accessible and performant."),
  capability("Working Calibration", "not_started", "early", ["No mutable overlay contract"], ["Real loading", "Immutable Current/Reference", "Validation"], "founder_localhost", "Create an immutable-revision working overlay separate from Current and Reference.", "Working revisions never mutate source Datasets and replay deterministically."),
  capability("Manual Editor", "not_started", "early", ["Working state absent"], ["Working Calibration", "Change Management", "Validation"], "founder_localhost", "Implement cell/region absolute and percentage edits, then bounded smoothing/interpolation.", "Every edit is explicit, reversible, validated and traceable."),
  capability("Change Management", "not_started", "early", ["Working state absent"], ["Working Calibration"], "founder_localhost", "Add command history, undo/redo and before/after evidence.", "Replay produces the same Working revision and preserves immutable inputs."),
  capability("Validation", "partial", "early", ["No Working Calibration validator"], ["Definition constraints", "Working Calibration"], "founder_localhost", "Compose structural, numeric, representation and reconstruction validation.", "Invalid edits fail closed with exact cells, rules and evidence."),
  capability("Suggested Calibration", "not_started", "early", ["Recommendation authority and semantic evidence sparse"], ["Knowledge", "Working Calibration", "Validation"], "founder_localhost", "Create evidence/confidence/limitations proposals requiring explicit user acceptance.", "No suggestion mutates Working state without explicit acceptance and validation."),
  capability("Analysis ↔ Calibration", "partial", "early", ["Exact cross-reference coverage incomplete"], ["Definition identities", "Analysis findings"], "founder_localhost", "Bind findings to exact Definitions/Tables and preserve source context.", "Navigation is bidirectional and exact-revision scoped."),
  capability("Telemetry Relationships", "partial", "early", ["Channel-to-Table Knowledge incomplete"], ["Qualified channels", "Knowledge binding"], "f30_thor_mhd", "Add governed channel/Definition relationships without platform UI branches.", "Only qualified relationships display; unknowns remain unavailable."),
  capability("Live Vehicle Gauges", "partial", "early", ["Physical adapter/channel qualification"], ["Read-only transport", "Channel registry"], "f30_thor_mhd", "Build configurable channel-driven gauges and qualified Actual/Target pairs.", "Qualified channels stream safely with no invented thresholds or write surface."),
  capability("Map/Tune Output", "not_started", "early", ["Reconstruction and checksum contracts absent"], ["Working Calibration", "Validation", "Checksum", "Container reconstruction"], "platform_vehicle", "Design deterministic complete-binary reconstruction and verification before export.", "Output round-trips unchanged bytes, applies only validated edits and verifies checksums."),
  capability("DME Read", "partial", "early", ["Physical acquisition protocol not validated"], ["Read-only session", "Identity acquisition", "Safe binary acquisition"], "f30_thor_mhd", "Validate identity first, then separately bounded calibration acquisition.", "Read completes or fails without mutation and preserves exact acquired bytes/evidence."),
  capability("Flashing Prerequisites", "not_started", "blocked", ["Compatibility, checksums, reconstruction, recovery and safety not qualified"], ["Map/Tune Output", "Physical DME read", "Recovery design"], "platform_vehicle", "Establish per-platform compatibility/checksum/recovery gates.", "All prerequisites pass on controlled hardware with recoverable failure testing."),
  capability("Flashing", "later_after_prerequisites", "blocked", ["Prerequisite gate incomplete", "No DME write authorization"], ["Flashing Prerequisites"], "platform_vehicle", "Begin only after explicit Founder authorization and prerequisite completion.", "Controlled qualified write, verification and recovery pass physical validation."),
]);

export function getCalibrationCompletionProgramme(): CalibrationCompletionProgramme {
  const v1Gate = Object.freeze(["Subscriber uploads a supported Calibration and reaches the generic Workshop through exact ROM/Definition resolution.", "Explorer, education, Grid, 2D and 3D are production-usable.", "Working Calibration supports traceable manual edits, undo/redo, before/after and deterministic validation.", "Analysis and qualified telemetry relationships navigate to exact Tables; configurable read-only gauges work on physically qualified channels.", "Validated Map/Tune output architecture is implemented; flashing is included only if its separately reviewed safety prerequisites pass within the programme.", "No fuzzy applicability, fabricated Knowledge, implicit recommendation mutation or DME write authority exists."]);
  const laterEnhancements = Object.freeze(["Broader platform and semantic Knowledge coverage", "Advanced automated optimization", "Additional visualization and editor operations", "Additional adapter/channel qualifications", "Flashing beyond explicitly qualified platforms"]);
  const material = { contractVersion: CALIBRATION_COMPLETION_PROGRAMME_CONTRACT, objective: "Calibration Workshop V1 substantially finished within or before two months.", primaryProgramme: true as const, subscriberPriority: true as const, capabilities: CAPABILITIES, v1Gate, laterEnhancements };
  const hash = createHash("sha256").update(JSON.stringify(material)).digest("hex");
  return Object.freeze({ programmeId: "calibration-completion-programme:v1", programmeRevision: `calibration-completion-programme-revision:${hash}`, ...material });
}
