import type { QualifiedCalibrationDataset, CalibrationDatasetDefinition } from "../xdf/qualifiedCalibrationDataset.ts";
import type { TableQuarantineRecord } from "../xdf/tableQuarantine.ts";

export type CurrentOnlyCell = Readonly<{ index: number; row: number; column: number; currentValue: number; currentRawValue: number; currentRawOffset: number; units: string | null }>;
export type CurrentOnlyDefinition = Readonly<{ key: string; title: string; definitionRevision: string; occurrence: number; shape: "scalar" | "1D" | "2D" | "unavailable"; units: string | null; availability: "current_available" | "unavailable" | "unavailable_quarantined"; rows: number; columns: number; axes: readonly Readonly<{ id: string; units: string | null; values: readonly (number | string)[] }>[]; cells: readonly CurrentOnlyCell[]; findings: readonly string[]; provenance: readonly string[]; limitations: readonly string[] }>;
export type CurrentOnlyWorkshopViewModel = Readonly<{ mode: "current_only"; source: Readonly<{ currentDatasetId: string; referenceDatasetId: null; comparisonId: null }>; states: readonly Readonly<{ id: "reference" | "current"; availability: "available" | "unavailable"; message: string }>[]; summary: Readonly<{ totalDefinitions: number; currentAvailable: number; unavailable: number; quarantined: number; changed: null; unchanged: null; changedCells: null; comparison: "unavailable_without_reference" }>; definitions: readonly CurrentOnlyDefinition[]; selectedDefinition: CurrentOnlyDefinition; capabilities: Readonly<{ readOnly: true; mutation: false; referenceComparison: false }>; provenance: readonly string[]; limitations: readonly string[] }>;
const freeze = <T>(value: T): T => { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as T; if (value && typeof value === "object") return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, freeze(item)]))) as T; return value; };
function shape(definition: CalibrationDatasetDefinition): CurrentOnlyDefinition["shape"] { if (!definition.dimensions) return "unavailable"; if (definition.dimensions.kind === "array_1d") return "1D"; if (definition.dimensions.kind === "table_2d") return "2D"; return "scalar"; }
export function buildCurrentOnlyWorkshopViewModel(input: Readonly<{ current: QualifiedCalibrationDataset; quarantines: readonly TableQuarantineRecord[]; selectedKey?: string | null }>): CurrentOnlyWorkshopViewModel {
  const occurrences = new Map<string, number>();
  const definitions = input.current.definitions.map((definition) => { const occurrence = occurrences.get(definition.definitionRevisionId) ?? 0; occurrences.set(definition.definitionRevisionId, occurrence + 1); const quarantine = input.quarantines.find((item) => item.affectedBinary.digest === input.current.exactBinaryIdentity.digest && item.occurrence.definitionRevisionId === definition.definitionRevisionId && item.occurrence.occurrence === occurrence); const available = definition.engineeringEvidence !== null; const cells = available ? definition.engineeringEvidence.engineeringValues.map((currentValue, index) => { const trace = definition.engineeringEvidence!.cellTrace[index]!; return { index, row: trace.row, column: trace.column, currentValue, currentRawValue: trace.rawValue, currentRawOffset: trace.rawOffset, units: definition.units }; }) : []; return freeze({ key: `current-only:${input.current.datasetRevision}:${definition.definitionRevisionId}:${occurrence}`, title: definition.title?.trim() || "Untitled Definition", definitionRevision: definition.definitionRevisionId, occurrence, shape: shape(definition), units: definition.units, availability: quarantine ? "unavailable_quarantined" as const : available ? "current_available" as const : "unavailable" as const, rows: definition.dimensions?.rows ?? 0, columns: definition.dimensions?.columns ?? 0, axes: available ? definition.engineeringEvidence.axes.map((axis) => ({ id: axis.axisId, units: axis.units, values: axis.outcome === "static_literal" ? axis.literalValues : axis.engineeringValues })) : [], cells, findings: quarantine ? [quarantine.failureEvidence.finding, ...definition.findings] : definition.findings, provenance: quarantine ? [...definition.provenance, ...quarantine.provenance] : definition.provenance, limitations: quarantine ? quarantine.limitations : [] }); });
  const selectedDefinition = definitions.find((item) => item.key === input.selectedKey) ?? definitions.find((item) => item.availability === "current_available") ?? definitions[0]; if (!selectedDefinition) throw new Error("Current-only Workshop requires at least one Definition."); const quarantined = definitions.filter((item) => item.availability === "unavailable_quarantined").length, unavailable = definitions.filter((item) => item.availability !== "current_available").length;
  return freeze({ mode: "current_only", source: { currentDatasetId: input.current.datasetId, referenceDatasetId: null, comparisonId: null }, states: [{ id: "reference", availability: "unavailable", message: "Authoritative Reference is not established; comparison is unavailable." }, { id: "current", availability: "available", message: "Qualified subscriber Current Dataset" }], summary: { totalDefinitions: definitions.length, currentAvailable: definitions.length - unavailable, unavailable, quarantined, changed: null, unchanged: null, changedCells: null, comparison: "unavailable_without_reference" }, definitions, selectedDefinition, capabilities: { readOnly: true, mutation: false, referenceComparison: false }, provenance: input.current.provenance, limitations: [...new Set([...input.current.limitations, "No Reference values, deltas or comparison classifications are available."])] });
}
export function filterCurrentOnlyDefinitions(definitions: readonly CurrentOnlyDefinition[], search: string, availability: "all" | CurrentOnlyDefinition["availability"] = "all") { const query = search.trim().toLocaleLowerCase(); return definitions.filter((item) => (!query || [item.title, item.definitionRevision, item.units].some((value) => value?.toLocaleLowerCase().includes(query))) && (availability === "all" || item.availability === availability)); }
export function currentOnlyVisualization(definition: CurrentOnlyDefinition) { const grid = definition.availability === "current_available" && definition.cells.length > 0, twoDimensional = grid && (definition.shape === "1D" || definition.shape === "2D"), threeDimensional = grid && definition.shape === "2D"; return freeze({ capabilities: { grid, twoDimensional, threeDimensional }, cells: definition.cells, axes: definition.axes, referenceSeries: null, currentSeries: definition.cells.map((cell) => ({ index: cell.index, row: cell.row, column: cell.column, value: cell.currentValue })), changedCells: null }); }
