import assert from "node:assert/strict";
import test from "node:test";
import { bindDefinitionKnowledge, searchDefinitionsByIntent, type QualifiedSemanticField, type WorkshopKnowledgeRecord } from "./definitionKnowledgeBinding.ts";

const field = <T>(value: T, id="assertion"): QualifiedSemanticField<T> => ({ value, assertionId:id, assertionRevision:"assertion-revision-1", authority:"Founder-authorised Knowledge", provenance:["evidence:1"], limitations:[] });
const record = (overrides: Partial<WorkshopKnowledgeRecord>={}): WorkshopKnowledgeRecord => ({ knowledgeId:"knowledge:boost-target",knowledgeRevision:"knowledge-revision-1",lifecycle:"active",verification:"verified",conflict:false,exactDefinitionIdentities:["definition:1"],exactDefinitionRevisions:["revision:1"],applicability:["definition:1"],aliases:[field("boost target","alias")],engineeringSystem:field("Boost & Air Control","system"),controls:[field("Qualified control meaning","controls")],whyItMatters:[field("Qualified engineering intent","intent")],howToRead:[field("Qualified reading guidance","reading")],axisMeanings:[field({axisId:"x",meaning:"Qualified axis meaning"},"axis")],relatedCalibrations:[field({targetKnowledgeId:"knowledge:limiter",relationship:"limits"},"related")],telemetryRelationships:[field({channelId:"boostActual",meaning:"Qualified observation relationship"},"telemetry")],limitations:[],...overrides});
const definition={definitionIdentity:"definition:1",definitionRevision:"revision:1"};

test("exact binding preserves Knowledge revision, assertions, provenance and governed relationships",()=>{const result=bindDefinitionKnowledge(definition,[record()]);assert.equal(result.outcome,"exact");assert.equal(result.knowledgeRevision,"knowledge-revision-1");assert.equal(result.engineeringSystem?.value,"Boost & Air Control");assert.equal(result.axisMeanings[0]?.value.axisId,"x");assert.equal(result.relatedCalibrations.length,1);assert.equal(result.telemetryRelationships.length,1);assert.deepEqual(result.provenance,["evidence:1"])});
test("candidate/context-only Knowledge remains partial",()=>{assert.equal(bindDefinitionKnowledge(definition,[record({exactDefinitionIdentities:[],exactDefinitionRevisions:[],verification:"candidate"})]).outcome,"partial")});
test("multiple candidates, conflict and absence remain explicit",()=>{assert.equal(bindDefinitionKnowledge(definition,[record(),record({knowledgeId:"knowledge:other"})]).outcome,"ambiguous");assert.equal(bindDefinitionKnowledge(definition,[record({conflict:true})]).outcome,"conflict");assert.equal(bindDefinitionKnowledge(definition,[]).outcome,"unavailable")});
test("title and ungoverned text cannot create authority",()=>{const unrelated=record({exactDefinitionIdentities:[],exactDefinitionRevisions:[],applicability:[],aliases:[field("Definition title")]});assert.equal(bindDefinitionKnowledge(definition,[unrelated]).outcome,"unavailable")});
test("intent search uses exact Knowledge fields only and literal search remains a separate Workshop concern",()=>{const exact=bindDefinitionKnowledge(definition,[record()]),partial=bindDefinitionKnowledge(definition,[record({exactDefinitionIdentities:[],exactDefinitionRevisions:[],verification:"candidate"})]);const definitions=[{id:"exact",semantic:exact},{id:"partial",semantic:partial}];assert.deepEqual(searchDefinitionsByIntent(definitions,"boost target").map(item=>item.id),["exact"]);assert.deepEqual(searchDefinitionsByIntent(definitions,"Definition title"),[])});
test("generic binding contract contains no BMW-family branch or recommendation field",()=>{const material=JSON.stringify(record());assert.doesNotMatch(material,/N54|N55|N13|S55|B58|S58|S63/);assert.doesNotMatch(material,/recommend/i)});
