import test from "node:test";
import assert from "node:assert/strict";
import { buildCalibrationEditCensus } from "./editAuthorityCensus.ts";
import { classifyCalibrationEditCapability, classifyEntryEditCapabilities, toWorkingEditCapability } from "./editAuthority.ts";
import { RepositoryDefinitionCatalog } from "./repositoryDefinitionCatalog.ts";
import { applyWorkingEdit, createWorkingCalibration } from "./workingCalibration.ts";

const entries = () => RepositoryDefinitionCatalog.listEntries().filter((entry) => entry.lifecycleState === "active" && entry.applicabilityState === "published");
const classify = (overrides: Partial<Parameters<typeof classifyCalibrationEditCapability>[0]> = {}) => { const entry = entries()[0]!, definition = entry.authority.definitions.find((item) => item.identity.status === "derived")!; return classifyCalibrationEditCapability({ definition, occurrence: 0, relationshipRevision: entry.authority.relationship.relationshipRevision, definitionSetRevision: entry.authority.definitionSet.revisionId, definitionSetDefinitionRevisions: entry.authority.definitionSet.definitionRevisionIds, ...overrides }); };

test("generic EDIT authority classifies every VIEW Table without granting EXPORT or FLASH", { timeout: 180_000 }, (context) => { const census = buildCalibrationEditCensus(), sum = Object.values(census.totals).reduce((total, value) => total + value, 0); assert.equal(census.relationships, 65); assert.equal(census.tables, 70_738); assert.equal(sum, census.tables); assert.equal(census.totals.EDIT_QUALIFIED, 70_686); assert.equal(census.totals.EDIT_BLOCKED_QUARANTINE, 1); assert.equal(census.rows.length, 65); for (const entry of entries()) for (const capability of classifyEntryEditCapabilities(entry)) { assert.equal(capability.exportQualified, false); assert.equal(capability.flashQualified, false); } context.diagnostic(`BMW_BULK_EDIT_CENSUS ${JSON.stringify({ revision: census.revision, relationships: census.relationships, tables: census.tables, totals: census.totals })}`); });

test("non-invertible, representation, quarantine, dependency and constraint gates are distinct", () => {
  const base = entries()[0]!, definition = base.authority.definitions[0]!, b58 = entries().find((item) => item.quarantines.length > 0)!, quarantinedDefinition = b58.authority.definitions.find((item) => item.revisionId === b58.quarantines[0]!.occurrence.definitionRevisionId)!;
  assert.equal(classify({ definition: { ...definition, axes: definition.axes.map((axis) => axis.axisId.toLowerCase() === "z" ? { ...axis, equationSource: "X*X" } : axis) } }).state, "EDIT_BLOCKED_NON_INVERTIBLE");
  assert.equal(classify({ definition: { ...definition, identity: { ...definition.identity, status: "conflicting" } } }).state, "EDIT_BLOCKED_REPRESENTATION");
  assert.equal(classifyCalibrationEditCapability({ definition: quarantinedDefinition, occurrence: b58.quarantines[0]!.occurrence.occurrence, relationshipRevision: b58.authority.relationship.relationshipRevision, definitionSetRevision: b58.authority.definitionSet.revisionId, definitionSetDefinitionRevisions: b58.authority.definitionSet.definitionRevisionIds, quarantine: b58.quarantines[0] }).state, "EDIT_BLOCKED_QUARANTINE");
  assert.equal(classify({ dependencyBlockers: ["Overlapping write dependency requires review."] }).state, "EDIT_BLOCKED_DEPENDENCY");
  assert.equal(classify({ constraintReviewRequired: true }).state, "EDIT_BLOCKED_CONSTRAINT");
});

test("N54 and B58 qualified capabilities activate the same Working mutation path", { timeout: 180_000 }, () => { for (const family of ["N54", "B58gen1"]) { const entry = entries().find((item) => item.identity.family === family)!, capabilities = classifyEntryEditCapabilities(entry), index = capabilities.findIndex((item) => item.state === "EDIT_QUALIFIED"), capability = capabilities[index]!, definition = entry.authority.definitions[index]!, inverse = capability.inverse!; const currentValue = inverse.offset + inverse.scale * Math.max(inverse.rawMinimum, Math.min(inverse.rawMaximum, 10)), address = { definitionRevision: definition.revisionId, occurrence: capability.occurrence, index: 0, row: 0, column: 0 }, working = createWorkingCalibration({ ownerScope: "owner", vehicleId: `vehicle-${family}`, currentDatasetId: `current-${family}`, currentDatasetRevision: "current-revision", romLayoutId: entry.authority.layout.layoutId, relationshipRevision: entry.authority.relationship.relationshipRevision, definitionSetRevision: entry.authority.definitionSet.revisionId, createdAt: "2026-09-15T00:00:00.000Z", definitions: [{ definitionRevision: definition.revisionId, occurrence: capability.occurrence, rows: 1, columns: 1, availability: "available", capability: toWorkingEditCapability(capability), cells: [{ ...address, currentValue, units: definition.axes.at(-1)?.units ?? null }] }] }), result = applyWorkingEdit(working, { operation: "delta", operand: inverse.scale, targets: [address], updatedAt: "2026-09-15T00:00:01.000Z" }); assert.equal(result.status, "applied", family); if (result.status === "applied") { assert.equal(result.calibration.validation, "WARNING"); assert.equal(result.calibration.state, "dirty"); } } });

test("unpublished relationships cannot inherit EDIT capability", () => { const entry = entries()[0]!, definition = entry.authority.definitions[0]!, capability = classifyCalibrationEditCapability({ definition, occurrence: 0, relationshipRevision: "", definitionSetRevision: entry.authority.definitionSet.revisionId, definitionSetDefinitionRevisions: entry.authority.definitionSet.definitionRevisionIds }); assert.equal(capability.state, "EDIT_REVIEW_REQUIRED"); assert.equal(capability.validation, "BLOCKED"); });
