import { createHash } from "node:crypto";
import type { XdfDefinitionRevision } from "../xdf/canonicalXdfDefinition.ts";
import { deriveReversibleAffineEquation, parseXdfEquation } from "../xdf/engineeringValueConversion.ts";
import type { TableQuarantineRecord } from "../xdf/tableQuarantine.ts";
import type { DefinitionCatalogEntry } from "./masterCalibrationResolver.ts";
import type { WorkingEditCapability } from "./workingCalibration.ts";

export const CALIBRATION_EDIT_AUTHORITY_CONTRACT = "tunesight.calibration-edit-authority.v1" as const;
export type EditCapabilityState = "EDIT_QUALIFIED" | "EDIT_BLOCKED_NON_INVERTIBLE" | "EDIT_BLOCKED_REPRESENTATION" | "EDIT_BLOCKED_QUARANTINE" | "EDIT_BLOCKED_DEPENDENCY" | "EDIT_BLOCKED_CONSTRAINT" | "EDIT_REVIEW_REQUIRED";
export type CalibrationEditCapability = Readonly<{ contractVersion: typeof CALIBRATION_EDIT_AUTHORITY_CONTRACT; capabilityId: string; capabilityRevision: string; state: EditCapabilityState; relationshipRevision: string; definitionSetRevision: string; definitionRevision: string; occurrence: number; inverse: WorkingEditCapability["inverse"]; engineeringMinimum: number | null; engineeringMaximum: number | null; validation: "VALID" | "WARNING" | "BLOCKED"; findings: readonly string[]; exportQualified: false; flashQualified: false }>;
const canonical = (value: unknown): string => { if (value === null || typeof value === "boolean" || typeof value === "string" || typeof value === "number") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; const record = value as Record<string, unknown>; return `{${Object.keys(record).sort().map((key) => `${JSON.stringify(key)}:${canonical(record[key])}`).join(",")}}`; };
const hash = (domain: string, value: unknown) => createHash("sha256").update(domain).update(Buffer.from([0])).update(canonical(value)).digest("hex");
const freeze = <T>(value: T): T => { if (Array.isArray(value)) return Object.freeze(value.map(freeze)) as T; if (value && typeof value === "object") return Object.freeze(Object.fromEntries(Object.entries(value).map(([key, item]) => [key, freeze(item)]))) as T; return value; };

export function classifyCalibrationEditCapability(input: Readonly<{ definition: XdfDefinitionRevision; occurrence: number; relationshipRevision: string; definitionSetRevision: string; definitionSetDefinitionRevisions: readonly string[]; quarantine?: TableQuarantineRecord | null; dependencyBlockers?: readonly string[]; engineeringMinimum?: number | null; engineeringMaximum?: number | null; constraintReviewRequired?: boolean }>): CalibrationEditCapability {
  const findings: string[] = [], axis = input.definition.axes.find((item) => item.axisId.toLowerCase() === "z") ?? input.definition.axes.at(-1); let state: EditCapabilityState = "EDIT_QUALIFIED", inverse: WorkingEditCapability["inverse"] = null;
  if (!input.relationshipRevision.trim() || !input.definitionSetRevision.trim() || !input.definitionSetDefinitionRevisions.includes(input.definition.revisionId)) { state = "EDIT_REVIEW_REQUIRED"; findings.push("Exact active relationship and Definition Set binding are required."); }
  else if (input.quarantine) { state = "EDIT_BLOCKED_QUARANTINE"; findings.push("Exact Table quarantine prohibits mutation."); }
  else if (input.definition.identity.status !== "derived") { state = "EDIT_BLOCKED_REPRESENTATION"; findings.push("Definition representation is unresolved or conflicting."); }
  else if (input.dependencyBlockers?.length) { state = "EDIT_BLOCKED_DEPENDENCY"; findings.push(...input.dependencyBlockers); }
  else if (!axis?.equationSource) { state = "EDIT_BLOCKED_NON_INVERTIBLE"; findings.push("Value conversion equation is absent."); }
  else {
    const equation = parseXdfEquation(axis.equationSource);
    if (equation.outcome === "unsupported_expression" || equation.outcome === "malformed_equation") { state = "EDIT_BLOCKED_NON_INVERTIBLE"; findings.push(equation.finding); }
    else { const affine = deriveReversibleAffineEquation(equation), bits = axis.embeddedData.elementSizeBits ?? input.definition.defaultDataLayout.elementSizeBits, signed = input.definition.defaultDataLayout.signed; if (affine.outcome !== "reversible_affine") { state = "EDIT_BLOCKED_NON_INVERTIBLE"; findings.push(affine.finding); } else if ((bits !== 8 && bits !== 16 && bits !== 32) || signed === null || input.definition.defaultDataLayout.floatingPoint !== false) { state = "EDIT_BLOCKED_REPRESENTATION"; findings.push("Exact integer width, signedness, and non-floating representation are required."); } else inverse = freeze({ scale: affine.scale, offset: affine.offset, rawMinimum: signed ? -(2 ** (bits - 1)) : 0, rawMaximum: signed ? 2 ** (bits - 1) - 1 : 2 ** bits - 1 }); }
  }
  if (state === "EDIT_QUALIFIED" && input.constraintReviewRequired) { state = "EDIT_BLOCKED_CONSTRAINT"; findings.push("A disclosed constraint requires qualification before editing."); }
  const warning = state === "EDIT_QUALIFIED" && input.engineeringMinimum == null && input.engineeringMaximum == null; if (warning) findings.push("Technically representable edit; no qualified engineering safety envelope is asserted.");
  const identity = { relationshipRevision: input.relationshipRevision, definitionSetRevision: input.definitionSetRevision, definitionRevision: input.definition.revisionId, occurrence: input.occurrence }, material = { ...identity, state, inverse, engineeringMinimum: input.engineeringMinimum ?? null, engineeringMaximum: input.engineeringMaximum ?? null, findings: [...findings].sort(), contractVersion: CALIBRATION_EDIT_AUTHORITY_CONTRACT, exportQualified: false, flashQualified: false };
  return freeze({ contractVersion: CALIBRATION_EDIT_AUTHORITY_CONTRACT, capabilityId: `calibration-edit-capability:${hash("tunesight.calibration-edit-capability-identity.v1", identity)}`, capabilityRevision: `calibration-edit-capability-revision:${hash("tunesight.calibration-edit-capability-revision.v1", material)}`, ...identity, state, inverse, engineeringMinimum: input.engineeringMinimum ?? null, engineeringMaximum: input.engineeringMaximum ?? null, validation: state === "EDIT_QUALIFIED" ? warning ? "WARNING" : "VALID" : "BLOCKED", findings, exportQualified: false, flashQualified: false });
}
export function classifyEntryEditCapabilities(entry: DefinitionCatalogEntry): readonly CalibrationEditCapability[] {
  const occurrences = new Map<string, number>(); return freeze(entry.authority.definitions.map((definition) => { const occurrence = occurrences.get(definition.revisionId) ?? 0; occurrences.set(definition.revisionId, occurrence + 1); const quarantine = entry.quarantines.find((item) => item.occurrence.definitionRevisionId === definition.revisionId && item.occurrence.occurrence === occurrence); return classifyCalibrationEditCapability({ definition, occurrence, relationshipRevision: entry.authority.relationship.relationshipRevision, definitionSetRevision: entry.authority.definitionSet.revisionId, definitionSetDefinitionRevisions: entry.authority.definitionSet.definitionRevisionIds, quarantine }); }));
}
export function toWorkingEditCapability(capability: CalibrationEditCapability): WorkingEditCapability { return freeze({ state: capability.state === "EDIT_QUALIFIED" ? "EDIT_QUALIFIED" : "VIEW_ONLY", revision: capability.state === "EDIT_QUALIFIED" ? capability.capabilityRevision : null, inverse: capability.inverse, engineeringMinimum: capability.engineeringMinimum, engineeringMaximum: capability.engineeringMaximum, warnings: capability.validation === "WARNING" ? capability.findings : [], blockers: capability.validation === "BLOCKED" ? capability.findings : [] }); }
