import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { createSourceBinaryLeaseRecord, resolveSourceBinaryLease, SOURCE_BINARY_RECONSTRUCTION_TTL_MS, verifyExactSourceBinary, type SourceBinaryBinding } from "./sourceBinaryReconstructionLease.ts";
import { discoverBmwChecksumIntegrityAuthority } from "./checksumIntegrityAuthority.ts";
import { decideExportCapability, deriveExportActionState } from "./calibrationReconstruction.ts";

const bytes = Uint8Array.from([1, 2, 3, 4]), digest = "9f64a747e1b97f131fabb6b447296c9b6f0201e79fb3c5356e6c77e89b6a806a";
const binding: SourceBinaryBinding = Object.freeze({ currentCalibrationId: "engineering-binary:test", currentCalibrationRevision: "current-revision", currentDatasetId: "dataset", currentDatasetRevision: "dataset-revision", romLayoutId: "layout", relationshipRevision: "relationship", exactBinaryDigest: digest, byteLength: 4, containerType: "bin" });
const record = () => createSourceBinaryLeaseRecord({ ownerId: "owner-a", vehicleId: "vehicle-a", objectId: "object_id", leaseId: "lease_id", binding, createdAt: "2026-09-15T00:00:00.000Z", ttlMs: 1000 });

test("source lease is exactly owner, vehicle, Current Calibration, Dataset, layout and digest bound", () => { const lease = record(), resolved = resolveSourceBinaryLease(lease, { ownerId: "owner-a", vehicleId: "vehicle-a", expected: binding, now: Date.parse("2026-09-15T00:00:00.500Z") }); assert.equal(resolved.status, "resolved"); assert.equal(resolveSourceBinaryLease(lease, { ownerId: "owner-b", vehicleId: "vehicle-a", expected: binding, now: 0 }).status, "unauthorized"); assert.equal(resolveSourceBinaryLease(lease, { ownerId: "owner-a", vehicleId: "vehicle-b", expected: binding, now: 0 }).status, "unauthorized"); assert.equal(resolveSourceBinaryLease(lease, { ownerId: "owner-a", vehicleId: "vehicle-a", expected: { ...binding, currentDatasetRevision: "different" }, now: 0 }).status, "binding_mismatch"); });

test("lease expiry leaves Working history independent but blocks source resolution", () => { assert.equal(SOURCE_BINARY_RECONSTRUCTION_TTL_MS, 7 * 24 * 60 * 60 * 1000); assert.equal(resolveSourceBinaryLease(record(), { ownerId: "owner-a", vehicleId: "vehicle-a", expected: binding, now: Date.parse("2026-09-15T00:00:01.000Z") }).status, "expired"); });

test("exact re-upload can rebind while a different binary cannot inherit mutations", () => { assert.equal(verifyExactSourceBinary(bytes, binding), true); assert.equal(verifyExactSourceBinary(Uint8Array.from([1, 2, 3, 5]), binding), false); assert.equal(verifyExactSourceBinary(bytes, { ...binding, currentDatasetId: "other" }), true, "bytes establish identity only; full Dataset binding is independently resolved by the lease"); });

test("server storage architecture is private, opaque, cross-invocation durable and replacement-cleaning", () => { const storage = fs.readFileSync(new URL("./sourceBinaryReconstructionStorage.ts", import.meta.url), "utf8"), route = fs.readFileSync(new URL("../../app/api/calibration-workshop/upload/route.ts", import.meta.url), "utf8"); assert.match(storage, /import "server-only"/); assert.match(storage, /createTrustedServerClient/); assert.match(storage, /randomBytes\(24\)/); assert.match(storage, /source-active/); assert.match(storage, /removeLease\(previous\)/); assert.match(storage, /cleanupExpiredSourceBinaryLeases/); assert.doesNotMatch(storage, /getPublicUrl|createSignedUrl|ownerId\}\/|vehicleId\}\//); assert.doesNotMatch(storage, /console\.|logger|analytics/); assert.match(route, /persistSourceBinaryReconstructionLease/); assert.match(route, /revokeSourceBinaryReconstructionLease/); assert.match(route, /finally[\s\S]*upload\.cleanup/); });

test("BMW-wide checksum discovery remains evidence-driven and EXPORT/FLASH fail closed", { timeout: 180_000 }, (context) => { const census = discoverBmwChecksumIntegrityAuthority(); assert.equal(census.relationships, 68); assert.equal(census.checksumUnknown, 68); assert.equal(census.exportQualified, 0); assert.equal(census.exportBlocked, 68); assert.equal(census.externalFlasherAuthoritativeEvidence, 0); assert.ok(census.rows.every((row) => row.checksumState === "CHECKSUM_UNKNOWN" && row.algorithm === null && row.exportState === "EXPORT_BLOCKED_CHECKSUM_UNKNOWN" && row.flashState === "FLASH_NOT_QUALIFIED")); context.diagnostic(`BMW_CHECKSUM_AUTHORITY_CENSUS ${JSON.stringify({ revision: census.revision, groups: census.groups })}`); });

test("generic action state never enables Export without source and checksum authority", () => { const blocked = decideExportCapability(true, { state: "CHECKSUM_UNKNOWN", strategyRevision: null, findings: ["unknown"] }); assert.deepEqual(deriveExportActionState({ source: "active", capability: blocked }), { buildEnabled: true, exportEnabled: false, message: "Export unavailable — checksum qualification required." }); assert.equal(deriveExportActionState({ source: "expired", capability: blocked }).buildEnabled, false); });
