import { createHash } from "node:crypto";
import { collectInternalIdentityObservations } from "../xdf/applicabilityEvidenceProposal.ts";
import { identifyEngineeringBinary } from "../xdf/definitionRomApplicability.ts";
import { resolveDefinitionCoverage, type DefinitionCoverageCandidate, type DefinitionCoverageResolution } from "../xdf/definitionCoverageDiscovery.ts";
import { defineEcuIdentityObservation } from "../vehicle-interface/nativeVehicleData.ts";
import { compareQualifiedCalibrationDatasets, constructQualifiedCalibrationDatasetComparisonRequest, type QualifiedCalibrationComparisonEvidence } from "../xdf/qualifiedCalibrationComparison.ts";
import { constructQualifiedCalibrationDatasetRequest, materializeQualifiedCalibrationDataset, type QualifiedCalibrationDataset } from "../xdf/qualifiedCalibrationDataset.ts";
import { N54_CURRENT_ROM_LAYOUT_REGISTRY } from "../xdf/n54GovernedApplicabilityAdmission.ts";
import { resolveBinaryContainer } from "../tunes/binaryContainer.ts";
import { buildWorkshopViewModel, type WorkshopViewModel } from "./viewModel.ts";
import { constructN54PreviewFixtureDescriptor, constructWorkshopDiscoveryRegistry, type N54PreviewRom } from "./developmentFixtureProvider.ts";
import type { RomLayoutMembershipAuthority } from "../xdf/romLayoutDiscovery.ts";

export const SUBSCRIBER_CALIBRATION_MAX_UPLOAD_BYTES = 32 * 1024 * 1024;
const N54 = ["I8A0S", "IJE0S", "IKM0S", "INA0S"] as const;
const B58_GEN1 = ["00003076501103", "00003076501D02", "000030765A3C06", "000030765A5005", "00003081501102", "00003081501D04", "00007972000705"] as const;
const VOCABULARY = [...N54, ...B58_GEN1] as const;
export type SubscriberCalibrationFailure = Readonly<{ status: "coverage_unavailable" | "invalid_upload"; title: string; message: string; identity: string | null; digest: string | null; container: string | null; byteLength: number | null; coverage: DefinitionCoverageResolution | null; timings: Readonly<Record<string, number>> }>;
type SubscriberWorkshopMaterial = Readonly<{ reference: QualifiedCalibrationDataset; current: QualifiedCalibrationDataset; comparison: QualifiedCalibrationComparisonEvidence }>;
export type SubscriberCalibrationSuccess = Readonly<{ status: "workshop_ready"; workshop: WorkshopViewModel; material: SubscriberWorkshopMaterial; identity: N54PreviewRom; digest: string; container: string; byteLength: number; coverage: DefinitionCoverageResolution; timings: Readonly<Record<string, number>> }>;
export type SubscriberCalibrationResult = SubscriberCalibrationFailure | SubscriberCalibrationSuccess;

function candidates(): readonly DefinitionCoverageCandidate[] { return N54.map((identity) => { const descriptor = constructN54PreviewFixtureDescriptor(identity); return Object.freeze({ candidateId: `n54-qualified-coverage:${identity}`, family: "N54", romSoftwareIdentity: identity, calibrationIdentity: identity, sourceArtifactId: descriptor.source.set.sourceArtifactId, sourceArtifactRevision: descriptor.source.set.sourceArtifactDigest, definitionSetRevision: descriptor.source.set.revisionId, coverageState: "exact_qualified", exactIdentityEvidence: Object.freeze([descriptor.relationship.relationshipRevision]), provenance: Object.freeze(["Published exact current N54 governed relationship"]), limitations: Object.freeze(["Applicability is limited to the exact published ROM/software identity."]) }); }); }
const sha = (bytes: Uint8Array) => createHash("sha256").update(bytes).digest("hex");

export async function loadSubscriberCalibration(input: Readonly<{ bytes: Uint8Array; fileName: string; mimeType: string | null; selectedDefinition?: string | null; observedAt?: string }>): Promise<SubscriberCalibrationResult> {
  const timings: Record<string, number> = {}; let mark = performance.now(); const record = (name: string) => { const now = performance.now(); timings[name] = Math.round(now - mark); mark = now; };
  if (!input.bytes.byteLength || input.bytes.byteLength > SUBSCRIBER_CALIBRATION_MAX_UPLOAD_BYTES) return Object.freeze({ status: "invalid_upload", title: "Calibration file invalid", message: `Calibration payload must be between 1 byte and ${SUBSCRIBER_CALIBRATION_MAX_UPLOAD_BYTES} bytes.`, identity: null, digest: null, container: null, byteLength: input.bytes.byteLength, coverage: null, timings: Object.freeze(timings) });
  const resolved = resolveBinaryContainer({ bytes: input.bytes, fileName: input.fileName, mimeType: input.mimeType }); record("containerResolutionMs");
  if (resolved.status !== "resolved") return Object.freeze({ status: "invalid_upload", title: "Calibration file unsupported", message: resolved.message, identity: null, digest: null, container: resolved.containerType, byteLength: input.bytes.byteLength, coverage: null, timings: Object.freeze(timings) });
  const binary = resolved.engineeringBinary, digest = sha(binary.bytes), observations = collectInternalIdentityObservations({ binaryBytes: binary.bytes, credibleIdentifiers: VOCABULARY.map((identifier) => ({ identifier, kind: "calibration_identifier" as const, confidence: "known_identity" as const, reason: "Governed subscriber calibration identity vocabulary", encodings: N54.includes(identifier as N54PreviewRom) ? ["ascii" as const] : ["ascii" as const, "hex_encoded" as const] })) }); record("romIdentityMs");
  const identities = [...new Set(observations.map((item) => item.normalizedForm))], identity = identities[0] ?? null, family = identity && (N54 as readonly string[]).includes(identity) ? "N54" : identity && (B58_GEN1 as readonly string[]).includes(identity) ? "B58gen1" : null;
  const observedAt = input.observedAt ?? new Date().toISOString(), observation = defineEcuIdentityObservation({ sessionId: `subscriber-upload:${digest}`, endpointId: "subscriber-file", protocol: "file-upload", observedDmeFamily: family, softwareIdentity: identity, calibrationIdentity: identity, vin: null, observedAt, capabilityObservations: observations.map((item) => item.observationId), qualification: "observed_unqualified", provenance: "Subscriber-supplied calibration file; exact bytes were not persisted." });
  const coverage = resolveDefinitionCoverage({ connectedRom: { observation, trust: "qualified_supplied_evidence", ecuFamily: family === "N54" ? identity === "I8A0S" ? "MSD80" : "MSD81" : null, binary: { digest, byteLength: binary.byteLength, container: binary.source.containerType, markers: observations.map((item) => ({ marker: item.normalizedForm, offsets: item.offsets })) }, provenance: ["Bounded server-side upload resolution"], limitations: ["Subscriber-supplied identity Evidence does not create applicability authority."] }, recognizedRomIdentities: VOCABULARY, candidates: candidates(), conflicts: identities.length > 1 ? ["Multiple governed ROM/software identities were observed in one binary."] : [] }); record("definitionCoverageMs");
  if (coverage.outcome !== "EXACT_DEFINITION_COVERAGE" || !identity || !(N54 as readonly string[]).includes(identity)) return Object.freeze({ status: "coverage_unavailable", title: coverage.outcome === "CONFLICT" ? "Calibration coverage conflict" : "Calibration coverage unavailable", message: coverage.workshopMessage, identity, digest, container: binary.source.containerType, byteLength: binary.byteLength, coverage, timings: Object.freeze(timings) });
  const descriptor = constructN54PreviewFixtureDescriptor(identity as N54PreviewRom), cohort = N54.map(constructN54PreviewFixtureDescriptor), discoveryRegistry = constructWorkshopDiscoveryRegistry(cohort.map((item) => item.layout)), authority: RomLayoutMembershipAuthority = { layout: descriptor.layout, relationship: descriptor.relationship, definitionSet: descriptor.source.set, definitions: descriptor.source.definitions };
  const binaryIdentity = identifyEngineeringBinary({ engineeringBinary: binary, romFamily: "N54", softwareIdentity: identity, internalRomIdentifiers: observations.map((item) => item.normalizedForm), identityProvenance: [observation.observationId] });
  const currentResult = materializeQualifiedCalibrationDataset(constructQualifiedCalibrationDatasetRequest({ engineeringBinary: binary, binaryIdentity, observations, discoveryRegistry, applicabilityRegistry: N54_CURRENT_ROM_LAYOUT_REGISTRY, membershipAuthorities: [authority], sourceRole: "other_observed", sourceProvenance: ["Subscriber-supplied Current Calibration", `Exact binary digest: ${digest}`, observation.observationId, coverage.resolutionRevision], independentlyQualifiedEcuFamily: null })); record("currentDatasetMs");
  if (!currentResult.dataset) return Object.freeze({ status: "coverage_unavailable", title: "Calibration coverage unavailable", message: currentResult.finding, identity, digest, container: binary.source.containerType, byteLength: binary.byteLength, coverage, timings: Object.freeze(timings) });
  const referenceResult = materializeQualifiedCalibrationDataset(constructQualifiedCalibrationDatasetRequest({ engineeringBinary: descriptor.referenceBinary.engineering, binaryIdentity: descriptor.referenceBinary.identity, observations: descriptor.referenceBinary.observations, discoveryRegistry, applicabilityRegistry: N54_CURRENT_ROM_LAYOUT_REGISTRY, membershipAuthorities: [authority], sourceRole: "stock_candidate", sourceProvenance: [...descriptor.configuration.provenance, "Independently resolved governed Reference candidate"], independentlyQualifiedEcuFamily: null })); record("referenceResolutionMs");
  if (!referenceResult.dataset) throw new Error("Governed N54 Reference Dataset could not be materialized.");
  const compared = compareQualifiedCalibrationDatasets(constructQualifiedCalibrationDatasetComparisonRequest({ reference: referenceResult.dataset, modified: currentResult.dataset })); record("comparisonMs"); if (compared.status === "rejected") throw new Error(compared.finding);
  const material = Object.freeze({ reference: referenceResult.dataset, current: currentResult.dataset, comparison: compared.evidence });
  const successBase = { status: "workshop_ready" as const, material, identity: identity as N54PreviewRom, digest, container: binary.source.containerType, byteLength: binary.byteLength, coverage };
  const workshop = buildSubscriberWorkshop(successBase, input.selectedDefinition); record("viewModelMs");
  return Object.freeze({ ...successBase, workshop, timings: Object.freeze(timings) });
}

export function buildSubscriberWorkshop(result: Pick<SubscriberCalibrationSuccess, "material" | "identity" | "digest">, selectedDefinition?: string | null): WorkshopViewModel {
  return buildWorkshopViewModel({ reference: result.material.reference, current: result.material.current, comparison: result.material.comparison, source: { kind: "subscriber_upload", label: `${result.identity} governed Reference → subscriber Current`, fixtureIdentity: `subscriber-upload:${result.digest}` }, selectedKey: selectedDefinition });
}
