import type { SupabaseClient } from "@supabase/supabase-js";
import type { AcquiredXdfContributionReceipt, AcquiredXdfMetadataStore, AcquiredXdfPrivateObjectStore, AcquiredXdfSourceRecord } from "./acquiredDefinitionLibrary.ts";

export const ACQUIRED_XDF_BUCKET = "acquired-xdf-private";
const SOURCE_TABLE = "acquired_xdf_source_artifacts", RECEIPT_TABLE = "acquired_xdf_contribution_receipts";
type SourceRow = Readonly<{ source_record_id: string; source_artifact_id: string | null; source_digest: string; byte_length: number; parser_version: string; storage_object_id: string; provenance_class: "subscriber_contribution"; lifecycle: AcquiredXdfSourceRecord["lifecycle"]; definition_set_id: string | null; definition_set_revision: string | null; definition_count: number; parser_outcome: AcquiredXdfSourceRecord["parserOutcome"]; safe_finding_codes: string[]; validation: AcquiredXdfSourceRecord["validation"]; source_authority_state: AcquiredXdfSourceRecord["sourceAuthorityState"]; applicability_state: AcquiredXdfSourceRecord["applicabilityState"]; admission_state: AcquiredXdfSourceRecord["admissionState"] }>;
const fromRow = (row: SourceRow): AcquiredXdfSourceRecord => Object.freeze({ sourceRecordId: row.source_record_id, sourceArtifactId: row.source_artifact_id, sourceDigest: row.source_digest, byteLength: row.byte_length, parserVersion: row.parser_version as AcquiredXdfSourceRecord["parserVersion"], storageObjectId: row.storage_object_id, provenanceClass: row.provenance_class, lifecycle: row.lifecycle, definitionSetId: row.definition_set_id, definitionSetRevision: row.definition_set_revision, definitionCount: row.definition_count, parserOutcome: row.parser_outcome, safeFindingCodes: Object.freeze(row.safe_finding_codes), validation: Object.freeze(row.validation), sourceAuthorityState: row.source_authority_state, applicabilityState: row.applicability_state, admissionState: row.admission_state });
const toRow = (record: AcquiredXdfSourceRecord): SourceRow => ({ source_record_id: record.sourceRecordId, source_artifact_id: record.sourceArtifactId, source_digest: record.sourceDigest, byte_length: record.byteLength, parser_version: record.parserVersion, storage_object_id: record.storageObjectId, provenance_class: record.provenanceClass, lifecycle: record.lifecycle, definition_set_id: record.definitionSetId, definition_set_revision: record.definitionSetRevision, definition_count: record.definitionCount, parser_outcome: record.parserOutcome, safe_finding_codes: [...record.safeFindingCodes], validation: record.validation, source_authority_state: record.sourceAuthorityState, applicability_state: record.applicabilityState, admission_state: record.admissionState });

export function createSupabaseAcquiredDefinitionPersistenceCore(client: SupabaseClient): Readonly<{ objectStore: AcquiredXdfPrivateObjectStore; metadataStore: AcquiredXdfMetadataStore }> {
  return Object.freeze({
    objectStore: Object.freeze({ putPrivate: async (objectKey: string, bytes: Uint8Array) => { if (!/^acquired-xdf\/raw\/[A-Za-z0-9_-]{24,64}$/.test(objectKey)) throw new Error("ACQUIRED_XDF_OBJECT_KEY_INVALID"); const { error } = await client.storage.from(ACQUIRED_XDF_BUCKET).upload(objectKey, bytes, { contentType: "application/octet-stream", cacheControl: "0", upsert: false }); if (error) throw new Error("ACQUIRED_XDF_PRIVATE_WRITE_FAILED"); } }),
    metadataStore: Object.freeze({
      findSourceByDigest: async (sourceDigest: string) => { const { data, error } = await client.from(SOURCE_TABLE).select("source_record_id,source_artifact_id,source_digest,byte_length,parser_version,storage_object_id,provenance_class,lifecycle,definition_set_id,definition_set_revision,definition_count,parser_outcome,safe_finding_codes,validation,source_authority_state,applicability_state,admission_state").eq("source_digest", sourceDigest).maybeSingle(); if (error) throw new Error("ACQUIRED_XDF_METADATA_READ_FAILED"); return data ? fromRow(data as SourceRow) : null; },
      insertSource: async (record: AcquiredXdfSourceRecord) => { const { error } = await client.from(SOURCE_TABLE).insert(toRow(record)); if (error) throw new Error("ACQUIRED_XDF_METADATA_WRITE_FAILED"); },
      insertReceipt: async (receipt: AcquiredXdfContributionReceipt) => { const source = await client.from(SOURCE_TABLE).select("id").eq("source_record_id", receipt.sourceRecordId).single(); if (source.error || !source.data) throw new Error("ACQUIRED_XDF_RECEIPT_SOURCE_MISSING"); const { error } = await client.from(RECEIPT_TABLE).insert({ receipt_record_id: receipt.receiptId, source_artifact_id: source.data.id, owner_id: receipt.ownerId, contribution_state: receipt.state, contributed_at: receipt.contributedAt }); if (error) throw new Error("ACQUIRED_XDF_RECEIPT_WRITE_FAILED"); },
    }),
  });
}
