import assert from "node:assert/strict";
import test from "node:test";
import { buildEngineeringNavigationIndex, filterEngineeringNavigation } from "./engineeringNavigation.ts";
import { TUNING_ESSENTIAL_SYSTEMS, tuningEssentialSystem } from "./tuningEssentials.ts";
import { PUBLISHED_CALIBRATION_SEMANTICS } from "../knowledge/publishedCalibrationSemantics.ts";
import { bindDefinitionKnowledge } from "./definitionKnowledgeBinding.ts";
import { buildCalibrationTerminology } from "./calibrationTerminology.ts";
import { I8A0S_FOUNDER_REVIEW_QUEUE, I8A0S_SEMANTIC_EQUIVALENCE_PAIRS } from "../knowledge/i8a0sTuningEssentialsAudit.ts";
import { constructN54RepositoryDefinitionDescriptor } from "./n54RepositoryDefinitionAdapter.ts";

test("seven-system taxonomy is universal and normalizes accepted legacy labels",()=>{assert.deepEqual(TUNING_ESSENTIAL_SYSTEMS,["Boost & Air Control","WGDC / Turbo Control","Load & Torque","Fueling / Lambda","Ignition / Timing","IAT / Temperature Compensation","Protection / Safety / Limiters"]);assert.equal(tuningEssentialSystem("Wastegate / WGDC"),"WGDC / Turbo Control");assert.equal(tuningEssentialSystem("Limiters & Safety"),"Protection / Safety / Limiters");assert.equal(tuningEssentialSystem("unknown"),null)});

test("IJE0S spans seven curated systems while B58 gaps remain explicit",()=>{const systems=(rom:string)=>new Set(PUBLISHED_CALIBRATION_SEMANTICS.filter(item=>item.rom===rom).flatMap(item=>[item.knowledge.engineeringSystem?.value,...(item.knowledge.relatedEngineeringSystems??[]).map(field=>field.value)].flatMap(value=>value?[tuningEssentialSystem(value)??value]:[])));assert.deepEqual([...systems("IJE0S")].sort(),[...TUNING_ESSENTIAL_SYSTEMS].sort());const b58=systems("00003076501103");assert.ok(!b58.has("Load & Torque"));assert.ok(!b58.has("Fueling / Lambda"));assert.equal(b58.size,5)});

test("I8A0S publishes ten separately scoped Essentials spanning all seven systems",()=>{const records=PUBLISHED_CALIBRATION_SEMANTICS.filter(item=>item.rom==="I8A0S"),systems=new Set(records.flatMap(item=>[item.knowledge.engineeringSystem?.value,...(item.knowledge.relatedEngineeringSystems??[]).map(field=>field.value)].flatMap(value=>value?[tuningEssentialSystem(value)??value]:[])));assert.equal(records.length,10);assert.deepEqual([...systems].sort(),[...TUNING_ESSENTIAL_SYSTEMS].sort());assert.ok(records.every(item=>item.knowledge.applicability.length===1&&item.knowledge.exactDefinitionRevisions.length===1));});

test("seven new I8A0S publications require independently equal semantic representation rather than title matching",()=>{const i8=constructN54RepositoryDefinitionDescriptor("I8A0S").source.definitions,ije=constructN54RepositoryDefinitionDescriptor("IJE0S").source.definitions,signature=(revision:string,definitions:typeof i8)=>{const definition=definitions.find(item=>item.revisionId===revision);assert.ok(definition);return {title:definition.title,description:definition.description,kind:definition.definitionKind,layout:definition.defaultDataLayout,axes:definition.axes.map(axis=>({axisId:axis.axisId,indexCount:axis.indexCount,dataType:axis.dataType,representation:axis.representation,literalLabels:axis.literalLabels,units:axis.units,elementSizeBits:axis.embeddedData.elementSizeBits,rowCount:axis.embeddedData.rowCount,columnCount:axis.embeddedData.columnCount,majorStrideBits:axis.embeddedData.majorStrideBits,minorStrideBits:axis.embeddedData.minorStrideBits,typeFlags:axis.embeddedData.typeFlags,equationSource:axis.equationSource,equationVariables:axis.equationVariables}))}};for(const [i8Revision,ijeRevision] of I8A0S_SEMANTIC_EQUIVALENCE_PAIRS){assert.deepEqual(signature(i8Revision,i8),signature(ijeRevision,ije));assert.ok(PUBLISHED_CALIBRATION_SEMANTICS.some(item=>item.rom==="I8A0S"&&item.knowledge.exactDefinitionRevisions.includes(i8Revision)));}});

test("high-value I8A0S candidates remain a small explicit Founder queue and are not title-only publications",()=>{assert.equal(I8A0S_FOUNDER_REVIEW_QUEUE.length,7);assert.deepEqual(I8A0S_FOUNDER_REVIEW_QUEUE.map(item=>item.priority),[1,2,3,4,5,6,7]);const published=new Set(PUBLISHED_CALIBRATION_SEMANTICS.flatMap(item=>item.knowledge.exactDefinitionRevisions));for(const candidate of I8A0S_FOUNDER_REVIEW_QUEUE){assert.ok(candidate.evidence.length>0);assert.ok(candidate.limitations.length>0);assert.equal(published.has(candidate.definitionRevision),false);}});

test("intent search uses exact Knowledge and never promotes unclassified source titles",()=>{const record=PUBLISHED_CALIBRATION_SEMANTICS.find(item=>item.originalTitle==="Base Fuel Pressure")!.knowledge,semantic=bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:record.exactDefinitionRevisions[0]!},[record]);const index=buildEngineeringNavigationIndex([{key:"qualified",title:"opaque",available:true,semantic},{key:"unclassified",title:"Boost target title only",available:true}]);assert.equal(filterEngineeringNavigation(index,{mode:"all",query:"fuel pressure"})[0]?.classification,"ENGINEERING_QUALIFIED");assert.equal(filterEngineeringNavigation(index,{mode:"essentials",query:"boost target"}).length,0)});

test("multi-token engineering intent search can combine a qualified name and role",()=>{const record=PUBLISHED_CALIBRATION_SEMANTICS.find(item=>item.originalTitle==="RPM limit during oil pressure limp mode")!.knowledge,semantic=bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:record.exactDefinitionRevisions[0]!},[record]),index=buildEngineeringNavigationIndex([{key:"qualified",title:"opaque",available:true,semantic}]);assert.equal(filterEngineeringNavigation(index,{mode:"all",query:"RPM limiter"}).length,1)});

test("selected-Table terminology and navigation remain effectively immediate",context=>{const record=PUBLISHED_CALIBRATION_SEMANTICS.find(item=>item.originalTitle.startsWith("Boost Ceiling (Relative)"))!.knowledge,semantic=bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:record.exactDefinitionRevisions[0]!},[record]),definitions=Array.from({length:1175},(_,index)=>({key:`definition-${index}`,title:`Definition ${index}`,available:true,semantic:index<10?semantic:undefined})),index=buildEngineeringNavigationIndex(definitions),started=performance.now();for(let iteration=0;iteration<1000;iteration++){filterEngineeringNavigation(index,{mode:"essentials",query:"boost"});filterEngineeringNavigation(index,{mode:"systems",system:"Boost & Air Control"});buildCalibrationTerminology({mode:iteration%2?"engineer":"standard",sourceTitle:"Source",shape:"2D",rows:2,columns:2,axes:[{id:"x",units:"RPM",values:[1000,2000]},{id:"y",units:"Gear",values:[1,2]}],semantic,outputUnits:"psi"})}const elapsed=performance.now()-started;assert.ok(elapsed<1000);context.diagnostic(`TUNING_ESSENTIALS_PERFORMANCE ${JSON.stringify({iterations:1000,definitions:1175,elapsedMs:Number(elapsed.toFixed(2))})}`)});
