import assert from "node:assert/strict";
import test from "node:test";
import { buildEngineeringNavigationIndex, filterEngineeringNavigation } from "./engineeringNavigation.ts";
import { TUNING_ESSENTIAL_SYSTEMS, tuningEssentialSystem } from "./tuningEssentials.ts";
import { PUBLISHED_CALIBRATION_SEMANTICS } from "../knowledge/publishedCalibrationSemantics.ts";
import { bindDefinitionKnowledge } from "./definitionKnowledgeBinding.ts";
import { buildCalibrationTerminology } from "./calibrationTerminology.ts";

test("seven-system taxonomy is universal and normalizes accepted legacy labels",()=>{assert.deepEqual(TUNING_ESSENTIAL_SYSTEMS,["Boost & Air Control","WGDC / Turbo Control","Load & Torque","Fueling / Lambda","Ignition / Timing","IAT / Temperature Compensation","Protection / Safety / Limiters"]);assert.equal(tuningEssentialSystem("Wastegate / WGDC"),"WGDC / Turbo Control");assert.equal(tuningEssentialSystem("Limiters & Safety"),"Protection / Safety / Limiters");assert.equal(tuningEssentialSystem("unknown"),null)});

test("IJE0S spans seven curated systems while B58 gaps remain explicit",()=>{const systems=(rom:string)=>new Set(PUBLISHED_CALIBRATION_SEMANTICS.filter(item=>item.rom===rom).flatMap(item=>[item.knowledge.engineeringSystem?.value,...(item.knowledge.relatedEngineeringSystems??[]).map(field=>field.value)].flatMap(value=>value?[tuningEssentialSystem(value)??value]:[])));assert.deepEqual([...systems("IJE0S")].sort(),[...TUNING_ESSENTIAL_SYSTEMS].sort());const b58=systems("00003076501103");assert.ok(!b58.has("Load & Torque"));assert.ok(!b58.has("Fueling / Lambda"));assert.equal(b58.size,5)});

test("I8A0S receives only the three separately scoped exact shared-Definition publications",()=>{const records=PUBLISHED_CALIBRATION_SEMANTICS.filter(item=>item.rom==="I8A0S");assert.equal(records.length,3);assert.deepEqual(records.map(item=>item.originalTitle).sort(),["Boost Ceiling (Relative) (Gear x RPM) (Map 1)","Min Load Threshold for P/D Factors","WGDC D-Factor (Custom)"]);assert.ok(records.every(item=>item.knowledge.limitations.some(value=>value.includes("separately scoped publication"))))});

test("intent search uses exact Knowledge and never promotes unclassified source titles",()=>{const record=PUBLISHED_CALIBRATION_SEMANTICS.find(item=>item.originalTitle==="Base Fuel Pressure")!.knowledge,semantic=bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:record.exactDefinitionRevisions[0]!},[record]);const index=buildEngineeringNavigationIndex([{key:"qualified",title:"opaque",available:true,semantic},{key:"unclassified",title:"Boost target title only",available:true}]);assert.equal(filterEngineeringNavigation(index,{mode:"all",query:"fuel pressure"})[0]?.classification,"ENGINEERING_QUALIFIED");assert.equal(filterEngineeringNavigation(index,{mode:"essentials",query:"boost target"}).length,0)});

test("multi-token engineering intent search can combine a qualified name and role",()=>{const record=PUBLISHED_CALIBRATION_SEMANTICS.find(item=>item.originalTitle==="RPM limit during oil pressure limp mode")!.knowledge,semantic=bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:record.exactDefinitionRevisions[0]!},[record]),index=buildEngineeringNavigationIndex([{key:"qualified",title:"opaque",available:true,semantic}]);assert.equal(filterEngineeringNavigation(index,{mode:"all",query:"RPM limiter"}).length,1)});

test("selected-Table terminology and navigation remain effectively immediate",context=>{const record=PUBLISHED_CALIBRATION_SEMANTICS.find(item=>item.originalTitle.startsWith("Boost Ceiling (Relative)"))!.knowledge,semantic=bindDefinitionKnowledge({definitionIdentity:null,definitionRevision:record.exactDefinitionRevisions[0]!},[record]),definitions=Array.from({length:1175},(_,index)=>({key:`definition-${index}`,title:`Definition ${index}`,available:true,semantic:index<10?semantic:undefined})),index=buildEngineeringNavigationIndex(definitions),started=performance.now();for(let iteration=0;iteration<1000;iteration++){filterEngineeringNavigation(index,{mode:"essentials",query:"boost"});filterEngineeringNavigation(index,{mode:"systems",system:"Boost & Air Control"});buildCalibrationTerminology({mode:iteration%2?"engineer":"standard",sourceTitle:"Source",shape:"2D",rows:2,columns:2,axes:[{id:"x",units:"RPM",values:[1000,2000]},{id:"y",units:"Gear",values:[1,2]}],semantic,outputUnits:"psi"})}const elapsed=performance.now()-started;assert.ok(elapsed<1000);context.diagnostic(`TUNING_ESSENTIALS_PERFORMANCE ${JSON.stringify({iterations:1000,definitions:1175,elapsedMs:Number(elapsed.toFixed(2))})}`)});
