import assert from "node:assert/strict";
import test from "node:test";
import type { WorkshopDefinitionDetail } from "./viewModel.ts";
import { buildCalibrationSlice, buildCalibrationSurfaceMesh, buildCalibrationVisualizationModel, capabilitiesForDefinition, moveSelectedCell } from "./visualizationModel.ts";
import { deriveWorkshopLayout } from "./workspaceLayout.ts";

function detail(shape: "scalar"|"1D"|"2D", rows: number, columns: number, available=true): WorkshopDefinitionDetail {
  const cells=available?Array.from({length:rows*columns},(_,index)=>({index,row:Math.floor(index/columns),column:index%columns,referenceValue:index,currentValue:index+(index===1?1:0),changed:index===1,signedDelta:index===1?1:0,percentageDelta:0,percentageState:"available",units:"unit",referenceRawValue:index,currentRawValue:index,referenceRawOffset:index,currentRawOffset:index,equationRevision:"eq"})):[];
  return {summary:{key:"instance",occurrence:0,definitionIdentity:"definition",definitionRevision:"revision",title:"Source title",description:null,shape,units:"unit",outcome:available?"changed":"comparison_unavailable",changedCellCount:available?1:0,available},rows,columns,axes:[{id:"X",units:"x-unit",values:Array.from({length:columns},(_,i)=>i*10)},{id:"Y",units:"y-unit",values:Array.from({length:rows},(_,i)=>i*5)}],cells,unavailableStage:available?null:"conversion",findings:[],equationRevision:"eq",sourceArtifactDigest:"digest"};
}

test("shape capability rules reject fabricated geometry",()=>{assert.deepEqual(capabilitiesForDefinition(detail("scalar",1,1)),{grid:true,twoDimensional:false,threeDimensional:false,reason2d:"A scalar has no qualified line axis.",reason3d:"A scalar has no two-axis surface geometry."});assert.equal(capabilitiesForDefinition(detail("1D",1,4)).twoDimensional,true);assert.equal(capabilitiesForDefinition(detail("1D",1,4)).threeDimensional,false);assert.equal(capabilitiesForDefinition(detail("2D",3,4)).threeDimensional,true);assert.equal(capabilitiesForDefinition(detail("2D",3,4,false)).grid,false)});
test("visual model preserves qualified axes, units, values and changed Evidence",()=>{const model=buildCalibrationVisualizationModel(detail("2D",2,3));assert.deepEqual(model.columnAxis,{id:"X",units:"x-unit",values:[0,10,20]});assert.deepEqual(model.rowAxis,{id:"Y",units:"y-unit",values:[0,5]});assert.equal(model.valueUnits,"unit");assert.equal(model.surface[1]?.changed,true);assert.equal(model.surface[1]?.currentValue,2);assert.ok(!JSON.stringify(model).includes("RPM"));assert.ok(!JSON.stringify(model).toLowerCase().includes("recommend"))});
test("1D and 2D slices retain exact linked cell identities",()=>{const model=buildCalibrationVisualizationModel(detail("2D",2,3));assert.deepEqual(buildCalibrationSlice(model,"row",1).map(p=>p.cellIndex),[3,4,5]);assert.deepEqual(buildCalibrationSlice(model,"column",1).map(p=>p.cellIndex),[1,4])});
test("linked selection moves by intrinsic Grid coordinates",()=>{const item=detail("2D",3,4);assert.equal(moveSelectedCell(item,5,1,0),9);assert.equal(moveSelectedCell(item,9,0,-1),8)});
test("every panel state gives Workspace an actual expanding column",()=>{const open=deriveWorkshopLayout({explorerCollapsed:false,inspectorCollapsed:false,focusWorkspace:false}),left=deriveWorkshopLayout({explorerCollapsed:true,inspectorCollapsed:false,focusWorkspace:false}),right=deriveWorkshopLayout({explorerCollapsed:false,inspectorCollapsed:true,focusWorkspace:false}),closed=deriveWorkshopLayout({explorerCollapsed:true,inspectorCollapsed:true,focusWorkspace:false}),focus=deriveWorkshopLayout({explorerCollapsed:false,inspectorCollapsed:false,focusWorkspace:true});assert.equal(open.columns,"xl:grid-cols-[300px_minmax(0,1fr)_320px]");assert.equal(left.columns,"xl:grid-cols-[minmax(0,1fr)_320px]");assert.equal(right.columns,"xl:grid-cols-[300px_minmax(0,1fr)]");assert.equal(closed.columns,"xl:grid-cols-1");assert.equal(focus.columns,"xl:grid-cols-1");assert.equal(left.explorerVisible,false);assert.equal(right.inspectorVisible,false);assert.equal("selectedCell" in focus,false);assert.equal("selectedDefinition" in focus,false);assert.equal("view" in focus,false);assert.equal("surfaceState" in focus,false)});
test("surface mesh has exact qualified topology, bindings and Evidence",()=>{const model=buildCalibrationVisualizationModel(detail("2D",3,4));const mesh=buildCalibrationSurfaceMesh(model);assert.equal(mesh.available,true);assert.equal(mesh.triangles.length,12);assert.deepEqual(mesh.triangles[0]?.cellIndices,[0,4,1]);assert.deepEqual(mesh.triangles[0]?.points.map(point=>[point.x,point.y,point.referenceValue,point.currentValue,point.changed]),[[0,0,0,0,false],[0,5,4,4,false],[10,0,1,2,true]]);assert.equal(mesh.triangles.flatMap(triangle=>triangle.points).some(point=>point.changed&&point.cellIndex===1),true)});
test("surface mesh fails locally when qualified geometry is unavailable or incomplete",()=>{assert.equal(buildCalibrationSurfaceMesh(buildCalibrationVisualizationModel(detail("1D",1,4))).available,false);const complete=detail("2D",2,2);const incomplete={...complete,cells:complete.cells.slice(0,-1)};const mesh=buildCalibrationSurfaceMesh(buildCalibrationVisualizationModel(incomplete));assert.equal(mesh.available,false);assert.match(mesh.reason??"",/complete qualified rectangular mesh/)});
