import test from "node:test";
import assert from "node:assert/strict";
import { applyWorkingEdit, createWorkingCalibration, listWorkingChanges, redoWorkingEdit, undoWorkingEdit, workingCellDelta, workingCellValue, type WorkingDefinitionSeed } from "./workingCalibration.ts";
import { createBrowserWorkingCalibrationStore } from "./workingCalibrationPersistence.ts";
import { deriveReversibleAffineEquation, parseXdfEquation } from "../xdf/engineeringValueConversion.ts";

const time = (second = 0) => `2026-09-15T00:00:${String(second).padStart(2, "0")}.000Z`;
const address = (index: number) => ({ definitionRevision: "definition-revision", occurrence: 0, index, row: Math.floor(index / 2), column: index % 2 });
const qualified = Object.freeze({ state: "EDIT_QUALIFIED" as const, revision: "edit-capability-revision", inverse: Object.freeze({ scale: 1, offset: 0, rawMinimum: 0, rawMaximum: 255 }), engineeringMinimum: 0, engineeringMaximum: 255, warnings: Object.freeze([]), blockers: Object.freeze([]) });
function definition(overrides: Partial<WorkingDefinitionSeed> = {}): WorkingDefinitionSeed { return Object.freeze({ definitionRevision: "definition-revision", occurrence: 0, rows: 2, columns: 2, availability: "available" as const, capability: qualified, cells: Object.freeze([10, 20, 30, 40].map((currentValue, index) => Object.freeze({ ...address(index), currentValue, units: "unit" }))), ...overrides }); }
function calibration(definitions: readonly WorkingDefinitionSeed[] = [definition()], ownerScope = "owner-a", vehicleId = "vehicle-a") { return createWorkingCalibration({ ownerScope, vehicleId, currentDatasetId: "current-id", currentDatasetRevision: "current-revision", romLayoutId: "layout", relationshipRevision: "relationship", definitionSetRevision: "set", createdAt: time(), definitions }); }
const applied = (result: ReturnType<typeof applyWorkingEdit>) => { assert.equal(result.status, "applied"); if (result.status !== "applied") throw new Error("expected applied"); return result.calibration; };

test("Working Calibration is deterministic and Current seed remains immutable", () => { const current = definition(), first = calibration([current]), second = calibration([current]); assert.equal(first.workingCalibrationId, second.workingCalibrationId); assert.equal(first.workingCalibrationRevision, second.workingCalibrationRevision); const changed = applied(applyWorkingEdit(first, { operation: "assign", operand: 25, targets: [address(0)], updatedAt: time(1) })); assert.equal(current.cells[0]!.currentValue, 10); assert.equal(workingCellValue(first, address(0)), 10); assert.equal(workingCellValue(changed, address(0)), 25); assert.equal(changed.state, "dirty"); });

test("single and region assignment, delta and percentage edits preserve before/after", () => { let working = calibration(); working = applied(applyWorkingEdit(working, { operation: "assign", operand: 50, targets: [address(0)], updatedAt: time(1) })); working = applied(applyWorkingEdit(working, { operation: "delta", operand: 5, targets: [address(1), address(2)], updatedAt: time(2) })); working = applied(applyWorkingEdit(working, { operation: "percentage", operand: 10, targets: [address(3)], updatedAt: time(3) })); assert.deepEqual([0, 1, 2, 3].map((index) => workingCellValue(working, address(index))), [50, 25, 35, 44]); assert.deepEqual(working.mutations[1]!.before, [20, 30]); assert.deepEqual(working.mutations[1]!.after, [25, 35]); assert.deepEqual(workingCellDelta(working, address(0)), { current: 10, working: 50, delta: 40, percentageDelta: 400 }); assert.equal(listWorkingChanges(working).length, 4); });

test("undo, redo and branch invalidation are exact and deterministic", () => { const start = calibration(), one = applied(applyWorkingEdit(start, { operation: "delta", operand: 1, targets: [address(0)], updatedAt: time(1) })), two = applied(applyWorkingEdit(one, { operation: "delta", operand: 2, targets: [address(0)], updatedAt: time(2) })), undone = undoWorkingEdit(two, time(3)), redone = redoWorkingEdit(undone, time(4)); assert.equal(workingCellValue(undone, address(0)), 11); assert.equal(workingCellValue(redone, address(0)), 13); assert.equal(redone.workingCalibrationRevision, two.workingCalibrationRevision); const branch = applied(applyWorkingEdit(undone, { operation: "assign", operand: 99, targets: [address(0)], updatedAt: time(5) })); assert.equal(branch.mutations.length, 2); assert.equal(redoWorkingEdit(branch, time(6)), branch); assert.equal(workingCellValue(branch, address(0)), 99); });

test("quarantine, unavailable, VIEW-only, dimensions and non-representable values fail closed", () => { const cases: readonly [WorkingDefinitionSeed, number, RegExp][] = [[definition({ availability: "quarantined" }), 11, /quarantined/], [definition({ availability: "unavailable" }), 11, /unavailable/], [definition({ capability: { ...qualified, state: "VIEW_ONLY", revision: null, blockers: ["VIEW qualification does not grant EDIT authority."] } }), 11, /VIEW qualification/], [definition(), 10.5, /not representable/], [definition(), 300, /maximum|representable/]]; for (const [seed, operand, expected] of cases) { const result = applyWorkingEdit(calibration([seed]), { operation: "assign", operand, targets: [address(0)], updatedAt: time(1) }); assert.equal(result.status, "blocked"); if (result.status === "blocked") assert.match(result.findings.join(" "), expected); } const outside = applyWorkingEdit(calibration(), { operation: "assign", operand: 1, targets: [{ ...address(0), row: 9 }], updatedAt: time(1) }); assert.equal(outside.status, "blocked"); });

test("bounded persistence survives reload and isolates owner, vehicle and Current Dataset", () => { const memory = new Map<string, string>(), store = createBrowserWorkingCalibrationStore({ getItem: (key) => memory.get(key) ?? null, setItem: (key, value) => { memory.set(key, value); }, removeItem: (key) => { memory.delete(key); } }), seed = calibration(), working = applied(applyWorkingEdit(seed, { operation: "delta", operand: 5, targets: [address(0)], updatedAt: time(1) })); store.save(working); const scope = { ownerScope: "owner-a", vehicleId: "vehicle-a", currentDatasetId: "current-id" }; assert.equal(store.load(scope, seed)?.workingCalibrationRevision, working.workingCalibrationRevision); assert.ok([...memory.values()].every((value) => !value.includes("definitions") && !value.includes("currentValue"))); assert.equal(store.load({ ...scope, ownerScope: "owner-b" }, seed), null); assert.equal(store.load({ ...scope, vehicleId: "vehicle-b" }, seed), null); assert.equal(store.load({ ...scope, currentDatasetId: "other-current" }, seed), null); });

test("same Current Dataset can create separate owner and vehicle Working identities", () => { assert.notEqual(calibration(undefined, "owner-a", "vehicle-a").workingCalibrationId, calibration(undefined, "owner-b", "vehicle-a").workingCalibrationId); assert.notEqual(calibration(undefined, "owner-a", "vehicle-a").workingCalibrationId, calibration(undefined, "owner-a", "vehicle-b").workingCalibrationId); });

test("only one-to-one affine conversion equations produce deterministic inverse plans", () => { const linear = parseXdfEquation("(X * 0.5) - 10"), nonlinear = parseXdfEquation("X * X"); assert.ok(linear.outcome === "parsed"); assert.ok(nonlinear.outcome === "parsed"); if (linear.outcome === "parsed" && nonlinear.outcome === "parsed") { assert.deepEqual(deriveReversibleAffineEquation(linear), { outcome: "reversible_affine", scale: 0.5, offset: -10 }); assert.equal(deriveReversibleAffineEquation(nonlinear).outcome, "not_reversibly_affine"); } });
