import { applyWorkingEdit, createWorkingCalibration, undoWorkingEdit, workingDefinitionSeed, type WorkingCalibration, type WorkingDefinitionSeed } from "./workingCalibration.ts";

export const WORKING_CALIBRATION_STORAGE_PREFIX = "tunesight:working-calibration:v1";
type Scope = Readonly<{ ownerScope: string; vehicleId: string; currentDatasetId: string }>;
type StoredWorkingCalibration = Pick<WorkingCalibration, "contractVersion" | "workingCalibrationId" | "workingCalibrationRevision" | "ownerScope" | "vehicleId" | "currentDatasetId" | "currentDatasetRevision" | "romLayoutId" | "relationshipRevision" | "definitionSetRevision" | "createdAt" | "updatedAt" | "mutations" | "cursor">;
export type WorkingDefinitionResolver = (definitionRevision: string, occurrence: number) => WorkingDefinitionSeed | undefined;
export type WorkingCalibrationStore = Readonly<{ load: (scope: Scope, currentSeed: WorkingCalibration, resolveDefinition?: WorkingDefinitionResolver) => WorkingCalibration | null; save: (calibration: WorkingCalibration) => void; remove: (scope: Scope) => void }>;
const key = (scope: Readonly<{ ownerScope: string; vehicleId: string; currentDatasetId: string }>) => `${WORKING_CALIBRATION_STORAGE_PREFIX}:${encodeURIComponent(scope.ownerScope)}:${encodeURIComponent(scope.vehicleId)}:${encodeURIComponent(scope.currentDatasetId)}`;
export function createBrowserWorkingCalibrationStore(storage: Pick<Storage, "getItem" | "setItem" | "removeItem">): WorkingCalibrationStore {
  return Object.freeze({
    load: (scope, currentSeed, suppliedResolver) => { try { const raw = storage.getItem(key(scope)); if (!raw) return null; const parsed = JSON.parse(raw) as StoredWorkingCalibration; if (parsed.ownerScope !== scope.ownerScope || parsed.vehicleId !== scope.vehicleId || parsed.currentDatasetId !== scope.currentDatasetId || parsed.currentDatasetRevision !== currentSeed.currentDatasetRevision || parsed.romLayoutId !== currentSeed.romLayoutId || parsed.relationshipRevision !== currentSeed.relationshipRevision || parsed.definitionSetRevision !== currentSeed.definitionSetRevision || parsed.cursor < 0 || parsed.cursor > parsed.mutations.length) return null; const resolveDefinition = suppliedResolver ?? ((revision: string, occurrence: number) => workingDefinitionSeed(currentSeed, revision, occurrence)); const rebuilt = createWorkingCalibration({ ownerScope: parsed.ownerScope, vehicleId: parsed.vehicleId, currentDatasetId: parsed.currentDatasetId, currentDatasetRevision: parsed.currentDatasetRevision, romLayoutId: parsed.romLayoutId, relationshipRevision: parsed.relationshipRevision, definitionSetRevision: parsed.definitionSetRevision, createdAt: parsed.createdAt }); let current = rebuilt; for (const mutation of parsed.mutations) { const definitions = [...new Map(mutation.targets.map((target) => { const definition = resolveDefinition(target.definitionRevision, target.occurrence); return [`${target.definitionRevision}:${target.occurrence}`, definition] as const; })).values()]; if (definitions.some((definition) => !definition)) return null; const result = applyWorkingEdit(current, { operation: mutation.operation, source: mutation.source, operand: mutation.operand, targets: mutation.targets, definitions: definitions as WorkingDefinitionSeed[], updatedAt: parsed.updatedAt }); if (result.status !== "applied") return null; current = result.calibration; } while (current.cursor > parsed.cursor) current = undoWorkingEdit(current, parsed.updatedAt); return current.workingCalibrationRevision === parsed.workingCalibrationRevision ? current : null; } catch { return null; } },
    save: (calibration) => { const { state: _state, validation: _validation, ...stored } = calibration; void _state; void _validation; storage.setItem(key(calibration), JSON.stringify(stored satisfies StoredWorkingCalibration)); },
    remove: (scope) => storage.removeItem(key(scope)),
  });
}
